### ISSUE TITLE
DNS Resolvers drops the http-request header

### ISSUE THREAD

**Issue by vumdao** [haproxy/haproxy#1002]
haproxy.cfg

```
resolvers awsvpc

        nameserver vpc 169.254.169.253:53

        hold valid           10s

backend myweb

        http-request set-header myheader 123

        server disabled-server 127.0.0.1:1 disabled

        server srv reader01-1111111111.us-east-1.elb.amazonaws.com:80 check port 80 resolvers awsvpc inter 2000 fall 5

```

ALB listen rule
![2020-12-11_10-36](https://user-images.githubusercontent.com/37215642/101858715-c0c4ec00-3b9c-11eb-8ab7-01a5c4db8bd3.png)

With the above backend setting, the request does not match the rule but it works without resolvers
`server srv reader01-1111111111.us-east-1.elb.amazonaws.com:80`

**Comment by jmagnin** [comment]
Hi,

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

The mailing list (no need to subscribe) is: haproxy@formilux.org
Subscribe to the list: haproxy+subscribe@formilux.org
Unsubscribe from the list: haproxy+unsubscribe@formilux.org

Forum and mailing list are correct places for questions about HAProxy or general suggestions
and topics, e.g. usage or documentation questions! This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.

If you really think you encountered a bug, please take the time to fill the bug report template that you ignored in your first post. It helps reporters provide enough information for developers to be able to work on the issue.

Thanks for understanding, and for contributing to the project!
