### ISSUE TITLE
gcc 11 build failure

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1010]
```
src/ssl_sock.c: In function 'cli_io_handler_tlskeys_files':
src/ssl_sock.c:6338:21: error: array subscript 'struct tls_keys_ref[0]' is partly outside array bounds of 'struct list[1]' [-Werror=array-bounds]
 6338 |                 ref = LIST_NEXT(&ref->list, struct tls_keys_ref *, list);
src/ssl_sock.c:489:13: note: while referencing 'tlskeys_reference'
  489 | struct list tlskeys_reference = LIST_HEAD_INIT(tlskeys_reference);
      |             ^~~~~~~~~~~~~~~~~
  CC      src/cfgparse-ssl.o
```

**Comment by wtarreau** [comment]
I've looked carefully at this part, even preprocessed the code and run by hand, and for me gcc is bogus here: there is never a single access to the struct outside of its bounds. It is used as a list end pointer check, is never dereferenced, and "ref" stops iterating as soon as it meets this target, in which case NULL is returned. Therefore I suspect there's something wrong in the bounds checking involved here, and it could be useful to report this to gcc before it's released.

**Comment by chipitsine** [comment]
In order to report, it would be good to have simple repro source code.

**Comment by wtarreau** [comment]
Sure, but I don't have a gcc 11 handy at the moment.

**Comment by TimWolla** [comment]
Expanding the macros in `tlskeys_list_get_next`:

This warns:

```
		ref = (struct tls_keys_ref *)
			(
				(
					(const char *) ((&ref->list)->n)
				) - (
					(size_t) &((struct tls_keys_ref *) NULL)->list
				)
			);
```

```
[root@1dbd7fd1ab3f pwd]# make -j4 all TARGET=linux-glibc USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  CC      src/ssl_sock.o
  CC      src/version.o
src/ssl_sock.c: In function ‘cli_io_handler_tlskeys_files’:
src/ssl_sock.c:6366:21: warning: array subscript ‘struct tls_keys_ref[0]’ is partly outside array bounds of ‘struct list[1]’ [-Warray-bounds]
 6366 |                 ref = (struct tls_keys_ref *)
      |                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
 6367 |                         (
      |                         ~
 6368 |                                 (
      |                                 ~
 6369 |                                         (const char *) ((&ref->list)->n)
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 6370 |                                 ) - (
      |                                 ~~~~~
 6371 |                                         (size_t) &((struct tls_keys_ref *) NULL)->list
      |                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 6372 |                                 )
      |                                 ~
 6373 |                         );
      |                         ~
src/ssl_sock.c:490:13: note: while referencing ‘tlskeys_reference’
  490 | struct list tlskeys_reference = LIST_HEAD_INIT(tlskeys_reference);
      |             ^~~~~~~~~~~~~~~~~
  LD      haproxy
```

Replacing the `NULL` with `1`:

```
		ref = (struct tls_keys_ref *)
			(
				(
					(const char *) ((&ref->list)->n)
				) - (
					(size_t) &((struct tls_keys_ref *) 1)->list
				)
			);
```

Results in:

```
[root@1dbd7fd1ab3f pwd]# make -j4 all TARGET=linux-glibc USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  CC      src/ssl_sock.o
  CC      src/version.o
src/ssl_sock.c: In function ‘cli_io_handler_tlskeys_files’:
src/ssl_sock.c:6369:69: warning: array subscript ‘struct tls_keys_ref[0]’ is partly outside array bounds of ‘struct list[1]’ [-Warray-bounds]
 6369 |                                         (const char *) ((&ref->list)->n)
      |                                                        ~~~~~~~~~~~~~^~~~
src/ssl_sock.c:490:13: note: while referencing ‘tlskeys_reference’
  490 | struct list tlskeys_reference = LIST_HEAD_INIT(tlskeys_reference);
      |             ^~~~~~~~~~~~~~~~~
  LD      haproxy
```

Simplifying this further:

```
ref = (void *) (ref->list.n);
```

Results in:
```
[root@1dbd7fd1ab3f pwd]# make -j4 all TARGET=linux-glibc USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  CC      src/ssl_sock.o
  CC      src/version.o
src/ssl_sock.c: In function ‘cli_io_handler_tlskeys_files’:
src/ssl_sock.c:6366:21: warning: array subscript ‘struct tls_keys_ref[0]’ is partly outside array bounds of ‘struct list[1]’ [-Warray-bounds]
 6366 |                 ref = (void *) (ref->list.n);
      |                 ~~~~^~~~~~~~~~~~~~~~~~~~~~~~
src/ssl_sock.c:490:13: note: while referencing ‘tlskeys_reference’
  490 | struct list tlskeys_reference = LIST_HEAD_INIT(tlskeys_reference);
      |             ^~~~~~~~~~~~~~~~~
  LD      haproxy
```

**Comment by TimWolla** [comment]
This is related to the `inline` on the function. If I remove that then the error disappears.

**Comment by TimWolla** [comment]
This makes the error disappear:

```
diff --git i/src/ssl_sock.c w/src/ssl_sock.c
index 35298d530..5e1be6a7c 100644
--- i/src/ssl_sock.c
+++ w/src/ssl_sock.c
@@ -6435,7 +6435,7 @@ static int cli_io_handler_tlskeys_files(struct appctx *appctx) {
                 * tlskeys_list_get_next() for retruning the first available entry
                 */
                if (appctx->ctx.cli.p0 == NULL) {
-                       appctx->ctx.cli.p0 = LIST_ELEM(&tlskeys_reference, struct tls_keys_ref *, list);
+                       appctx->ctx.cli.p0 = (struct tls_keys_ref *) 1;//LIST_ELEM(&tlskeys_reference, struct tls_keys_ref *, list);
                        appctx->ctx.cli.p0 = tlskeys_list_get_next(appctx->ctx.cli.p0, &tlskeys_reference);
                }
 ```

**Comment by TimWolla** [comment]
Okay, I have a simple reproducer:

```c
#include <stdio.h>
#include "include/haproxy/list.h"

struct tls_keys_ref {
	struct list list;
	char *filename;
	int unique_id;
	int refcount;
};

struct list tlskeys_reference = LIST_HEAD_INIT(tlskeys_reference);

int main(void) {
	void * p0;
	const struct tls_keys_ref * tmp = LIST_ELEM(&tlskeys_reference, struct tls_keys_ref *, list);
	p0 = LIST_NEXT(&tmp->list, struct tls_keys_ref *, list);
	printf("%p\n", p0);
	return 0;
}
```

**Comment by TimWolla** [comment]
So, my understanding is that the warning is in fact correct:

1. `tlskeys_reference` is a `struct list` (= 2 Pointers).
2. `tmp` is equal to `tlskeys_reference`, because `tlskeys_reference - offsetof(struct tls_keys_ref, list) = tlskeys_reference - 0 = tlskeys_reference`.
3. `tmp` is a pointer to `struct tls_keys_ref` (= 3 Pointers + 2 int) which is larger than `tlskeys_reference` (= 2 Pointers).

If the `struct list list` would not be the first member of the `struct tls_keys_ref` then `tmp` would be a pointer to the area *before* `tlskeys_reference` which is undefined behavior.

**Comment by TimWolla** [comment]
I'm sending a patch.

**Comment by TimWolla** [comment]
:point_right: https://www.mail-archive.com/haproxy@formilux.org/msg39306.html

**Comment by wtarreau** [comment]
Unless I'm still running on -ENOCOFFEE, I completely disagree here. In your test you had to replace NULL by 1 to make it fail. And in the reproducer, everything is correct. Only the ->list element is dereferenced, and is located exactly where expected, because the list element of this struct is of the same size as the tlskeys_reference so there is no access outside of bounds at all here. Moreover, 100% of our lists and trees work like this.

I suspect that after we had to change the definition of our LIST_ELEM to please gcc 10, it started to see better through it but is then confused. Maybe even just casting the pointer to a size_t before turning it to the final result will be enough to shut it up.

In anyway I'm pretty positive that the compiler is wrong here. If you simplify the code to eliminate the macros, you'll find that tmp == tls_keys_reference and that only tmp->list is used, which is of the same type as tls_keys_reference (list).

It would be funny also to try to put an `__attribute__((packed))` around either the first or the second struct just to see if the warning moves away. Also I'm suspecting that if you remove the initialization of your tls_keys_reference list, gcc shuts up, which would indicate that it detected that this variable is an invariant because nowhere do we assign anything to it. Thus there could be a similar issue in the real code where it complains.

**Comment by wtarreau** [comment]
I'm seeing a few very similar regressions already reported in gcc, leading me to think that we should possibly, sadly, disable this bogus warning:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94985
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=95072
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96900

The one below is interesting, as one developer suggests this warning can trivially be fooled due to incomplete pointer analysis and even provides a simple example:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94675

Thus we'll likely have to shut it up :-/

**Comment by wtarreau** [comment]
So I could reproduce it on godbolt by further simplifying your reproducer above. It's definitely a false positive, and I have not found a way to shut it up yet so we might have to disable this bogus warning. It only complains about accesses to global variables. I still don't know why it doesn't complain on the numerous list_for_each() we have though. Repro below:

https://godbolt.org/#g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:___c,selection:(endColumn:1,endLineNumber:23,positionColumn:1,positionLineNumber:23,selectionStartColumn:1,selectionStartLineNumber:23,startColumn:1,startLineNumber:23),source:'%23include+%3Cstddef.h%3E%0A%0Astruct+list+%7B%0A++++struct+list+*n%3B%0A++++struct+list+*p%3B%0A%7D%3B%0A%0Astruct+list+head%3B%0A%0Astruct+ref+%7B%0A++++++++struct+list+list%3B%0A++++++++char+*filename%3B%0A%7D%3B%0A%0Astruct+list+*first(void)%0A%7B%0A++++++++struct+ref+*tmp%3B%0A%0A++++++++//tmp+%3D+(struct+ref+*)((char+*)%26head+-+(size_t)%26((struct+ref+*)0)-%3Elist)%3B%0A++++++++tmp+%3D+(struct+ref+*)%26head%3B%0A++++++++return+tmp-%3Elist.n%3B%0A%7D%0A'),l:'5',n:'0',o:'C+source+%231',t:'0'),(h:output,i:(compiler:1,editor:1,fontScale:14,wrap:'1'),l:'5',n:'0',o:'%231+with+x86-64+gcc+(trunk)',t:'0'),(h:compiler,i:(compiler:cgsnapshot,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),fontScale:14,j:1,lang:___c,libs:!(),options:'-Wall+-W+-Wextra+-O2',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'x86-64+gcc+(trunk)+(Editor+%231,+Compiler+%231)+C',t:'0')),k:100,l:'4',m:100,n:'0',o:'',s:0,t:'0')),version:4

**Comment by wtarreau** [comment]
I managed to escape gcc's surveillance using asm statements like `asm("" : "+rm"(tmp));` but it's ugly and it obviously deoptimizes the code. I'll add -Wno-array-bounds for now, and once gcc11 is released we'll see if we can remove it.

**Comment by wtarreau** [comment]
Opened https://gcc.gnu.org/bugzilla/show_bug.cgi?id=98503 for this.

**Comment by TimWolla** [comment]
> Moreover, 100% of our lists and trees work like this.

They don't actually. Have you checked my patch: https://www.mail-archive.com/haproxy@formilux.org/msg39306.html?

Compare:

https://github.com/haproxy/haproxy/blob/23cc52d34b89fa1f2ec2c4b3ac1526bae84aff93/src/acl.c#L33-L35

and:

https://github.com/haproxy/haproxy/blob/23cc52d34b89fa1f2ec2c4b3ac1526bae84aff93/src/ssl_sock.c#L490

One embeds the `LIST_HEAD_INIT` into the outer structure, the other doesn't.

**Comment by wtarreau** [comment]
Yes I have looked, but it only hides the dust under the carpet. We use exactly zero byte outside the struct list. There is no reason for adding unneeded fat around that will never be dereferenced. Please have a look at the simplified reproducer on the gcc bug report (based on yours), it shows how the compiler is mistaken. It seems to me that it assumes that any field of a structure may be dereferenced as soon as a pointer to that structure is assigned, which is obviously wrong.

A quick check in the code shows me at least 53 global lists used like this:
```
$ git grep "^\(static\s*\)\?struct list" | wc -l
53
```

The only reason why this one pops out is because the distance between the pointer assignment and its dereferencing are close enough to let the compiler's optimizer see where it comes from. I'm not too much worried, given that the compiler is still in development phase with many bug reports opened around the same warning, and none of all the other ones have this problem. It will surely be addressed, which is why I preferred to file the report.

**Comment by wtarreau** [comment]
The issue was just confirmed and bisected by the gcc crew. I'll mark it invalid here since there's not much else we can do at this point (the warning was disabled in the makefile for now).

**Comment by chipitsine** [comment]
Can we keep it open not to forget to remove suppression once it is fixed on gcc side?

**Comment by wtarreau** [comment]
I'd rather not, we already have quite some noise here and we don't know how long it would have to stay open. In any case I'm subscribed to the gcc issue and will definitely not forget once I see it fixed.

**Comment by wtarreau** [comment]
Now worked around by slightly modifying the calling convention of the tlskeys_list_get_next() function. The warning was re-enabled so that we're safe again :-)
