### ISSUE TITLE
Haproxy 2.2.7 HAPROXY_CFGFILES is broken with Lua

### ISSUE THREAD

**Issue by khvzak** [haproxy/haproxy#1041]
## Detailed description of the problem

Haproxy rewrites env variable `HAPROXY_CFGFILES` while processing Lua.
## Steps to reproduce the behavior

On 2.2.7
```
$ haproxy -f haproxy1.cfg
lua.serve
```

On 2.2.6
```
$ haproxy -f haproxy1.cfg
haproxy1.cfg
```

## Do you have any idea what may have caused this?
http://git.haproxy.org/?p=haproxy-2.2.git;a=commit;h=a9bca65df7674d2091ad753bad4e689d76a4a9db

## What is your configuration?

haproxy1.cfg:
```
global
    lua-load test.lua

defaults
    mode http
    timeout connect 1s
    timeout client 3s
    timeout server 3s

listen http-in
    bind 127.0.0.1:8080
```

test.lua
```
core.register_fetches("get_fact", function () end)
core.register_service("serve", "http", function () end)
core.register_init(function ()
    print(os.getenv("HAPROXY_CFGFILES"))
end)
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.7-f10629d 2021/01/08 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.7.html
Running on: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
Build options :
  TARGET  = osx
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_THREAD=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
  DEBUG   =

Feature list : -EPOLL +KQUEUE -NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H -GETADDRINFO +OPENSSL +LUA -FUTEX -ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL -THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=1).
Built with OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
Running on OpenSSL version : OpenSSL 1.1.1i  8 Dec 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using:
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with clang compiler version 12.0.0 (clang-1200.0.32.28)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app


Darwin C02V37K2HTD8 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```

**Comment by capflam** [comment]
It is not a lua bug here. The chunk used to set the HAPROXY_CFGFILES env variable is a static trash chunk. The static trash chunks must not be reserved on large scopes, otherwise, there is no guarantee they will not be used in sub-functions. Here, it is reserved during the whole configuration parsing. It is far too large. A dynamic trash chunk must be used instead.

**Comment by wtarreau** [comment]
Ah and the code is confusing because what it calls "trash" is not the trash but one of the rotating ones, so it shadows the other one. In addition it's missing length checks when appending to the trash variable, so if you start with a large directory having 1k files or so, the total variable will exceed the 16kB limit and the final variables will be silently ignored.

I'm extremely surprised this has ever worked, considering that this wraps around the whole config parser (readcfgfile())! Chances are that setups which involve complex init or parsers will use these trashes. A quick `git grep --show-function` already reveals that the 51d module's init as well as any expression using a binary pattern will break it.

I don't really see any value in using a trash here, a realloc really is all that's needed (or even a lazy memprintf if desired, the cost will really not be noticeable).

**Comment by capflam** [comment]
Relying on memprintf is indeed a good idea. Here is a patch to fix this bug. I have just a doubt about the fatal error if the allocation fails. It is not really critical if the variable is not exported. In other hand, a memory allocation error is probably worst enough to exit.

[0001-BUG-MINOR-init-Use-a-dynamic-buffer-to-set-HAPROXY_C.patch.txt](https://github.com/haproxy/haproxy/files/5807997/0001-BUG-MINOR-init-Use-a-dynamic-buffer-to-set-HAPROXY_C.patch.txt)

**Comment by wtarreau** [comment]
I thought this variable was used by the master code on reloads but it is not. Maybe it used to be, I don't know. However if anyone relies on the file, it makes sense to ensure that it matches reality instead of silently failing to set some values. Also there's little risk of allocation error for strings, and as you say if it happens, better stop. BTW, better add a '#' in front of the issue number so that it's easily tracked. Looks good to me, thank you!

**Comment by capflam** [comment]
Ok thanks I'll push it (and add a "#" in front of the issue number).
