### ISSUE TITLE
TLS issue after upgrade haproxy 2.3.2

### ISSUE THREAD

**Issue by amolarote** [haproxy/haproxy#1056]
## Steps to reproduce the behavior

1. 
2. 
3. 

## What is your configuration?

```
(paste your output here)
```

## Output of `haproxy -vv` and `uname -a`

```
(paste your output here)
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by amolarote** [comment]
org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (javax.net.ssl.SSLException) caught when processing request: Received fatal alert: protocol_version

**Comment by amolarote** [comment]
Dear Team,

After upgrading haproxy 2.3.2 we are facing below issue.
org.apache.commons.httpclient.HttpMethodDirector executeWithRetry
INFO: I/O exception (javax.net.ssl.SSLException) caught when processing request: Received fatal alert: protocol_version

Centos 7.6
Java 1.7

**Comment by jmagnin** [comment]
Hi,

This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

If you believe you are indeed facing a bug, please take the time to provide the information requested in the bug report template.
