### ISSUE TITLE
shall we ignore status of "apt-get update" for github builds ?

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1062]
https://github.com/haproxy/haproxy/runs/1740517534

@TimWolla

**Comment by TimWolla** [comment]
I don't think so. A broken mirror indicates a much larger problem and I expect that GitHub / the mirror operator fixes these quickly. If the `apt-get update` fails then most likely the actual `apt-get install` will also fail due to outdated package lists (in fact we had that issue previously).

In fact the most recent push from William already succeeded to build.
