### ISSUE TITLE
Support Chunk Size > 2GB

### ISSUE THREAD

**Issue by MysticRyuujin** [haproxy/haproxy#1065]
## What should haproxy do differently? Which functionality do you think we should add?

According to the documentation HAProxy does not support chunk sizes (HTTP/1.1 Transfer-Encoding: chunked) greater than 2GB. I'm requesting a configurable setting that will allow me to increase that.

https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#8.5

## What are you trying to do?

I have multiple server application that are capable of generating up to 5GB of response data during some debug routines. `mode tcp` is not an option because it is an HTTP application and I need to be able to set/modify headers and perform other `mode http` things.

## Output of `haproxy -vv` and `uname -a`

See #1064 (same system)

**Comment by wtarreau** [comment]
You should be extremely careful with such large chunks. I remember discussions on the HTTP-WG where we were trying to decide whether or not the spec ought to enforce a hard limit on chunk sizes, and by then it was identified that 2^31-1 was already a hard limit for a non-negligible number of agents. That's probably when we upgraded our limit from 256M to 2G.

I think that now that most machines use 64-bit efficiently we could change the operations and switch this to 64b, but regardless your chunks are probably highly unreliable and it's very likely that your application will have to constantly rely on a front component to rechunk them for you. That's quite a strange design approach IMHO, given that chunks were made to send small buffer-sized pieces when the size is not known.

**Comment by MysticRyuujin** [comment]
Indeed, I agree that it is sub-optimal that single chunk sizes are so large, and I'm looking for ways to fix this. I'm coming at the problem from both ends 🙂  but I am surprised that this limit isn't configurable.

**Comment by wtarreau** [comment]
There would be no reason to make it configurable and slow everything down with yet another check, it's already set as large as permitted by the type. Going beyond the current limit requires some code modifications and audits to make sure we don't accidentely open a risk of overflow anywhere and introduce vulnerabilities. In any case I don't want to set it larger than 2^53 because some popular languages in web environments (JS) have this as a hard limit beyond which they start to lose in accuracy, and accepting larger values from them would mean accepting to process possibly bogus length. In any case once we're speaking about 10 petabytes per chunk, that should be enough for most requests :-)

**Comment by capflam** [comment]
@wtarreau, the unsigned integer used to parse the chunk size is only used in the parsing function (`h1_parse_chunk_size`). The result is immediately stored in a 64bits integer. Thus that should ease the audit and seems reasonable. Especially if we rework this part as planned to speed-up parsing of small chunks.

**Comment by wtarreau** [comment]
Yep I noticed this yesterday as well, forgot to update the ticket. We could simply turn this to u64 and make sure we don't get more than 13 digits (2^52) so that we're never fed possibly bogus values from languages that use floats for their integers. This would still permit 4 petabytes per chunk, this should be OK :-)

**Comment by capflam** [comment]
Fixed in 2.4-dev and will be backported as far as 2.2 soon
