### ISSUE TITLE
src/server.c: unused value suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1083]
```
5073                /* check if we can handle some connections queued at the proxy. We
5074                 * will take as many as we can handle.
5075                 */
    CID 1399857 (#1 of 1): Unused value (UNUSED_VALUE)returned_value: Assigning value from pendconn_grab_from_px(s) to xferred here, but that stored value is overwritten before it can be used.
5076                xferred = pendconn_grab_from_px(s);
5077        }
```

**Comment by wdauchy** [comment]
looks like a false positive with a quite complicated code path. I think @wtarreau can confirm as he was the last one to modify this line

**Comment by capflam** [comment]
It is indeed an unused value. But everywhere `pendconn_redistribute()` or `pendconn_grab_from_px()` are called in this function, the result is used to set `xferred` variable. So, It is probably better to set it as intentional because it is safer to do the same here to avoid future bugs if the code is led to change.

**Comment by chipitsine** [comment]
I've marked as intentional
