### ISSUE TITLE
src/http_fetch.c: uninitialized variable suspected by coverity (new finding)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1087]
```
797        smp->data.type = SMP_T_STR;
 798        smp->flags |= SMP_F_VOL_HDR | SMP_F_CONST;
    CID 1445801 (#1 of 1): Uninitialized scalar variable (UNINIT)10. uninit_use_in_call: Using uninitialized value name when calling http_get_htx_fhdr. [show details]
 799        if (http_get_htx_fhdr(htx, name, occ, ctx, &smp->data.u.str.area, &smp->data.u.str.data))
 800                return 1;
 801        smp->flags &= ~SMP_F_NOT_LAST;
 802        return 0;
 803}
```

**Comment by capflam** [comment]
`name` variable is always set here because `args` is never NULL. I suspect there are some extra checks on `args` variable in sample fetches because it may be called by hand with no argument. And indeed, in the stick-table code, there are calls to `smp_fetch_src()` with `NULL` as arguments. But `empty_arg_list` must be used instead. For me, when a sample fetch or a sample converter is called,`args` must always be set. Some cleanup must be performed to avoid any ambiguities.

**Comment by capflam** [comment]
It should be fixed now.
