### ISSUE TITLE
Add lua action support to `tcp-request session`

### ISSUE THREAD

**Issue by phemmer** [haproxy/haproxy#113]
## What should haproxy do differently? Which functionality do you think we should add?

HAProxy should be able to execute Lua functions as part of `tcp-request session`.

## What are you trying to do?

My use case is to log SSL data at the start of the connection of an http frontend. I want to emit a separate log line, independent of the normal http request log.

As HAProxy's native log functionality does not support this, my intention is to trigger a Lua function which can emit the log. However this function should only trigger at the start of the SSL session, not on every request. Currently HAProxy only has the ability to trigger Lua functions as part of `http-request` and `tcp-request content`, which both trigger on every http request.

With http/1 I could use `http_first_req` as a condition when triggering the action. However `http_first_req` does not work with http/2.

Thus the feature request is to add the ability to invoke Lua function as an action from `tcp-request session`.

&nbsp;

Ref mailing list discussion: https://www.mail-archive.com/haproxy@formilux.org/msg34015.html

**Comment by wtarreau** [comment]
I'm now figuring it will not be easy at all as Lua requires a stream context which doesn't exist at the session layer :-(

For your use case Patrick, maybe you could instead use a session variable. Basically you would use a variable "sess.first_req_done" in your HTTP rules. You'd decide to perform the operation if the variable is not set, then you set it to one. All other requests will see it set and that will be done. And as a benefit it will really be the first *processed* request which will perform the operation, not necessarily the first one on the wire.

**Comment by phemmer** [comment]
> I'm now figuring it will not be easy at all as Lua requires a stream context which doesn't exist at the session layer :-(

I had a suspicion that might be the case.

> For your use case Patrick, maybe you could instead use a session variable. Basically you would use a variable "sess.first_req_done" in your HTTP rules. You'd decide to perform the operation if the variable is not set, then you set it to one. All other requests will see it set and that will be done.

Indeed, this is essentially what I ended up doing as an interim solution.

But this makes me think that if I can implement such functionality manually, should `http_first_req` not work the same?

**Comment by wtarreau** [comment]
On Fri, Jun 07, 2019 at 10:59:39AM -0700, Patrick Hemmer wrote:
> But this makes me think that if I can implement such functionality manually,
> should `http_first_req` not work the same?

That's an interesting question. http_first_req is (historically) a proper
of the stream. We could imagine moving that to the session. However one
difficulty remains which is to decide which stream will see it first.

We could very well imagine for example that the first stream to be processed
is declared the first one but that it calls a yielding sample fetch causing
another one to be executed in parallel and completed first. This last one
would then not have matched and you'd get the same problem again.

The real issue is the lack of atomicity between the observation (calling
http_first_req) and the action (whatever you want to do afterwards). We
could imagine that the first to fetch it resets it but it would break
some configs doing stuff like :

     http-request add-header foo foz if { http_first_req }
     http-request add-header bar baz if { http_first_req }

Maybe we should change the paradigm and create a new one explicitly
documented as matching only once per session. We could call it
"once_per_session" for example. Or better, we could have a per-session
counter that is incremented when it's fetched. You could then even use
it to assign numbers to your streams as they are processed.

Willy

**Comment by git001** [comment]
@phemmer is this issue still valid or can it be closed?

**Comment by git001** [comment]
@phemmer is this issue still valid or can it be closed?
