### ISSUE TITLE
Add new server during runtime via cli

### ISSUE THREAD

**Issue by a-denoyelle** [haproxy/haproxy#1136]
This note is created to track the progress of dynamic server creation via a new cli command. The general idea is to be able to add new servers during runtime execution via a new cli command, probably by reusing a syntax similar to the server line in the configuration file.

```add <backend>/<server> [params...]```

A special care must be taken for the limitations which will reject the creation of a new server. Here is a first list.
- invalid proto specified as opposed to the backend mode
- undefined port but load balancing algorithm is rdp-cookie
- cookie or redir defined but backend mode is tcp
- server ip address set to 0.0.0.0 and defined via a http header but backend mode is tcp
- server name already registered for the backend
- track activated on an unknown server/no check in the track chain/tracked server with different disable-on-404 statement
- dynamic cookie generated with the same value as another server
- the load balancing hash method must be consistent, to avoid to remap all clients as soon as a new server is added

**Comment by wdauchy** [comment]
wow what a revolution :+1: happy to read that one!

**Comment by wtarreau** [comment]
I think we can even be stricter on certain restrictions by rejecting stuff that's usually not used in such situations. E.g. instead of checking "redir" vs "tcp" we can simply reject "redir". We should even start by not supporting rdp-cookie LB at all, as it requires that the backend knows all the servers list and that's definitely not a primary targetted use case.

Adding a tracking at run time could be challenging because you need the state to be synchronized with the one of the server you're tracking. We can probably start without supporting it.

Dyncookie is interesting to support but may indeed present some difficulties.

**Comment by a-denoyelle** [comment]
FYI, a first implementation of the feature has been landed in the recent 2.4-dev13. Currently, only a small subset of server keywords is supported. This feature has been marked as experimental. For all interested users here, do not hesitate to test it and report your impression. If you miss some important keywords, feel free to mention it so that it will guide our next priorities.

**Comment by anitgandhi** [comment]
I tested this out on version 2.4.0, overall it worked well!

Couple points of feedback based on our use-cases:

1. supporting the `track` keyword - we have a variable number of backends, but in order to de-duplicate health checks, we make a standalone "dummy_health" backend that handles all health checking, and all other backends simply track that one.

2. some option for inheriting from existing `default-server` configuration would be ideal as well; we use that to consolidate all the common options.
    1. with that, our server lines in our config file essentially are just `server <name> <IP_address>:<port> track dummy_health/<name>`

Excited to see how this develops further!

**Comment by a-denoyelle** [comment]
@anitgandhi thanks for your feedback !
Regarding your remarks, here are my answers.

1. ssl support for dynamic servers has just been merged in the development tree. The next step will be to implement checks. But I will probably start by just implementing the 'track' keyword as it should be quick and with a nice benefit for you and other users.

2. we have chosen to not inherit any statement from default-server for dynamic servers. The reason is that in many environment where dynamic servers will be used, the configuration is unknowned to the user and it will be a surprise to see some statements activated on a newly server without being explicitly specified on the CLI. Also, as this feature will probably be used through automatisation, it shouldn't really be a problem to specify the options via a script. That said, if the need is still present for many users, we might reconsider this and find an alternative solution.

**Comment by anitgandhi** [comment]
1. sounds good!

2. > it will be a surprise to see some statements activated on a newly server without being explicitly specified on the CLI.

I agree with this sentiment. 

While it is easy to do via automation, I feel that there are still use cases where you have a dynamic number of frontends/backends with different configs, but they all use the same "farm"/"pool" of servers, which are all configured identically, with things like `default-server` in the `backend` and even `defaults`. 

Perhaps a good middle ground could be another dynamic `server` keyword like `inherit-defaults`, where, if that keyword is provided on the runtime api call, it will inherit all existing `default-server` configurations in the backend. 

That way, it doesn't automatically opt people into surprising behavior, but still allows those that need the simplicity to not need to do extra work.

**Comment by wtarreau** [comment]
We were thinking probably the other way around, like mentioning in the backend that `default-server` can be reused, or using a `default-dynamic-server` directive which would apply to dynamically added servers, which will probably restrict what can be used there. Because one of the difficulties is that there will possibly not be a perfect 1:1 match between what is permitted in the config and the CLI, so if some settings are present in a `default-server` keyword that cannot be used by a dynamic server, this will be even more confusing.

**Comment by a-denoyelle** [comment]
An update here to notify interested people : dynamic server features have been extended in the current development tree, with support of ssl and check/track. Feel free to test the master branch if you can to report any comments/issues.

**Comment by wtarreau** [comment]
Thanks. We'll have to issue dev4 in a day or two for a number of fixes, it will be a great opportunity to help testing these new features.

**Comment by Darlelet** [comment]
This feature is now stable since 2.6, should we close this issue? cc @a-denoyelle

**Comment by a-denoyelle** [comment]
Sure let's do it.
