### ISSUE TITLE
Add base directory for map files

### ISSUE THREAD

**Issue by Mo3m3n** [haproxy/haproxy#1198]
## What should haproxy do differently? Which functionality do you think we should add?

Provide a directive to specify a base directory for map files, similar to what we already use for ca,crt,server-state ([ca-base](https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#ca-base), [crt-base](https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#crt-base), [server-state-base](https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#server-state-base)).
This way a user can reference a map file via path relative to the base directory instead of an absolute path

## What are you trying to do?

Working in an environment where a user only knows the map name but not the absolute/relative path of the map. So when this user provides haproxy directives he can only reference the map by its name.

**Comment by wtarreau** [comment]
I think it makes sense, but it will also apply to ACL files. We could think a bit further, with crt-lists and possibly other files loaded at boot time (I think we already have a lua-load-path). I suspect that most users would in fact need to be able to use a default prefix corresponding to the location where haproxy config files are stored. Maybe we can think about an option that would make all paths relative to the config file itself. It would probably be very convenient because it would mean that an archive containing a config file and its accompanying files would always work. What do you think ?

**Comment by Mo3m3n** [comment]
>  Maybe we can think about an option that would make all paths relative to the config file itself.

I think this is going to be helpful and address more use-cases than what I have reported above. Actually I have even thought about doing smth similar, by running haproxy in the same location as haproxy config to be able to use a default prefix. So it will be convenient to have an option for this.

**Comment by TimWolla** [comment]
> I think we already have a lua-load-path

The lua-load-path should remain independent, because it is about the Lua *library* path and not necessarily related to the HAProxy configuration itself (you would not store the libraries in `/etc`).

**Comment by wtarreau** [comment]
OK, I'm always confused in that I believe it's about portable Lua libraries (i.e. .lua or .lc files). For these ones it could make sense for a hosting provider to allow their customers to provide a tar.gz containing the config files and all required dependencies.

**Comment by wlallemand** [comment]
It depends, you could have .lua but also .so libraries.
For example on my dev setup I have:
```
 lua-prepend-path /opt/lua-5.4.2/share/lua/5.4/?.lua
 lua-prepend-path /opt/lua-5.4.2/lib/lua/5.4/?.so cpath
```

It's useful for people using 3rd party lua libraries which can be installed manually or with luarocks.

**Comment by TimWolla** [comment]
> OK, I'm always confused in that I believe it's about portable Lua libraries (i.e. .lua or .lc files).

Both. `lua-prepend-path` (there is no `lua-load-path`) can be used for both pure Lua as well as C libraries. I was the person that added that directive for use with my haproxy-auth-request script that depends on haproxy-lua-http:

https://github.com/TimWolla/haproxy-auth-request#usage
https://github.com/TimWolla/haproxy-auth-request/blob/6736c7cb042ff8a860c69d7451ccb1a938846036/test/allow.vtc#L19-L20
https://github.com/TimWolla/haproxy-auth-request/blob/6736c7cb042ff8a860c69d7451ccb1a938846036/auth-request.lua#L25

**Comment by wtarreau** [comment]
OK in this case it remains absolute anyway. BTW I remembered pretty well it came from you :-)

I'm thinking about adding something like this:
```
    relative-path { current | config | parent }
```
It would specify how to handle relative paths for files.
- current => relative to CWD, what is currently done
- config => relative to config file
- parent => relative to config file's parent directory

We could even make sure that all unix-path-prefix and whatever are relative to this one when not starting with a '/' so that it really works like a "cd" to the directory.

I too am really suffering from the current behavior when developing. I cannot for example do "./haproxy -f ../haproxy/test.cfg" because it will load the certs and maps from the wrong place, so I'm forced to develop from the wrong directory and instead do "../haproxy/haproxy-2.3 -f test.cfg" which is annoying.

With such a solution I could finally start to put "relative-path config" in all of my test configs so that they finally are relocatable.

**Comment by wtarreau** [comment]
Marking as fixed and closing since now done.
