### ISSUE TITLE
gRPC backend showing as down with 'reason: Socket error'

### ISSUE THREAD

**Issue by nkn1111** [haproxy/haproxy#1214]
## Detailed description of the problem
The gRPC backend is showing as down in the HAproxy stats page and requests are not being proxied to gRPC server. However, the gRPC server is up and running and is able to serve when connecting directly.

## Expected behavior
The defined backend should be available without having an socket error.

## Do you have any idea what may have caused this?
Any missing configuration?
## Do you have an idea how to solve the issue?
No
## What is your configuration?

```
---CUT---
defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000
  retries 3
  option redispatch
  maxconn 2000
  option httpchk
  option http-use-htx

frontend stats
  bind *:1900
  stats uri /haproxy?stats

frontend grpc-frontend
   bind *:2005 proto h2
   default_backend grpc-backend

backend grpc-backend
  balance roundrobin
  server grpc-server-ha1 172.16.28.83:XXXX check proto h2
  server grpc-server-ha2 172.16.28.60:XXXX check proto h2
```

## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.2.10-6a09215 2021/03/03 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.10.html
Running on: Linux 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=15).
Built with network namespace support.
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-36)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

## If HAProxy crashed: Last outputs and backtraces

```
 [WARNING] 095/081338 (23914) : Server grpc-backend/grpc-server-ha1 is DOWN, reason: Socket error, check duration: 17ms. 0 active and 0 backup serve
 [NOTICE] 095/081338 (23914) : haproxy version is 2.2.10-6a09215
 [NOTICE] 095/081338 (23914) : path to executable is /usr/local/sbin/haproxy
 [ALERT] 095/081338 (23914) : sendmsg()/writev() failed in logger #1: No such file or directory (errno=2)
 [ALERT] 095/081338 (23914) : backend 'grpc-backend' has no server available!
```

**Comment by Mo3m3n** [comment]
You are using an incompatible health check.
In your defaults section you are using [option httpchk](https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#4-option%20httpchk) and as mentioned in docs this about HTTP/1.x
You can either:
- Remove `option httpchk`, so haproxy is going to perform the default TCP check.
- Add `check-proto h2` to your server lines to perform HTTP2 health checks.

**Comment by capflam** [comment]
By default the server protocol is used for health-checks. Thus, they will be performed in H2. `check-proto` is used to use a different protocol than the server's one. Here the `Socket error` means a connection error was caught very early. @nkn1111, if you remove the health-check, are you able to send traffic to your backend servers though HAProxy ?

**Comment by capflam** [comment]
Ok, I got it. In HTTP/1.1 and above, the `Host` header is mandatory. Most of time, it is not an issue in HTTP/1.1 because servers don't complain. But in HTTP/2, it is usual to have an error if there is no `:authority` pseudo-header nor `Host` header. Of course, setting `:authority` pseudo-header is cleaner but it is not possible for now with the health-checks. Thus, you must set a `Host` header.
@nkn1111, could you try to add a `http-check send` line setting the host header ? For instance:
```
option httpchk
http-check send meth OPTIONS uri / ver HTTP/2 hdr Host some.header
```

**Comment by capflam** [comment]
Just an update, you may also choose to send a absolute form request, this way the `:authority` and `:scheme` pseudo-headers are set : 
```
option httpchk
http-check send meth OPTIONS uri http://some.header/ ver HTTP/2
```

**Comment by nkn1111** [comment]
I was able to use a `listen` block as a workaround for this. This config is working for my case. Not sure if this is the best practice. Please let me know if there is an issue using the `listen` block instead of the frontend and backend.

```
listen hap-grpc
                bind *:2005 proto h2
                mode http
                timeout client  10800s
                timeout server  10800s
                balance roundrobin
                option http-use-htx
                option tcp-check
                option allbackups
                server grpc-server-ha1 172.16.28.83:XXXX proto h2 check
                server grpc-server-ha1 172.16.28.60:XXXX proto h2 check
```

**Comment by capflam** [comment]
It is not related to the `listen` section versus `backend` section. In your example, you have configured TCP health-checks.

**Comment by nkn1111** [comment]
Alright, I got it! In the `listen` block am using `option tcp-check` which overrides the `option httpchk` in the default. The backend should also work if I use `option tcp-check`, right? 
Anyhow am happy with the listen block. 👍   Thanks for helping out. 😃

**Comment by capflam** [comment]
That's it, options set in the frontend/backend/listen section always override the default ones. Thus, if you enable TCP health-check in your backend via `option tcp-check`, this will work. However, this only validates the connection to the server.  It is far from a full HTTP check. If you are ok with that, it is not a problem. But you must understand the difference to make a choice.

I guess this issue is solved now. I'm closing it.

**Comment by Mo3m3n** [comment]
@capflam 
Does it make sense to change the default behavior of `option httpchk` so it sends a `Host` Header by default  (the one in the request)?
Because ideally users just want H2 to work out of the box without having to configure too many stuff.
Sending the Host header by default should be compatible I guess with HTTP/1.0 and HTTP/1.1

**Comment by capflam** [comment]
You should configure the request to send via `http-check send` directive or use the default one (OPTIONS / HTTP/1.0). There is no Host by default because there is no good value to set. It may be set using the server IP, but I guess we should also add the port if it is not a default port (not 80 nor 443). And if we add a host header, we should also be sure to use the sni name if set for SSL connections. Honestly it is not an easy task to choose the right value to make most of users happy.

Also note the Host header must be set for HTTP/1.1 health-checks. Some servers will reply with an error if there is no Host header. So it is not a new issue and it is not specific to H2.

**Comment by MiraD1n** [comment]
It took me a long time to fix it, so I decided to leave a comment here.
I used this block from [this documentation.](https://severalnines.com/resources/whitepapers/mysql-load-balancing-with-haproxy/) 
```
  listen  haproxy_192.168.55.110_3307
        bind *:3307
        mode tcp
        timeout client  10800s
        timeout server  10800s
        balance leastconn
        option tcp-check
        tcp-check expect string is\ running.
        option allbackups
        default-server port 9200 inter 2s downinter 5s rise 3 fall 2 slowstart 60s maxconn 64 maxqueue 128 weight 100
        server galera1 192.168.55.111:3306 check
        server galera2 192.168.55.112:3306 check
        server galera3 192.168.55.113:3306 check
```
