### ISSUE TITLE
acl with path_beg returns HTTP 403 if path begins with `/.`

### ISSUE THREAD

**Issue by chrissound** [haproxy/haproxy#122]
```
    frontend http-in
        log /dev/log local0 info
        option httplog

        bind *:80
        acl letsencrypt-acl path_beg /.abc/
        use_backend letsencrypt-backend if letsencrypt-acl


        default_backend trycatchchris
```

```
* Expire in 150000 ms for 3 (transfer 0x15fc470)
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /.abc/ HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 403 Forbidden
< Transfer-Encoding: chunked
< Date: Sun, 16 Jun 2019 11:40:46 GMT
< Server: Warp/3.2.26
< Content-Type: text/plain
< 
* Connection #0 to host localhost left intact
```

I expect it to instead route to `letsencrypt-backend`.

**Comment by TimWolla** [comment]
> Server: Warp/3.2.26

The 403 is not generated by HAProxy, but by your backend.

> I expect it to instead route to `letsencrypt-backend`.

Can you show the backend configuration and possibly the relevant log line for the request in question?

**Comment by chrissound** [comment]
acl letsencrypt-acl path_reg ^/.abc/

Same issue.

Here is the whole config:

```
global
        maxconn 1024
        tune.ssl.default-dh-param 2048

    defaults
        mode http
        timeout connect 5000ms
        timeout client 50000ms
        timeout server 50000ms


    frontend http-in
        log /dev/log local0 info
        option httplog

        bind *:80
        acl letsencrypt-acl path_reg ^/.abc/
        use_backend letsencrypt-backend if letsencrypt-acl


        default_backend trycatchchris

    backend letsencrypt-backend
        server letsencrypt 127.0.0.1:8888

    backend trycatchchris
        option redispatch
        option forwardfor 
        server server1 127.0.0.1:3000 maxconn 32 # nginx cache
```

**Comment by chrissound** [comment]
If I change path_beg to /abc/ it works correctly - I get a 404 (from my backend).

**Comment by chrissound** [comment]
Ohhhh you're right @TimWolla ... Hmmm.. Will have to check this again as I tried setting up a minimal example in this particular case.

**Comment by TimWolla** [comment]
To me it sounds like that HAProxy is properly routing the request to your backend, but _your backend_ is unable to handle requests starting with a `.` (responding with 403). You should **fix your backend** then.

With your example configuration HAProxy logs that it attempted to use the `letsencrypt` backend for me:

```
127.0.0.1:39174 [16/Jun/2019:13:56:06.583] http-in letsencrypt-backend/letsencrypt 0/0/-1/-1/3002 503 237 - - SC-- 1/1/0/0/3 0/0 "GET /.abc/ HTTP/1.1"
```

Thus I'm closing this issue as “invalid”. If you need help configuring HAProxy to your needs please ask on the mailing list, on Discourse or in the IRC. If you believe you *actually* found a bug then please open a new issue and fill in the complete template instead of deleting it.
