### ISSUE TITLE
HA-Proxy version 1.8.24 2020/02/15 not send access log to /dev/log

### ISSUE THREAD

**Issue by letnab** [haproxy/haproxy#1237]
HA-Proxy version 1.8.24 2020/02/15 not send access log to /dev/log

`journalctl -f -u haproxy
-- Logs begin at Пн 2021-04-26 21:01:39 MSK. --
апр 27 13:00:15 node02.local haproxy[10715]: Proxy 1-OUT started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy 2-OUT started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy SSL started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy NOCHECK-SSL started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy check-SSL started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy deer started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy deru started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy 001-IN started.
апр 27 13:00:15 node02.local haproxy[10715]: Proxy 20001-IN started.
апр 27 13:00:15 node02.local systemd[1]: Started HAProxy Load Balancer.`
without access logs
package rh-haproxy18-haproxy-1.8.24-3.el7.x86_64

**Comment by lukastribus** [comment]
Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
