### ISSUE TITLE
getting stats from nbproc > 1

### ISSUE THREAD

**Issue by imbosser** [haproxy/haproxy#125]
Hi all, any way to get metrics when haproxy is configured as nbproc > 1?
I try to get metrics via unix socket but just received a half statistics compare to reality.

**Comment by wtarreau** [comment]
Since 1.8 threads are available so that you don't need nbproc anymore. If you're running on an older version (or even just 1.8 since by then they were not very scalable to be honest), you can still have a look at the following tools which are designed to work with large deployments and which support multi-process mode:

  https://github.com/unixsurfer/haproxystats
  https://github.com/unixsurfer/haproxytool
  https://github.com/unixsurfer/haproxyadmin

The main point is that you need to have one "stats socket" per process and pass the "process X" directive on their respective lines so that each socket exclusively sees one process.

I'm closing this issue since it doesn't match a particular bug nor corresponds to any expected improvement, but do not see anything negative in this :-) If you need more info or to exchange with other users, better ask for help on the mailing list.
