### ISSUE TITLE
Rewrite endpoint backend with haproxy

### ISSUE THREAD

**Issue by matty111** [haproxy/haproxy#1264]
I have 1 backend and 1 frontend with these endpoints:

Http://backend.com
Http://frontend.com
Frontend calls backend a this api, but i want use always only endpoint of the frontend.

For example backend.com must become frontend.com/api.

I tried with acl but this doesn't work.

Ha proxy works for this problem?

**Comment by lukastribus** [comment]
Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
