### ISSUE TITLE
Load balancer issue with sticky affinity and round/robin or least connection resetting after endpoint reload

### ISSUE THREAD

**Issue by DME-PEGA** [haproxy/haproxy#1282]
Greetings and Salutations,
I noticed an odd behavior at a client site. They have one enterprise HAProxy for all their K8 applications/service offerings. For applications that use sticky affinity cookie based - you have the option to use round robin/least connections as your load balancing policy.

Whenever HAProxy reloads endpoints (an endpoint/pod is removed or added or it just refreshes) - The state of both round robin/least connections is reset. Since this can happen 500ms-5seconds a time - it effectively makes round robin/least connections useless since it resets to the first path for round robin and it resets the connection counts for least connections.

I consider this a bug.

The application using HAProxy is state-full - the end reset of the position/metric loss is profoundly unbalanced traffic since every 500m-5s - traffic is reset and the first endpoint receives the traffic. For a state-full applicatin - they are placed on that endpoint and will never leave it until it blows up by being driven past capacity.

Is there a setting that will stop this behavior - or is this a bug - or is this some sort of feature?
I see no practical advantage to resetting the load balancing statistics on every reload of endpoints.

At an enterprise level with PODS spinning up like crazy - this behavior destroys load balancing.
Best Regards,
Dean

**Comment by wtarreau** [comment]
You didn't say the most important. How do you add your servers (or "endpoints") ? The load balancing algorithms are particularly picky about maintaining the smoothest load balance between all servers and this "reset" mechanism not only doesn't exist, but in addition is part of the reasons why the algorithms are complex.

Or maybe you restarting a new process each time something changes ? If so, for sure, a new process is a fresh new one, and this action will destroy load balancing. But in such a case I'd rather suggest to use alternative methods like using a more capable API that can enable pre-provisioned servers at run time, or if for any reason you couldn't, then use a more suitable "random" algorithm instead.

**Comment by DME-PEGA** [comment]
I don't understand the question :)  This is a client that uses K8 with multiple applications that scale up and down.  If HAProxy resets the metrics - then this blow up.  Client uses HAProxy and an enterprise tool - so pods come and go like wild.  What is the question? :) #

**Comment by DME-PEGA** [comment]
> I don't understand the question :) This is a client that uses K8 with multiple applications that scale up and down. If HAProxy resets the metrics - then this blow up. Client uses HAProxy and an enterprise tool - so pods come and go like wild. What is the question? :) #

**Comment by DME-PEGA** [comment]
And who are you to say this isn't triage?

**Comment by DME-PEGA** [comment]
I have a client with  in stress with this junk - you have solutions - let us know.

**Comment by chipitsine** [comment]
You open a ticket for open source HAProxy. However, you state that you use enterprise edition.

Shouldn't enterprise edition has its own support channel?

**Comment by wtarreau** [comment]
I must confess I'm even more confused now than I was on the first question, I suspect it will be hard to make forward progress on this one :-/

@DME-PEGA the question is: "how does your client add/remove servers". What "enterprise tool" do they use to inform haproxy about the changes, and how does this tool apply the changes? Please report the output of "show info" from the stats socket, I suspect we'll see a very short process uptime, indicating that your client spends their time rebooting haproxy. If that's the case, it's just as if they were complaining that every time they reboot their load balancer, the first server is used and they'd rather use a different one upon each boot. That's why I said that if (for any reason) they can't refrain from reloading all the time, then they should rather use "balance random" rather than "balance roundrobin".

**Comment by jmagnin** [comment]
Hello,

> And who are you to say this isn't triage?

I'm not sure why you complain about the needs-triage tag being removed, it's not like it means your issue is not looked at.  adding an invalid tag would mean that.  

> I consider this a bug.

If you consider this a bug, you should fill a proper bug report. When you create an issue for a bug report, there is a template that you have to fill, so as to provide enough information for developers to work on the report. You ignored that template.

> They have one enterprise HAProxy for all their K8 applications/service offerings. 

They can reach out to support@haproxy.com for enterprise level support, and feel entitled like you do because they pay for support.

**Comment by DME-PEGA** [comment]
Greetings,
I was just pointing out behavior (load balancer gets reset on pods being added and removed).  Thank you for your time.
Best Regards, Dean
