### ISSUE TITLE
No Host header accepted in 1.1 requests

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [haproxy/haproxy#1299]
## Detailed description of the problem

When Haproxy receives a 1.1 request without a `Host` header, the request is accepted and forwarded onward. Example request:

```
GET / HTTP/1.1
Connection: close

```

## Expected behavior

According to RFC 7230 Haproxy should instead respond with 400 Bad Request:

```
   A server MUST respond with a 400 (Bad Request) status code to any
   HTTP/1.1 request message that lacks a Host header field and to any
   request message that contains more than one Host header field or a
   Host header field with an invalid field-value.
```
Source: last paragraph of https://datatracker.ietf.org/doc/html/rfc7230#section-5.4

## Steps to reproduce the behavior

1. Start Haproxy with the config below: `haproxy -f config.cfg`
2. Start a listener on port 5000: `nc -lvnp 5000`
3. Send a request without `Host`-header to port 8080: `echo -en "GET / HTTP/1.1\r\nConnection: close\r\n\r\n" | nc localhost 8080`

You can see that the request turns up in stdout of the listener. Haproxy didn't reject the request.

## Do you have any idea what may have caused this?

Nope

## Do you have an idea how to solve the issue?

Reject requests without `Host` headers.

## What is your configuration?

```
# https://cbonte.github.io/haproxy-dconv/2.3/configuration.html#2.5
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

listen http-in
    bind *:8080
    server server1 localhost:5000 maxconn 32
```

## Output of `haproxy -vv` and `uname -a`

`haproxy -vv`:

```
HAProxy version 2.4.1-1ce7d49 2021/06/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.1.html
Running on: Linux 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

`uname -a`:
```
Linux hostname 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

(Found by Mattias Grenfeldt and Asta Olofsson)

**Comment by TimWolla** [comment]
> A server […]

HAProxy is not a server, but a gateway as defined in RFC 7230#2.3, thus my understanding is that this paragraph does not apply to HAProxy.

You can achieve your desired behavior using:

```
http-request deny deny_status 400 unless { req.hdr(host) -m found }
```

or

```
http-request deny deny_status 400 unless { req.hdr_cnt(host) eq 1 }
```

**Comment by mattiasgrenfeldt** [comment]
Yes, HAProxy is a gateway. But a gateway is a server:

> A "gateway" (a.k.a. "reverse proxy") is an intermediary that acts as an origin server for the outbound connection [...]
> All HTTP requirements applicable to an origin server also apply to the outbound communication of a gateway. [...]

Source: https://datatracker.ietf.org/doc/html/rfc7230#section-2.3

So the requirement still applies to HAProxy

**Comment by lukastribus** [comment]
I'm not sure whether we should blindly follow the RFC suggestion in this case, it is unclear what the benefit is in the haproxy scenario. It certainly breaks the robustness principal. This needs careful consideration.

**Comment by wtarreau** [comment]
Actually the requirement for Host for gateways remains a gray area, given that an empty Host header is explicitly permitted. We've been supporting the missing Host header essentially for legacy reasons (as inserting a gateway between a client and a server is never as transparent as you might think), and as Lukas says, the benefit is moot there. What we ought to do though in such a case is to emit an outgoing request with an empty Host header.

Additionally, when you're a gateway, you can speak different versions on the two sides, so you're not an HTTP/1.0 or HTTP/1.1 gateway. We can for example receive HTTP/1.0 requests and pass them to 1.1 or even to 2.0. So that's where the distinction between 1.0 and 1.1 regarding Host becomes blurry: you could technically pretend to be a 1.0 gateway receiving a 1.1 request lacking a Host but being 1.0 you don't care, then you forward it to 1.1 on the other side (with an empty host admittedly).

We at least need to make sure that we always emit the authority (even if void) on 1.1 output though.

**Comment by wtarreau** [comment]
By the way regarding the rule, please note "outbound" in the text's spec. What a gateway is bound to is to properly format its output responses (and output requests of course). The vast majority of gateways outthere are in fact half-way between a tunnel and a gateway due to interoperability necessities.

**Comment by mattiasgrenfeldt** [comment]
>Actually the requirement for Host for gateways remains a gray area, given that an >empty Host header is explicitly permitted.

In what way are the requirements for a gateway a gray area regarding the Host header? A gateway should act like a server should act. Is there a behavior that servers should have regarding the header that becomes problematic when applied by a gateway?

You seem to be thinking about "outbound" as "output from the gateway", but the spec defines "outbound" as "towards the client":

> [...] The terms "inbound" and
> "outbound" are used to describe directional requirements in relation
> to the request route: "inbound" means toward the origin server and
> "outbound" means toward the user agent.

Yes, there are not "1.0-gateways" or "1.1-gateways", there are rather gateways that are capable of handling different versions of HTTP. And HAProxy handles both 1.0 and 1.1. As you say, HAProxy could act as a 1.0 gateway when receiving 1.1 requests, and then the Host header would be lost. But would/does HAProxy ever do that? What would be the advantage of doing that?

If you want to keep backwards compatibility with 1.1-clients that don't send Host headers, why not do just that: switch to 1.0 parsing when receiving 1.1-requests without a Host header. Instead of trying to continue speaking 1.1 with a client that has shown that it doesn't implement 1.1 correctly.

**Comment by wtarreau** [comment]
> In what way are the requirements for a gateway a gray area regarding the Host header? A gateway should act like a server should act. Is there a behavior that servers should have regarding the header that becomes problematic when applied by a gateway?

The reality is that a gateway has to adapt to both the client and the server. It's way easier to impose a version of a protocol when you are an endpoint. The gateway has no protocol since it's neither a recipient nor a sender. It just relays between two sides, doing its best to make sure both sides understand each other even when they don't speak the same version, while always keeping in sync with them to make sure there's never any risk of smuggling attack.

It doesn't use the host header for itself, it passes it on the other side which decides what to do if it's missing. Here if haproxy doesn't make use of a host header and there is no impact from not having it, it can pass the request to the next hop which will decide if it likes it or not.
 
> You seem to be thinking about "outbound" as "output from the gateway", but the spec defines "outbound" as "towards the client":
> > [...] The terms "inbound" and
> > "outbound" are used to describe directional requirements in relation
> > to the request route: "inbound" means toward the origin server and
> > "outbound" means toward the user agent.

For having participated quite a bit to this spec, I think understand well enough what it says, and as I already mentioned above, what the gateway is bound to is to respecting the spec for outbound traffic, which we do.

> Yes, there are not "1.0-gateways" or "1.1-gateways", there are rather gateways that are capable of handling different versions of HTTP. And HAProxy handles both 1.0 and 1.1. As you say, HAProxy could act as a 1.0 gateway when receiving 1.1 requests, and then the Host header would be lost. But would/does HAProxy ever do that? What would be the advantage of doing that?

No that's the opposite. It could receive 1.0 requests missing a Host header, and have to pass them to an 1.1 server. Or it could receive 1.1 requests that come out of an 1.0-to-1.1 gateway that advertise 1.1 only to support chunked encoding, which passed through another gateway that lost the empty Host header. You could say that we ought to block that but it's not our business to decide what the upstream server ought to accept, particularly if in the end that server is 1.0 and ignores Host.

> If you want to keep backwards compatibility with 1.1-clients that don't send Host headers, why not do just that: switch to 1.0 parsing when receiving 1.1-requests without a Host header. Instead of trying to continue speaking 1.1 with a client that has shown that it doesn't implement 1.1 correctly.

But what exactly is the problem you're trying to solve here ? 1.0 vs 1.1 is way more than just a Host header field. It's about message delimitation, supported methods etc. If we'd decide to stop speaking to agents that do not implement HTTP correctly, nobody would speak to anyone anymore. You probably know the classical mantra of RFCs: "be liberal in what you accept and be strict in what you send".  That's the basics of interoperability. If one agent doesn't strictly respect something we're not interested in, we won't ban it for that.

Think about a compression gateway for example. It doesn't need the Host header *at all*. It only acts on responses once it knows both sides can process them. Why would one want to implement extra useless rules there to verify if the client properly formats certain header fields, options etc if it doesn't use them ?

**Comment by mattiasgrenfeldt** [comment]
Okay, I understand now the approach that HAProxy takes. Thanks for taking the time to write about this.

While there are some details that I don't fully understand, I also know that all of you have a lot more experience than I do and I don't want to waste your time further.

> But what exactly is the problem you're trying to solve here ?

I should have been more clear about this in the beginning. For the last couple of months me and Asta Olofsson have been looking for HTTP Request Smuggling (HRS) issues in various servers and proxies. We found some issues, but none in HAProxy. But we did find some minor RFC violations that we couldn't imagine being used for HRS. So we decided to report them as normal issues. We know of the famous Robustness Principle "be liberal in what you accept and be strict in what you send", but when defending against HRS the approach should rather be to be as strict as possible with what you accept. Since violating the most benign RFC requirement could lead to HRS.

So the goal with this issue was to say that:

- this is the behavior of HAProxy
- it is against the RFC

But from this discussion I have also learnt that sometimes the robustness principle really is good and should be followed. But it is unclear to me when it should be followed and when it shouldn't.

Anyhow, thanks for taking the time write here back and forth!
