### ISSUE TITLE
Grace-option (which is planned for deprecation) is needed in some environments

### ISSUE THREAD

**Issue by kaspergrubbe** [haproxy/haproxy#1348]
### Your Feature Request

_(I am following up from a thread here: https://discourse.haproxy.org/t/the-grace-is-deprecated-and-will-be-removed-in-a-future-version/6362)_

The 2.4 and 2.5 releases added this deprecation:

> The grace directive has been marked as deprecated and is scheduled tentatively for removal in 2.4 with a hard deadline of 2.5. It was meant to postpone stopping of a process during a soft-stop, but is incompatible with soft reloading. We suspect that it is not widely used, but the warning will help us to know if some specific uses remain.

For some setups, it is very helpful for having the `grace` option.

### What are you trying to do?

We are using the Classic Elastic Load Balancer at Amazon (ELB), and it will not retry or redispatch traffic if the connection is failing.

Our current routing layer looks like this:

```
Classic AWS ELBs -> Haproxy -> Application servers.
```

The ELBs are configured to look for `/healthy` on Haproxy as a healthcheck, Haproxy is configured like this:

```
listen fe_ingress_stats
  bind *:8887
  mode http
  stats enable
  stats show-legends
  stats show-node
  stats uri /

  acl going_down stopping
  grace 10s
  monitor-uri /healthy
  monitor fail if going_down
```

And we setup the ELB healthchecks like this:

```
  # Haproxy dashboard answers on /healthy on port 8887
  health_check {
    healthy_threshold   = 2
    unhealthy_threshold = 2
    timeout             = 3
    target              = "HTTP:8987/healthy"
    interval            = 5
  }
```

On deployment of new Haproxy loadbalancers we first send SIGUSR1 to Haproxy, then we wait 12 seconds, and then the Haproxy is shut off. So now we can ask Haproxy to shut down in 10 seconds, and we are sure that our ELBs will reroute traffic to other containers.

This allows for ELBs to reconfigure traffic, but allow current requests to finish (at least within 10 seconds, long running requests would still be lost).

# Testing

I've tried to setup a test-suite.

Assumptions:

- AWS ELB sends a healthcheck every 5 seconds.
- AWS ELB needs 2 failed healthchecks to mark a node as unhealthy.
- AWS ELB will not retry or redispatch traffic of connection is failing.

## Without grace 10s

```
00:00: Haproxy receives SIGUSR1 and closes LISTENING socket.
00:05: AWS ELB tests the /healthy endpoint, notices it is down.
00:10: AWS ELB tests the /healthy endpoint, notices it is down.
00:10: Haproxy have failed the healthcheck twice so the node is removed from rotation
```

In this example AWS ELB would have been sending new traffic to the Haproxy server for 10s, which means that some of the traffic will have been lost for the duration.

## With grace 10s

```
00:00: Haproxy receives SIGUSR1 and keeps LISTENING socket open for 10s.
00:05: AWS ELB tests the /healthy endpoint, notices it is down.
00:10: AWS ELB tests the /healthy endpoint, notices it is down.
00:10: Haproxy have failed the healthcheck twice so the node is removed from rotation.
00:12: Our scheduler kills Haproxy.
```

Because of `grace 10s` all the the traffic that was sent towards the node during the 10 seconds would still have been handled until the process have been removed from the rotation.

# Testsuite

I don't know how helpful it is, but I've setup a small testsuite here: https://github.com/kaspergrubbe/haproxy-grace-test

Without grace I can see that we're losing requests, but with grace we aren't.

### Output of `haproxy -vv`

```plain
#5 1.058 HA-Proxy version 2.2.9-a947cc2 2021/02/06 - https://haproxy.org/
#5 1.058 Status: long-term supported branch - will stop receiving fixes around Q2 2025.
#5 1.058 Known bugs: http://www.haproxy.org/bugs/bugs-2.2.9.html
#5 1.058 Running on: Linux 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64
#5 1.058 Build options :
#5 1.058   TARGET  = linux-glibc
#5 1.058   CPU     = generic
#5 1.058   CC      = gcc
#5 1.058   CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
#5 1.058   OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1
#5 1.058   DEBUG   =
#5 1.058
#5 1.058 Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS
#5 1.058
#5 1.058 Default settings :
#5 1.058   bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
#5 1.058
#5 1.058 Built with multi-threading support (MAX_THREADS=64, default=4).
#5 1.058 Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
#5 1.058 Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
#5 1.058 OpenSSL library supports TLS extensions : yes
#5 1.058 OpenSSL library supports SNI : yes
#5 1.058 OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
#5 1.058 Built with Lua version : Lua 5.3.3
#5 1.058 Built with network namespace support.
#5 1.058 Built with zlib version : 1.2.11
#5 1.058 Running on zlib version : 1.2.11
#5 1.058 Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
#5 1.058 Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
#5 1.058 Built with PCRE2 version : 10.32 2018-09-10
#5 1.058 PCRE2 library supports JIT : yes
#5 1.058 Encrypted password support via crypt(3): yes
#5 1.058 Built with gcc compiler version 8.3.0
#5 1.058 Built with the Prometheus exporter as a service
#5 1.058
#5 1.058 Available polling systems :
#5 1.058       epoll : pref=300,  test result OK
#5 1.058        poll : pref=200,  test result OK
#5 1.058      select : pref=150,  test result OK
#5 1.058 Total: 3 (3 usable), will use epoll.
#5 1.058
#5 1.058 Available multiplexer protocols :
#5 1.058 (protocols marked as <default> cannot be specified using 'proto' keyword)
#5 1.058             fcgi : mode=HTTP       side=BE        mux=FCGI
#5 1.058        <default> : mode=HTTP       side=FE|BE     mux=H1
#5 1.058               h2 : mode=HTTP       side=FE|BE     mux=H2
#5 1.058        <default> : mode=TCP        side=FE|BE     mux=PASS
#5 1.058
#5 1.058 Available services : prometheus-exporter
#5 1.058 Available filters :
#5 1.058 	[SPOE] spoe
#5 1.058 	[COMP] compression
#5 1.058 	[TRACE] trace
#5 1.058 	[CACHE] cache
#5 1.058 	[FCGI] fcgi-app
#5 1.058
```
```

**Comment by wtarreau** [comment]
Hi Kasper,

thanks for your input, it's very useful.

Note that it's never by pleasure that we remove some features (even if rarely used). Here the grace prevented new processes from reloading and was causing huge difficulties in the listener code to pass FDs between the older and the newer process (i.e. we had to stop but not completely so that the new process can reuse the FD).

I'm having a concern with your description however, you're stopping hparoxy and never restarting it ? Maybe you use it only for the graceful stop ? If so we could have other ways to deal with your need to make the health check fail, typically by setting a variable on the CLI (or even via HTTP), that the health check will use to signal ELB that it needs to stop.

In your example, it would simply consist in changing the ACL definition to:
```
acl going_down var(proc.stopping) -m int gt 0
```

It will check if a process-wide variable named "stopping" is defined as a non-zero int.

Then on the CLI you can do this:
```
set var proc.stopping int(1)
```

And this will make your monitor suddenly return a failure. After a while (the equivalent of the grace period) you can stop it.

Please try it, and share your feedback, it should work from 2.4 and above. In older releases you can do the same using ACLs or maps defined as coming from a dummy file, that were updatable from the CLI.

**Comment by kaspergrubbe** [comment]
Hi @wtarreau, thank you for your explanition on why the deprecation was needed and a possible solution to the problem.

> I'm having a concern with your description however, you're stopping hparoxy and never restarting it ?

Yes, we're running Haproxy inside of Docker containers, and we are using Hashicorp Nomad as a scheduler and it runs the containers for us. An upgrade to Haproxy therefore requires us to build a new image, push it, and deploy it into our cluster, so one container replaces the old one.

Is it possible to trigger the variable through a signal? I don't think our scheduler allows us to run an external command or use CLI to set the `proc.stopping` variable.

**Comment by wtarreau** [comment]
No there's no way to set a variable through a signal, the only "visible" signal is the softstop one (USR1) that sets the stopping flag. However, given that the CLI is getting increasingly popular to operate changes on the fly, I do think you should really consider improving your scheduler to support it before it becomes totally obsolete :-/

**Comment by ktosiek** [comment]
My use case for grace is similar to the one described here - I only want grace on stop, to give another load balancer time to stop sending new traffic to a specific HAProxy server. Would it make sense to replace the current `grace` option with some `grace-on-stop` that only works on full stop? 

Even a global `grace-on-stop` combined with `proc.stopping` would be enough for many environments - I know Kubernetes suffers from the same race as described here for Nomad, where it doesn't wait for Ingresses to reconfigure themselves before stopping a Pod.

**Comment by wtarreau** [comment]
I think that what you're asking for in fact is to have the option to delay the soft-stop. I.e. have a global option allowing you to configure that delay, send a SIGUSR1, instantly see "stopping=1", but the service continues until that configured delay is expired, then everything stops for real. @ktosiek and @kaspergrubbe do you confirm that would suit your needs ?

I think I'm seeing how this could be done, and it could even be pretty clean, considering that we already haveaa `hard-stop-after` setting we could similarly have a `soft-stop-after` to configure that soft-stop delay. Of course, having the process-wide proc.stopping variable would be needed. Or maybe we'd use a new scope for the variable so that it doesn't conflict with existing ones (e.g. `core.stopping` or something like this). But at this level this is a detail.

**Comment by ktosiek** [comment]
This `soft-stop-after` would work for my use case.

**Comment by wtarreau** [comment]
OK thanks. I've thought about it a bit more, and I think it's the right way to go. However my proposed option name would be confusing ("soft-stop-after") because it wouldn't make it clear whether that stopping flag ought to be set or not, nor what happens after. The previous "grace" keyword was more straightforward. So I'm going to see if I can add a global "grace" option with a delay and postpone the stopping task with it. Regarding the "stopping" variable, I'm seeing we already have such a sample fetch function called `stopping` so we don't need to add another variable.

**Comment by wtarreau** [comment]
I'll merge this today, I'd be interested in your feedback.

[0001-MINOR-proxy-add-a-global-grace-directive-to-postpone.patch.txt](https://github.com/haproxy/haproxy/files/7120258/0001-MINOR-proxy-add-a-global-grace-directive-to-postpone.patch.txt)

**Comment by kaspergrubbe** [comment]
Hi @wtarreau 

I can confirm that the proposed solution will solve the issues we are seeing with the deprecation. If I can figure out how to build Haproxy with the patch I can give it a go in our staging environments.

Thank you so much ♥️

**Comment by wtarreau** [comment]
Perfect, thanks for your encouraging feedback!

In order to ease your testing, I've just merged it into the latest 2.5-dev. It's not yet released, but if you're willing to test out of the git tree, you can clone this repository and build it. If you do not feel at ease with Git, you can download a tar.gz or zip snapshot from the github interface or from git.haproxy.org. Otherwise just let me know and I'll guide you through other options.

**Comment by kaspergrubbe** [comment]
I am back from holiday today, so I will look into this right away, thanks for the wait.

**Comment by kaspergrubbe** [comment]
Hello @wtarreau, I've tested your patch inside our cluster, and it works brilliantly without losing connections, it was very helpful that you push your devbuilds to Dockerhub, that saved me a lot of time.

I did see the message, because I put it in the `defaults` section:

> the 'grace' keyword is not supported any more since HAProxy version 2.5.

Perhaps the message should be different? Maybe that it is moved to the `global` section? Or only allowed in the `global` section?

I updated the haproxy-grace-test repo here, to use docker containers: https://github.com/kaspergrubbe/haproxy-grace-test 

I don't know if there is a regression in newer versions of Haproxy, but it seems a bit interesting to me that:

- In the `grace` test, the total number of transactions goes from 5543 to 8625, and no dropped connections! (good!)
- In the `non-grace` test, the total number of transactions goes from 5449 all the way down to 1508 (this seems low): https://github.com/kaspergrubbe/haproxy-grace-test/commit/74ccab0344694670120e7854d80bf3fae49e5c09#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L46-L58

The log from the `non-grace` test (If helpful):

```
$ docker compose up
[+] Running 4/0
 ⠿ Container haproxytest_lb01_1    Created                                                                                                                                              0.0s
 ⠿ Container haproxytest_awselb_1  Created                                                                                                                                              0.0s
 ⠿ Container haproxytest_lb02_1    Created                                                                                                                                              0.0s
 ⠿ Container haproxytest_app_1     Created                                                                                                                                              0.0s
Attaching to app_1, awselb_1, lb01_1, lb02_1
lb02_1    | [NOTICE]   (1) : New worker #1 (8) forked
lb01_1    | [NOTICE]   (1) : New worker #1 (7) forked
app_1     | [NOTICE]   (1) : New worker #1 (9) forked
awselb_1  | [NOTICE]   (1) : New worker #1 (11) forked
lb02_1    | [NOTICE]   (1) : haproxy version is 2.5-dev8-538f3e0
lb02_1    | [NOTICE]   (1) : path to executable is /usr/local/sbin/haproxy
lb02_1    | [WARNING]  (1) : Exiting Master process...
lb02_1    | [WARNING]  (8) : Proxy fe_ingress_stats stopped (cumulated conns: FE: 5, BE: 0).
lb02_1    | [WARNING]  (8) : Proxy fe_http stopped (cumulated conns: FE: 0, BE: 0).
lb02_1    | [WARNING]  (1) : Current worker #1 (8) exited with code 0 (Exit)
lb02_1    | [WARNING]  (1) : All workers exited. Exiting... (0)
lb02_1 exited with code 0
awselb_1  | [WARNING]  (11) : Server be_app/lb02 is DOWN, reason: Layer4 timeout, check duration: 2005ms. 1 active and 0 backup servers left. 30 sessions active, 0 requeued, 0 remaining in queue.
```


All in all we're very happy with your suggested solution, and it works great! :)

**Comment by wtarreau** [comment]
> Hello @wtarreau, I've tested your patch inside our cluster, and it works brilliantly without losing connections,

Ah, cool, thanks for the feedback!

> it was very helpful that you push your devbuilds to Dockerhub, that saved me a lot of time.

I didn't :-) I think it's Tim who's doing this.

> I did see the message, because I put it in the `defaults` section:
> 
> > the 'grace' keyword is not supported any more since HAProxy version 2.5.
> 
> Perhaps the message should be different? Maybe that it is moved to the `global` section? Or only allowed in the `global` section?

You're right, I didn't think about the old message. Technically speaking it's not the same but I can surely figure a better explanation and update it. Maybe something around this: `Starting with HAProxy 2.5, the 'grace' keyword is only supported in the 'global' section` ?

> I updated the haproxy-grace-test repo here, to use docker containers: https://github.com/kaspergrubbe/haproxy-grace-test
> 
> I don't know if there is a regression in newer versions of Haproxy, but it seems a bit interesting to me that:
> 
>     * In the `grace` test, the total number of transactions goes from 5543 to 8625, and no dropped connections! (good!)
> 
>     * In the `non-grace` test, the total number of transactions goes from 5449 all the way down to 1508 (this seems low): [kaspergrubbe/haproxy-grace-test@74ccab0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L46-L58](https://github.com/kaspergrubbe/haproxy-grace-test/commit/74ccab0344694670120e7854d80bf3fae49e5c09#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L46-L58)

I don't think it's a mistake, it's likely because we try to close idle connections ASAP when stopping, something that we didn't do in the past. So that used to encourage clients to continue to push new requests over those old connections instead of switching to the new process, and now they're encouraged to switch to a new connection much faster.

> All in all we're very happy with your suggested solution, and it works great! :)

You see me pleased :-)

**Comment by TimWolla** [comment]
> I didn't :-) I think it's Tim who's doing this.

Technically it isn't me either. The Docker image [is a community effort](https://github.com/docker-library/haproxy/#maintained-by-the-docker-community) and the updates are automated. It's true that I participate there, though.

**Comment by kaspergrubbe** [comment]
> > I did see the message, because I put it in the `defaults` section:
> > > the 'grace' keyword is not supported any more since HAProxy version 2.5.
> > 
> > 
> > Perhaps the message should be different? Maybe that it is moved to the `global` section? Or only allowed in the `global` section?
> 
> You're right, I didn't think about the old message. Technically speaking it's not the same but I can surely figure a better explanation and update it. Maybe something around this: `Starting with HAProxy 2.5, the 'grace' keyword is only supported in the 'global' section` ?

That sounds good to me, that would tell me where to go investigate if I had an old config.

Thank you so much 🥇
