### ISSUE TITLE
src/acl.c: variable set, but not used (clang-13)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1359]
### Tool Name and Version

clang-13

### Code Report

```plain
CC      src/trace.o
src/acl.c:104:6: error: variable 'unresolved' set but not used [-Werror,-Wunused-but-set-variable]
        int unresolved = 0;
            ^
1 error generated.
```

caught on Fedora Rawhide

https://gitlab.com/chipitsine/haproxy-ci-playground/-/jobs/1523732709
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
It *seems* we can indeed remove it, that's a leftover of this cleanup in 2.3: 9fa0df55c ("BUG/MINOR: acl: Fix freeing of expr->smp in prune_acl_expr") and it looks like the unresolved check is performed later in release_sample_arg(). CCing @TimWolla for a double check in case he remembers this.

**Comment by TimWolla** [comment]
I probably just worked off valgrind's output without really understanding what I'm doing, instead relying on the committer double checking this. Checking my inbox it appears to be part of this huge patch bomb: https://www.mail-archive.com/haproxy@formilux.org/msg37808.html. I believe you committed it into the next branch without further verification, because it could easily rolled back if it caused issues.

So I can't really comment on this, but I agree with you that this can be removed from a look at the code.

**Comment by wtarreau** [comment]
OK thanks Tim, I'll do that once I'm done with the more important stuff :-)
