### ISSUE TITLE
Haproxy=2.4.3-1 idle spikes when no requests are made

### ISSUE THREAD

**Issue by toonvd** [haproxy/haproxy#1366]
### Detailed Description of the Problem

After upgrading from 2.3.12-2, our monitoring started flagging HaProxy instances for low idle.pct values.
When checking the info with nc, a low value is indeed visible.
When checking top and viewing the HaProxy logs, usage is 0 or close to 0.
I decided to roll back to 2.3.12-2 and the alerts were gone.

### Expected Behavior

The idle.pct value should be consistent / in proportion to the actual usage.

### Steps to Reproduce the Behavior

I can reproduce this on all servers that got an upgrade from 2.3.12-2 to 2.4.3-1.
However the spikes are fast so it can only be picked up by watching the info or monitoring it.

### Do you have any idea what may have caused this?

At first, I thought the change in nbthreads calculation was the cause. However, after setting nbthreads manually, I could still reproduce the issue.

### What is your configuration?

```haproxy
global
    stats socket                "${HOME}/.config/haproxy/run/haproxy.sock"  mode 600  user "${USER}"  level admin
    log                         "/dev/log"  local3  debug
    spread-checks               5
    ssl-default-bind-ciphers    EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
    ssl-default-bind-options    ssl-min-ver TLSv1.2  no-tls-tickets
    tune.ssl.default-dh-param   2048
    lua-load                    /etc/haproxy/includes/tuning.lua

defaults
    log                         "/dev/rsyslog"  local6  debug
    balance                     leastconn
    mode                        http
    option                      dontlognull
    option                      http-server-close
    option                      httplog
    option                      log-health-checks
    timeout check               4s
    timeout client              7202s
    timeout connect             5s
    timeout server              7202s
    timeout http-keep-alive     120s
    timeout http-request        10s
    timeout queue               30s
    timeout tarpit              60s
    default-server              inter 3s  fastinter 1s  downinter 1s  fall 30  rise 2  slowstart 10s
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.3-1ppa1~focal 2021/08/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.3.html
Running on: Linux 5.11.0-27-generic #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-o2a0Ov/haproxy-2.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by toonvd** [comment]
Extra observation, since the upgrade, Haproxy forks a child process, it did not do that before.

**Comment by wtarreau** [comment]
There is no way it could spawn a child process and it's even unable to do it thanks to a protection measure. The only other process you might see could be the master process in a master-worker configuration. But there's no reason this could change with just an upgrade, as the master-worked mode has existed since 2.0 or so. Since it's not mentioned in your config it must be on the command line. Do you see a "-W" that you didn't see previously in its command line arguments ?

When you're saying that sometimes the idle.pct reports zero, do you confirm that for you it looks like it is essentially a wrong measurement ? From what I remember it is averaged over a few values, but since 2.4 the wakeups happen less often (so that it uses even less CPU) and it would be possible that some values are miscalculated with longer pauses.

**Comment by toonvd** [comment]
Hi

Thanks for the reply (and the awesome work on HaProxy). It seems the argument got added indeed. I will check file diffs.
The idle.pct indeed looks incorrect to me. It sometimes jumps from 100 to 15 for example while there are no requests happening. Checking htop meanwhile shows there is no spike in cpu usage. Is there some other measurement we could check for monitoring? Because we were getting an ample amount of Pagerduties :).

**Comment by wtarreau** [comment]
So I've just checked, and first, I was wrong, not only it's not averaged, but in addition only the *current* thread's idle_pct is reported. Thus depending on which one gets the request, its own activity to deal with the request will be accounted for, and if for example it requires two rounds of the poll loop, this will affect the measurement. I think we completely messed up on this one when we went multi-threaded in 1.8 and it got significantly worse with the higher pauses in 2.4. I'll have to work on a fix to 1) calculate this differently (at least over two loop rounds), and 2) report the average of all threads and not just the thread dealing with the request. I suspect that the variations you're observing are simply caused by health checks running in the background, and now it's clear that it reports total garbage :-/

I'm wondering if we could average it over a few tens of milliseconds instead (it's used to enable/disable HTTP compression on the fly so it must keep a thin resolution).

I'm tagging the bug as reviewed so that we don't miss it. I don't have any short-term solution I'm afraid. You could imagine collecting values in Lua and writing a small service that averages them but that's ugly.

Maybe I have an idea for a temporary workaround. On the CLI in "show activity" you have a line "avg_loop_us", it's the average time to perform a loop between poll() and poll(). It's the complement of the idle time. It's not expressed in percentage but must remain small. If you're starting to see high values such as 20k or so, it indicates that your process is experiencing high latencies due to huge loads and it will certainly not be idle anymore. The first column is the aggregated one and it's averaged over the last 1024 passes through the loop. For totally idle processes it can take some time to go down, but if you have permanent activity it could very well be smoothed over one second or even less. Maybe give it a try.

**Comment by toonvd** [comment]
It looks like this won't be an easy one indeed.
I will try to figure it out with the loop indeed, if that doesn't work, our lua script will get some extra additions :3
It surprises me that this was noticed so late though. Am I right in thinking that most people are still on an older major release?

**Comment by wtarreau** [comment]
No, 2.4 got quite some adoption, at least from the issue reports we're seeing. And the issue has been there since 1.8 from what I can see, but less visible. I think that very few people monitor the idle_pct instead :-) Most monitoring suites have native support for system-wide measurements and that's most likely considered as totally sufficient most of the time. But I agree that idle_pct is a pretty convenient health indicator (if it works, of course)!

**Comment by wtarreau** [comment]
So I've looked at the code and in fact it already does what I expected to implement. I've looked carefully, and it does report an average over 500ms. The only thing I'm thinking about is if the system is experiencing time jumps. Is this running in a VM by an chance ? I haven't faced time jumps in a while but who knows.

**Comment by wtarreau** [comment]
Got it! It's indeed caused by the longer sleep times in 2.4. The percentage calculation uses a multiply by 100 so sleep times longer than 43s will overflow the multiply. That's now fixed, feel free to pick the patch above and apply it to your local tree. If you depend on a distro package, you'll have to wait for 2.4.4 in a week or two at best.

I guess you have no health checks, which explains why nobody reported it yet since about every config has at least a few health checks which prevent the threads from staying asleep for too long. Thus I guess that as a temporary workaround, you could simply enable checks on a server, even a dummy one. Even a check every 30s should be enough to wake threads up often enough.

**Comment by toonvd** [comment]
Hi

Actually, the proxies (over a 100) all have `check` on Varnish and `backup` on Apache.
I think it is more likely that people just don't use it then.
We wil wait for a while since I have seen some other issues for 2.4 that might get us in trouble.
I will however, test it on one of our servers so I can confirm to you.

**Comment by wtarreau** [comment]
OK! Well, maybe sometimes you're unlucky and all checks run on a subset of the threads and one thread does nothing before getting a stats request, leaving such stupid idle times. I'll also check if it makes sense to average the idle reporting over all threads or if there was a particular reason for keeping it per-thread.

**Comment by wtarreau** [comment]
I could finally reproduce it with a simple config doing nothing. First test, I waited ~50 seconds before sending the stats request:
```
$ while :; do socat /tmp/sock1 - <<< "show info"|grep ^Idle;sleep 1;done
Idle_pct: 6
Idle_pct: 16
Idle_pct: 100
Idle_pct: 100
Idle_pct: 100
^C
```

Same test after the fix:
```
$ while :; do socat /tmp/sock1 - <<< "show info"|grep ^Idle;sleep 1;done
Idle_pct: 100
Idle_pct: 100
^C
```

I'll also backport to 2.4 commit fe456c581 that now reports process-wide idle instead of per-random-thread.

**Comment by wtarreau** [comment]
Backported into 2.4.4, closing.
