### ISSUE TITLE
Bogus pointer overflow check in ssl_sock_parse_clienthello()

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1371]
### Tool Name and Version

CodeQL

### Code Report

```plain
if (msg + rec_len > list_end || msg + rec_len < msg)

>>>  Range check relying on pointer overflow.
```

### Additional Information

`msg + rec_len < msg` certainly looks odd to me. This same check appears multiple in the function. This was introduced in 769fd2e447487a1433350f727aee47b265d875b0.

### Output of `haproxy -vv`

```plain
2.5-dev5
```

**Comment by wtarreau** [comment]
No, actually this is the correct way to check for overflows: if rec_len is greater than -msg, then `msg + rec_len` will not validate `>list_end` and this would hide an overflow. This is valid since we're not building with `-fstrict-overflow` (this option is only useful to introduce security bugs by disabling critical tests).

**Comment by TimWolla** [comment]
@wtarreau CodeQL suggests the following instead:

```
rec_len > list_end - msg
```

I can't comment on this topic, but that suggestion looks more correct to me, because it does not rely on a specific wraparound behavior.

**Comment by chipitsine** [comment]
I have a feeling that `-fsanitize=undefined` should catch such cases. I'll try

**Comment by wtarreau** [comment]
> @wtarreau CodeQL suggests the following instead:
> 
> ```
> rec_len > list_end - msg
> ```
> 
> I can't comment on this topic, but that suggestion looks more correct to me, because it does not rely on a specific wraparound behavior.

Except that this does not catch the negative values for signed ints, thus the test's validity solely relies on the signedness of the length. E.g. take `ssize_t` or `int` and you're doomed. Also it's important not to underestimate the problem of integer type promotion of different sizes. E.g. `ptr+int` is always a pointer of the same type as `ptr` thus it may be compared to another such pointer. However `ptr2-ptr1` is a ptrdiff_t which will be a long or an int depending on the platform. You can have nice jokes when comparing ints of different signedness and size, as the conversion is not always done in the order you expect (I believe the smallest one is first extended to the size of the largest one using its type but I'm not even certain it always applies, nor do I know when it's compiler-specific or comes from the standard). That's why there are even warnings emitted for some such cases.

Regarding defined vs undefined, it's even documented in our beloved compiler's man page as being supported unless `-fstrict-overflow` is used.

**Comment by wtarreau** [comment]
Ilya, regarding `-fsanitize=undefined`, it will in fact prove that the first form is the preferred one :-)

Look, compile this with `gcc -c -Os -fsanitize=undefined`:

```
bool wrap_a1(const char *msg, ssize_t len, const char *end)
{
	return msg + len > end || msg + len < msg;
}

bool wrap_a2(const char *msg, ssize_t len, const char *end)
{
	return len > end - msg;
}
```
It gives:
```
0000000000000000 <wrap_a1>:
   0:   48 01 f7                add    %rsi,%rdi
   3:   0f 92 c0                setb   %al
   6:   48 39 d7                cmp    %rdx,%rdi
   9:   0f 97 c2                seta   %dl
   c:   09 d0                   or     %edx,%eax
   e:   c3                      retq   

000000000000000f <wrap_a2>:
   f:   55                      push   %rbp
  10:   53                      push   %rbx
  11:   48 89 d5                mov    %rdx,%rbp
  14:   48 89 f3                mov    %rsi,%rbx
  17:   48 83 ec 08             sub    $0x8,%rsp
  1b:   48 29 fd                sub    %rdi,%rbp
  1e:   71 10                   jno    30 <wrap_a2+0x21>
  20:   48 89 d6                mov    %rdx,%rsi
  23:   48 89 fa                mov    %rdi,%rdx
  26:   bf 00 00 00 00          mov    $0x0,%edi
                        27: R_X86_64_32 .data
  2b:   e8 00 00 00 00          callq  30 <wrap_a2+0x21>
                        2c: R_X86_64_PC32       __ubsan_handle_sub_overflow-0x4
  30:   48 39 dd                cmp    %rbx,%rbp
  33:   5a                      pop    %rdx
  34:   0f 9c c0                setl   %al
  37:   5b                      pop    %rbx
  38:   5d                      pop    %rbp
  39:   c3                      retq   
```

So actually the compiler is pretty happy with the former but emits specific code for the second one due to the identified risk of mishandling the integer check.
