### ISSUE TITLE
tcp-request connection set-var

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#1408]
### Your Feature Request

I would like to be able to use `tcp-request connection set-var` and `tcp-request connection unset-var` in `haproxy.cfg`. Currently its possible to reference maps in ACLs and use those ACLs with different `tcp-request connection` actions, but no way to set a variable which makes certain usage patterns supported with `http-request`, `http-response` actions etc. impossible - I describe my specific example below.

### What are you trying to do?

I am trying to use a map to set IP-specific rate limits on TCP connections that are then enforced with `tcp-connection request reject`. The problem with that is that there is no way to say `tcp-connection request set-var` and if I understand correctly no way to both fetch a sample `sc0_conn_cur` and a value from a map `src,map_ip_int(http_conn_limits)` directly in a single ACL so that they can be compared. I hacked together a patch that makes it possible to do what I want:

[0001-Add-tcp-connection-request-set-var.patch.txt](https://github.com/haproxy/haproxy/files/7284166/0001-Add-tcp-connection-request-set-var.patch.txt)

I can then write this in `haproxy.cfg`:

```
tcp-request connection track-sc0 src
tcp-request connection set-var(sess.conn) sc0_conn_cur
tcp-request connection set-var(sess.limit) src,map_ip_int(http_conn_limits)
acl limit var(sess.limit),sub(sess.conn) lt 0
tcp-request connection reject if limit
```

Its only a proof of concept patch, showing that apparently this use case can be supported with just a little code, I am not sure how much sense the change in this specific form makes sense. For example I am not sure if the session scope is fine for this or if there should be one more scope (what is the relation between a session in the way HAProxy code uses the word and a TCP connection?).

### Output of `haproxy -vv`

```plain
HAProxy version 2.5-dev8-1cdb53-39 2021/10/01 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_OPENSSL=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1l  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by wtarreau** [comment]
Hi Jaroslaw,

the reason we didn't do it is that there are no connection-level variables, the lowest level is the session, and you can already manipulate them using `tcp-request session set-var`. Note that technically speaking, internally the session is allocated with the connection, it's just not filled with all info yet (that's what we call an embryonic session). That's why your patch worked, but it will have plenty of nasty side effects regarding the samples that act at the session level that is not ready yet.

However I definitely understand your need for operations, of course it makes sense. Please first check if `tcp-request session` does the right thing for you (with your `sess.` variables). The single difference between the connection and the session is that at the session level, handshakes are completed (i.e. ssl, proxy protocol etc).

**Comment by jaroslawr** [comment]
@wtarreau But if I use `tcp-request session set-var`, then I would also need to do `tcp-request session reject` instead of `tcp-request connection reject`, right? I want to terminate the connections before the TLS handshake.

**Comment by wtarreau** [comment]
Hmmm OK. I'm wondering if we should hack something to make sure that `sess.*` can always reliably be used during the connection phase or if we'd need to add yet another scope (which I'm not fond of). I think that the former is not too difficult, and your proposed patch tends to confirm this. But it's just that we need to check this in details in the code and if we figure it can reliably be done, then document this particularity.

**Comment by jaroslawr** [comment]
@wtarreau Sounds good, I understand my hack is not exactly production-quality :) There is one more thing that would be nice for this use case and even a bit more broadly for any subnet-based rate-limiting including HTTP requests limiting etc. I want the the map file to contain subnets and their respective limits, like this:

```
192.168.1.0/24 100
123.124.0.0/16 10
```

But I can't find a way to mask the source IP based on which subnet it matched in the map, so that I can track the connection count for the whole matched subnet together. I would like to do something like this, where `map_ipmask` is something that does not exist currently:

```
acl has_limit src,map_ip_int(http_conn_limits) -m found
tcp-request connection track-sc0 src,map_ipmask(http_conn_limits) if has_limit
tcp-request connection set-var(sess.conn) sc0_conn_cur
tcp-request connection set-var(sess.limit) src,map_ip_int(http_conn_limits)
acl limit var(sess.limit),sub(sess.conn) lt 0
tcp-request connection reject if limit
```

I attach a patch, again of proof-of-concept quality...
[0001-Add-map_ipmask-converter-that-masks-an-IP-using-mask.patch.txt](https://github.com/haproxy/haproxy/files/7291108/0001-Add-map_ipmask-converter-that-masks-an-IP-using-mask.patch.txt) 

Or maybe there is an existing way to do it that I have not figured out?

**Comment by wtarreau** [comment]
I think that what you need in fact is a converter that returns the matching key from a map. It could be a normalized string when looking for case-insentive match, or a matching regex, an integer range like "12:45", or like here, a matching network. I suspect that what could make sense would be to have a set of `map_*_key()` that return the matching key instead of the associated value. That's a bit what you're doing with your ipmask except that it's very specific. Here we'd just return the string as it is in the file, so that it could be really used for anything. I do see some value in having this, especially networks and integer ranges that could serve to map to buckets. Using that to match prefixes with `map_beg_` could prove useful sometimes as well.

There are currenly 3 output types for maps (str, int, ip). and 9 matching methods. It could be nice to add a 4th output type (key) to these 9 matching methods. Is this something you'd be willing to work on, since you seem eager to code ? The reference pattern  (the verbatim line loaded from the file) is in `pattern->ref`, have a look at `pat_ref_elt` in pattern.h. You'll find the `pattern` field which should be the left column of the map, hence the element to return.

I like your idea :-)

**Comment by wtarreau** [comment]
By the way for the short term you can simply have an extra map file that contains two similar columns.

**Comment by a-denoyelle** [comment]
@wtarreau I looked at the vars code at the request of Willy and saw nothing that could prevent to use variables in embryonic sessions. They are also properly destroyed via session_free in any case. For me the first patch should be safe.

**Comment by wtarreau** [comment]
Excellent, thank you Amaury! @jaroslawr could you please add the relevant doc part and put a commit message to your patch ? We can merge it then :-)

**Comment by jaroslawr** [comment]
@wtarreau Here it is: 
[0001-MINOR-vars-add-set-var-for-tcp-request-connection-ru.patch.txt](https://github.com/haproxy/haproxy/files/7462596/0001-MINOR-vars-add-set-var-for-tcp-request-connection-ru.patch.txt)

(I will do the map thing as well whenever I have the time for it)

**Comment by wtarreau** [comment]
Wow that was fast! Now merged, thank you!

**Comment by wtarreau** [comment]
For the map one, no rush, as we're really getting close to 2.5. If you find a very trivial and riskless implementation within the week, I might still consider it otherwise we'll postpone.

**Comment by wtarreau** [comment]
I created a new feature for the map-related stuff, so we can close this one now.
