### ISSUE TITLE
Can haproxy group by node via consul

### ISSUE THREAD

**Issue by xerox-xeon** [haproxy/haproxy#1418]
### Your Feature Request

Can HAProxy group by node via consul?

If consul discovery has 6 nodes, then  I want to access 1,2 nodes!

backend http_back
    balance roundrobin
    server-template mywebapp 1-10 _web._tcp.service.consul resolvers consul    resolve-opts allow-dup-ip resolve-prefer ipv4 check

### What are you trying to do?

N/A

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by TimWolla** [comment]
Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.
 
Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

If this in fact *is* a feature request, then please make sure to fill in the issue template in full.
