### ISSUE TITLE
h2spec tests are permanently red

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1422]
### Detailed Description of the Problem

h2spec compliance tests are red

https://github.com/haproxy/haproxy/runs/3945798851?check_suite_focus=true

if they are considered useful, should they be fixed ?
if not, probably we should drop it

### Expected Behavior

tests should be green

### Steps to Reproduce the Behavior

https://github.com/haproxy/haproxy/runs/3945798851?check_suite_focus=true

### What is your configuration?

```haproxy
default
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
Indeed they deserve some look. All of them are related to a missing GOAWAY frame on close, which is normally sent, so either it got lost in the difficulty to preserve a working connection on errors while not looping forever, or it's just one of the usual measurement artefacts causing a TCP RST due to unconsumed data in the socket buffers when the close() happens. I can have a look (one more item on the todo list).

**Comment by chipitsine** [comment]
good news, I tested h2spec with ASAN enabled, no memory issues so far.

as for current failures, we can, for example, exclude those failing tests if we consider them not very meaningful (or we can wait them being fixed which is a better option).

**Comment by wtarreau** [comment]
Now bisected. It's the result of this fix from exactly one year ago:
9a3d3fcb5 ("BUG/MAJOR: mux-h2: Don't try to send data if we know it is no longer possible")

It's sad because it was painful. I'm on it now.

**Comment by wtarreau** [comment]
So I could fix it, and now the only random ones are those occasionally reporting "reset by peer" (in version 2.6.0). I debugged it to be sure, and it's related to the way the test is scheduled: h2spec sends an invalid frame in one TCP segment, then sends additional data in another one. The invalid frame is immediately intercepted, the GOAWAY is emitted, but the additional data that itsends afterwards causes its own socket to report a reset by peer. The only way to make this work reliably would be to significantly slow down haproxy, which makes no sense.
Example below, here's what h2spec sends:
```
17:16:48.961692 write(3, "\0\0\10\6\0\0\0\0\3", 9) = 9

[ that's 0x000010 = 16 bytes frame length; type=6=PING; flags=0; stream ID=3 (invalid) ]

17:16:48.961730 write(1, "        \33[90m     [send] Raw Data (0x0000000000000000)\33[0m\n", 59             [send] Raw Data (0x0000000000000000)
) = 59
17:16:48.961753 write(3, "\0\0\0\0\0\0\0\0", 8) = 8

[ that's 8 bytes of PING payload for a frame that was already invalid ]
```

The only way to comply with this would be to become insecure and wait for the advertised payload *after* an invalid frame, but that's non-sense, it's like waiting for all bytes with an invalid advertised size.

The best solution for now (if it can be done) would be to ignore the "connection reset by peer" type of errors, as they are always wrong (which differs from those saying that haproxy closed the connection instead of sending GOAWAY).

I'm going to push the fix for the missing GOAWAY ones. The problem was that CS_ERROR2 indicates that the GOAWAY was queued into the output buffer, but it needs to be sent on the socket, and that test was placed before the location where we send to the socket, so the bytes were never sent on the wire. Given that all other errors are tested, it looks safe to remove that one.

**Comment by chipitsine** [comment]
I'll check whether we can mute remaining failures or not.

**Comment by TimWolla** [comment]
> h2spec sends an invalid frame in one TCP segment, then sends additional data in another one.

/

> The best solution for now (if it can be done) would be to ignore the "connection reset by peer" type of errors, as they are always wrong (which differs from those saying that haproxy closed the connection instead of sending GOAWAY).

Is one of these two something that should be fixed / reported upstream? Their issue tracker appears to be here: https://github.com/summerwind/h2spec/issues

**Comment by chipitsine** [comment]
I think h2spec just follows h2 rfcs.
but I'll check

**Comment by TimWolla** [comment]
FWIW: There's already an open pull requests related to TCP RST in their repository: https://github.com/summerwind/h2spec/pull/119. I'm not sure however whether it fixes the issue Willy is seeing.

**Comment by wtarreau** [comment]
Tim, it's possible, indeed. Ilya, it has nothing to do with RFC compliance, the HTTP RFC doesn't cover the TCP layer nor the operating systems. Here the issue is that h2spec has to send enough bytes to please everyone (since some implementations could possibly time out waiting for all the advertised payload to be received), and as it's done in two write(), it ends up being delivered in two TCP segments, thus with a first one that gets parsed and a second one that fills the socket's TCP buffers while the close() is already done, resulting in a reset. That's always the same issue with RSTs and TCP that affects and bidirectional protocol, actually there is nothing new here.

Also, sending the two parts using a single write() isn't even a clean solution, that's a workaround, because the system remains free to cut that into multiple segments. It's just that in practice it will not with data smaller than an MSS, and this will work.

Anyway, what matters to me is that h2spec continues to help us detect bugs and regressions. As long as we know that there are corner cases (just like the occasional timeouts on vtest in the CI), and we can deal with them, that's fine to me.

**Comment by wtarreau** [comment]
By the way, I remember that we've worked around a similar one some time ago, I believe it was redirects on POST but could be wrong. We created the ->drain() method for this on the socket layer. I'll have a look to see if we could try to improve reliability a little bit there by trying to drain pending data from the socket before closing. This will not solve everything since it's a timing issue, but if the second segment is already in the socket buffers we should be able to drain it. A long time ago I proposed a close() variant for TCP that would silently delete pending data before closing to avoid sending an RST. It was rejected by fear of causing breakage, and with some longer experience on this it was right to reject it because that could indeed have some breakage by then. Regardless operating systems would definitely need something like this with interactive protocols :-/

**Comment by wtarreau** [comment]
It works. I've implemented a drain on close of h2 connections. I don't think it will really be useful in other circumstances but in any case if it makes h2spec happy it will improve other corner cases. I consider that the cost is very low considering that h2 connections are not setup/torn down that often.

**Comment by TimWolla** [comment]
For the record: CI indeed looks better now.

https://github.com/haproxy/haproxy/actions/workflows/compliance.yml

**Comment by wtarreau** [comment]
Yeah, much better indeed. I often saw messages about such compliance issues but had no idea how to access these reports, nor if they existed at all.

I'm keeping this open so that we don't forget to backport the fixes. I expect some differences in older versions so we'll probably not rush them too fast.

**Comment by chipitsine** [comment]
I was about to close the issue, but tags for backporting stopped me.

**Comment by chipitsine** [comment]
@wtarreau , reports are accessed in [Actions](https://github.com/haproxy/haproxy/actions) tab

maybe we should add badges to README, what do you think ?

**Comment by wtarreau** [comment]
@chipitsine yep, please keep it opened since in the end you reported a bug :-)
Thanks for the actions tab, sometimes I go there but am not sure what to look for. That part is a bit obscure to me and I don't always understand the output nor how things are presented. No worries though, I know I can rely on others who master this. Regarding the badges, I have no idea what it would bring.

**Comment by chipitsine** [comment]
I've added demo badge to [my fork](https://github.com/chipitsine/haproxy/commit/a5047411dc39abba3d2610afd65a654839524464)


![image](https://user-images.githubusercontent.com/2217296/139522318-88555558-3cd7-4c9d-978c-09461b508fc1.png)

**Comment by wtarreau** [comment]
OK. I'm not fond of markdown because it turns the readmes to ugly and painfully readable files for those reading them in the directory after extracting the sources, but if we limit this to the strict minimum that could work (e.g. instead of a table we present yet another list called "test results" and one description per line with the related URL). The other thing to be careful about is if it's possible to use relative URL so that haproxy forks or even other branches do not report the build status of the main project's master branch, but their own. Maybe it's possible to use some variables there to name the project and the branch, I don't know.

**Comment by TimWolla** [comment]
I always hate seeing those badges in the README, because they mean nothing to me as the end user: I don't know what's being tested and if there's a red badge I don't understand what issues I will encounter.

The developers can be expected to check the "Actions" tab or simply the build status at the commit. Personally I also try to keep track of the build status and report an issue if a bad build persists for several days (or I just send a patch if it's easy to fix).

A big -1 from me for those badges. However I'd be happy so see some updated README with a little bit of clean markdown to make the GitHub index page a bit more user friendly.

**Comment by chipitsine** [comment]
Tim, Willy, if you are happy with current state, I won't suggest badges anymore
