### ISSUE TITLE
Incorrect value for HLUA_TXN_FLT_CTX?

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1429]
### Detailed Description of the Problem

`HLUA_TXN_FLT_CTX` is defined as `0x00000030`.

### Expected Behavior

Should this be `0x00000040` for a proper bitmap?

### Steps to Reproduce the Behavior

1. Read the code.

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
Current git master.
```

**Comment by wtarreau** [comment]
Looks so, indeed, and HLUA_TXN_CTX_MASK ought to turn to 0x70, unless there's a very good reason for having one that covers both flags, but it's not mentioned around so I think you're right. CCing @capflam for a double-check.

**Comment by capflam** [comment]
No there is no issue here. `HLUA_TXN_*_CTX` flags are exclusives. They cannot be cumulated. It is an "enum". Of course, there is no reason to have plenty of lua contexts. So, a proper bitmap is also possible. In this case `HLUA_TXN_CTX_MASK` should be removed. But it is not a bug.

**Comment by TimWolla** [comment]
> It is an "enum".

Should they be converted into a regular enum then?

> But it is not a bug.

Depending on what you want to call a bug :smiley: I consider this confusing enough that it might get broken by accident, so IMO at least a comment would be warranted here.

**Comment by capflam** [comment]
An enum requires a new field. This "trick" is already used in the code. For instance `SF_ERR_*` and `SF_FINST_*`. I agree, a comment may help to not introduce a bug in future. But I guess it is a question of perspective. Because, for me the opposite is confusing. Here, `HLUA_TXN_*_CTX` flags are exclusives by construction. I'll add a comment to avoid any ambiguity.

**Comment by wtarreau** [comment]
The doubt is always possible when there are too few possibilities like here. I guess that a comment saying "these are the execution contexts (enum)" and clear separation before and after would help. Also the lack of the 0x00 context is troubling, you could have a list of HTX_TXN_CTX_* starting with _NONE and ending with _MASK that would void any doubt.

Anyway I agree that this type of construct is pretty useful and common (we've had a lot in the streams or in proxies for example) but that they need great care as it's common to take them for pure flags. For example those we have in proxy options are always set via a "& ~mask | value" instead of just "|=" to avoid any doubt.
