### ISSUE TITLE
Link HAProxy to crustls(rustls-ffi)

### ISSUE THREAD

**Issue by IceCodeNew** [haproxy/haproxy#1430]
### Your Feature Request

I suggest we support linking HAProxy to crustls(rustls-ffi).
OpenSSL is over bloat and was infamous for its vulnerability, switching the implementation to rustls is sound to me. Particularly, considering that they failed to adopt the QUIC patch for years, this may affect HAProxy's development in the future.

### What are you trying to do?

I may only be capable of testing. Should there be anything else I can do, I am willing to do it.

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.7-d858cbf 2021/10/22 - https://haproxy.org/ Status: long-term supported branch - will stop receiving fixes around Q2 2026. Known bugs: http://www.haproxy.org/bugs/bugs-2.4.7.html Running on: Linux 5.12.9-300.fc34.x86_64 #1 SMP Thu Jun 3 13:51:40 UTC 2021 x86_64 Build options : TARGET = linux-glibc CPU = generic CC = cc CFLAGS = -O2 -pipe -D_FORTIFY_SOURCE=2 -fexceptions -fstack-clash-protection -fstack-protector-strong -g -grecord-gcc-switches -Wl,-z,noexecstack,-z,relro,-z,now,-z,defs -Wl,--icf=all -fPIE -pie -fwrapv OPTIONS = USE_PCRE2_JIT=1 USE_STATIC_PCRE2=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PROMEX=1 DEBUG = Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE +STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING Default settings : bufsize = 16384, maxrewrite = 1024, maxpollevents = 200 Built with multi-threading support (MAX_THREADS=64, default=2). Built with OpenSSL version : OpenSSL 1.1.1m-dev xx XXX xxxx Running on OpenSSL version : OpenSSL 1.1.1m-dev xx XXX xxxx OpenSSL library supports TLS extensions : yes OpenSSL library supports SNI : yes OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3 Built with Lua version : Lua 5.4.3 Built with the Prometheus exporter as a service Built with network namespace support. Built with libslz for stateless compression. Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip") Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND Built with PCRE2 version : 10.37 2021-05-26 PCRE2 library supports JIT : yes Encrypted password support via crypt(3): yes Built with gcc compiler version 8.3.0 Available polling systems : epoll : pref=300,
2021/10/24 上午10:04:50test result OK poll : pref=200, test result OK select : pref=150, test result OK Total: 3 (3 usable), will use epoll. Available multiplexer protocols : (protocols marked as <default> cannot be specified using 'proto' keyword) h2 : mode=HTTP side=FE|BE mux=H2 flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG fcgi : mode=HTTP side=BE mux=FCGI flags=HTX|HOL_RISK|NO_UPG <default> : mode=HTTP side=FE|BE mux=H1 flags=HTX h1 : mode=HTTP side=FE|BE mux=H1 flags=HTX|NO_UPG <default> : mode=TCP side=FE|BE mux=PASS flags= none : mode=TCP side=FE|BE mux=PASS flags=NO_UPG Available services : prometheus-exporter Available filters : [SPOE] spoe [CACHE] cache [FCGI] fcgi-app [COMP] compression [TRACE] trace
```

**Comment by wtarreau** [comment]
Well, regardless of your (lack of) love for OpenSSL and its derivatives, it happens to be fairly complete, to offer a lot of the features most users rely on, and more importantly, to be maintained. I've never heard of the one you mentioned, I don't even know if it provides compatible features nor if it's maintained at all (hint: could you check over the last 3 years if fixes were properly backported to stable branches, and do they flow into distros?). However I'd say that even supporting OpenSSL derivatives gives us gray hair, and we've only done it because some were available by default on other operating systems, so I'm having a hard time imagining supporting a completely different stack in parallel (we thought about it long ago but nothing was done, and by then our features were still a bit limited).

Now if you have patches to propose to try to support a well maintained alternate library with a roughly equivalent feature set, feel free to propose something that can be reviewed and discussed. The code is modular, and adding support for an alternate transport layer shouldn't be too hard. But keep the maintenance aspect in mind. I.e. we don't want to see API changes in stable branches or that would immediately disqualify it of course.

**Comment by wlallemand** [comment]
I took a look a few weeks ago at this library. This is an interesting library which make a lot of buzz, apache and curl were ported to it. I think most of the features required to be used with haproxy are here. I could miss some crypto feature that are used in haproxy outside the TLS scope though.

This is a very young library and it could be a serious alternative to OpenSSL in the future. However, the maintenance cycle isn't clear to me, like most rust projects, I didn't see any explanations about the release and the maintenance.

Regarding the port to haproxy, from a code perspective, even if if haproxy is modular, it will require to rewrite a lot of the haproxy TLS implementation, because the API is not the same as OpenSSL. Maintaining the SSL layer is hard, it's not only a matter of providing the patches that support it, it also need to be bug-fixed and evolved with the HAProxy. HAProxy aims to support OpenSSL, and support partially boringSSL and libreSSL, and it's hard to maintain because it pollutes a lot of the code with #ifdef for multiple library support.

Also,  I have no fear that QUIC will be integrated one day within OpenSSL, I didn't follow the subject myself but I know that @haproxyFred has used a patched version at some point.

**Comment by IceCodeNew** [comment]
I will help test https://github.com/ymjing/tabbyssl this week. Not only it can solve this problem, but also save lots of work in porting rustls to other projects.
Its predecessor has been deployed by a Chinese major IT company Baidu, who announced that this project is ready for production.

**Comment by wlallemand** [comment]
That's interesting, I didn't knew about this project, it could indeed helps a lot. If there is a compatibility layer it could be done easily. A long time ago we ported haproxy to cyaSSL using their compatibility layer, that could do the trick.

What I fear the most is the maintenance, I don't want us to experience again the pain we had with boringSSL whose haproxy port is unmaintainable because they constantly change their API because of the rolling release.

**Comment by lukastribus** [comment]
Haproxy is not a "simple" OpenSSL user, it uses *a lot* of the OpenSSL features, even low level ones, which we don't even know if rustls provides.

This is a considerable amount of work in the best case scenario.

I like rustls, but we must not underestimate the effort to make this move and the long term maintenance impact.


> I will help test https://github.com/ymjing/tabbyssl this week. Not only it can solve this problem, but also save lots of work in porting rustls to other projects.

That's nice, and would work for a POC, but we can't rely on a 3 days old github projects for core functionality.

**Comment by IceCodeNew** [comment]
> That's nice, and would work for a POC, but we can't rely on a 3 days old github projects for core functionality.

As I said, this project has been developed a long time ago. And been deployed in production by a major Chinese company.
The author made this fork because he left Baidu in 2019 and has to avoid problems like CLA or branding.

**Comment by lukastribus** [comment]
The point is that it is a one man project, it doesn't matter how good the quality is or how many years Baidu runs this in production.

**Comment by wtarreau** [comment]
As I said (and what Lukas also insisted on), we're *extremely* picky about maintenance concerns. BorinSSL, while popular, is already a nightmare to deal with (and they didn't betray anyone, it's advertised on the box). Other projects that have even less experience with maintenance are extremely unlikely to even do as good...

**Comment by lukastribus** [comment]
> Also, I have no fear that QUIC will be integrated one day within OpenSSL, I didn't follow the subject myself but I know that @haproxyFred has used a patched version at some point.

Regarding QUIC, that will take a few years, as it's developed from scratch:

https://daniel.haxx.se/blog/2021/10/25/the-quic-api-openssl-will-not-provide/

**Comment by wtarreau** [comment]
Yep, just saw that and it's dramatic, particularly for the openssl project itself. It's time we add quictls to the CI and to the doc, and officially support it (which could also allow us to drop the useless boringssl). Let's just hope quictls gets some mainstream support and is packaged in distros so that users do not need to maintain their own packages.

**Comment by lukastribus** [comment]
FYI curl just removed support for MesaLink, it appears no one stepped up to support TabbySSL:

https://github.com/curl/curl/issues/8188
https://twitter.com/bagder/status/1480491264936189954/photo/1

**Comment by IceCodeNew** [comment]
> FYI curl just removed support for MesaLink, it appears no one stepped up to support TabbySSL:
> 
> [curl/curl#8188](https://github.com/curl/curl/issues/8188) [twitter.com/bagder/status/1480491264936189954/photo/1](https://twitter.com/bagder/status/1480491264936189954/photo/1)

I saw that too. As I dig deeper into the rustls hole, it seems to me that it is far from a 100% alternative to OpenSSL. While TabbySSL, as a compatibility layer, is not capable for compensate for the missing functions.
From a view at this very time, I agree that supporting rustls is not even a sane idea. And despite how much I fear about the vulnerability of OpenSSL, the quictls, which has stable APIs, seems to be the only option for now.
