### ISSUE TITLE
Compiling with opentracing and "use-vars" support fails on HAproxy 2.5.0/master

### ISSUE THREAD

**Issue by leonardolang** [haproxy/haproxy#1493]
### Detailed Description of the Problem

Compiling HAproxy 2.5.0 (and master) with USE_OT=1 and OT_USE_VARS=1 fails due to `struct vars` not having a `name` field anymore (replaced by `name_hash`).

### Expected Behavior

Compilation to succeed.

### Steps to Reproduce the Behavior

`make USE_OT=1 OT_USE_VARS=1`

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

### Last Outputs and Backtraces

```plain
N/A
```

**Comment by chipitsine** [comment]
@zaga00 , can you have a look please ?

**Comment by zaga00** [comment]
Hello @leonardolang, @chipitsine,

to clarify the situation here, you can see the comment related to commit 4cb2c83:

"Due to a recent change in the handling of haproxy variables, their use for
OpenTracing context transfer has been excluded from the compilation process.

The use of variables can be re-enabled if the newly defined variable
OT_USE_VARS is set to 1 when calling the 'make' utility.  However,
this should not be used for now as the compilation will end in error."

The use of variables within the opentracing filter is not necessary for its operation, at least as far as it seems to me.  Of course, I do not mean the use of variables in general (say within the tag, baggage and log) but the specific transfer of opentracing context through special variables, which are excluded from use by that commit.

The use of these variables may one day return to haproxy source, but I need to have more time for that.

Best regards.

**Comment by chipitsine** [comment]
if there's no ETA, shall we add warning to Makefile for a while ? it will prevent people from asking such questions

**Comment by zaga00** [comment]
That's a good idea.  I actually added this new definition for myself, so that the day I take enough time to return that functionality to haproxy I can compile the source without any modification of the makefile file.

At the time I was developing that filter, I didn't know much about opentracing and I added everything that came to my mind at the time; some possibilities you may never need.  Perhaps one of them is the transfer of opentracing context across haproxy variables.  But just as anything can be done in haproxy (which is a great product), so I added that.  :)

**Comment by zaga00** [comment]
To clear up any doubts: variables can be used to configure opentracing settings (without using OT_USE_VARS). Special read-only variables used to convey opentracing context cannot be used.

**Comment by wlallemand** [comment]
@zaga00 should we close the issue?

**Comment by wtarreau** [comment]
Let's not close it yet. We need to determine the best way forward, either re-implement something similar to the variables to carry these info, or definitely decide to drop them if unused, in which case we'll have to put a message on USE_OT_VARS.
I'll mark it as "works as designed" since that's what it really is, even though it's not really cool for users.

**Comment by wtarreau** [comment]
"future fix" is even better.

**Comment by zaga00** [comment]
I thought to solve this by creating a special variable in which I would put the names of all special variables related to the transmission of opentracing context.  That way I could restore the previous functionality.  Unfortunately, I have other obligations now, but we should find time to solve it soon, I hope by the end of this month.

**Comment by wtarreau** [comment]
OK no rush! We'll do it for 2.6-dev and if the solution looks good enough for a backport, we'll backport it to 2.5. Thanks Miroslav!

**Comment by wlallemand** [comment]
Is the problem solved?

**Comment by zaga00** [comment]
This has been addressed recently so that the use of variables to transfer opentracing context is enabled on haproxy version 2.6. However, it has been agreed with Willy that these patches will not be backported to version 2.5, unless users urgently need it. You can see this discussion before announcing haproxy-2.6-dev5, on the mailing list.

**Comment by wtarreau** [comment]
Indeed, that's here (conclusion of that thread): https://www.mail-archive.com/haproxy@formilux.org/msg42086.html

I'm marking this fixed, leaving 2.5 set so that we know it's not there yet, and we can close. Thanks!
