### ISSUE TITLE
ERR_HTTP2_SERVER_REFUSED_STREAM

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#1495]
### Detailed Description of the Problem

We are seeing issues where some requests within our Munin instance fail to load due to `ERR_HTTP2_SERVER_REFUSED_STREAM` in both Chrome and Firefox. The issue is not clearly reproducible, but happens often enough that I'm able to extract debug information on request. The Munin pages are pretty request/image heavy which might or might not be related.

I think some of the refused requests had a termination code of SD--, but other do not. So this is not a 100% reliable indicator. I might have also looked at the wrong log lines.

#1489 might be related / the same issue.

### Expected Behavior

I expected all requests to succeed.

### Steps to Reproduce the Behavior

1. Open Munin.
2. Watch the developer tools.
3. Hope that an error is logged in the console.

### What is your configuration?

```haproxy
global
	log stdout format short daemon
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	tune.ssl.default-dh-param 2048

	ssl-default-bind-ciphers ECDHE+CHACHA20:ECDHE+AESGCM
	ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
	ssl-default-bind-options ssl-min-ver TLSv1.2

	lua-prepend-path /usr/local/share/?.lua
	# https://github.com/TimWolla/haproxy-auth-request
	lua-load /usr/local/share/haproxy-auth-request.lua

defaults
	timeout connect 5s
	timeout client  50s
	timeout server  50s

	unique-id-format %{+X}o\ %[hostname,field(1,.),upper]-%Ts%rt

	default-server init-addr none resolvers unbound

resolvers unbound
	nameserver unbound 127.0.0.1:53

frontend https
	mode http
	log global
	log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r %ID"
	# *snip*

	bind :::443 v4v6 ssl crt /etc/haproxy/tls strict-sni alpn h2,http/1.1 ca-file /etc/haproxy/ca.pem verify optional

	# *snip*

	acl oauth_proxy      path_beg /oauth2/

	# *snip*

	acl munin req.hdr(host),lower munin.example.com

	# *snip*

	http-request lua.auth-request oauth_proxy /oauth2/auth if munin
	use_backend oauth_proxy if munin ! { var(txn.auth_response_successful) -m bool }
	use_backend oauth_proxy if oauth_proxy

	# *snip*

	use_backend munin       if munin

	# *snip*

backend munin
	mode http

	option forwardfor

	# This is an nginx in the backend.
	server munin munin.example.com:443 ssl sni str(munin.example.com) check-sni munin.example.com ca-file /etc/haproxy/ca.pem check
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.9-1~bpo10+1 2021/11/24 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.9.html
Running on: Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-2.4.9=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 8.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Additional Information

- Also happens in 2.3.16-1~bpo10+1.
- I can provide HAProxy Access Logs and Traces in private on request.

**Comment by wtarreau** [comment]
The REFUSED_STREAM error could indeed correspond to certain server errors on the backend side. Typically if an HTTP/1 persistent connection is closed by the server while we're sending a request on it, in HTTP/1 we silently close the client connection so that the browser can retry, but in H2 we must use REFUSED_STREAM to tell the browser the request is retryable. I'm just surprised it's SD--, as I would have imagined SH-- here. But maybe sometimes some partial responses are received and data are truncated (e.g. if the server process dies), and we fail to deliver these partial responses.

Maybe if you're not having too much load on this haproxy it could be useful to enable h1 traces so that we can detect if an error happens on the backend side, and if so, how it manifests itself.

Maybe the load is important for the server and it tends to close persistent connections a bit too fast to preserve resources and is causing lots of transmission failures because of this. These ones could be addressed using l7 retries, but I would prefer to first be certain of the situation before starting to hide the dust under the carpet :-/

**Comment by TimWolla** [comment]
> Maybe if you're not having too much load on this haproxy it could be useful to enable h1 traces so that we can detect if an error happens on the backend side, and if so, how it manifests itself.

This is a production instance, but fairly low traffic, so I can do this. Can you give me a copy-pastable list of commands to enable the tracing with the level of detail you would need?

For the record: The nginx technically advertises H2 on port 443.

> Maybe the load is important for the server and it tends to close persistent connections a bit too fast to preserve resources and is causing lots of transmission failures because of this.

The nginx for munin is a fairly standard nginx instance with nothing odd in the configuration. I would expect seeing this issue much more often if this was some general behavior of nginx.

**Comment by wtarreau** [comment]
For the command I usually do it this way:
```
(echo "trace h1 sink buf0; trace h1 level developer; trace h1 verbosity complete; trace h1 start now; show events buf0 -w -n" ; cat ) | socat /path/to/socket - > /path/to/log-file
```

Then at the end I disable all traces using:
```
socat /path/to/socket - <<< "trace 0"
```

Given that you don't have alpn advertised on the "server" line, there won't be protocol negotiation and the default h1 will be used instead, no matter what nginx advertised. And indeed I agree that with nginx behind you're not in a case of a dummy server randomly crashes while delivering data so I'd be tempted to generally trust what is retrieved there.

**Comment by wtarreau** [comment]
Tim, there could be another explanation related to H2. If for any reason we reset the H2 stream to the client in the middle of an object, the error may propagate to the other side and it's one of the rare cases where we know we can occasionally log SD instead of CD (some cases reported long ago on the ML already). So maybe the issue is indeed in H2 like it seems to be in the other issue you linked.

**Comment by TimWolla** [comment]
I just managed to reproduce the issue with traces enabled. All the requests in the access log show a termination code of `----`.

I'll double check the trace logs for sensitive information and will then send you a link to them via private email.

**Comment by capflam** [comment]
`SD--` may be reported instead of `SH--` if the server abort is detected on the request side. It is especially true if the request payload was not fully sent.

**Comment by TimWolla** [comment]
> All the requests in the access log show a termination code of `----`.

… and that is because it appears that the broken requests have not been logged at all, unless I'm completely misreading the data.

**Comment by wtarreau** [comment]
Thus it would confirm that it was identified as an aborted connection on the server side, i.e. we sent a request on a reused connection that was closed while sending. Since the request is not processed, no log is produced either. Ideally we ought to find a way to represent these ones but I remember that we've decided to hide them because some users were confused by apparently duplicate entries in their logs.

For such use cases `retry-on conn-failure empty-response` can be useful and safe. Still I'm puzzled by the fact hat nginx would close idle connections early. Maybe you have a too short a keep-alive timeout there ?

In any case I'm not ruling out an issue on the H2 side, it's just possible that your pattern revealed it.

**Comment by TimWolla** [comment]
@wtarreau I just sent an email to you in private.

**Comment by wtarreau** [comment]
Many thanks Tim for the traces. BTW one day we'll have to discuss about efficient ways to anonymize traces, because you're probably the one doing that the best and your feedback on this could be invaluable!

You'll see in the H1 trace that there are many "shutdown on connection" with flags such as `0x00182300` which once decoded give: `CO_FL_ERROR | CO_FL_SOCK_WR_SH | CO_FL_ADDR_TO_SET | CO_FL_XPRT_READY | CO_FL_CTRL_READY`.

And it's clear that a TCP reset was received. Let's pick for example connection 0x7f9cc8313790. The last line with flags 0x00002300 is:
```
[06|h1|5|mux_h1.c:2544] h1_recv(): entering : [B] - h1c=0x7f9cc83b52d0(0x80002200) conn=0x7f9cc8313790(0x00002300) ibuf=0@(nil)+0/0 obuf=0@(nil)+0/0
```
Then it's immediately followed by:
```
[06|h1|5|/mux_h1.c:394] h1_recv_allowed(): recv not allowed because of (error|read0|waitl4|waitl6) on connection : [B] - h1c=0x7f9cc83b52d0(0x80002200) conn=0x7f9cc8313790(0x00102300) ...
```
This new connection flag 0x00100000 is the error, it was received during the recv() call. And from there the connection is dead and unusable. This corresponds exactly to a server closing at the same time haproxy is sending the request, thus you might be having too low keep-alive timeouts on the server side. Note that with lots of images it's very possible that some connections remain idle for a long time. I remember having seen some monitoring pages taking ages to render plenty of graphs at once, so in this case some server connections might remain idle long enough to be closed. This could be confirmed by the fact that several of your requests are aborted simultaneously. At a few times we see nothing during exactly one second, so maybe your keep-alive timeout is of one second there and it perfectly collides with the attempt to retrieve new data at once.

I think it deserves some digging to see if you can easily play with this keep-alive timeout on the nginx side, otherwise, just enable retry-on, which is perfectly fit for this specific case (to be honest that's the only case where I accept it :-)).

**Comment by TimWolla** [comment]
> thus you might be having too low keep-alive timeouts on the server side.

I checked the nginx configuration. The keep-alive timeout is configured as:

```
/etc/nginx/nginx.conf:	keepalive_timeout   65;
```

And I can confirm with `openssl s_client` that this unitless number is not milliseconds. I did not measure exactly, but it certainly feels like 65 seconds :smiley: 

As you can see in the access logs I sent you, all the requests in question have been sent within ~20 seconds. Before that the last logged connection to the backend was roughly 10 minutes ago (at 08:59:45 UTC).

So, I certainly could try adjusting this number, but I feel that the current configuration already should work.

**Comment by TimWolla** [comment]
@wtarreau I've sent you some other important findings via email.

**Comment by wtarreau** [comment]
So according to your traces, the issue clearly stems at the SSL layer on the backend side. However I cannot reproduce it at all here (as usual) thus I'm wondering if we're not instead revealing a deepeer issue. There were a few recent reports of SSL-related crashes and it's possible that several of them were revealed by a recent fix, and manifest themselves differently depending on the environment :-/  Still digging.

**Comment by TimWolla** [comment]
@wtarreau Did you receive all of my emails? I sent the last at 14:20 PM CET.

**Comment by wtarreau** [comment]
Yes I did till the one saying "last one for now". William is also having a look and finds this pretty bizarre.

**Comment by TimWolla** [comment]
> Yes I did till the one saying "last one for now".

Okay, then that's all of them. I wasn't sure whether you were working off my first one with the traces or not and wanted to make sure you've seen them all to not waste your time.

**Comment by wtarreau** [comment]
I've got them all, no problem. It's just that I'm jungling between several issues as usual and this is terrible for my concentration.

**Comment by TimWolla** [comment]
> However I cannot reproduce it at all here (as usual)

I attempted to set up a simple reproducer environment, but I was not successful. Every request succeeded just fine. Instead of Munin I created simple static HTML page with many images. On the HAProxy I disabled the use of haproxy-auth-request, because that was non-trivial to replicate.

Maybe for some reason having haproxy-auth-request / Lua connections within the request pipeline makes the issue worse / appear? You can grab the script here: https://github.com/TimWolla/haproxy-auth-request/blob/3d7ca6bb6edd2aa154d41ea97071ceb1dede9e10/auth-request.lua and will also need this: https://github.com/haproxytech/haproxy-lua-http/tree/4ac4483142c4f12445d47e55c8ecf155d9be0904

As the backend we're running https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.2.0.

**Comment by wtarreau** [comment]
Tim, we just found a way to reproduce it. It involves threads. We need to use a client that closes connections and http-reuse always so that idle connections are reused by different threads. I think that now we have what we need to dig deeper!

**Comment by wtarreau** [comment]
Tim, as I suspected, using `tune.idle-pool.shared off` in the global section fixes the problem, so this is clearly an issue of reused SSL connection between threads. Very strange.

**Comment by TimWolla** [comment]
Interesting. In an attempt to narrow down the issue I tried with `nbthread 1` and still managed to reproduce the issue.

However when setting up the reproducer environment I used single-core VMs, so that might've hidden the issue.

**Comment by wtarreau** [comment]
That doesn't correspond to our experience here, nbthread 1 always stops it. Maybe you were observing the refused_stream only and not the other part in the SSL layer though.

**Comment by TimWolla** [comment]
I just tested again with `nbthread 1`, but I am no longer able to reproduce the issue. I am not seeing refused streams there.

Not sure what went different the last time I tested.

**Comment by TimWolla** [comment]
Okay, I tested once more. I'm still seeing both the TLS issue and the refused stream when I am running with `nbthread 1`. I restarted both HAProxy and nginx before running my test and the process list confirms that there is only one HAProxy worker and no threads in that worker.

To be crystal clear: I am seeing both issues with `nbthread 1`.

**Comment by wtarreau** [comment]
Thanks for confirming, but then this is even more strange. Here my assumption was that it was related to the per-thread storage of reused_sess[thread_id] which cannot change with nbthread 1. It very much looks like an initialization issue somewhere. No way to break it in 2.5, but in 2.4 it does. And if I send at least as many concurrent connections as threads at once, no issue either, just as if that was sufficient to pre-initialize a context on each thread first. Of course -dM and UAF do not change anything :-(  So the issue clearly seems to go beyond the previous patch that probably just opened the pandora box a bit wider.

**Comment by TimWolla** [comment]
I'm happy to provide additional traces / PCAPs upon request. I can also recompile that HAProxy with any patches you throw at me.

Also as a heads up: I'll be off work over Christmas and New Year and I'll attempt to not touch my computer too much. So please expect some delay over the holidays, unless a miracle happens and you can resolve this until tomorrow.

**Comment by wtarreau** [comment]
Christopher found that commit 655dec81b ("BUG/MINOR: backend: do not set sni on connection reuse") is missing from 2.4 and it seems to address the issue here (at least it could explain why we see the bug in 2.4 and not 2.5). We're still trying to figure the root cause, as I'm suspecting we're circling around it and it can pop up under various forms.

You may want to try again with this patch (it backports well) since you're seeing the issue even with nbthread 1. At least this could bring us a clean solution for a 2.4.10 that would be on par with 2.5 bug-wise.

**Comment by TimWolla** [comment]
Thanks, I'll test including that patch early tomorrow and report back to you.

**Comment by capflam** [comment]
@TimWolla, could you also include this one: 2b1d91758 ("BUG/MINOR: backend: restore the SF_SRV_REUSED flag original purpose") ? It is missing too.

**Comment by wtarreau** [comment]
Good to know so if I emit 2.4.10 I'll grab it as well.

**Comment by TimWolla** [comment]
It got a bit later than I planned:

1. I once again tested whether I was able to reproduce this with `nbthread 1`. I was not. With a single thread the issue must be extremely sensitive to the environment.
2. I once again tested with the default number of threads. I was not able to reproduce this either. Here the issue was apparently that I did not restart Chrome in between my tests and thus not all images were loaded due to caching. Good to know.

3. I've tested Vincent's package for 2.4.9 + 137779e4e32bcaae7c41676881c934e9a3512373 + 93dc04417daab8354578ab59347837cc06cd1630.

I was not able to reproduce the issue with the two patches applied. HAProxy was running with the default number of threads (8), I completely restarted HAProxy and nginx and I also restarted Chrome. After being unable to reproduce this, I restarted Chrome once more to clear its cache, but it still worked fine.

All these results are not completely reliable indicators, it might've been luck. But I'd say that applying the two patches definitively improved the situation.

**Comment by TimWolla** [comment]
> 3\. I've tested Vincent's package for 2.4.9 + 137779e4e32bcaae7c41676881c934e9a3512373 + 93dc04417daab8354578ab59347837cc06cd1630.

Whoops. Those IDs are my local IDs. For the reference:

```
commit 93dc04417daab8354578ab59347837cc06cd1630 (HEAD)
Author: Amaury Denoyelle <adenoyelle@haproxy.com>
Date:   Thu Jun 17 15:14

    BUG/MINOR: backend: restore the SF_SRV_REUSED flag original purpose
    
    The SF_SRV_REUSED flag was set if a stream reused a backend connection.
    One of its purpose is to count the total reuse on the backend in
    opposition to newly instantiated connection.
    
    *snip*

commit 137779e4e32bcaae7c41676881c934e9a3512373
Author: Amaury Denoyelle <adenoyelle@haproxy.com>
Date:   Tue Jun 1 17:04

    BUG/MINOR: backend: do not set sni on connection reuse
    
    When reusing a backend connection, do not reapply the SNI on the
    connection. It should already be defined when the connection was
    instantiated on a previous connect_server invocation. As the SNI is a
    parameter used to select a connection, only connection with same value
    can be reused.
    
```

So these should be the commits in question.

**Comment by wtarreau** [comment]
Tim, I suspect it might be possible that it happens with nbthread 1 only if you have at least two distinct SNIs on the same server. For example if the health checks and the traffic use a different one, then there's a small window where the check might cause an update to the cached SNI that will cause the reused connection to be reset again.

I'm going to backport the patches above (when I reduce my context switch rate and finish all that's begun). After a long discussion with William we got our minds clearer on how exactly this happens. Thanks for your tests!

**Comment by TimWolla** [comment]
> Tim, I suspect it might be possible that it happens with nbthread 1 only if you have at least two distinct SNIs on the same server. For example if the health checks and the traffic use a different one, then there's a small window where the check might cause an update to the cached SNI that will cause the reused connection to be reset again.

This is not the case, based on the configuration I gave in my initial report:

```
	server munin munin.example.com:443 ssl sni str(munin.example.com) check-sni munin.example.com ca-file /etc/haproxy/ca.pem check
```

However there's a second backend pointing to port 444 on `munin.example.com` that also uses TLS (via the same SNI, though).

**Comment by wtarreau** [comment]
Then another possibility is the one I discussed with William, which is that the SNI entry being updated too late causes several new connection attempts to be reset during a reuse. But I'm not seeing this pattern at the moment in the code since a reused connection must have completed first. Anyway, it's clear that the problem is caused by resetting the session on an existing connection.

**Comment by wtarreau** [comment]
Stupid question, do you know if your backend server supports TLS 1.3 ? William told me that SSL_get_servername() never returns the server name in 1.3 and if so that would explain it because we'd never get the configured name in `ssl_sess_new_srv_cb()` hence the entry is never updated and it could be reset all the time without Amaury's patch.

**Comment by TimWolla** [comment]
> Stupid question, do you know if your backend server supports TLS 1.3 ?

It does. This is all OpenSSL 1.1.1d internally.

FWIW: This fact is also visible in the Wireshark screenshot I sent you in private and the fact that reverting that one commit I emailed you fixed the issue.

**Comment by wtarreau** [comment]
So my analysis was incomplete, SSL_get_servername() properly returns it right after a set, which is the case here, thus the returned value is OK. I'm going to pick Amaury's patches and emit 2.4.10 now.

**Comment by TimWolla** [comment]
I've just marked this as fixed, because it's very likely fixed. I'll leave this open until I had the time to verify this or until you believe it's definitely fixed in all versions.

**Comment by wtarreau** [comment]
Thank you Tim!

**Comment by wtarreau** [comment]
I could backport the required patches as far as 2.0, which is as far as the SNI change was backported. So I'm closing now.
