### ISSUE TITLE
warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes)

### ISSUE THREAD

**Issue by brad0** [haproxy/haproxy#1502]
### Detailed Description of the Problem

```
cc -Iinclude  -O2 -pipe   -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wtype-limits -Wshift-negative-value -Wnull-dereference       -DUSE_KQUEUE  -DUSE_PCRE    -DUSE_POLL  -DUSE_THREAD     -DUSE_TPROXY   -DUSE_LIBCRYPT  -DUSE_GETADDRINFO -DUSE_OPENSSL   -DUSE_ACCEPT4 -DUSE_CLOSEFROM -DUSE_ZLIB                      -DUSE_PCRE -I/usr/local/include  -DCONFIG_HAPROXY_VERSION=\"2.4.9-f8dcd9f\" -DCONFIG_HAPROXY_DATE=\"2021/11/24\" -c -o src/ssl_sock.o src/ssl_sock.c
src/ssl_sock.c:5698:4: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
                        HA_ATOMIC_INC(&counters->sess);
                        ^
include/haproxy/atomic.h:317:43: note: expanded from macro 'HA_ATOMIC_INC'
#define HA_ATOMIC_INC(val)           do { __atomic_add_fetch(val, 1, __ATOMIC_SEQ_CST); } while (0)
                                          ^
src/ssl_sock.c:5699:4: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
                        HA_ATOMIC_INC(&counters_px->sess);
                        ^
include/haproxy/atomic.h:317:43: note: expanded from macro 'HA_ATOMIC_INC'
#define HA_ATOMIC_INC(val)           do { __atomic_add_fetch(val, 1, __ATOMIC_SEQ_CST); } while (0)
                                          ^
src/ssl_sock.c:5703:3: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
                HA_ATOMIC_INC(&counters->reused_sess);
                ^
include/haproxy/atomic.h:317:43: note: expanded from macro 'HA_ATOMIC_INC'
#define HA_ATOMIC_INC(val)           do { __atomic_add_fetch(val, 1, __ATOMIC_SEQ_CST); } while (0)
                                          ^
src/ssl_sock.c:5704:3: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
                HA_ATOMIC_INC(&counters_px->reused_sess);
                ^
include/haproxy/atomic.h:317:43: note: expanded from macro 'HA_ATOMIC_INC'
#define HA_ATOMIC_INC(val)           do { __atomic_add_fetch(val, 1, __ATOMIC_SEQ_CST); } while (0)
                                          ^
src/ssl_sock.c:5730:3: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
                HA_ATOMIC_INC(&counters->failed_handshake);
                ^
include/haproxy/atomic.h:317:43: note: expanded from macro 'HA_ATOMIC_INC'
#define HA_ATOMIC_INC(val)           do { __atomic_add_fetch(val, 1, __ATOMIC_SEQ_CST); } while (0)
                                          ^
src/ssl_sock.c:5731:3: warning: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes) [-Watomic-alignment]
                HA_ATOMIC_INC(&counters_px->failed_handshake);
                ^
include/haproxy/atomic.h:317:43: note: expanded from macro 'HA_ATOMIC_INC'
#define HA_ATOMIC_INC(val)           do { __atomic_add_fetch(val, 1, __ATOMIC_SEQ_CST); } while (0)
                                          ^
6 warnings generated.
```

### Expected Behavior

It builds without warnings as is the case on 64-bit archs.

### Steps to Reproduce the Behavior

Build haproxy on i386 with Clang 12 or newer.

### Do you have any idea what may have caused this?

Regarding the atomic alignment diagnostic...

https://reviews.llvm.org/D85102

### What is your configuration?

```haproxy
.
```

### Output of `haproxy -vv`

```plain
.
```

**Comment by wtarreau** [comment]
Thanks for your report. There's something stupid in this warning in that the compiler warns about the alignment it has chosen itself based on the architecture. On a 64-bit arch there will be a 32-bit hole before the field but here the compiler knows the CPU doesn't support 64-bit accesses and filled the hole, which is why it's surprising that it complains about the unaligned atomic since this arch can't do better.

**Comment by wtarreau** [comment]
By the way, do you notice it only on this file or on other files as well ? Generally speaking we try to fill holes. If this is the only one, we could easily reorder the structure. But if there are a lot, we're not going to change everything to work around this warning, so we might have to add yet another -Wno- something.

**Comment by brad0** [comment]
The warnings pop up for a handful of files throughout the build. Give me a bit and I can do a full build and attach a log of the build.

**Comment by wtarreau** [comment]
OK thank you.

**Comment by brad0** [comment]
[build.log](https://github.com/haproxy/haproxy/files/7799815/build.log)

**Comment by wtarreau** [comment]
Thanks. There are a lot, but most of them seem to be stats, in which case we might possibly afford to reorder some of these field, given that they leave holes in 64 bits anyway. I'll have a look.

**Comment by wtarreau** [comment]
So I found what's happening. clang emits a cmpxchg8b instruction (which technically is only available on Pentium and above), so it seems to assume that your i386 is in fact a Pentium. However, according to intel's architecture software manual, that instruction does *not* require that the memory operand is 64-bit aligned (32-bit processors do not use alignments larger than 32-bits). I think the compiler falls into this mistake by associating it with the equivalent cmpxchg16b used in 64-bit to perform a 128-bit operation, which requires the memory operand to be aligned.

I tried to reorder fields, just to see, and that doesn't work, because 64-bit fields do not force a struct to be 64-bit aligned on 32-bit archs, so the compiler complains all the time. The only way to calm it would be to put __attribute__((aligned(8))) on all fields that are accessed from atomics, which is excessive. We could declare some aligned types using typedefs but that would be more cumbersome to use and even result in larger hence less efficient structure on small architectures, for no benefit. As such I think we'll have no other solution but adding a new `-Wno-` to shut up this incorrect warning.

**Comment by brad0** [comment]
I added to the Makefile..

```
SPEC_CFLAGS += $(call cc-nowarn,atomic-alignment)
```

and no more atomic alignment warnings.

**Comment by wtarreau** [comment]
Sure, and thanks for confirming. I just find it sad that we're forced to shut up a total class of warnings for possible real problems just because of an overzealous compiler doing stupid things :-(  I'm seeing that even firefox gave up on this one. If at least there was a level for the warning to differentiate between missed optimization opportunities and real alignment issues...

**Comment by wtarreau** [comment]
Applied to 2.6, 2.5 and 2.4 now.

**Comment by brad0** [comment]
It looks as if this can be closed now?

**Comment by wtarreau** [comment]
1.8 is still tagged for backports. Not sure it will be done but I don't want to close until it's either done or decided against.
Thanks!

**Comment by brad0** [comment]
Ok, just checking.

**Comment by wtarreau** [comment]
OK it was quick enough to backport, so I've just done it and now we can close :-)
Thanks for the ping, one less issue now!
