### ISSUE TITLE
Pattern cache hurts performance with high cardinality values

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#1518]
### Detailed Description of the Problem

Due to a bit of historical accident (related to the absense of the resolvers server option on older versions of haproxy), we currently reload config, restarting the haproxy worker process, approximately every minute. I’m looking at making better use of resolvers so we only reload when configuration actually changes, however I’ve run into a bit of a roadblock.

If the haproxy runs for more than a few minutes without being restarted, the CPU usage steadily climbs until haproxy is using 100% of available CPU. Unfortunately, initially I wasn't able to reproduce this in non-production environments, and for obvious reasons I want to avoid this situation in production.

However, acting on a theory from previous data from perf, I was eventually able to reproduce a situation (see below). From looking at the results of perf record, a substantial amount of time is spent in the `lru64_get` function. And, interestingly, if I disable the pattern cache by setting `tune.pattern.cache-size 0`, then the performance improves by a noticeable amount. Below I've given the throughput in requests per second with and without the pattern cache enabled for my test run with the haproxy and jmeter config described below.

with cache: 7149.921946685416/sec
without cache: 12103.851041939844/sec

### Expected Behavior

Be able to run haproxy for a significant amount of time without CPU usage increasing. And disabling the pattern cache shouldn't significantly improve performance.

### Steps to Reproduce the Behavior

1. Use haproxy config below and start haproxy
2. Run jmeter with the following configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="2.8" jmeter="2.13.20180731">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Haproxy high cpu test" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <RandomVariableConfig guiclass="TestBeanGUI" testclass="RandomVariableConfig" testname="Random Variable" enabled="true">
        <stringProp name="maximumValue">1000000</stringProp>
        <stringProp name="minimumValue">10000</stringProp>
        <stringProp name="outputFormat"></stringProp>
        <boolProp name="perThread">false</boolProp>
        <stringProp name="randomSeed"></stringProp>
        <stringProp name="variableName">randId</stringProp>
      </RandomVariableConfig>
      <hashTree/>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Clients" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <stringProp name="LoopController.loops">50000</stringProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">4</stringProp>
        <stringProp name="ThreadGroup.ramp_time">1</stringProp>
        <longProp name="ThreadGroup.start_time">1642807105000</longProp>
        <longProp name="ThreadGroup.end_time">1642807105000</longProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.delayedStart">true</boolProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="Account" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">localhost</stringProp>
          <stringProp name="HTTPSampler.port">8989</stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
          <stringProp name="HTTPSampler.protocol"></stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">/user/${randId}/account</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <boolProp name="HTTPSampler.monitor">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <ConfigTestElement guiclass="HttpDefaultsGui" testclass="ConfigTestElement" testname="HTTP Request Defaults" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">localhost</stringProp>
          <stringProp name="HTTPSampler.port">8989</stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
          <stringProp name="HTTPSampler.protocol"></stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path"></stringProp>
          <stringProp name="HTTPSampler.concurrentPool">4</stringProp>
        </ConfigTestElement>
        <hashTree/>
        <RandomVariableConfig guiclass="TestBeanGUI" testclass="RandomVariableConfig" testname="Random Variable" enabled="true">
          <stringProp name="variableName">rand2</stringProp>
          <stringProp name="outputFormat"></stringProp>
          <stringProp name="minimumValue">0</stringProp>
          <stringProp name="maximumValue">100000000</stringProp>
          <stringProp name="randomSeed"></stringProp>
          <boolProp name="perThread">false</boolProp>
        </RandomVariableConfig>
        <hashTree/>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="doc name" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain"></stringProp>
          <stringProp name="HTTPSampler.port"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
          <stringProp name="HTTPSampler.protocol"></stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">/user/${randId}/docs/${rand2}/name</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <boolProp name="HTTPSampler.monitor">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="doc metadata" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain"></stringProp>
          <stringProp name="HTTPSampler.port"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
          <stringProp name="HTTPSampler.protocol"></stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path">/user/${randId}/docs/${rand2}/metadata</stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <boolProp name="HTTPSampler.monitor">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <ResultCollector guiclass="SummaryReport" testclass="ResultCollector" testname="Summary Report" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp>
            <name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>false</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>false</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <threadCounts>true</threadCounts>
            </value>
          </objProp>
          <stringProp name="filename"></stringProp>
        </ResultCollector>
        <hashTree/>
      </hashTree>
      <TestFragmentController guiclass="TestFragmentControllerGui" testclass="TestFragmentController" testname="Test Fragment" enabled="false"/>
      <hashTree/>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
```
which will make many requests using randomly generated ids in the paths.
3. Look at CPU usage, throughput, perf, etc. 
4. Disable the pattern cache (uncomment line 7 in the config) and repeat steps 1-3, notice it performs better.

### What is your configuration?

```haproxy
global
  log-tag haproxy-test
  master-worker
  #log stdout local2
  log /dev/log local2
  nbthread 1
  #tune.pattern.cache-size 0

defaults
  timeout client 10s
  timeout connect 10s
  timeout server 10s
  mode http
  log global
  option httplog

resolvers systemdns
  parse-resolv-conf

frontend test
  bind :8989

  acl dummy1 path_reg ^/user1/\d+-\d+-\d+$
  http-request deny if dummy1
  acl dummy2 path_reg ^/user2/\d+-\d+-\d+$
  http-request deny if dummy2
  acl dummy3 path_reg ^/user3/\d+-\d+-\d+$
  http-request deny if dummy3
  acl dummy4 path_reg ^/user4/\d+-\d+-\d+$
  http-request deny if dummy4
  acl dummy5 path_reg ^/user5/\d+-\d+-\d+$
  http-request deny if dummy5
  acl dummy6 path_reg ^/user6/\d+-\d+-\d+$
  http-request deny if dummy6
  acl dummy7 path_reg ^/user7/\d+-\d+-\d+$
  http-request deny if dummy7
  acl dummy8 path_reg ^/user8/\d+-\d+-\d+$
  http-request deny if dummy8
  acl dummy9 path_reg ^/user9/\d+-\d+-\d+$
  http-request deny if dummy9
  acl dummy10 path_reg ^/user10/\d+-\d+-\d+$
  http-request deny if dummy10

  acl account_path path_reg ^/user/\d+/account$
  acl doc_path     path_reg ^/user/\d+/docs/\d+

  http-request return status 200 content-type text/plain string "User account" if account_path
  http-request return status 200 content-type text/plain string "Document" if doc_path

  default_backend httpbin

backend httpbin
  server httpbin httpbin.org:80

# vim: ft=haproxy
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.17-dd94a25 2021/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.17.html
Running on: Linux 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2_JIT=1 USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=12).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

**Comment by wtarreau** [comment]
Hi,

that's interesting. Do you know how many threads you're running ? There might be more CPU spent on contention to update entries that never match than evaluating non-matching rules. It would be interesting to re-run this test on 2.5 or 2.6-dev as a few things were improved on the pattern matching. I'm thinking that maybe we could improve the situation by sharding the cache tree on the hashing key in order to significantly reduce contention.

**Comment by lukastribus** [comment]
I can see `nbthread 1` in the configuration there, but also, shouldn't the pattern cache be thread local? Docs suggest so.

**Comment by wtarreau** [comment]
Ah you're right, I just rechecked and it's indeed thread-local. Also sorry for nbthead, I looked for it but didn't see it.

Thus at this point I think we're just seeing the extra cost of dealing with never matching entries that are inserted but rarely or even never used. That's a perfectly valid case for disabling the cache in this case.

**Comment by lukastribus** [comment]
There are more details in the discourse topic:
https://discourse.haproxy.org/t/cpu-climbs-up-if-haproxy-runs-for-more-than-a-few-minutes/6935

Since the CPU climbs only after a few minutes, it  sounds like the performance drops due to GC, when hitting the cache cap. 


https://discourse.haproxy.org/t/cpu-climbs-up-if-haproxy-runs-for-more-than-a-few-minutes/6935/5

**Comment by wtarreau** [comment]
Thank you Lukas for the extra context. @tmccombs, that's a good idea except that there's no rebalancing and that actually removing an entry from a tree is the fastest operation (O(1)). But your description definitely makes me think something is related to the moment we start to release older objects.

Just thinking, are you certain you're not swapping for example, or running in a VM with memory ballooning enabled, or at least that your cache is not getting huge ? I'm asking because once the cache reaches its max number of objects, the oldest (least recently used) object is released when adding a new one. We could imagine that accessing an object that's not anymore in the L3 cache or worse, no more in RAM because the machine swaps, would be slower.

It would be useful if you could share a copy of "perf top" output when this happens, to give us some more guidance. Please do not select "zoom on DSO" as it would get rid of kernel and libc, which are also important (e.g. memcpy, free() calls etc). Thanks!

**Comment by wtarreau** [comment]
I tried your config with randoms here and instrumented the code. There's no hit, only misses in the LRU cache (as expected), so each new entry gets committed. But with 2 cores I'm seeing 280000 requests/s, and 3.4 million accesses to the LRU cache per second. Despite this it stays at 16% CPU. I can only make it use more CPU by significantly increasing the pattern cache size (e.g it grows to 40% CPU with 500k entries due to the slower memory accesses). But given that at such rates it's instantly full and refreshed, I still don't know what could possibly slow it down after so long a time :-(

**Comment by wtarreau** [comment]
Thayne, I think we're both wasting our time here. In fact since you're injecting randoms, you're doing a 100% miss rate on the cache and it's unavoidable that a cache that has to store entries that are never found and that looks up only entries that never exist increases lookup costs. Testing with your workload indeed shows me that we're spending time there but that's totally expected. As I said, the CPU time increases as soon as the cache doesn't fit into the CPU caches anymore, as memory accesses start to count quite a bit, and the cost as reported by perf is directly in the tree descent during the lookup (i.e. memory lookups).

In a normal workload, users perform regex/str matches against patterns that tend to repeat themselves, which is why the cache usually speeds up host header lookups etc. On randoms it will never bring any value of course. If you think that you're dealing a lot with such a workload, it might be worth disabling it. Maybe we could improve the doc on this subject as well.

I have no idea how it's possible that it starts to further slow down after a few minutes. By default the cache stores 10k entries, so in your case it starts to recycle its contents during the first tenth of a second since you're doing ~12 lookups per request. Maybe you're simply seeing the CPU frequency slowing down after a while (like my laptop does after heating a bit).

I'm interested in your feedback on these points but I don't see anything more to be done there (except maybe improving the doc) as for me the lower performance on randoms is expected.

**Comment by tmccombs** [comment]
> are you certain you're not swapping for example, 

Yes, I have swapping disabled on the system

> or running in a VM with memory ballooning enabled,

I don't think so. In production it is running on EC2 instances, which from my understanding don't use memory ballooning. For my local tests, I ran directly on the hardware.

> or at least that your cache is not getting huge ?

I'm using the default size for the cache.

> I have no idea how it's possible that it starts to further slow down after a few minutes. By default the cache stores 10k entries, so in your case it starts to recycle its contents during the first tenth of a second since you're doing ~12 lookups per request. Maybe you're simply seeing the CPU frequency slowing down after a while (like my laptop does after heating a bit).

Running my example config with the jmeter settings I gave does result in high cpu withing a second for me. It is only a rough approximation of the actual production workload where it slows down after a minute or so. In the real workload there is repetition among requests, but the requests do  contain things like user ids, document ids, etc. and unfortunately we have quite a few regex/sub/end rules. So while I don't know the ratio of hit to miss on the cache (is there a way to see that?) I suspect it is pretty low, but not zero.  I also don't think a single instance of haproxy would be receiving quite as many requests as jmeter is able to produce under normal workload. Certainly not a single thread. 

I agree that disabling the cache is probably the best way to move forward in my case. 

FWIW, here's the top of my perf report (unfortunately, I seem to have been missing something so it doesn't have symbols for everything):

```
Samples: 298K of event 'cycles', Event count (approx.): 90797237702                                                                                                                                                  Overhead  Command  Shared Object        Symbol                        
  11.39%  haproxy  haproxy              [.] lru64_get                                                                                                                                                                   3.05%  haproxy  [unknown]            [k] 0xffffffff857f597c                                                                                                                                                          2.71%  haproxy  haproxy              [.] process_stream                                                                                                                                                           
   1.77%  haproxy  haproxy              [.] sess_build_logline                                                                                                                                                          1.30%  haproxy  haproxy              [.] acl_exec_cond                                                                                                                                                               1.28%  haproxy  haproxy              [.] h1_snd_buf                                                                                                                                                               
   1.25%  haproxy  haproxy              [.] h1_headers_to_hdr_list                                                                                                                                                      0.97%  haproxy  haproxy              [.] pattern_exec_match                                                                                                                                                          0.96%  haproxy  libc-2.31.so         [.] __vfprintf_internal                                                                                                                                                      
   0.87%  haproxy  libpcre2-8.so.0.9.0  [.] pcre2_match_8                                                                                                                                                               0.87%  haproxy  [unknown]            [k] 0xffffffff85a0001d                                                                                                                                                          0.83%  haproxy  [unknown]            [k] 0xffffffff85a0014f                                                                                                                                                       
   0.72%  haproxy  haproxy              [.] _do_poll                                                                                                                                                                    0.64%  haproxy  haproxy              [.] h1_rcv_buf                                                                                                                                                                  0.63%  haproxy  haproxy              [.] smp_fetch_path                                                                                                                                                           
   0.61%  haproxy  [unknown]            [k] 0xffffffff85804633                                                                                                                                                       
   0.59%  haproxy  haproxy              [.] http_wait_for_request                                                                                                                                                    
   0.57%  haproxy  haproxy              [.] stream_new                                                                                                                                                               
   0.50%  haproxy  [unknown]            [k] 0xffffffff84d0be66                                                                                                                                                       
   0.46%  haproxy  haproxy              [.] h1_io_cb                                                                                                                                                                 
   0.45%  haproxy  haproxy              [.] process_runnable_tasks                                                                                                                                                   
   0.44%  haproxy  haproxy              [.] http_req_get_intercept_rule                                                                                                                                              
   0.42%  haproxy  haproxy              [.] si_cs_recv                                                                                                                                                               
   0.42%  haproxy  libpcre2-8.so.0.9.0  [.] 0x000000000001ccaf                                                                                                                                                       
   0.42%  haproxy  libpcre2-8.so.0.9.0  [.] pcre2_jit_match_8 
   ```

I am a little surprised that in the case where every cache lookup misses, the time spent in doing cache lookups is so much more than doing the actual regex evaluations. Assuming I'm interpreting the perf results correctly.

**Comment by wtarreau** [comment]
Thanks for the details.

>  It is only a rough approximation of the actual production workload where it slows down after a minute or so.

OK makes sense then. Thus basically when the pattern cache doesn't fit into the CPU cache anymore, it's getting much slower. If your prod traffic is significantly lower it makes sense.

> So while I don't know the ratio of hit to miss on the cache (is there a way to see that?)

I re-discovered during testing that no, there's no such indicator at the moment. The problem is always the same, high-frequency counters must absolutely not be shared between threads, so this will require to have per-thread counters. Some elements already have such, but still few (they're expensive in terms of memory and collection). I do think that we would benefit having that particularly for this one, it could be a good hint for users to decide to disable the cache if the benefit is too low for them.

> I am a little surprised that in the case where every cache lookup misses, the time spent in doing cache lookups is so much more than doing the actual regex evaluations

It's not just the lookup but also the insertion and it's purely a matter of workload size. The insertion tends to be forgotten (including by me initially in the response) because we have to cache the fact that this value didn't match that pattern (otherwise the cache is useless). The hot instruction is the tree descent during the insertion. Re-writing elements that were recently modified with other changes in between will force CPU cache write-backs to maintain write-ordering, and as long as the data set is small this is fast, but here you have to keep in mind that you're doing 86k lookups, 86k deletion and 86k insertions per second within 10k nodes for 11% CPU. It's neither great not awful, it's average.

I think that with a small top-level hash we could shard the trees and reduce the memory overwrites. I don't know how much of a speed up this could bring, but this would definitely complicate eviction. And eviction by definition accesses colder objects so we must not dismiss the importance of this part. However, one benefit of a radix tree is that the vast majority of the descent concerns shared nodes and that only the last 1 or 2 levels will be slower if moved back to DRAM.

I'll do some tests with a small hash table, at least for curiosity as I find this interesting. I'm keeping the issue open to share findings if any.

**Comment by wtarreau** [comment]
I've tried to hash the key into an array of roots. It's interesting to see that it doesn't bring anything as we're still limited by the workload size and memory access time. With less than 1024 entries, it gets slightly slower by 0.5%. With 4096 entries the performance recovers and it reaches a 2% gain. At 65k entries, it's 1% slower. But even 4k entries taking 32kB RAM gaining only 2% is ridiculous. What's amusing is to see that the instructions eating time are spread all over the lru_get() one, probably because CPU cache misses are much more frequent and can hit any instruction.

So in the end it looks like we're more or less optimal at this point. When I'm done with the compact trees, I'll see if I can use them there. That could be interesting as each node is significantly smaller, so we'll stuff more LRU nodes into the same amount of L1, L2, and L3 caches, and possibly observe gains corresponding to those resulting from lowering the cache size.

**Comment by wtarreau** [comment]
Noting this for reference. I tested on 2024-04-07 with the compact trees, and it was significantly slower (4.08M/s vs 6.55M/s) as soon as 10% of the operations cause a delete, which is the case here since we're in the worst case with many misses hence eviction. So probably the only solution in these cases is to just disable the LRU cache.

**Comment by wtarreau** [comment]
@tmccombs you might be interested in trying this patch. It skips the LRU cache for low-cardinality patterns (5 min for regex, 20 min for others), based on local measurements showing that some evaluations are faster than the LRU cache lookup. Some of the speed up also comes from not evicting objects for entries that would match very fast, so it allows to further reduce the cache size (2k gives me best results here from the patterns gathered on haproxy.org). I'm interested in your feedback, I can easily merge that into 3.1 if results are positive for you.

[0001-OPTIM-pattern-only-apply-LRU-cache-for-large-enough-.patch.txt](https://github.com/user-attachments/files/17611428/0001-OPTIM-pattern-only-apply-LRU-cache-for-large-enough-.patch.txt)

**Comment by wtarreau** [comment]
Just FYI I've merged this. We can further refine thresholds later if needed.

**Comment by wtarreau** [comment]
I propose that we close this issue for now since it's been silent for more than two years and future access patterns will differ anyway and will require new captures.
