### ISSUE TITLE
Haproxy 2.5.* left a lot connections to backend 

### ISSUE THREAD

**Issue by Jarvis-Zhou** [haproxy/haproxy#1522]
### Detailed Description of the Problem

We're migrating from haproxy 1.6 to haproxy 2.5. But after one day, there are many connection to backend are not closed.

![image](https://user-images.githubusercontent.com/30723592/150790938-9b23ae60-2abc-4d9f-8b0e-22856c6f1a5d.png)

![image](https://user-images.githubusercontent.com/30723592/150790888-1e403ade-dfbb-40a7-8452-87cfc4000a53.png)

The port haproxy listening on is 5443, and backend listen on 5444.

### Expected Behavior

connections to haproxy equals to connections to backend

### Steps to Reproduce the Behavior

Run haproxy newer than 2.5

### What is your configuration?

```haproxy
global
    daemon
    maxconn 64000
    spread-checks 4
    stats socket /var/lib/haproxy/haproxy.sock mode 600 level admin

defaults
    option   dontlognull
    retries  3
    timeout  connect 30s
    timeout  client  30s
    timeout  server  30s
    timeout  client-fin 30s
    timeout  server-fin 30s
    timeout  tunnel  1h
    option   redispatch
    balance  roundrobin
    maxconn  10000
listen apiserver
    bind 192.168.157.134:5443
    bind 172.16.0.222:5443
    bind 172.16.0.55:5443
    mode tcp
    balance roundrobin
    option httpchk GET /healthz
    http-check expect status 401
    server apiserver1_5444 172.16.0.168:5444 check check-ssl verify none maxconn 5000
    server apiserver2_5444 172.16.0.222:5444 check check-ssl verify none maxconn 5000
    server apiserver3_5444 172.16.0.228:5444 check check-ssl verify none maxconn 5000
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.12-4b7772e 2022/01/11 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.12.html
Running on: Linux 4.18.0-147.5.1.6.h475.eulerosv2r9.x86_64 #1 SMP Wed Jun 2 09:00:31 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_OPENSSL=1 USE_ZLIB=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL -LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC -PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 7.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by Jarvis-Zhou** [comment]
I found that many fds not in session. like this one.
![image](https://user-images.githubusercontent.com/30723592/150791995-d26167d1-797d-438d-acdb-65c93e4f31aa.png)

**Comment by wtarreau** [comment]
Sorry, I didn't understand your last statement. What do you mean, that there are many FDs and not many sessions in `show sess` maybe ?

It could happen to have many connections due to idle conns, but you will never get more than 25% of the total FDs in idle conns by default. Haproxy will continually monitor the number of connections it needs on average for a server and will maintain just the right number to avoid establishing new ones all the time. If your load is high, it's perfectly possible that it notices that due to some traffic spikes you need such a large number, and the number you indicate is roughly 25% of maxfd (roughly twice maxconn) so that's not impossible.

However I'm concerned because your config presents only 3 servers with each a maxconn of 5000. So for this to be possible it would imply that you're running with at least 8 servers. Maybe that's the case because you shared only a config snippet, but I'd like to check this with you.

Other question, you mentioned 2.5 in the title but showed an haproxy 2.4.12 output. Did you try both versions and do they both exhibit the same behavior ?

In order to check if it's related to connection pools, you can disable connection reuse and work like 1.6 by setting `http-reuse never` in your backend(s). If that's it you'll see that number significantly shrink. But note that in this case it will likely imply that in 1.6 such high values per server periodically happen (possibly for very short durations so that you didn't notice them).

**Comment by capflam** [comment]
@wtarreau, there is no reuse here, it a TCP proxy.

**Comment by wtarreau** [comment]
Ah you're right, I missed that one! The other questions still stand, though.

**Comment by Jarvis-Zhou** [comment]
@wtarreau I test both 2.5.* and 2.4.12.  

I shared only a config snippet, but the other is just some other listeners. Listener apiserver has just 3 backends.

In tcp mod, does http-reuse nerver make sense ?

**Comment by wtarreau** [comment]
Thank you. No you're right, there's no such a thing in TCP. However I don't see why/how there could be an increase in number of connections in pure TCP mode :-/  I wouldn't rule out a stupidity related to connection pools though, but I don't see what, given that by definitions these established connections are not closed, hence not recycled.

Did you observe if that number grows continually with traffic or with time ? Or are you observing sawtooth-like shapes ?

**Comment by Jarvis-Zhou** [comment]
At first it grows very slow, then it grow up very quick.

**Comment by Jarvis-Zhou** [comment]
It grows with time, the client connections is nearly 8000.

**Comment by Jarvis-Zhou** [comment]
What can I do to finger out this problem ?

**Comment by wtarreau** [comment]
Issuing "show sess all" and "show fd" on the CLI could possibly help, we'll see old connections and check from their flags if it's expected that they're still there. Be careful, it may disclose some possibly private information (e.g. server IPs, backend names etc). Have a look at the dump before posting. You can edit the IPs if you want, they will not affect analysis.

**Comment by Jarvis-Zhou** [comment]
[logs.zip](https://github.com/haproxy/haproxy/files/7934421/logs.zip)

**Comment by Jarvis-Zhou** [comment]
Just like fd 17261, it can not be found in sess.

**Comment by wtarreau** [comment]
OK thank you very much, you've very likely uncovered a real bug. Your timeouts are all short, despite this we can see connections like this one which have been idling for 3 hours without any timeout set:
```
0xe77b10: [25/Jan/2022:16:43:33.052555] id=23 proto=tcpv4 source=172.16.22.xxx:53918
  flags=0x4e, conn_retries=1, srv_conn=0xdde270, pend_pos=(nil) waiting=0 epoch=0
  frontend=apiserver (id=2 mode=tcp), listener=? (id=3) addr=172.16.0.xxx:5443
  backend=apiserver (id=2 mode=tcp) addr=172.16.0.xxx:29258
  server=apiserver2_5444 (id=2) addr=172.16.0.xxx:5444
  task=0xe77f80 (state=0x00 nice=0 calls=372 rate=0 exp=14s tmask=0x1 age=2h57m)
  si[0]=0xe77dc0 (state=EST flags=0x200008 endp0=CS:0xe77ac0 exp=<NEVER> et=0x000 sub=1)
  si[1]=0xe77e18 (state=EST flags=0x200018 endp1=CS:0xe798a0 exp=<NEVER> et=0x000 sub=1)
  co0=0x7fc94c03a1a0 ctrl=tcpv4 xprt=RAW mux=PASS data=STRM target=LISTENER:0xddce60
      flags=0x80003300 fd=58 fd.state=121 updt=0 fd.tmask=0x1
      cs=0xe77ac0 csf=0x00008200 ctx=(nil)
  co1=0xe796f0 ctrl=tcpv4 xprt=RAW mux=PASS data=STRM target=SERVER:0xdde270
      flags=0x10003300 fd=341 fd.state=10121 updt=0 fd.tmask=0x1
      cs=0xe798a0 csf=0x00008200 ctx=(nil)
  req=0xe77b20 (f=0x848202 an=0x0 pipe=0 tofwd=-1 total=1110910)
      an_exp=<NEVER> rex=23s wex=<NEVER>
      buf=0xe77b28 data=(nil) o=0 p=0 i=0 size=0
  res=0xe77b80 (f=0x80048202 an=0x0 pipe=0 tofwd=-1 total=9182138)
      an_exp=<NEVER> rex=23s wex=<NEVER>
      buf=0xe77b88 data=(nil) o=0 p=0 i=0 size=0
```
This connection is still valid at the system level (still being polled and not shut), but the
absence of timeouts on both sides is absolutely not normal.

For the FD that cannot be found, it may sometimes simply indicate that the connection finished
between the two commands. But I'm really concerned by the lack of timeouts above, this deserves
a deeper analysis.

**Comment by wtarreau** [comment]
By the way, what is the most recent version that you're aware of that is not affected ?

**Comment by Jarvis-Zhou** [comment]
I have tried 2.4.12 and 2.5.1, both have this problem. I have not found a version that is not affected.

**Comment by Jarvis-Zhou** [comment]
Is there any other stable version that I can have a try?

**Comment by Jarvis-Zhou** [comment]
But the problem I met is that the connection between haproxy and apiserver is not closed correctly, and then use all of my client ports. Maybe this kind of session later will cause the connection between haproxy and apiserver not closed?

**Comment by wtarreau** [comment]
I made a mistake in my analysis, the connection I extracted above does have a timeout, so likely it's a long connection with some activity on it.

If you want to try another stable version it could be useful to test an older 2.4 like 2.4.7, and the latest 2.2 (2.2.20).

**Comment by capflam** [comment]
I extracted some info from your files. here is the result:
 * There are 7593 client connections on `lport` 5443 in `fd.log`
 * There are 8607 server connections on `rport` 5444 in `fd.log`
 * 40 of these client connections are not attached to any session listed in `sess-all.log`
 * 1058 of these server connections are not attached to any session listed in `sess-all.log` file (too much to be a side effect of the delay between the two commands)

All "leaked" connections follow the same pattern. For instance:

``` 
   160 : st=0x010121(cL heopI W:sRa R:srA) tmask=0x4 umask=0x0 owner=0x7fc988258770 iocb=0x573130(sock_conn_iocb) back=1 cflg=0x10002300 fam=ipv4 lport=6594 rport=5444 sv=apiserver/apiserver1_5444 mux=PASS ctx=0x7fc98815eee0 xprt=RAW
```

**Comment by wtarreau** [comment]
Good job Christopher! so his means that these connections are simply waiting for data (or a close) from a server and are not seeing it come! That's strange.

I'm suspecting that we're facing streams that have already timed out and aborted, but that for some reason that's yet to be figured out, the close hasn't propagated to the connection. I have absolutely no idea how this can happen but as you're saying, there are too many of them for this to be pure luck!

**Comment by lukastribus** [comment]
Can you try with `nbthread 1` in your global section, just to exclude multi-threading? You certainly did not have that in 1.6, and I can see that 32 threads would be used on your box. How is CPU usage anyway?

`Built with multi-threading support (MAX_THREADS=64, default=32).`

Not sure how likely this is related, but it's a single config line to disable multi threading so it's worth a try.

**Comment by Jarvis-Zhou** [comment]
I have not tried 1.6 yet. I will try v2.2.20 and v1.6 next.

**Comment by Jarvis-Zhou** [comment]
version 2.2.20 looks good to me, the connections is nearly equal between the two side.

**Comment by wtarreau** [comment]
Thank you, that can help us compare what could have changed. Please also have a look at Lukas' suggestions above so that we can try to narrow the issue down.

**Comment by Jarvis-Zhou** [comment]
Which version should I test on. 2.4.12 ?

**Comment by wtarreau** [comment]
Let's say the first one that causes trouble. 2.4.12 is fine since you're seeing the issue there.

**Comment by Jarvis-Zhou** [comment]
Wait for a moment. It takes some time to check if this problem will be reproduced.

**Comment by Jarvis-Zhou** [comment]
v2.4.12 with `nbthread 1` also have this problem. 
![image](https://user-images.githubusercontent.com/30723592/151280993-168dfd50-6485-4994-a617-fc111075429d.png)

**Comment by wtarreau** [comment]
Thank you for testing!

**Comment by hujiko** [comment]
Hey,

I also experience this issue on a TCP-Proxy.
I also experience it, regardless of using multithreading or not.

According to `netstat` those connections are all `ESTABLISHED`.
According to the HAProxy stats, it currently has 5-10 connections to that Backend in total, but a `netstat -anp | grep 10.x.x.x | wc -l` gives me 144712 Connections to the Backend.

If you need any information form me, I am willing to provide it

**Comment by wtarreau** [comment]
@hujiko I didn't see your response. If you're still seeing this with latest versions, I'd be interested in the output of "show info", "show sess all" and "show fd". Beware that it might be large, and could reveal some internal addressing or server names, so you may want to double-check/edit before sharing (or send us privately).

**Comment by capflam** [comment]
@hujiko, thanks for the info (sent offline). After a quick look, there is a huge number of FDs attached to no session. Except few ones, all of them are server connections to your graphite server (the TCP one).  The connection flags are  `0x10402300 (CO_FL_PRIVATE | CO_FL_WAIT_L4_CONN | CO_FL_ADDR_TO_SET | CO_FL_XPRT_READY | CO_FL_CTRL_READY)`.

I must dig more deeper now. But in the mean time, could you disable the health-check to confirm or refute it is related ?


EDIT: It is probably not related to heath-check because you had 40K leaked connections in less than 5min

**Comment by capflam** [comment]
For instance here is an orphan fd:
```
47108 : st=0x010001(cL heopi W:sra R:srA) tmask=0x4 umask=0x0 owner=0x7f81ffae0770 iocb=0x56399ed973a0(sock_conn_iocb) back=1 cflg=0x10402300 fam=ipv4 lport=35647 rport=XXXX sv=BCK/SRVmux=PASS ctx=0x7f81ffab3720 xprt=RAW
```

**Comment by wtarreau** [comment]
Very interesting, because if there's PRIVATE then it eliminates the possibility of leaks in the connection pool, and already cuts the problem in half (we could have imagined that they would be placed there by accident despite being in TCP for example).

Note that the read side is being polled (active but not ready). It could possibly be a check that finished before the connection closed, but I don't understand then why we never receive a response. Or maybe the server never closes and the check never closes either ?

**Comment by capflam** [comment]
If these FDs are attached to health-checks, it explains why there is no stream. But this also means a health-check is creating connections in loop because @hujiko graphs suggest 40k connections were created in 4min. With an inter to 5s and a connection timeout to 1s, it is huge. No error are reported on these connections and they are not fully established from HAProxy point of view (` CO_FL_WAIT_L4_CONN` flag is still set).

I'll review the health-check code.

**Comment by capflam** [comment]
For now, I've no idea. Reading the code, there is nothing obvious. I really don't know how a connection with the flags above set may be detached from the health-check to open a new one, and this on a loop. Disabling the health-check temporarily for the proxy may help to validate it is the root of the issue.

@hujiko, does the leak occur immediately after starting ?

**Comment by capflam** [comment]
@hujiko, checking more carefully graphs you sent me, it seems the connection leak is related to a connection burst during ~10sec every minute from 15:31:00 with many retransmits  (4k/sec for the first 2 bursts). It seems the leak happens during the burst. Is there anything that can explain these bursts on your side ?

**Comment by hujiko** [comment]
Hey @capflam,

the leak does not seem to start immediately after starting HAProxy. (or it is so little that I didn't see it due to "regular" connections)
I also don't see the leak when health checks are enabled, but no actual traffic is coming in.

But: How I am testing is:
- First start HAProxy
- Then DNS-Switch the traffic from the old system to HAProxy.

Therefore, I can not switch traffic ON or OFF in an atomic operation, but it will always be a "slow" rise and fall due to DNS propagation (normally 1-2 Minutes).

On my last test, 2 days ago, After I updated the DNS-Record it took around 15 Minutes until the insane rise of connections started.

The first blue marker in the graph shows when I updated the DNS-Record to point to HAProxy.
The second blue marker shows when I updated the DNS-Record again to switch traffic away from HAProxy.
The four lines in the diagram show the four HAProxy nodes that are getting this kind of traffic.

The metric itself shows the amount of established TCP connection from the OS-view:

![sockets in use](https://user-images.githubusercontent.com/946442/157428836-e01d7119-b7b3-49be-a19e-f44fc45b79ac.png)


The respective listen block:
```
listen TCP_GRAPHITE-2003
  mode tcp
  bind 10.X.X.X:2003
  option tcplog
  timeout client 30s
  timeout server 30s

  option tcp-check
  timeout check 500ms
  default-server inter 5s

  server my-server 10.X.X.X:2003  check source 10.X.X.X
```

As far as I know, established connections are never closed by the backend server / statsd.
The only way a connection can be closed, is when the frontend connection is terminated, then I would expect the backend connection to drop.


> Is there anything that can explain these bursts on your side ?

Yes, a lot of nodes send their metrics once per Minute.
As that is sadly not distributed over the whole minute, at the beginning of the Minute, all Nodes start opening a connection at the same time.

**Comment by capflam** [comment]
Thanks @hujiko. I made a test and by chance I reproduce the issue. Or it seems to be the same issue. If a client connects to haproxy and aborts before the connection establishment, the stream is closed but the back connection remains open. It is just a quick observation. I'm digging.

**Comment by capflam** [comment]
@hujiko could try the following patch ? it should fix your issue. Note that the 2.2 and 2.0 are not affected.

[0001-BUG-MAJOR-mux-pt-Always-destroy-the-backend-connecti.patch.txt](https://github.com/haproxy/haproxy/files/8216022/0001-BUG-MAJOR-mux-pt-Always-destroy-the-backend-connecti.patch.txt)

**Comment by hujiko** [comment]
Yes, it fixed my issue.

I applied it to three out of the four nodes and on none of the patched ones, the issue popped up again.
For validation I left one node unpatched and there it was happening, so I am sure, that this patch does fix my issue.

Interestingly, on the patched nodes also the TCP retransmits per second did not rise, while that metric jumped very high on the unpatched node again.
I expected the retransmits to be the cause for the connection leaks, but it seems to be the other way around.

Anyways, I am looking forward to see this merged and backported :)

**Comment by capflam** [comment]
Thanks for the feedback !

Retransmits is not the cause but the result of the bug. Now, when a connection attempt times out, the connection is closed. Thus, with a connect timeout to 1s, you will probably have no retransmit. With the bug, the connection is left open. It will be closed by the kernel after all SYN retires (6 by default).

So the patch fixes the issue. But it means you have many connection failures.

**Comment by hujiko** [comment]
> So the patch fixes the issue. But it means you have many connection failures.

Would those connections have worked without the fix?
As far as I understood, those backend connections could be established after a retransmit, but would then be detached from the frontend connections, so effectively not useable anyways?

Is that something, that `option redispatch` would catch and reopen a connection to another backend server then?

**Comment by capflam** [comment]
That's a good point. If the connection is finally established but after a retry, it will indeed be lost. If the server has no timeout and never close the connection on its side, the connection will stay in this state.

Note that if  you want to use these connections, you should increase the connect timeout. The question is how long ? Is there any reason to have so much delay to establish a connection ? If yes, increasing the connection timeout may be a good idea.

redispatch option will indeed open a connection on a new server on retry. But this does not help in this case. With or without this option, a new connection is created on retry. The old one should be closed (in TCP only, in HTTP it is an other story).
