### ISSUE TITLE
Add prometheus custom labels to metrics(backend, frontends)

### ISSUE THREAD

**Issue by Infusible** [haproxy/haproxy#1531]
### Your Feature Request

Currently, there are no settings for backends or frontends to add labels for Prometheus metrics. Example:
```
# HELP haproxy_frontend_status Current status of the service, per state label value.
# TYPE haproxy_frontend_status gauge
haproxy_frontend_status{proxy="fe_main",state="DOWN"} 0
haproxy_frontend_status{proxy="fe_main",state="UP"} 1
```

### What are you trying to do?

I want the following
```
frontend fe_main
  bind *:80
  labels my_label1=my_team,my_label2=prod_env
```
and 
```
# HELP haproxy_frontend_status Current status of the service, per state label value.
# TYPE haproxy_frontend_status gauge
haproxy_frontend_status{proxy="fe_main",state="DOWN",my_label1="my_team",my_label2="prod_env"} 0
haproxy_frontend_status{proxy="fe_main",state="UP",my_label1="my_team",my_label2="prod_env"} 1
```

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.2.0-1.0.0-244.597 2021/11/19 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around February 2025.
Known bugs: https://www.haproxy.com/documentation/hapee/2-2r1/onepage/changelog/#2.2.0
Running on: Linux 4.14.252-195.483.amzn2.x86_64 #1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -Werror -DMAX_SESS_STKCTR=12 -DSTKTABLE_EXTRA_DATA_TYPES=10
  OPTIONS = USE_PCRE_JIT=1 USE_LINUX_TPROXY=1 USE_LINUX_SPLICE=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_CPU_AFFINITY=1 USE_NS=1 USE_SYSTEMD=1 USE_MODULES=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS +MODULES -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : prometheus-exporter
Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace
        [CACHE] cache
        [FCGI] fcgi-app
```

**Comment by bgrooot** [comment]
Is there anything discussed about this feature?
I'm asking because it's a feature I need..

**Comment by capflam** [comment]
AFAIK, nobody is working on this issue. But I don't really understand the need. Probably because I'm not a Prometheus expert. Adding the same labels on all metrics seems strange to me. There is nothing in the Prometheus configuration to identify the jobs or to add some annotations ? 

In addition, the exporter is already pretty verbose because of the Prometheus format itself, adding more labels will make it more verbose. But I guess it is not an issue for those adding these extra labels. Instead of adding extra labels, we can also think to add a name to the exporter and expose it in a dedicated metrics. For instance:

```
haproxy_process_exporter{name="promex"} 1
```

Technically speaking, since we add some directives to configure the prometheus exporter, it is probably a good idea to think about a true config section for it. The question is to know if this configuration should be global or if there is a reason to have several exporters with different configurations. Of course, a unique global configuration is far easier to implement and it seems reasonable. But again, I'm not a Prometheus expert.

Finally, and the most important, we must find someone to work on it :)

**Comment by Infusible** [comment]
haproxy already has an endpoint for collecting metrics by Prometheus out of the box, no need to add any other exporters)
https://www.haproxy.com/documentation/haproxy-configuration-tutorials/alerts-and-monitoring/prometheus/#configure-the-prometheus-exporter

But it would be cool to add custom labels to the backends that would indicate teams of workers or people responsible for the given backend, so you can set up additional alerting on such custom labels

**Comment by capflam** [comment]
The idea was not to add another exporter but to add a dedicated name for an specific haproxy instance, exported in a metric. Instead of having it as a label for all metrics, it seems lighter to have it in a metric.

But by reading your comment,  I realized that you want to add custom labels per entity: for frontends, backends, servers and listeners.  Honestly, I have not idea. In this case, it seems easier to add a dedicated metric per entity to convey these labels. My only concern is about the size of data exported and the CPU required to export them. With not so huge configurations, requests to the prometheus exporter are far from free. So we must be careful.

**Comment by bgrooot** [comment]
Is there a way to add dedicated metrics?
I wish it was possible without modifying the `service-prometheus.c` file..

**Comment by capflam** [comment]
unfortunately no. The service must be modify to do so.

**Comment by Infusible** [comment]
It is possible to add labels only for the frontend and backend and only for them?
How example "description" - https://www.haproxy.com/documentation/haproxy-configuration-manual/latest/#4.2-description

**Comment by capflam** [comment]
It is indeed an idea. I don't know if there are some limitations on Prometheus side  for the length of label value. But it seems feasible. On Prometheus, having this kind of metrics is common ? usable ? I don't use it, so I don't really know if it is a hack or a common usage.

**Comment by Infusible** [comment]
this is an example of an option that can be taken as a base and add another directive that will be used for prometheus metrics
now the "description" directive simply adds a description to the webview of the statistics page

**Comment by roock** [comment]
having the description exposed in the prometheus metrics would be helpful

**Comment by pmaoui** [comment]
This feature would be very interesting, that's also something we want to do.

**Comment by capflam** [comment]
Just to be sure, is a new metrics with the frontend/backend description, if defined, good enough to match your needs ? Something like:

```
haproxy_frontend_description{proxy="...", description="some description"} 1
```

Note there is also a global description for the process that could exported.

**Comment by roock** [comment]
@capflam I would vote for having the description directly on all affected metrics, not as a separate metric e.g.

`haproxy_backend_active_servers{proxy="...", description="some description"} 4` 

For the global description, this could be added to all of the `haproxy_process_*` metrics.
Concerning your questions about limits on metric labels, [there shouldn't be any limit on the label length.](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)

Additional input since you're not so familar with prometheus: having the description directly in the metrics makes queries easier e.g. searching for a metrics with "CRIT" inside the description.

with description directly on the metrics: `haproxy_backend_active_servers{description=~"CRIT"}`

with description as a seperate metric this would be something like this: (derived from a similar query, so not 100% this is the correct one):
`(haproxy_backend_active_servers) and ON (instance, proxy) (haproxy_backend_active_servers ) * on(proxy) group_left (description) haproxy_backend_description{description=~"CRIT"}`

Also for the first method, you can also use the `description` label in your alerts  e.g. as additional information, which doesn't work in the second case.

**Comment by capflam** [comment]
Thanks @roock. 

It is now implemented. If defined, the description of a section (global,frontend,backend,listen) will be added in the`desc` label. But only if `desc-labels` parameter is added in the URL. Note that if a description is provided for a backend, all its servers will inherit of the description too. `desc` label is not set if there is no description on a section or if `desc-labels` parameter is not set. 

Finally, the global description and node values are now exposed in all cases, via `haproxy_process_description` and `haproxy_process_node` metrics.

For now it is not planned to backport it to 3.0. But the 3.1 should be emitted in few weeks. 

It is not exactly what was asked for in the feature request description. But not too far. Can we consider it as closed or not ?

**Comment by Infusible** [comment]
@capflam 
this is very good
we use the enterprise version, but I think that in 3.1 and 3.2 this functionality will also appear soon) thank you

**Comment by capflam** [comment]
Because it is in HAPoxy-3.1, this will automatically be included in the entreprise edition of the same version.

**Comment by roock** [comment]
Thanks @capflam. I guess the issue can be closed.
