### ISSUE TITLE
Sync active branches on github mirror

### ISSUE THREAD

**Issue by geaaru** [haproxy/haproxy#1537]
### Your Feature Request

Hi, could be possible to have synced to the GH mirror all the active branches and the tags of the minor releases (like for example 2.5.1)?

This will help on integrate automatic bump of the ebuild in Funtoo or other distro that using automatic bumper systems.

### What are you trying to do?

Automatic bump of the new ebuild in Funtoo Linux Community.

### Output of `haproxy -vv`

```plain
N.A.
```

**Comment by lukastribus** [comment]
You can't track individual repositories? How do you track linux kernel stable trees?

**Comment by geaaru** [comment]
For kernel there is a json:
```
curl -Ls https://kernel.org/releases.json 
```
An alternative could be also supply something similar in `http://www.haproxy.org/download/2.5/src/` with a file `LATEST` or a json file too.

**Comment by lukastribus** [comment]
Basically, the informations we have in the `Latest versions` table on haproxy.org, but in a machine readable format (`json` would probably be best).

**Comment by geaaru** [comment]
Yeah, could be the best. Can you add this in your workflow and share the link on the json resource?

**Comment by lukastribus** [comment]
I'm not sure how much of that is automated, tagging @wtarreau @capflam

**Comment by wtarreau** [comment]
We used to have a LATEST file a while ago, and it was probably lost along process updates.  We used to have a link pointing to the latest files but that proved inconvenient over the long term when using multiple extensions and because the name was not always provided in response. Given that we launch a script to produce and publish the tar.gz into the directory, it's not difficult at all to create a separate file for that. I'm open to suggestions. Maybe a pure text file or json would make sense indeed.

Please feel free to propose something detailed enough so that we can validate if that would be sufficient and can implement it accordingly. If you want inspiration, the current script is `scripts/publish-release` in the source tree :-)

**Comment by geaaru** [comment]
ok, thanks. I will take a look to your scripts in these days.

**Comment by geaaru** [comment]
If i understood correctly, for every branch you run something like this?
```shell
$> ./scripts/public-release -a -b haproxy-2.5 -n 2.5.2 /tmp/src/
```
So could be needed only the generation of the json file under the $TARGET_DIR.

I will try to prepare a PR for this here.

**Comment by wtarreau** [comment]
Just checked, and it's even simpler, it's called from the source directory with only the installation directory for argument:
```
/usr/local/haproxy/scripts/publish-release /..../haproxy.org/download/
```
Branches and versions are automatically determined from the Git directory. But yes, the idea will be to produce that file over there. I have absolutely no idea what you want to see in this file, reason why I prefer that you propose what to put into it :-)

**Comment by geaaru** [comment]
WDYT if this script could be an independent script that parse the download/$TARGET_DIR directory and generate the json?
I begin to see the publish-release script but it seems that requires a new release to update. I mean it checks if the last commit of the master branch has the same commit used by last tag.
If you manage this with the parsing the download tree you could run this script in any moment without to wait for a new release.

**Comment by geaaru** [comment]
Ok, i have it... preparing the PR in one hour:
```shell
$ bash haproxy-2.5/scripts/generate-tags-json.sh ./target/
Parsing haproxy-2.5.2.tar.gz for branch 2.5...
Parsing haproxy-2.5.1.tar.gz for branch 2.5...

$ cat target/2.5/src/releases.json 
{
  "branch": "2.5",
  "last_release": "2.5.2",
  "releases": {
    "2.5.2": {
      "file": "haproxy-2.5.2.tar.gz",
      "md5": "7e08480a6c52f2c3be8a9b778c54105f",
      "sha256": "0666cea8d90f9f5635b5fd8e4f49a555ed132def650d463125b2106d53d11187"
    },
    "2.5.1": {
      "file": "haproxy-2.5.1.tar.gz",
      "md5": "7e08480a6c52f2c3be8a9b778c54105f",
      "sha256": "0666cea8d90f9f5635b5fd8e4f49a555ed132def650d463125b2106d53d11187"
    }
  }
}

$ cat target/2.5/src/releases.yaml 
branch: "2.5"
last_release: 2.5.2
releases:
  2.5.2:
    file: haproxy-2.5.2.tar.gz
    md5: 7e08480a6c52f2c3be8a9b778c54105f
    sha256: 0666cea8d90f9f5635b5fd8e4f49a555ed132def650d463125b2106d53d11187
  2.5.1:
    file: haproxy-2.5.1.tar.gz
    md5: 7e08480a6c52f2c3be8a9b778c54105f
    sha256: 0666cea8d90f9f5635b5fd8e4f49a555ed132def650d463125b2106d53d11187
```

I used the same tarball/md5 for test multiple releases. Ignoring the same md5, etc.

**Comment by wtarreau** [comment]
Thanks. I would prefer it if the script would only deal with the version being worked on and not the other ones. I.e. possibly that it just appends to the existing json/yaml files. Otherwise it becomes worse in processing time for every new release. Fortunately we're not like the kernel, doing 300 releases in a stable branch, but you get the idea, the principle doesn't scale. Otherwise let's just produce the info for the latest file and do not enumerate the other ones since, in the end, they do not add any value, they're already in the directory.

**Comment by geaaru** [comment]
Hold on, it's just execute a `find` of the directories. It's very fast.

Btw, you have two possibility to use my script:
a) just pass the directory of the branch under analysis. This will generate the releases.json file only in that branch with the new release. This will be more fast. You can just add the call on my script in the publish-release script and supply $TARGET_DIR/src/$BRANCH as argument.
b) connected to the point a, you can comment the logic available in the `else` and this will avoid to add all others release. 
https://github.com/haproxy/haproxy/pull/1539/files#diff-a320a7524f032745c900bebebfe7d241bd5d971e651e3116f31d5b205cdfd81bR94

Maybe you can now run the script manually to generate the files for any branch and then integrate it in the publish-release the parsing of the only branch that will be release as i described in point a

**Comment by wtarreau** [comment]
OK, if you reuse the contents of the existing signature files, then that's OK to me to fully regenerate the file on each release as it will be very fast. I was afraid that you'd recalculate the md5 and sha256 for each file upon each version, which I definitely wanted to avoid.

**Comment by TimWolla** [comment]
@geaaru I don't see why a .yml file should be generated. JSON is a subset of YAML, so you can just feed the JSON to your YAML parser and it should work.

**Comment by geaaru** [comment]
Well, i use yaml because it's more easy to modify and process and then i convert the yaml to json in one shot. If you prefer you can add a find that remove all releases.yaml at the end of the main function.

**Comment by TimWolla** [comment]
Maybe that's an indicator that shell scripting is not a suitable tool for the job here. After all you need two external dependencies (which are downloaded from the Internet without any verification). As an example we're already using Python to generate JSON for the CI (https://github.com/haproxy/haproxy/blob/master/.github/matrix.py) and a Python interpreter including the JSON module should be available on pretty much every system.

**Comment by geaaru** [comment]
1. The script downloads stuff only if you enable DOWNLOAD_TOOLS with value at 1. So, if you install it by your distro you don't need it. Personally, in all my system i have `yq` installed. You are free to download the binary, verify it and prepare the env how you prefer. The idea of the download function is: if you want to run it in a thin container you just need to enable the environment DOWNLOAD_TOOLS and the script does the fetching but it isn't mandatory.
2. In the real, the `jq` at the end is not used. I think to it at the begin but i used only `yq4` at the end. You can simply drop the line jq.

**Comment by wtarreau** [comment]
Quite frankly, if we're only enumerating a list of file names and dumping the md5/sha256 files, it's fine to fully regenerate them and there's no need to install any such tool at all, a trivial shell loop combined with "echo" will do it. My concern was that I initially feared you would be going to re-sign all archives. That's not the case, so let's regenerate a full file each time from small files and be done with it. And I agree with Tim that we don't need the YAML files there. The internal processing is never a valid excuse for the files we expose to the world, because once we start to expose them, there will always be users relying on them and these files will have to be maintained forever.

The example you pointed in the initial request was already just for getting the info on the latest version and we're already seeing that request inflate to dumping all files despite never having seen any request for this. Let's not further multiply this by multiple formats.

**Comment by geaaru** [comment]
So, i think that you can replace the `for` with this:
```bash
  for f in $(find ${SOURCE_DIR}  -name 'haproxy-*.tar.gz' | sort -r) ; do
    tarball=$(basename $f)
    branch=$(basename $(realpath $(dirname $f)/..))
    branchdir=$(dirname $f)
    release=$(echo ${tarball} | sed -e 's|haproxy-||g' -e 's|.tar.gz||g')
    md5=$(cat ${f}.md5 | cut -d' ' -f1)
    sha256=$(cat ${f}.sha256 | cut -d' ' -f1)

    echo "Parsing ${tarball} for branch ${branch}..."

    if [ "${branch}" != "${prevbranch}" ] ; then
      # POST: The first tarball is the last release of the branch.

      echo "{
\"branch\": \"${branch}\",
\"last_release\": \"${release}\",
\"md5\": \"${md5}\",
\"sha256\": \"${sha256}\"
}" > ${branchdir}/releases.json
    fi

    prevbranch=${branch}
  done
```

**Comment by wtarreau** [comment]
Looks good, thanks, i'll give this a try.

**Comment by geaaru** [comment]
I saw now that under download there is also a `snapshot` subdir.
So, just add `grep` to the find command to exclude that directories:
`find ${SOURCE_DIR}  -name 'haproxy-*.tar.gz' | grep -v snapshot | sort -r`

**Comment by geaaru** [comment]
Any news? does the script works correctly?

**Comment by wtarreau** [comment]
Been quite busy with other issues over the last few days and more generally weeks, I'm sorry. I'm not dismissing this, but need to progress on some important bugs before getting back to this.

**Comment by geaaru** [comment]
ok, n/p. Thanks for the update. Let me know when you have time if the script works ;)

**Comment by geaaru** [comment]
Hi, please, can you just run the script posted with the changes and close this issue?

**Comment by wtarreau** [comment]
I had a look at it and the problem is that it gets the version ordering wrong, which is why I left it aside, and for now I don't have the time to hack it. It's possible that "sort -rV" would get it right but I need to manually check among 7316 files if that's always correct or if there are mistakes left, and finally it needs to be modified so that for a given branch it makes the difference between devel and release, so for now this remains postponed.

In the end, I'd rather do it once and then modify the release script so that it produces the output with each release at the same time as the LATEST link instead of re-running over all files and applying fuzzy logic to figure the latest version.

**Comment by geaaru** [comment]
Thanks for the feedback.
The pro to have an independent script is that you can run now it and get the job done also for the existing tags.
It's weird. Can you paste the output of the script to understand better what is in wrong order so i could fix it?

**Comment by wtarreau** [comment]
But in fact there's no need to do it for existing tags since you're only doing it for the last one for each branch. So we're trying to define something very fragile just to save a one-time operation. I'd rather update `scripts/publish-release` to do that at the same time the CHANGELOG is produced, this way we'll be certain it's always done and will not represent a risk that a slightly different syntax is improperly handled. And for older branches that are not released often, we'll do it by hand, it will take less time than checking if the output is correct anyway.

**Comment by wtarreau** [comment]
If you want to try again, please propose a patch for the publish-release script. It'll be used for future releases, and from that it will not be too hard to handle old branches.

**Comment by wtarreau** [comment]
Update: I've now written a script to produce the json output when pushing. It's emitted in each branch's "src" directory and lists both devel and stable releases. Example: http://www.haproxy.org/download/2.5/src/releases.json

It may be adjusted a little bit if absolutely necessary but I'd rather limit the amount of changes because that's yet another moving part to take care of. I'm marking this a fixed now, but feel free to comment here if needed.

**Comment by TimWolla** [comment]
@wtarreau I believe the `src/` prefix should be dropped from the `file` value.

**Comment by wtarreau** [comment]
Ah thanks, it was a leftover from a previous attempt and I forgot to regenerate after updating. Now rebuilt and it looks ok!
