### ISSUE TITLE
src/ssl_sock.c: error handling suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1541]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1469513:  Error handling issues  (CHECKED_RETURN)
/src/ssl_sock.c: 7472 in ssl_ocsp_response_print()
7466                            /* Keep looking for empty lines in the rest of the data. */
7467                            ist_block = istadv(ist_block, empty_line_offset);
7468     
7469                            ist_double_lf = istist(ist_block, double_lf);
7470                    }
7471     
>>>     CID 1469513:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "b_istput" without checking return value (as is done elsewhere 10 out of 12 times).
7472                    b_istput(out, ist_block);
7473            }
7474     
7475            if (bio)
7476                    BIO_free(bio);
7477
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by rlebreton** [comment]
This missing return value check could not have a too bad side effect even in case of error but I added a check anyway. I stumbled across some other bugs while reading the ocsp response print code. Here are some patches that fix what I found. The first one adds the missing check, the other two are new bugs.

[0001-BUG-MINOR-ssl-Add-missing-return-value-check-in-ssl_.patch.txt](https://github.com/haproxy/haproxy/files/8080877/0001-BUG-MINOR-ssl-Add-missing-return-value-check-in-ssl_.patch.txt)
[0002-BUG-MINOR-ssl-Fix-leak-in-show-ssl-ocsp-response-CLI.patch.txt](https://github.com/haproxy/haproxy/files/8080878/0002-BUG-MINOR-ssl-Fix-leak-in-show-ssl-ocsp-response-CLI.patch.txt)
[0003-BUG-MINOR-ssl-Missing-return-value-check-in-ssl_ocsp.patch.txt](https://github.com/haproxy/haproxy/files/8080879/0003-BUG-MINOR-ssl-Missing-return-value-check-in-ssl_ocsp.patch.txt)

**Comment by wtarreau** [comment]
Thanks Rémi! For the 3rd one, are you sure about your test ?
```
 		write = BIO_read(bio, trash->area, trash->size - 1);
+		if (write <= 0)
+			goto end;
```
The commit mentions "Bio_read returns a negative value in case of error" so I don't know if 0 is in itself an error or just indicates an empty message for example.

@wlallemand if you're making another 2.5 soon maybe it would be worth integrating Rémi's fixes, what do you think ?

**Comment by rlebreton** [comment]
There is indeed a little mismatch between the patch and the commit message. I went for a '<=' because of the manpage which states that 'no data was successfully read or written if the result is 0 or -1' which is a little ambiguous. In our case, the bio should contain an already validated OCSP response's information so an empty bio in this function would be an error so I'd rather keep the '<=' and update the commit message as in this new patch.

[0003-BUG-MINOR-ssl-Missing-return-value-check-in-ssl_ocsp.patch.txt](https://github.com/haproxy/haproxy/files/8090194/0003-BUG-MINOR-ssl-Missing-return-value-check-in-ssl_ocsp.patch.txt)
