### ISSUE TITLE
Perfect Forward Secrecy with known DH group

### ISSUE THREAD

**Issue by arnebjarne** [haproxy/haproxy#1554]
### Your Feature Request

I noticed when I test HAproxy 2.0.x train with the testssl.sh suite it gives:

` DH group offered:            Unknown DH group (2048 bits)`

(I have tune.ssl.default-dh-param 2048 set in config)

I would expect something like:

` DH group offered:            RFC3526/Oakley Group 14 (2048 bits)`
(Example output from an Cisco ASA firewall)

http://git.haproxy.org/?p=haproxy-2.0.git;a=blob;f=src/ssl_sock.c;h=7ffcefc8cb6a80b11c854cedcac9a01aafe3595e;hb=HEAD#l2573

I guess this could be replaced with a well known prime?

BR,
Bjarne

### What are you trying to do?

See Your Feature Request

### Output of `haproxy -vv`

```plain
HA-Proxy version 2.0.25-6986403 2021/09/07 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE2=1 USE_REGPARM=1 USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1g FIPS  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1k  FIPS 25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.4
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.7
Running on zlib version : 1.2.7
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.23 2017-02-14
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

**Comment by arnebjarne** [comment]
You can the the primes from

https://www.ietf.org/rfc/rfc3526.txt

**Comment by arnebjarne** [comment]
Actually you should remove the 1024 prime

Add/extend
   2.   1536-bit MODP Group . . . . . . . . . . . . . . . . . . .  3
   3.   2048-bit MODP Group . . . . . . . . . . . . . . . . . . .  3
   4.   3072-bit MODP Group . . . . . . . . . . . . . . . . . . .  4
   5.   4096-bit MODP Group . . . . . . . . . . . . . . . . . . .  5
   6.   6144-bit MODP Group . . . . . . . . . . . . . . . . . . .  6
   7.   8192-bit MODP Group . . . . . . . . . . . . . . . . . . .  6
   
primes.

**Comment by lukastribus** [comment]
Removing 1024bit prime breaks older Java clients. If this is an option (for new release trains, obviously), then I'd suggest we consider removing all builtin DH params, just like nginx does:

http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_dhparam

> By default no parameters are set, and therefore DHE ciphers will not be used. 


DHE is only used with old or very old clients. If we start breaking those old clients, we may as well do a proper cleanup, instead of passing from one obsolete construct to the next.

**Comment by arnebjarne** [comment]
Erhm. disregard my comment about Unknown DH.
When I do not use my own openssl generated dhparam file, but use the HAproxy v2.0.x autogenerated, then testssl.sh shows a known DH

` DH group offered:            HAProxy (2048 bits)`

So my request can be rephrased to:

what about including all the Groups from [rfc3526.txt](https://www.ietf.org/rfc/rfc3526.txt) and not just 

1024,2048 and 4096?
(aka adding 1536, 3072,6144 and 8192) ?

**Comment by arnebjarne** [comment]
> DHE is only used with old or very old clients. If we start breaking those old clients, we may as well do a proper cleanup, instead of passing from one obsolete construct to the next.

Remember that the Internet includes old and obsolete and temporary systems (said with a ;-) )

**Comment by lukastribus** [comment]
> what about ... adding 1536, 3072,6144 and 8192?

Those bit sizes do not belong on public facing SSL server, it just an DoS opportunity. We are certainly not going to add new opportunities for people to shoot themselves in the foot for obsolete technology.


> Remember that the Internet includes old and obsolete and temporary systems (said with a ;-) )

Exactly. That's why when we cleanup something breaking older clients by default, it should be for an actual purpose and not like I said earlier, passing from one obsolete concept to the next.

That's why I'm saying we should remove this altogether in the long term (deprecating it for 2.6 and removing in 2.7 for example).

**Comment by arnebjarne** [comment]
@lukastribus just out of curiosity and ignorance: When you say DHE is only used with old clients:

Running a scan on https://www.ssllabs.com/ssltest/analyze.html

I get green OK's on
TLS 1.2 suites
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   DH 2048 bits   FS
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   DH 2048 bits   FS
TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xccaa)   DH 2048 bits   FS

Is that the same DHE you are referring to? And since they are not considered weak ciphers (yet) - would you still call it ciphers for old clients?

BR,
Bjarne

**Comment by TimWolla** [comment]
Everything reasonable that speaks TLS 1.2 should also speak ECDHE (or TLS 1.3). Personally I've never enabled the DHE ciphers on my servers.

**Comment by lukastribus** [comment]
No browser currently used and supported would ever negotiate DHE with a webserver that is running a supported OS/ssl/webserver release combination, unless one of those is severly miss-configured.

DHE is slow, causes high CPU loads on the servers especially with > 2048bit DH groups, it opens the server up for easy SSL handshake DoS due to its CPU load, it causes SSL negotiation failures with Java <= 7 when using DH groups greater than 1024 bit, it requires manual configuration with DH groups either in the certificate or on the server (which is what we are discussing here).

DHE needs to die, it's useless at this point and it continues to cause a lot of headaches.

**Comment by arnebjarne** [comment]
Ok thanks for the explanations. I will close this as "won't fix" :)
