### ISSUE TITLE
Haproxy 2.5.4 regularly drops backend responses with status 500, termination state PH--

### ISSUE THREAD

**Issue by daankets** [haproxy/haproxy#1597]
### Detailed Description of the Problem

In a configuration with different backends (NGinx static, rest microservices, ...), Haproxy shows intermittent response drops. The error code is **500** and the termination state is **PH--**.

`show errors` does provide information on OTHER issues when simulated, but not on the termination above. Most often, when replaying the request individually via the browser, the response is fine.

Inspecting the headers does not show any issues, neither does content-length or transfer mode.

```

```

### Expected Behavior

The expected behaviour would be for the requests to pass always, without failing occasionally. Also, I believe there is a mismatch between status code 500 and termination state PH--. PH-- is only listed in combination with error 502 in the documentation.
Finally, 'show errors' should provide at least some information on the early termination (reason).

### Steps to Reproduce the Behavior

Might be hard to reproduce. We have a setup with multiple haproxy instances that terminate SSL on port 443. With a let's encrypt certificate. There are path based acls that determine the chosen backend (static, nginx, dynamic rest api'ss via express). In both cases there are 200 responses from backend to haproxy, and then haproxy decides to terminate the request. Also, in both cases, the request works once retried. All load balancers balance of the same static and rest resources (on different nodes), and all have the same (occasional problem).

### Do you have any idea what may have caused this?

A bug in haproxy if you ask me. The same set of config files work with haproxy on an earlier version (HA-Proxy version 1.8.8-1ubuntu0.11 2020/06/22). However, we need the http2 features of the newer release.

### What is your configuration?

```haproxy
Ubuntu 20.04 LTS, EN US, UTF8
Running with HTTP2 enabled

Config global and defaults:

global
	lua-load /etc/haproxy/tenant.lua
	log /dev/log	local0 
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 2m
	maxconn 1000
	user haproxy
	group haproxy
	daemon

	# Default SSL material locations
	ca-base /etc/ssl/certs
	crt-base /etc/ssl/private

	ssl-default-bind-options ssl-min-ver TLSv1.2
	ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256
	ssl-default-server-options ssl-min-ver TLSv1.2
	ssl-default-server-ciphers ECDH+AESGCM:ECDH+CHACHA20:ECDH+AES256:ECDH+AES128:!aNULL:!SHA1:!AESCCM

  	tune.ssl.default-dh-param 2048
defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
	retries 2
	errorfile 400 /etc/haproxy/errors/400.http
	errorfile 403 /etc/haproxy/errors/403.http
	errorfile 408 /etc/haproxy/errors/408.http
	errorfile 500 /etc/haproxy/errors/500.http
	errorfile 502 /etc/haproxy/errors/502.http
	errorfile 503 /etc/haproxy/errors/503.http
	errorfile 504 /etc/haproxy/errors/504.http
```
```


### Output of `haproxy -vv`

```plain
HAProxy version 2.5.4-1ppa1~focal 2022/02/25 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2023.
Known bugs: http://www.haproxy.org/bugs/bugs-2.5.4.html
Running on: Linux 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-7oXbgr/haproxy-2.5.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wundef -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
Running on OpenSSL version : OpenSSL 1.1.1f  31 Mar 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Support for malloc_trim() is enabled.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.34 2019-11-21
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
N/A
```

### Additional Information

> This only seems to happen with GET requests so far.

**Comment by capflam** [comment]
Frontend and backend configurations are missing. Thus, it is hard to figure out what is the problem. Also, it could be useful to share the log line.

But, at first glance, it may be an HTTP header rewrite error, most probably because the response buffer is full. You should check the rewrite failures counter (wrew) in the stats.

**Comment by daankets** [comment]
@capflam was correct: in some cases the rewrite buffer was too small. Increasing the size to 1024 helped. So I guess the issue can be reduced to the fact that "show error" doesn't indicate this, and the response code being 500 (doc issue)?

**Comment by capflam** [comment]
Indeed, documentation for `PH` termination state may be updated to mention HTTP header rewrite failures. `PR` too if the error happens on the request processing. A 500 is reported because it is considered as a config error. It is also a good way to notify admin there was something that must be fixed. Note that for now, only parsing errors are reported in `show errors` output. 

If rewrite failures are acceptable for you, you can set the `http-response strict-mode` to off. It was the default mode before the 2.2. This way, failures will be ignored.

**Comment by daankets** [comment]
@capflam Thanks for the information, I will at least update my own docs here ;-). Your answer was much appreciated!

**Comment by daankets** [comment]
@capflam Sorry, accidentally clicked 'close' instead of comment 🤦

**Comment by capflam** [comment]
No pb. Thanks !

**Comment by DEvil0000** [comment]
I can confirm and reproduce the issue also I can provide workarounds and more insights. This issue also affects at least 2.2, 2.3, 2.4 versions.
### Setup details
running openstack xena with haproxy for services and its horizon web ui.
see openstack-ansible documentation - it is mostly close to the default config example.
### How I reproduced it / when I see it:
1) disable browser cache (e.g. F12, network, disable cache - keep window open)
2) disable retry in haproxy to increase reproduction chance
3) opening/reloading VM instance details page in horizon (but may happen on mast pages) - maybe reload multiple times
It does not happen every time - some randomness. However one active client is enough to reproduce it.
## About the requests/responses
* gzip/binary data
* mostly for bigger size responses (js, fonts, sometimes css)
* mostly on `transfer-encoding: chunked` responses
## Influencing factors / workarounds
* retry X in haproxy config (remove retries to reproduce it more offten) - retries hide this issue
* headers or response headers with long value over ~256chars cause the issue to happen (in my case a 350char long value on `http-response set-header Content-Security-Policy "$long_string"` in the frontend
* increasing the `tune.bufsize` reduces the likelihood for the issue to occur - a factor of about 10 was enough to neerly never get it.
* use `mode tcp` instead of `http` so all http and header parsing gets bypassed is also a workaround you may consider
### workaround I use
I reduced the length of the header value to below 256chars - which was possible in my case.
### Conclusion
I guess this may be a buffer overrun for headers with long values - maybe only for binary multipart/chunked responses.
### Note - maybe a related issue with binary data packages
I had issues with uploading images (binary data) over horizon->haproxy->glance in `mode http` see [here](https://bugs.launchpad.net/glance/+bug/1916482). the workaround there was to set `mode tcp`. I considered this a openstack service bug but now I think this may be a similar issue with binary data over haproxy.

**Comment by DEvil0000** [comment]
@capflam please review again

**Comment by capflam** [comment]
Sorry, I don't understand, there is nothing new and there is no bug. As explained, if headers rewriting fails, an internal error is triggered, except if you explicitly switch off the strict-mode. You can also increase `tune.maxrewrite` parameter. The error is random because it depends if haproxy receives the response payload with the headers or not.

**Comment by daankets** [comment]
I agree with @capflam . The shortcoming is/was in the docs only. Increasing the max size of the rewrite buffer should solve the issue.

**Comment by DEvil0000** [comment]
I don't understand - what am I missing here? Maybe it is mostly documentation but it feels much like a bug.
I think haproxy always receives the response with headers and in my case it then adds the CSP header. I would expect a consistent behaviour if this is just a config thing and not a bug. Also I would expect a more clear log message telling me about the issue and my options. Also the software should be able to avoid the issue without any impact or me changing any config - right?
If the value is below 256bytes it is working fine while about 350bytes was giving random HTTP `500` with not much info at all in the log file besides `PH--` and `500` - no event. So the error reporting is not very clear. I was also not able to find documentation on this exact case - only for `502` with `PH--`.
Thanks for hinting at `tune.maxrewrite` but the documentation is not clear to me there. What will it actually control/do and what is the default value? Is it a per header or a overall size?
If I understand correctly browsers are fine with header values up to 8k or 16k by default - maybe haproxy defaults should be aligned with that?
Thanks

**Comment by capflam** [comment]
First, you're right, the documentation must be update to document `PH--` + `500`. It is the purpose of this issue.

Then, you must understand that all headers manipulations are performed on the first buffer of the response before sending it to the client. Some space is reserved in this buffer to handle these manipulations. By default 1024 bytes. So, when HAProxy receives a response, it may contain part of the payload or not. In other words, the buffer may be almost full or not. Thus, if there is enough space to add your headers, there is no problem. However, if the buffer is almost full, only the last 1024 bytes are available. By default, any rewrite error will trigger a 500-Internal-error response with `PH--` termination state.

At this stage, you have several options depending on your requirement. If you can live with some rewrite errors, you can disable the strict-mode via an `http-response` rule. Otherwise, you can increase the `tune.maxrewrite` value to reserve a larger space for rewrites. You can also change the buffer size if it is wise in your case.

HAProxy is fine with huge header values if all the headers fit in one buffer (respecting the reserve). Note that default buffer size is 16k and last 1k are reserved. So be careful. Most of time, the default config is good enough to avoid any trouble. But depending on your application, it may require some tuning. There is no reason to use huge buffer size with a large reserve by default. This would penalize everyone for only few use-cases.

**Comment by capflam** [comment]
Note that there is a stat counter reporting the  rewrite errors, per frontend/backend:

 * `wrew`: Total number of failed HTTP header rewrites since the worker process started

**Comment by capflam** [comment]
The doc was update. Thanks !

**Comment by noonedeadpunk** [comment]
@DEvil0000 Hey! We accidentally has found this bug report and proposed fix to openstack-ansible to cover proposed solution.
It would be great if you could take part in reviewing it:
https://review.opendev.org/c/openstack/openstack-ansible-haproxy_server/+/846473
