### ISSUE TITLE
health checks with POST and data corrupted by extra "connection: close"

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#16]
This entry was reported here https://www.mail-archive.com/haproxy@formilux.org/msg28199.html

## Output of `haproxy -vv` and `uname -a`

```
haproxy 1.7.8
```

## What's the configuration?

```
option httpchk POST /myService/endpt HTTP/1.1\r\nContent-Type:\ application/json;charset=UTF-8\r\nContent-Length:\ 169\r\n\r\n{\"inputs\":[{\"id\":1,\"productType\":\"productType\",\"product Description\":\"productDescription\",\"metaDescription\":\"metaDescription\",\"metaTitle\":\"metaTitle\",\"rawxyz\":\"rawxyz\"}]}
http-check expect rstatus (2|3)[0-9][0-9]
```

## Actual behavior

"
After debugging with wireshark capture I came to know that, haproxy is adding *\r\f"Connection: close"\r\f\r\f* at the end of the post json data. From this manual, https://www.haproxy.org/download/1.7/doc/configuration.txt, I found that haproxy appends it if httpchk is combined with *http-check
expect*. But it should be added to header fields and not after data.

This is causing packet parse failure, as it considering POST data as a part
of header and reporting extra CRLF in headers.
"

## Expected behavior

"I would need the http-check expect block to verify error code, but then howwould I avoid adding *Connection: close* at the end.
"

## Do you have any idea what may have caused this?
Limited design of the check subsystem and the abuses we're doing on it :-(

## Do you have an idea how to solve the issue?
No simple solution. We do need this close to avoid timeouts or error reports on servers when we close. Ideally we should parse the produced request and append the header before the resulting double CRLF. It might be the less risky change for the short term that could be backported.

**Comment by kirangavali** [comment]
@wtarreau 
I have reproduced and analyzed the above bug on HAProxy v2.1.0 (using Wireshark). 
As per my findings, the **"Connection: close"** string is appended after the data block instead of being appended after the header. [Refer the attached Wireshark screenshot at the end]

On further analyzing the corresponding HAProxy code, I identified the  buffer in which the "option httpchk" directive is parsed as shown below: 


**args[4] : 0x714bca "HTTP/1.1\r\nHost: 10.10.26.236\r\nContent-Type: application/json\r\nContent-Length: 25\r\n\r\n{\"command\":\"getNodeInfo\"}"
args[3] : "/"
args[2] : "POST"
args[1] : "httpchk"
args[0] : "option"**

Based on the finding I was able to confirm that HAProxy treats the complete request as a packet and does not differentiate between the request header and the body.
As stated by @wtarreau  in [ #**https://www.mail-archive.com/haproxy@formilux.org/msg28200.html**], it would be best to add another option "body" to http-check directive so as to correctly differentiate body from header, as shown below:-

**option httpchk POST / HTTP/1.1\r\n
http-check header Host: 10.10.26.236\r\nContent-Type: application/json\r\nContent-Length: 38\r\n 
http-check body {\"command\":\"getNodeInfo\"}
http-check expect rstatus (2|3)[0-9][0-9]**

To incorporate the change, we need to do changes in below code:-
**File**: cfgparse-listen.c 
**Function**: int cfg_parse_listen(const char *file, int linenum, char **args, int kwm)
**Code Snippet**: `curproxy->check_len = snprintf(curproxy->check_req, reqlen, "%s %s %s\r\n", args[2], args[3], *args[4]?args[4]:"HTTP/1.0");`

Please let me know if my understanding of the above issue is correct, so that I can proceed further accordingly. Looking forward for your guidance.

Regards
Kiran Gavali


![connection_close_v2 1 0](https://user-images.githubusercontent.com/36035109/73735055-a7753700-4764-11ea-8383-cbbd544137ed.jpg)

**Comment by capflam** [comment]
No critical enough to be backported to 1.7. I close the issue keeping labels for the reference.
