### ISSUE TITLE
Support passing arbitrary arguments to "lua-load"

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#1609]
### Your Feature Request

Just like an "exec" command, a script or a function call, it would be really convenient to have `lua-load` support taking optional arguments that would directly be passed to the Lua script's init function. Some configs have to load a preliminary Lua file to set parameters, or to use `setenv`, none of which is handy. Arguments (strings likely) would solve all this.

### What are you trying to do?

Simplify passing arguments to Lua scripts being loaded. File paths are commonly encountered.

### Output of `haproxy -vv`

```plain
2.6-dev3, but used to be requested almost since Lua was included.
```

**Comment by Darlelet** [comment]
[0001-DRAFT-hlua-working-on-lua-load-and-lua-load-per-thre.patch.txt](https://github.com/haproxy/haproxy/files/9558654/0001-DRAFT-hlua-working-on-lua-load-and-lua-load-per-thre.patch.txt)

-- This is a draft. --
    
It might be more convenient to let the user directly specify the variable index
    or variable subname from config so that subsequents calls to lua-load with different
    arguments don't overwrite existing variables (set in global context) without
    the user meaning it. It would probably offer more options to user (and less
    confusion).
    Please let me know if it's a good idea, I'm planning to work on a v2 with this in mind.
    
  Current logic for lua-load and lua-load-per-thread:
    
```
  Optional arguments might be specified after the file location: each argument
  will be set in the global variable named HLUA_G_N (with N=relative argument
  position from 0 to N) prior to calling the lua script.
  Existing HLUA_G could be overwritten
  by the following lua-load(-per-thread) directives.
```
    
# Example:
    
## lua_test.lua
```
    core.Alert(HLUA_G_0.." "..HLUA_G_1.." "..HLUA_G_2);
```
    
## haproxy config:
```
[global]
    lua-load lua_test.lua toto is nice
    lua-load lua_test.lua mike
```
    
### will output:
```
    [alert] 255/171520 (1302259) : toto is nice
    [alert] 255/171520 (1302259) : mike is nice
```
    
(HLUA_G_0 has been overwritten to mike, but HLUA_G_1 HLUA_G_2 were not
 overwritten so they are still available to subsequent calls)

**Comment by wtarreau** [comment]
I thought we had an `init()` function in Lua modules, to which I thought we could pass the arguments, but apparently not :-(

That makes me wonder about several possible variants:
  - maybe we could decide that when args are passed, an init() function is called with them. Some would legitimately ask "what about init functions that take no args", to which I don't have an immediate response;
  - maybe we could decide to pass a Lua statement as the arg, which could then look like `init("toto","is","nice")`. Then this revives the recurrent demand for inline Lua
  - if we think there is some interest in the second option maybe we could have `lua-call <statement>` and `lua-load <file> [<optional_statement>]` and consider that the purpose is served.

These are just some ideas to try to fuel the discussion. CCing @thierryf78 in case he has any other suggestions or ideas on this.

**Comment by Darlelet** [comment]
I also thought of implementing the missing init() function the way you describe it.
It feels more "natural" as when it comes to using those arguments within lua scripts.

But there is some caveat (correct me if I'm wrong): we might be limited by the stack to a MAX number of arguments as we must push all arguments to the stack before calling the lua init() function.

From lua.org; https://www.lua.org/pil/24.2.1.html
> When Lua starts and any time that Lua calls C, the stack has at least 20 free slots (this constant is defined as LUA_MINSTACK in lua.h). This is more than enough for most common uses, so usually we do not even think about that. However, some tasks may need more stack space (e.g., for calling a function with a variable number of arguments)

We might face this as well with `lua-load <file> init("arg"...)` variant.

That being said, we could easily circumvent this by setting local variables that are only visible to the init function.
Or we could agree on a safe maximum number of arguments that could be passed to the init function.

I agree that `lua-call <statement>` could be an interesting feature..  with proper usage restrictions as it could lead to complex scenarios if used improperly (ie: mix between lua-load and inline lua that perform conflicting operations.. or typos due to inline syntax that degrades readability)

**Comment by wtarreau** [comment]
The limit on the number of arguments is not an issue at all, as long as it's properly documented. We do have limits in plenty of places (e.g. stick-counters etc) and that's fine. Those who'll need more will just rethink their design. Most of the time I guess we'll see an IP address or a file name being passed there.

Regarding lua-call, I agree it could lead to ugly stuff, but that's precisely what is attracting :-)  I mean, many users who want to reuse existing lua scripts have to add either modify them or add their own extra file just for a few instructions (call an init function, allocate some pools, open a file or whatever). Being able to pass such short statements just after loading a generic unmodified file could be really useful because we'd then keep the code out and the customization in the config file. Same here, maybe @thierryf78 who has a lot more experience on the subject could guide us.

**Comment by capflam** [comment]
First of all, we must decide if arguments on a `lua-load` line is private to the corresponding script or global and shared by all scripts. At first glance, it should be private. However a global variable created in a script is visible from all the others. In addition, in Lua, when a script is loaded, command-line arguments are stored within the `arg` global variable, which is a table of strings.
Because we can load several scripts, it is ambiguous to have a global array. And it may be tedious to set/unset this array to keep it private to each script. Another solution may be to add a `lua-args` directive to set the global arguments for all scripts.

About the `init` function, it is already possible to register such function with `core.register_init()`. So we may decide to pass an `arg` array to these functions. For now, there is no argument. So it is backward compatible. But it means we must be sure to set the arguments of the right lua-load line.

**Comment by wtarreau** [comment]
For me the args must be specific to the script. I'm seeing them as function arguments. If a module wants to share them, it can always do it explicitely.

When you're talking about command line arguments, which ones are you talking about ? The ones from the "lua-load" config line ? I'm not aware of this but I already understand how problematic it can be if that's the case (which means that nobody uses them with multiple scripts right now). If so we could keep the compatability by still having them copied by the last one loaded, but we'd still need to pass private args to each script.

I don't see any use case of having the same arguments to multiple scripts, that would force all scripts to use exactly the same positional args. That would be quite strangee a way to develop scripts.

Regarding core.register_init(), that still requires to first execute the code to register this init. But I agree that it would remain backwards compatible, which is important. I was more seeing something that is known from the first execution. E.g. if one passes "disabled" it could make sense to refrain from calling core.register_init() at all in the first place.

**Comment by capflam** [comment]
About command line arguments, I was referring to the Lua binary. Command line arguments are stored within the `arg` array. Of course, it is hardly applicable to HAProxy because all scripts share the same global environment. Except via `lua-args` directive, to be sure to define arguments before loading the scripts. But it means all scripts rely on the same argument list. To keep them private to each script, we indeed need to call a function. But we need to register it explicitly. Otherwise it will be possible to call a function defined in another script. It is more predictable this way and, at the end, in all cases, the script will need to be updated to define this function.  So registering it is probably not an issue. And it avoids hard-coded names.

Note that when a script is loaded, there is a first execution to interpret the script itself. You cannot mix it with a specific function call. It should be performed in 2 steps. Thus, there is no reason to add another kind of init function. it is possible to add extra args to the existing `init()` callback functions. To have something known at the first execution, you must set it in the global environment before executing the script in a way or another. 

We can add `lua-call` directive to interpret inline code. But if it is executed before loading a script, the code cannot use functions defined in the script. And  to have something usable by a script, it must be set globally and visible to all other scripts. Finally, there is only 2 solutions. The way to achieve it is just a detail. It does not mean it is easy and it must be discuss. But first of all, we must choose between calling an init function (registered or hard-coded per-script) or use global arguments. To be short, it is `core.register_init()` with extra args vs. `lua-args` (or `lua-load-args`) directive. There are pro and cons for both. The first seems to be easier to understand and more predictable.

**Comment by wtarreau** [comment]
OK thanks for enlighten me on the arg array. It doesn't apply here though as we're not loading a single script from an interpreter but assembling multiple scripts together.

However, tt's far too painful time-consuming to discuss and argument pros and cons like this. It takes one hour to summarize 5 minutes of talking, let's discuss this on monday during coffee.

**Comment by thierry-f-78** [comment]
The Lua documentation about "luaL_loadfile" > "lua_load" says :

```
Loads a Lua chunk without running it. If there are no errors, lua_load pushes the compiled chunk as a Lua function on top of the stack
````

So, the file is loaded and executed as a function. The function lua_pcall() executes the function, this function could take the number of argument taken in stack. So, the list of argument could be pushed on the stack, them the lua function loaded and finally the pcall executed with the number of args in the stack. Something like this:

There is a POC, luaL_loadfile is replaced by luaL_loadstring, but the behaviour is the same.

With this method, args are given like variable number of arguments. They are not named, their name is "...".

Technically this code seems answer fine to the problem:
 - variables are passed on the same line than haproxy directive lua-load(*)
 - arguments are local to the file (loaded as a function) and all the functions declared in this function.
 - I'm not sure that a variabel declared in a function with "local" will be forwarded through HAProxy/Lua to the registered functions with register_* directives
 - The user could process these variables as "local" and declare global what he wants

This way works but it is not so clean for the final user. The final user must get arguments in an array using this code `local args = table.pack(...)`.

```c
#include <stdio.h>

#include <lauxlib.h>
#include <lua.h>
#include <lualib.h>

#define LUA_TEST_CODE "\
	local args = table.pack(...)\n\
	for i = 1, args.n do\n\
		print(args[i])\n\
	end\n\
	\n\
	function test()\n\
		print(\"variable 'args[1]' seems global to the function:\", args[1])\n\
	end\n\
	\n\
	test()\n\
"

#define LUA_TEST_CODE2 "\
	print(\"variable 'args' seems not global to the Lua stack:\", args)\n\
"

int main(void)
{
	int error;
	lua_State *L;
	const char *s;

	L = luaL_newstate();
	if (L == NULL) {
		printf("luaL_newstate error\n");
		return 1;
	}

	luaL_openlibs(L);

	error = luaL_loadstring(L, LUA_TEST_CODE);
	if (error) {
		printf("error: %s\n", lua_tostring(L, -1));
		return 1;
	}

	lua_pushstring(L, "arg1");
	lua_pushstring(L, "arg2");
	lua_pushstring(L, "arg3");

	error = lua_pcall(L, 3, LUA_MULTRET, 0);
	if (error != LUA_OK) {
		s = lua_tostring(L, -1);
		if (s != NULL) {
			printf("lua_pcall error: %s\n", s);
		} else {
			printf("lua_pcall: error code %d\n", error);
		}
		return 1;
	}

	error = luaL_loadstring(L, LUA_TEST_CODE);
	if (error) {
		printf("error: %s\n", lua_tostring(L, -1));
		return 1;
	}

	lua_pushstring(L, "arg_toto");
	lua_pushstring(L, "arg_tata");
	lua_pushstring(L, "arg_voila");

	error = lua_pcall(L, 3, LUA_MULTRET, 0);
	if (error != LUA_OK) {
		s = lua_tostring(L, -1);
		if (s != NULL) {
			printf("lua_pcall error: %s\n", s);
		} else {
			printf("lua_pcall: error code %d\n", error);
		}
		return 1;
	}

	error = luaL_loadstring(L, LUA_TEST_CODE2);
	if (error) {
		printf("error: %s\n", lua_tostring(L, -1));
		return 1;
	}

	lua_pushstring(L, "arg_toto");
	lua_pushstring(L, "arg_tata");
	lua_pushstring(L, "arg_voila");

	error = lua_pcall(L, 3, LUA_MULTRET, 0);
	if (error != LUA_OK) {
		s = lua_tostring(L, -1);
		if (s != NULL) {
			printf("lua_pcall error: %s\n", s);
		} else {
			printf("lua_pcall: error code %d\n", error);
		}
		return 1;
	}

	return 0;
}
```

**Comment by wtarreau** [comment]
Very interesting, thank you Thierry! However I'm having a doubt now. If the Lua file is loaded as a function, does it mean that one function or global variable from one Lua file cannot be accessed from other Lua files ? I've always thought everything was shared in the same stack, but I could be completely mistaken. My hope was that by loading a few generic files used as libraries and a few local files used as setup/init/bootstrap, it would be possible to make the Lua code a bit more modular, in which case the arguments passed to the small init file could be used to completely setup the rest of the program by relying on the previously loaded files.

**Comment by thierry-f-78** [comment]
By default any variable is global. You must precise "local" to reduce the portability of a variable. It seems the functions follow the same way. The Lua code could be modular if the developper use namespace (an array with improbable name which reference all the exposed functions)

in other way, it seems the variable and functions declared with the same name are silently crushed. Only the symbol is crushed. The functions register in haproxy through register_* function keep an absolute reference on the function.

Look this code:

```lua
function test_1()
	print("test_1")
	function test_2()
		print "test_2"
	end
end

test_1()
-- test_2 is declared inside another function but registered as global
test_2()

function test_2()
	print "test_2_overide"
end

-- test_2 is crushed by another function with the same name
test_2()

test_1_ref = test_1

function test_1()
	print "test_1_overide"
end

test_1()

-- test_1 is crusged, but the function reference remain in test_1_ref
test_1_ref()
```

**Comment by wtarreau** [comment]
Ah yes, thanks a lot for this reminder, I now remember that on node-mcu (a stripped down variant for microcontrollers) I figured that `_G[var]` was exactly the same as accessing `var` directly.

So if I summarize it right, with your proposal we could make `arg*` local and thus different for each loaded file, with everything else continuing to be shared. I think it would perfectly match the desired use cases. Don't you think it's more convenient to use an array of args instead of naming them explicitly ? That *could* help parsing positional arguments, though it might be unlikely that we'd use them often. What matters in the end probably is to make sure to adapt to what users are used to and already expect.

**Comment by thierry-f-78** [comment]
> Don't you think it's more convenient to use an array of args instead of naming them explicitly ?

I don't understand.

With this proposition, args are passed with not visible mean (there a no named arg). The args are in `...` which is the notation for variable number of arguments. The user must write this line at the start of his file (`local` is optional):

```
local args = table.pack(...)
```

After this, args will be available in the array `args`.

**Comment by wtarreau** [comment]
Ah then it's fine. I thought you meant the local variables were expected to be named `arg0, arg1, arg2, arg3` etc which I didn't find the most convenient, but could have accepted if that was what users were commonly used to. Thank you!

**Comment by thierry-f-78** [comment]
I wrote a patch based on the poc above.
There is in attachment.

The 0001 fix some errors message which contains a jump and should be backported until 1.8
The 0002 is the patch.

Thierry

[0001-BUG-MINOR-Remove-n-in-Lua-error-message-built-with-m.txt](https://github.com/haproxy/haproxy/files/9598359/0001-BUG-MINOR-Remove-n-in-Lua-error-message-built-with-m.txt)
[0002-MINOR-Allow-argument-on-lua-lod-per-thread-directive.txt](https://github.com/haproxy/haproxy/files/9598362/0002-MINOR-Allow-argument-on-lua-lod-per-thread-directive.txt)

**Comment by capflam** [comment]
Thanks @thierry-f-78. It works like a charm !

**Comment by capflam** [comment]
Patches were merged. I'm closing now. Thanks @thierry-f-78

**Comment by Darlelet** [comment]
ae6b568 may cause a program crash when numerous arguments are provided to `lua-load `or `lua-load-per-thread` directives:

Stack wasn't checked before pushing the n-arguments, and we could easily overflow the stack with ~50 arguments.

Here is a complementary patch that prevents it:
[0001-BUG-MINOR-hlua-prevent-crash-when-loading-numerous-a.patch.txt](https://github.com/haproxy/haproxy/files/9632145/0001-BUG-MINOR-hlua-prevent-crash-when-loading-numerous-a.patch.txt)

**Comment by thierry-f-78** [comment]
Good catch ! Thanks for the fix. I think its strange that the Lua stack was full with 50 args !

**Comment by Darlelet** [comment]
You're welcome.

I guess it's because the pushes are happening very early in the program and lua_checkstack() has not been called that much so far, thus stack size is really small at that time.

Calling lua_checkstack() allows it to expand much more by allocating more space when needed.

With the fix I'm unable to reach stack's hard limit under normal circumstances (cfgparse complains about too many words in the config line and aborts the execution way before lua_checkstack() could actually fail).

**Comment by thierry-f-78** [comment]
You probably right. I never thought about this. The HAProxy code contains a lot of `lua_push*` functions called without stack check. In the case of protected function (function declaration prefixed by `__LJMP`), this causes a Lua software error, but in the case of non protected options this causes the same problem you just see.

For example, the init function `hlua_init_state` perform a lot of push in the stack without checking its size.

After some tests, it seems the stack has a capacity of 34 elements at start. I observe I can use the stack (push, get) without crash for a lot of iteration (69353 with a capacity of 34). Maybe the start of HAProxy work with luck !

```
#include <lstate.h>

(lua_State *)L->stacksize
```

I put the code below after each function `lua_push*` of the main Lua stack (`L`). I ignored threads stack (`lua->T`).

```
fprintf(stderr, "%d / %d\n", lua_gettop(L), L->stacksize);
```

The max usage of the stack during the start  is 5 slot of 34. So I'm reasonably sure that we can't exceed the stack during start. But it remains many functions with args from the configuration to the lua stack. I think about usage of lua converters and sample fetches.

It could be useful to extend your patch to some functions getting args from outside of lua:

 - `hlua_sample_conv_wrapper` (*)
 - `hlua_sample_fetch_wrapper` (*)
 - `action_register_lua`

(*) Note, I think the the number of arguments seems limited to 12 for converters and sample-fetches.

It should be prudent to control the stack size before each `lua_push*` function, but its a big work. I count 524 `lua_push*` functions. Maybe writing wrappers for these function and performing a sed on the original function names.

- During the start, we just want an error message and a crash if the stack can't growth (the throw of this error is absolutely not probable)
- During the runtime, use the Lua error controller `WILL_LJMP(luaL_error(L, ...));`
