### ISSUE TITLE
ability to configure connection termination after hard-stop-after in graceful termination 

### ISSUE THREAD

**Issue by maksimlikharevau** [haproxy/haproxy#1614]
### Your Feature Request

HAProxy can allow graceful termination and settings how to deal with the duration of “gracefulness”
specifically `hard-stop-after`

coming from the IoT world, where devices are keeping connections forever and reconnects on connections lost, I see a nice to have feature:
after waiting for the connection drain, `hard-stop-after`, be able to configure how remaining connections are terminated, either as a rate: connections/sec or simple duration, that will allow to add an additional degree of gracefulness and avoid reconnect storm.

as example:
**hard-stop-after 300s**
**terminate-after 60s**

so it will wait 300 sec to drain and will terminate remaining connections during the next 60s window, evenly.

### What are you trying to do?

currently, HAProxy is used to route IoT things to a specific MQTT broker shard, we run HAProxy in k8s.
we have ~60000 connections per HAProxy pod, total connections are ~2M, this is IoT, so the TCP connection is long-lived.
Termination of HAProxy terminates all clients connected to the HAProxy, and since things are simple and distributed, we see reconnect storm, all those 60K things start connecting back, adversely affecting MQTT infrastructure as well as downstream services.

Desire: be able to utilize graceful termination + spread of forceful termination of clients within a predefined window or termination batch size for infrastructure scale up/down, rolling deploy, or/and be able to handle cluster member loss with a better grace.

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.14-eaa786f 2022/02/25 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.14.html
Running on: Linux 5.4.170+ #1 SMP Tue Jan 18 21:21:01 PST 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   =

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
Running on OpenSSL version : OpenSSL 1.1.1k  25 Mar 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by wtarreau** [comment]
Hi,

thanks for your input because I was currently entering a very similar one we've got but that needs to be addressed slightly differently. Instead of maintaining connections *after* the hard-stop-after, we need to progressively replace them *before*, because hard-stop-after is the absolute deadline past which the process disappears. But that doesn't change much, in your case you'd just increase your hard-stop-after by the duration you were expecting for the spread close.

Until 2.4, idle connections are not actively closed, a "connection: close" is only appended to responses, which are overall spread over time. Since 2.5 we have a connections list and actively close them when receiving the stopping signal. Some users have already expressed concerns similar to yours and would like the connections to be progressively replaced. Given that the `hard-stop-after` is expressed as a duration, we need to do the same for the period over which connections are closed. For HTTP/1 we can continue to add "connection:close" to responses upon stopping, but condition it to `(random(close_spread_time) < stopping_age)` which will increase pressure on connection closure on response as time passes. For H1 and H2 with already idle connections, we should simply fire a timer after `random(close_spread_timer-stopping_age)`, and the task woken upon this timeout would close the connection.

I didn't have the info that some users also needed that for TCP connections (which absolutely makes sense in your situation), but it seems to me that the exact same principle as described above for idle connections will do the job. However right now there's no TCP connection list, but given that the list elements are already there, I don't think it would be a big deal to add them there as well. As such I'm adding this to the todo-list.

Ideally I would like to see this done as something prioritary for 2.6 that can be backported to 2.5, because we already had to add an option to revert to the 2.4 behavior for some users, which indicates that the solution is insufficient there.

**Comment by nmerdan** [comment]
The approach sounds good, but can we make sure this new way also supports working exactly like the TCP mode does today, ie. not close connections at all until either the client or the server close it (with or without hard-stop-after configured).

**Comment by lukastribus** [comment]
@nmerdan I'm not sure what you mean. `hard-stop-after` kills active connections, that's the point of this feature.

**Comment by nmerdan** [comment]
Of course, I'm saying this new development shouldn't require `hard-stop-after` to be configured to work. Like I said, have an additional parameter to make it work like `mode tcp`, ie. don't close any connections until done so by client or server, in addition to the option to close the connections gradually as @wtarreau described. 

So with this parameter, if there is no `hard-stop-after` configured, then the process terminates once the last client/server disconnects while not actively trying to close connections at all. If the `hard-stop-after` is configured, then all connections are of course closed when the `hard-stop-after` time passes and the process is killed.

**Comment by wtarreau** [comment]
@nmerdan, if I understand you well, you want an option to *disable* the behavior ? I think that it would simply be the case when the parameter is not specified. Out of curiosity, what use case do you have in mind where it would be desirable to only close all connections at once after the `hard-stop-after` expires ? This could help us refine the mechanism.

**Comment by nmerdan** [comment]
I'll write out all the scenarios here as it stands in 2.6, just talking about `mode http` and H1, for simplicity:

1. All idle connections are closed immediately (default)
2. Connections are closed after the first response when `option idle-close-on-response` is present by inserting `Connection: close` into the response.

New additions:

1. Ability to gradually close connections after SIGUSR1 was received up to `hard-stop-after` expires, so that all (or almost all) connections have already been closed before `hard-stop-after` hits.
2. Ability to not close idle HTTP connections, ever. 

So what I want is the last option above.

The use case is people will run a relatively long `hard-stop-after` time, but they absolutely want to avoid any chance of an idle connection being closed by HAProxy. Some may opt to not run `hard-stop-after` at all, understanding the risks. Maybe this could be done by setting the `close-spread-time` in the config to 0 or similar, just as a parameter to this new option that's gonna be added.

**Comment by wtarreau** [comment]
OK thanks for the clarifications. I must confess I'm a bit surprised by your last option, because that's a step back to version 1.3 where basically all users were complaining about this, but I think this can indeed be combined with the same option. Admittedly in 1.3 we didn't have `hard-stop-after` and that could make a difference.

**Comment by wtarreau** [comment]
Now complete, thanks @rlebreton. Thus I'm closing.
