### ISSUE TITLE
src/backend.c: checked return suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1654]
### Tool Name and Version

coverity

### Code Report

```plain
/src/backend.c: 1269 in do_connect_server()
1263                    else
1264                            s->csb->state = CS_ST_CON;
1265            }
1266     
1267            /* needs src ip/port for logging */
1268            if (s->flags & SF_SRC_ADDR)
>>>     CID 1487927:  Error handling issues  (CHECKED_RETURN)
>>>     Calling "conn_get_src" without checking return value (as is done elsewhere 20 out of 21 times).
1269                    conn_get_src(conn);
1270     
1271            return ret;
1272     }
1273     
1274     /*
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
I'm seeing this one as an opportunistic retrieval. The other places in fact only test the return code to see if the value may be used, nothing more. There's no particular error processing on this and some protocols will not have any address. As such I think we can mark as an FP. Thanks!

**Comment by TimWolla** [comment]
> As such I think we can mark as an FP. Thanks!

Can we get a `(void)` cast or similar? If Coverity is correct then it is literally the only place where the return value was not checked and as a human reader the function name to me implies that this is a pure getter (meaning it would be a noop if the return value is not used).

**Comment by wtarreau** [comment]
No, I regret but I disagree. All such things render the code much less readable, and the vast majority of bugs in the code come from lack of legibility. The code is perfectly valid C and there's no reason for making it less readable.

The return code is not used for error checking but to let the caller know if anything was done and if there is anything additional it can do. As such we're precisely in a case where we're simply not interested in the extra information that's provided exclusively for convenience. Coverity just makes statistics on calls and simply got this one wrong because it doesn't know why it's used differently between different places.

**Comment by chipitsine** [comment]
I've marked as "intentional"
