### ISSUE TITLE
When requests peak, timeout queue should timeout oldest requests first

### ISSUE THREAD

**Issue by DagW** [haproxy/haproxy#177]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.8.19 2019/02/11
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-format-truncation -Wno-address-of-packed-member -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_LINUX_TPROXY=1 USE_CRYPT_H=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.1.1a FIPS  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.1.1c FIPS  28 May 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.43-RC1 2019-01-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
```

## What should haproxy do differently? Which functionality do you think we should add?

When haproxy queues requests for a server, we would like to be able to control if the queue is First-in-First-out or Last-in-First-out. When requests are queued for a longer time dropping the oldest ones makes sense because those clients may no longer care about the results.  

One thought would be to be able to swich from FIFO to LIFO based on queue lenght or average time, and serve the most recent requests first when the queued requests ramp up.

## What are you trying to do?

Improve service degredation under high load.

**Comment by lukastribus** [comment]
Switching from FIFO to LIFO seems like a bad idea to me. Sounds like your queue timeout is already too large and you are trying to compensate that by switching to LIFO.

To improve service degradation under load, I'd suggest using properly tuned queue timeouts as well as [Server Queue Priority Control](https://www.haproxy.com/blog/haproxy-1-9-has-arrived/).

**Comment by DagW** [comment]
Thanks for your response.

We have the timeout queue configured at a low value, 2.5s. We have client implementations that are not under our control that sometimes because of networking issues and retries creates a large number of simultanious connections. This causes a large queue that will get computed resposes that probably will never be read, while blocking newer requests.
It would serve us better to down-prioritize these bursts and process newer requests first.

We also got the idea from the sre-handbook that suggests this is one method to distuingish what requests to serve in a high load condition.  
https://landing.google.com/sre/sre-book/chapters/addressing-cascading-failures/#xref_cascading-failure_load-shed-graceful-degredation
> Changing the queuing method from the standard first-in, first-out (FIFO) to last-in, first-out (LIFO) or using the controlled delay (CoDel) algorithm [Nic12] or similar approaches can reduce load by removing requests that are unlikely to be worth processing [Mau15]. 


And it also seems like facebook is doing something similar,  
https://queue.acm.org/detail.cfm?id=2839461

Any alternative angles to this would be appreciated. 
Thanks for the link to Server Queue Priority Control, definitly worth a look.

**Comment by wtarreau** [comment]
Doing LIFO when you have several populations with different behaviours
will not improve anything, it will just allow you to place the cursor
somewhere between these populations, which will happen to improve a part
of the problem by cheating. Doing LIFO (or better, RED) on homogenous or
highly heterogenous populations is different because as you mentioned,
at some points some are likely to already have given up. However, there
are a few points to keep in mind :

  - haproxy knows if a client aborts and will abort it while in the
    queue so that its place is not maintained. This means that any
    client that you decide to abort while in the queue has not aborted
    yet. What you've seen above is mostly generic and does not involve
    knowledge of the client's presence (typically this can be valid for
    packet drops).

  - any algo this will not prevent a single client from misbehaving and
    increasing the useless connection count and disturb everyone.

  - the prioritization definitely is the way to go, and it supports
    both classes (one class is always served before another one) and
    time offsets (you can define the service delay while in the queue
    to let others pass).

  - you can also know the number of connections from a given source,
    network, user-agent or any critierion of your choice, for this,
    please have a look at the "track-sc0" keyword and stick tables.

Typically I think that a good solution consists in setting a queue
priority offset proportional to the current number of connections from
the same source. It means that extra connections from the same source
decrease in priority and let others pass through. A typical way to
do that would basically involve :

  frontend public
      ...
      http-request track-sc0 src,ipmask(24) table per-addr
      http-request set-priority-offset sc0_conn_cur(per-addr),mul(10)

  backend per-addr
      stick-table type ip size 10k store conn_cur

This should add a 10ms queue penalty to each extra concurrent request
from a same /24 network. Your misbehaving client coming there in bursts
could establish 10k connections, these ones would not finish being
processed before 100 seconds for the last ones, leaving a lot of room
for other clients. It also encourages clients to abort after a short
timeout so that new requests have a chance of being served faster.

**Comment by DagW** [comment]
Thanks for the detailed response.   
I would like to give prioritization a go, I think we can work with some bits of information from the client connections to use your above suggestion.   
And I gather that LIFO is not on the roadmap :-) 

I think partly our problem is that we have misbehaving clients as its not only webbrowsers but also backend implementations that might not be properly closing the connections when this occurs - and also doing retries. Or maybe rst-packets being dropped due to network issues, so that haproxy keeps them in queue.

Maybe a bit off topic for this issue, but is there any configuration in haproxy that might help if we suspect clients are not properly closing connections?
