### ISSUE TITLE
SSL_load_error_strings is not defined when DEFINE="-DOPENSSL_API_COMPAT=0x10100000L -DOPENSSL_NO_DEPRECATED" is set

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1813]
### Tool Name and Version

gcc

### Code Report

```plain
https://github.com/haproxy/haproxy/runs/7663274388?check_suite_focus=true#step:4:53


  CC      src/cache.o
  CC      src/stconn.o
src/haproxy.c: In function ‘init’:
src/haproxy.c:2235:2: error: implicit declaration of function ‘SSL_load_error_strings’; did you mean ‘ERR_lib_error_string’? [-Werror=implicit-function-declaration]
 2235 |  SSL_load_error_strings();
      |  ^~~~~~~~~~~~~~~~~~~~~~
      |  ERR_lib_error_string
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
```
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
Indeed, according to the man page, this function is part of a deprecated API and is reserved for < 1.1.0. Let's wait for more knowledgeable devs to have a look at this.

**Comment by wlallemand** [comment]
erg, too bad. I'll try with OPENSSL_init_crypto() for recent versions but that does not do the same thing.

**Comment by rlebreton** [comment]
According to OPENSSL_init_crypto's manpage (https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_init_crypto.html), it is rarely required to call this function explicitely since it is already done during OpenSSL's start up. The only time when this function needs to be called in when some specific init settings are set. In our case, we wanted to load the library's error strings, which is already done by default. The attached patch should then be enough.
[0001-BUG-MINOR-ssl-SSL_load_error_strings-might-not-be-de.txt](https://github.com/haproxy/haproxy/files/9576504/0001-BUG-MINOR-ssl-SSL_load_error_strings-might-not-be-de.txt)

**Comment by wlallemand** [comment]
I don't think this is right, I added it explicitely in 3b8bafd4a74519c914e47845ec11700202475f2a because ERR_reason_error_string() was returning NULL values. The only place which uses it for now is the parsing of ca-file which was modified in 0f17ab2fdd83ff4f58151a44a8fe1bc22e5b9c18. I'll need to check this again.

**Comment by rlebreton** [comment]
My bad I did not realize it was added lately since it's an old function. I assumed that since the reg-tests were ok with all the versions I tested then it was good. I'll leave it to you then.

**Comment by wlallemand** [comment]
You seem to be right, I could not reproduce the problem I had, I must have mistaken. Applying the patch, I marked it to be backported only in 2.6, thank you.

**Comment by wlallemand** [comment]
No backport needed at all, it's a mistake.
