### ISSUE TITLE
Add `timeout retry` setting to disconnect from `timeout connect`

### ISSUE THREAD

**Issue by bartbutler** [haproxy/haproxy#1878]
### Your Feature Request

Rather than reusing `timeout connect` and clamping to 1s as is done today for retries, we would like to request that an explicit separate `timeout retry` setting be added so that we can control these two behaviors independently.

### What are you trying to do?

As discussed in https://github.com/haproxy/haproxy/issues/1867, we were trying to lower the time HAproxy waited to retry requests, and eventually found that the way to do this was to lower `timeout connect`. We did this, but it had unintended negative consequences when HAproxy was under load and we had to revert.

We'd like to keep `timeout connect` higher to mitigate these issues but lower the wait for retries (which we redispatch immediately) when a given backend server is alive and well but at capacity (our current architecture does not allow us to use maxconn effectively for this). 

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.15-7782e23 2022/03/14 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.15.html
Running on: Linux 5.18.3-1.el8.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jun 8 10:40:51 EDT 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_PCRE=1 USE_PTHREAD_PSHARED=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_TFO=1 USE_SYSTEMD=1 USE_OT=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD +PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS +OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
Running on OpenSSL version : OpenSSL 1.1.1n  15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.4
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with OpenTracing support.
Built with zlib version : 1.2.7
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.32 2012-11-30
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-44)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[  OT] opentracing
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by Kamveno** [comment]
hi @bartbutler  i would like to contribute to the issue

**Comment by wtarreau** [comment]
I'm a bit confused by the description, because we don't "wait" to perform a retry. We retry after various (configurable) events, one of them being a connection failure, in which case it's definitely the `timeout connect` that is being waited for.
In the other issue you rightfully mentioned the turn-around delay of 1s to avoid instantly wasting all retries on a restarting server, as users noticed that even a very fast restart of 1ms was sufficient to deplete all 3 retries in failed connect attempts. 

Just to understand the situation better, what exactly is the situation that causes the connect() issue that you would like to immediately retry ? Or are you experiencing this delay with other events than connect() where it's not appropriate ? I'm not fond of adding another configurable timeout for a situation that's not clear, because it will result in misunderstanding and misuse. However there may be situations where we should simply eliminate the turn-around delay if it's not appropriate. That's why I need the details.

**Comment by bartbutler** [comment]
Understood. We have configured our backend servers to reject connections when they are "full". This is basically instantaneous rather than a timeout. Health checks are on a different port so they aren't rejected and the server stays up in HAproxy in this particular case.

We've configured redispatches to immediately try a different backend rather than retrying the original server. However, we noticed that even when the retry is going to a different server entirely after "connection refused", the min(timeout connect, 1s) is enforced, and we'd like to eliminate it.

So another way to address this could be to not enforce the min(timeout connect, 1s) at all for redispatches to other servers as opposed to retries to the same server, unless you see a reason that someone might want to configure a wait for redispatches too, in which case I guess a configurable retry timeout would be more flexible.

**Comment by wtarreau** [comment]
This is strange because it's not intended to do that at all, and even when I need to abuse this to hack some delay somewhere it never works and I need to be certain to stay on the same server for this. Do you have a reproducer for this case ? It could be possible that it happens only when facing a specific combination of config options but it's really hard for me to imagine such a case. Normally retries are instant when the server changes.

**Comment by bartbutler** [comment]
It's certainly possible we have something strange going on, but our setup is as follows:

option                          redispatch 1
retries                          3
timeout connect         3500

in server defaults. We enforce the connection limit to the backend servers with a firewall reject rule, so with curl or similar you get an instant "connection refused".

When we do this, we always have a 1s wait before redispatch, always, despite the reject from the first server should be much faster.

I suppose you could reproduce this with a dummy health check that always returns success, blocking all connections to a backend with the firewall, and watch the request duration of the redispatched requests.

The other possibility is that the connection refused is not being registered correctly and it's treating it as a connection timeout, but if that was the case it would be 3.5s not 1s I would think.

**Comment by capflam** [comment]
It is indeed unexpected to observe a delay with such configuration. But it depends on your balance algorithm. It must be `roundrobin`, `static-rr` or `random`. Idea is to be sure to select another server. Otherwise a delay is applied.

**Comment by bartbutler** [comment]
Hmmm, I think we tend to use `balance source` to try to impose a soft stickiness on connections to our service because we feel it's better to be down 100% for 5% of users than have 5% of requests fail for all users.

In our experience, redispatch using `balance source` still always go to other servers. Would it be possible to have the no-delay apply for any redispatch?

**Comment by wtarreau** [comment]
That's interesting. We should check in the code, but it's indeed possible that the delay depends on the algo because hash-based algorithms are supposed to be stable and not to switch to another server (unless the server is taken out of the pool, of course). That could be one explanation. We need to analyze deeper to see how to avoid this and only rely on the server itself.

**Comment by bartbutler** [comment]
Thank you for looking into it! We very much appreciate it.

**Comment by wtarreau** [comment]
So... that's it! In back_handle_st_cer():
```
                /* only wait when we're retrying on the same server */
                if ((sc->state == SC_ST_ASS ||
                     (s->be->lbprm.algo & BE_LB_KIND) != BE_LB_KIND_RR ||
                     (s->be->srv_act <= 1)) && !reused) {
                        sc->state = SC_ST_TAR;
                        s->conn_exp = tick_add(now_ms, MS_TO_TICKS(delay));
                }
```
See that `s->be->lbprm.algo & BE_LB_KIND` checkint against `BE_LB_KIND_RR` ? This means that round robin is the only one that can escape this, and only when there's more than one server. Thus even leastconn has to endure it. The problem is that before the redispatch we don't know which server will be used, and this test was used as a hint of hash vs RR (leastconn didn't exist when the test was implemented). This test is already performed in `stream_choose_redispatch()` which is called a few lines earlier to set the SC_ST_ASS / SC_ST_REQ state. Additionally the function checks if the current server switched state, which is exactly your case. Thus I would remove the test on the LB kind above (and also fix the function above to consider leastconn as well).

Could you please try to apply this change to see if it works for you ?
```
diff --git a/include/haproxy/stream.h b/include/haproxy/stream.h
index f72a923ce..06716aeeb 100644
--- a/include/haproxy/stream.h
+++ b/include/haproxy/stream.h
@@ -334,7 +334,7 @@ static inline void stream_choose_redispatch(struct stream *s)
              ((s->be->redispatch_after < 0) &&
               (s->conn_retries % (s->be->conn_retries + 1 + s->be->redispatch_after) == 0))) ||
             (!(s->flags & SF_DIRECT) && s->be->srv_act > 1 &&
-             ((s->be->lbprm.algo & BE_LB_KIND) == BE_LB_KIND_RR)))) {
+             ((s->be->lbprm.algo & BE_LB_KIND) != BE_LB_KIND_HI)))) {
                sess_change_server(s, NULL);
                if (may_dequeue_tasks(objt_server(s->target), s->be))
                        process_srv_queue(objt_server(s->target));
diff --git a/src/backend.c b/src/backend.c
index dc30c7627..6ddd7f615 100644
--- a/src/backend.c
+++ b/src/backend.c
@@ -2413,7 +2413,6 @@ void back_handle_st_cer(struct stream *s)
 
                /* only wait when we're retrying on the same server */
                if ((sc->state == SC_ST_ASS ||
-                    (s->be->lbprm.algo & BE_LB_KIND) != BE_LB_KIND_RR ||
                     (s->be->srv_act <= 1)) && !reused) {
                        sc->state = SC_ST_TAR;
                        s->conn_exp = tick_add(now_ms, MS_TO_TICKS(delay));
```

**Comment by bartbutler** [comment]
Took a little time to figure out our haproxy build setup, but I can confirm that this patch solves our problem entirely as far as I can tell. Any chance we could get it backported to the 2.4 LTS or should we apply the patch ourselves in our build process?

**Comment by wtarreau** [comment]
Excellent, thanks for testing!

Well, I'm fine with backporting as far as 2.4, but in two steps. First it will be 2.6, and only if nobody complains after a few weeks (or one version) we can then bring it to 2.4. That may mean that you could have to deal with it in your build process for a few more weeks (assuming there's no reported regression with it, of course). I hope it's not too annoying.

**Comment by bartbutler** [comment]
Not at all, sounds good. Thanks!
