### ISSUE TITLE
Weight seems to be ignored in server-template

### ISSUE THREAD

**Issue by Peter2121** [haproxy/haproxy#1910]
### Detailed Description of the Problem

We use dynamic backend managed by server-template using DNS resolvers.
The weights are correctly taken from DNS system, but the statistics shows that they are not used when the sessions are distributed between backend servers. The CPU charge of backend servers are unbalanced too. The balance method is roundrobin.

![shot-2022-10-26_10-11-32](https://user-images.githubusercontent.com/3807655/197973032-910b53cd-a36d-431b-b148-5af9e4e7bc27.jpg)
![shot-2022-10-26_10-11-43](https://user-images.githubusercontent.com/3807655/197973041-83ce6034-329f-4167-97ac-1deb46ba17d8.jpg)

### Expected Behavior

The weight difference is really important (250/60 between erp1 and erp2). I suppose to see more difference in bytes in/out and sessions max/total between these two servers.

### Steps to Reproduce the Behavior

1. Configure haproxy with dynamic backend and different weights
2. See the stats

### What is your configuration?

```haproxy
global
    log         127.0.0.1:514 local0 debug
    pidfile     /var/run/haproxy.pid
    stats       timeout 30s
    maxconn     4000
    user        www
    group       www
    daemon

defaults
    log global
    mode http
    retries 3
    log-format "%ci:%cp [%tr] %ft %b/%si %TR/%Tw/%Tc/%Tr/%Ta %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
    option redispatch
    maxconn 2000
    timeout http-request    600s
    timeout queue           1m
    timeout connect         20s
    timeout client          1m
    timeout server          10m
    timeout http-keep-alive 10s
    timeout check           10s

resolvers coredns
    nameserver coredns4 10.192.20.176:53
    nameserver coredns2 10.192.20.177:53
    accepted_payload_size 8192
    resolve_retries 2

listen stats
    bind *:4443 ssl crt /usr/local/etc/haproxy/cert/_.xxxx.xx.pem
    stats enable
    stats hide-version
    stats refresh 30s
    stats show-node
    stats realm Haproxy\ Statistics
    stats auth admin:xxxxxxx
    stats uri /xxxxxx

frontend www-https
    bind *:443 ssl crt /usr/local/etc/haproxy/cert/_.xxxx.xx.pem
    http-request add-header X-Forwarded-Proto https
    default_backend erp-backend-dynamic

backend erp-backend-dynamic
    balance roundrobin
    dynamic-cookie-key XXXXXXXXXX
    cookie SRVID insert dynamic indirect nocache maxidle 10m maxlife 1h attr "SameSite=None" attr "Secure"
    option forwardfor
    option httpchk GET /public/test_serveur.php
    server-template erp 6 _weberp._tcp.service.consul.cloud.local ssl verify none check inter 10s check-ssl resolvers coredns resolve-prefer ipv4 init-addr none
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.6.1-f6ca66d 2022/06/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2027.
Known bugs: http://www.haproxy.org/bugs/bugs-2.6.1.html
Running on: FreeBSD 13.0-RELEASE-p8 FreeBSD 13.0-RELEASE-p8 #0: Tue Mar 15 09:36:28 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64
Build options :
  TARGET  = freebsd
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wnull-dereference -fwrapv -Wno-unknown-warning-option -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment -DFREEBSD_PORTS
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_ACCEPT4=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_PROMEX=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -EPOLL +KQUEUE -NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL +THREAD -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY -LINUX_TPROXY -LINUX_SPLICE +LIBCRYPT -CRYPT_H -ENGINE +GETADDRINFO +OPENSSL -LUA +ACCEPT4 +CLOSEFROM +ZLIB -SLZ +CPU_AFFINITY -TFO -NS -DL -RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER -PRCTL +PROCCTL -THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1k-freebsd  24 Aug 2021
Running on OpenSSL version : OpenSSL 1.1.1k-freebsd  24 Aug 2021
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with the Prometheus exporter as a service
Support for malloc_trim() is enabled.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_BINDANY IPV6_BINDANY
Built with PCRE2 version : 10.40 2022-04-14
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with clang compiler version 11.0.1 (git@github.com:llvm/llvm-project.git llvmorg-11.0.1-0-g43ff75f2c3fe)

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=

Available services : prometheus-exporter
Available filters :
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

haproxy installed from packages from FreeBSD repository in a jail.

**Comment by Darlelet** [comment]
Hi Peter,

This is strange indeed.

I cannot reproduce using the configuration options you provided with local test setup + haproxy "2.6.1 2022/06/21":
![image](https://user-images.githubusercontent.com/6534701/198023395-ba356b0c-7907-4eee-adce-162f2fa89422.png)


(I used SRV DNS records to populate backend servers, but I only have one nameserver in the resolvers section)

The load seems to be evenly distributed according to server weight.

Could it be that your coredns4 and coredns2 servers provide conflicting SRV records?

**Comment by TimWolla** [comment]
Independently of this specific issue you should also make sure to upgrade to the latest patch version within a given branch regularly. The current version in 2.6.x is 2.6.6 which contains 203 bug fixes you do not yet have. Some of those bugs are likely much worse than ignored weights:

https://www.haproxy.org/bugs/bugs-2.6.1.html

**Comment by Peter2121** [comment]
@Darlelet, 
No, the CoreDNS servers just forward the requests to Consul servers :

```
consul.cloud.local {
    acl {
        allow net 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 127.0.0.0/8
        block
    }
    forward . 10.192.20.115:8600 10.192.20.116:8600 10.192.20.117:8600 {
      prefer_udp
      expire 10s
      policy round_robin
      health_check 5s
    }
    cache 10
}
```
All Consul servers are from the same cluster, so they have the same data, something like this :

```
{
    "id": "weberp_3",
    "name": "weberp",
    "port": 443,
    "Address": "10.192.20.141",
    "checks": [
        {
            "http": "https://10.192.20.141/public/test_serveur.php",
            "tls_skip_verify": true,
            "interval": "20s",
            "timeout": "15s"
        }
    ],
    "weights": {
        "passing": 12799,
        "warning": 1
    }
}
```
The weight is calculated according to Consul documentation.

@TimWolla,
Thanks for marking this, I'll update haproxy during the next maintenance window.

**Comment by Darlelet** [comment]
Ok, thank you for the details.

What about Consul data changing over time? I mean, server weight data more specifically.
I don't know much about Consul though so please excuse me if this does not make sense here.

The only way I manage to "reproduce" the behavior you described is
to force SRV DNS responses to change over time (altering server weight from DNS without restarting haproxy).

In this situation it is not reliable to rely on the last known server weight to check if the total number of sessions / bytes processed is consistent because theses stats are not reset on server weight updates.

**Comment by Peter2121** [comment]
@Darlelet,
I Don't see any possibility of Consul data changing over time. The weight is defined during service registration, it could be changed only if the backend server goes down (to 1). Probably (as this is the same status test page used by Consul and HAproxy) at this moment the backend server goes down at the level of HAproxy as well, it should be visible in 'Status' column of stats page (but it is not the case).

**Comment by Darlelet** [comment]
Ok.

Also, I see on your stats screenshot that some servers have been UP for longer time than others.
Maybe you already had some DOWN/UP, given than your backend uptime is > 5days and max server uptime < 1 day?

Unfortunately from the stats there is no way to guess for how long the servers have been UP (cumulative) since they were added.
We only have current uptime.

It's really hard to tell if there is an issue related to server weight handling by simply looking at the stats page on such
a large test window.

Aside from haproxy stats, do you have another way to gather some metrics to check if the server weight is actually working regardless of the stats reported by haproxy?

Thanks

**Comment by Darlelet** [comment]
Moreover, please note the following behavior:

Consider you have multiple SRV records going down:
i.e: when Consul wants to notify haproxy that a server is down on its side, it stops advertising the SRV record for
that server, right?

When those SRV records are back up: haproxy does not guarantee the order in which SRV records are handled.
So you could potentially have haproxy server id swaps!

Server weight handling shouldn't be affected since it's provided by the SRV record alongside server target/ip, but attributes
stored internally by haproxy (not provided by SRV records, eg: server stats, server id) could be referring to another server that was also in maintenance state due to temporarily missing SRV record.

It seems to me like an additional motive not to rely solely on haproxy server stats when server-template backed by SRV records is in use.

You should consider adding the `stats show-legends` option in your stats section:
![image](https://user-images.githubusercontent.com/6534701/198556476-369e1209-0e8d-418e-a42b-ea899d21af1a.png)
-> Hovering server id with mouse will reveal last known server IP.
It could come in handy to check whether server id swaps are actually happening or not.

**Comment by Peter2121** [comment]
@Darlelet,
Thanks for your answers.
I understand your idea. I'll be able to do the checks you've asked at the end of the next week. I'll be back ASAP.

**Comment by gabrieltz** [comment]
@Peter2121 I'm running consul for autodiscovery and server templates as well, and have noticed the same behaviour. 
server order and swaps do occur when you have configured more servers in the server-template than you are actually using
for example consider this rpc-proxy cluster with 5 configured servers with blue/green deployments 
Note that green currently standby and blue is the active one:
`server-template rpcproxygreensrv 5 _rpc-proxy-green._tcp.service.XXXXXX.consul resolvers consul check observe layer4`
for the last few days i'm using 4 to save a few cpu cycles and this is what happens

```
Oct 28 15:23:56 haproxy[1317262]: rpc-proxy-green/rpcproxygreensrv4 changed its IP from (none) to XX.XX.XX.96 by consul/consul1.
Oct 28 15:23:56 haproxy[1317262]: [WARNING]  (1317262) : rpc-proxy-green/rpcproxygreensrv4 changed its IP from (none) to XX.XX.XX.96 by consul/consul1.
Oct 28 15:24:08 haproxy[1317262]: rpc-proxy-green/rpcproxygreensrv2 changed its IP from (none) to XX.XX.XX.96 by DNS additional record.
Oct 28 15:24:08 haproxy[1317262]: [WARNING]  (1317262) : rpc-proxy-green/rpcproxygreensrv2 changed its IP from (none) to XX.XX.XX.96 by DNS additional record.
```
somehow server id 4 ( ip ends with 96 ) becomes server id 2 and server id 4 is in maintenance
![Screenshot from 2022-10-28 21-49-54](https://user-images.githubusercontent.com/13848662/198710728-a37abff7-fccf-4c1e-84ed-26bf5cfdce45.png)

On other backeds that the server-template number of server matches the actually deployed and registered servers on consul 
this does not occur at all

I have `option redispatch` so it's not really a big problem for me

for the record i'm using version 2.7-dev8-0b13e9-44

**Comment by Peter2121** [comment]
@gabrieltz 
Hmm...
Do you think that this behavior is a bug or a feature? ;)

**Comment by gabrieltz** [comment]
well, according to the documentation, haproxy queries all configured resolvers in parallel and uses the first/fastest usable response, in my case it's 3 consul servers and each may respond with a different order of records. As such , i wouldn't call it a bug or a feature. I'll run a few tests on monday if time permits

**Comment by gabrieltz** [comment]
using `dig @consul-server -p 8600 fqdn SRV`  against any consul server returns the records in random order

**Comment by Darlelet** [comment]
@gabrieltz Indeed but this is not a consul specific behavior,
Other DNS server implementations could return SRV records in random or cyclic order.

e.g: bind9 name server does round-robin by default, except if `with-fixed-rrset` is used.

This is why you could have server id inconsistencies between 2 haproxy processes relying on the same DNS server (it seems issue https://github.com/haproxy/haproxy/issues/1410 is related to this behavior)

**Comment by Darlelet** [comment]
Here is my attempt at explaining why server id swaps / reordering occur when you have servers in SRV_ADMF_RMAINT state
(ie: because of temporarily missing SRV entries when Consul wants to tell haproxy that a server is down on its side):

In current implementation, as long as a SRV record remains valid for a given server, haproxy will do some lookup based on hostname+port to find the server associated with this existing SRV record. (random SRV records order is not an issue here thanks to lookup)

However, when SRV record is removed from DNS (even temporarily), haproxy enforces the related server to SRV_ADMF_RMAINT state.

But here is the catch:
haproxy can't tell between a completely new SRV record and a "returning" SRV record.

In both cases, it will look for an available server slot (any server in SRV_ADMF_RMAINT state) to link the "new" SRV record to it.

Maybe people at Consul didn't know of this "behavior" when developing the discovery service for haproxy?

**Comment by Darlelet** [comment]
I think we could still achieve expected behavior if Consul sets server weight to 0 instead of removing related SRV entry when it wants to tell haproxy that no more requests should be sent to server.

**Comment by Peter2121** [comment]
@Darlelet,
I think that we cannot ask Consul devs to drop the weights to 0 but keep the server in the list. Just because of A records where there are no weights at all. And it would be really strange to remove A records but keep SRV records in case of maintenance state.
IMHO, to avoid that behavior, haproxy should not use simple sequential numbers for backend servers, but something convertible from (and to) IP address and port number pairs.
For example, if the address of the server is 10.192.20.145 and the port is 443 - the name of the backend server at the haproxy level should be <prefix>.0ac01491.1bb (in my case erp.0ac01491.1bb).
If we have such relations between the backend name and the address:port pair - when the server comes back from maintenance it will retake his original place.
Another way would be an internal haproxy table where the 'old' servers are stored for a limited period of time.

**Comment by Peter2121** [comment]
@Darlelet,
I think that this issue should be classified as a bug now.
In the documents of haproxy it is claimed that one can use DNS discovery based on SRV records, and that the weights returned by DNS resolvers are taken into account. The weight information in DNS is based on IP addresses (name->IP), moreover, the DNS information is dynamic 'by design' with the TTL provided by DNS servers. But now we can see that in some circumstances the weight information is not correctly taken by haproxy. The names of backend servers ('server slots') is the internal information, purely related to haproxy management. So, these names must be used at the way the haproxy respects the DNS information received from resolvers.

**Comment by Darlelet** [comment]
As mentioned before, weight is always taken into account for a given target+port pair (extracted from the SRV record), server id swaps are not directly related.

Server id reuse/swaps occur because of the way SRV records are handled internally.

Strictly speaking, there doesn't seem to be a bug here, only implementation choices that affect server stats relevance in this specific context.

DNS discovery comes with a big limitation: removing a target means to stop advertising it. There is no way for the DNS subsystem to explicitly send a "DOWN" server request to haproxy.

To address this, haproxy assumes that when a SRV record associated with a server has not been seen for a given amount of time, it is considered stale (and server slot is set free for reuse).

It works but it is not perfect, DNS is probably not the perfect tool for this anyway.

**Comment by Peter2121** [comment]
@Darlelet,

> weight is always taken into account for a given target+port pair

> Strictly speaking, there doesn't seems to be a bug here, only implementation choices that affect server stats relevance in this specific context.

I have no such impression. In our case I started to explore the statistics _because_ my servers are not balanced correctly. I use Graylog to analyze haproxy and nginx (backend servers) logs, and I see that the my servers are randomly charged. One day I have two backend servers that receive the most of traffic, another day it could be _another_ two servers. And as I have some servers with weak CPU - some days I see these servers at 60% of CPU usage permanently, when the two most powerful servers are at 10%. _That's why_ I began to analyze the haproxy stats. As I knew that I cannot use backend server names in haproxy logs - I use IP based statistics. And I see that the load distribution is incorrect. It is confirmed by nginx logs too.

**Comment by capflam** [comment]
@Peter2121,  do your servers share the same IP ? I'm asking because I found a bug in the resolvers. When a SRV item is used to fill server's info, the port is set after the dynamic cookie computation. This means only the ip is used to create the server's dynamic cookie because the port is always equal to 0. Thus all servers sharing the same IP address will have the same cookie.

**Comment by Peter2121** [comment]
@capflam,
Non, all the servers use the same port 443 but different IP addresses.
I've done several tests recently - the load distribution does not follow the weights received from SRV records even if the servers list does not change. I tested the configuration during 2 hours approximately where I was sure that the backend servers list was static.

**Comment by capflam** [comment]
You are using cookie-based persistence. The load balancing is only performed on requests that don't provide a cookie. Could you check the distribution for new visitors only (with `--NI` termination state in HAProxy log) ?

**Comment by Peter2121** [comment]
@capflam,

> Could you check the distribution for new visitors only (with --NI termination state in HAProxy log) ?


Thanks for this idea. It will take some time though. I'll be back ASAP.

**Comment by wtarreau** [comment]
Note that on the stats page page there is an "LbTot" column that indicates how many times this server was selected by the load balancing algorithm (i.e. doesn't count persistent requests). If you're using roundrobin and your servers are stable (i.e. don't go up and down all the time) this will exactly match the weights.

**Comment by Peter2121** [comment]
Indeed, I completely underestimated the influence of sticky sessions on the load distribution. If I use the stats filtered by NI and OI status - the distribution is correct, in accord with the weights configured in DNS. Now we are adjusting the timings of sticky sessions to fix the problem of load distribution.
So, if you consider that the problem of stats mixed between backend servers after their UP/DOWN is not considered as a bug - this ticket can be closed.
Thanks to all!!

**Comment by capflam** [comment]
Thanks for the feedback !
