### ISSUE TITLE
Cannot communicate with MySQL server through haproxy

### ISSUE THREAD

**Issue by jean-christophe-manciot** [haproxy/haproxy#1915]
Ubuntu 22.04
haproxy 2.4.18-0ubuntu1

**Summary**: Mysql checks with the server pass on haproxy, but any call of mysql to haproxy from a client has no answers; a network sniff shows that no communication occurs between haproxy and mysql server (besides the regular checks).

**Relevant Configuration**:
```
frontend sql
        bind            :::3306 v4v6
        mode            tcp
        use_backend     mysql if { dst_port 3306 }
        default_backend postgresql
        ...
        
backend mysql
        mode            tcp
        default-server  check resolvers dns
        # Using MySQL health checks for server testing
        option          mysql-check user haproxy
        server          mysql1-kvm 192.168.122.42:3306
        stick           on src
        stick-table     type ip size 1m expire 5m peers load_balancer_replication
        ...
```

**Checks**:
```
# echo "show servers state" | sudo socat stdio /run/haproxy/admin.sock | grep mysql1-kvm
6 mysql 1 mysql1-kvm 192.168.122.42 2 0 1 1 940 15 3 4 6 0 0 0 192.168.122.42 3306 - 0 0 - - 0
```

**Calling mysql server from client**:
```
mysql --user="root" --host="192.168.122.109" --password="password" --execute="SHOW DATABASES;"
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```

**haproxy**:
```
haproxy -vv
HAProxy version 2.4.18-0ubuntu1 2022/08/25 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.18.html
Running on: Linux 5.19.0-23-generic #24-Ubuntu SMP PREEMPT_DYNAMIC Fri Oct 14 15:39:57 UTC 2022 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_SYSTEMD=1 USE_PROMEX=1
  DEBUG   = 

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -CLOSEFROM -ZLIB +SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL -PROCCTL +THREAD_DUMP -EVPORTS -OT -QUIC +PROMEX -MEMORY_PROFILING

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.5 5 Jul 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.39 2021-10-29
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

Am I missing something?

**Comment by wtarreau** [comment]
Mmmh strange. Could you check in your stats or logs if the connection was sent from the frontend to the backend ? This makes me think that for whatever reason the use_backend rule didn't match.

**Comment by jean-christophe-manciot** [comment]
> Mmmh strange. Could you check in your stats or logs if the connection was sent from the frontend to the backend ? This makes me think that for whatever reason the use_backend rule didn't match.

As I said, ```a network sniff shows that no communication occurs between haproxy [frontend] and mysql server [backend] (besides the regular checks)```.

Also,
```
# grep -i mysql /var/log/haproxy.log
#
```
and the stats:
```
# echo "show stat" | sudo socat stdio /run/haproxy/admin.sock | grep mysql
mysql,mysql1-kvm,0,0,0,0,,0,0,0,,0,,0,0,0,0,UP,1,1,0,0,0,445,0,,1,6,1,,0,,2,0,,0,L7OK,0,0,,,,,,,,,,,0,0,,,,,-1,,,0,0,0,0,,,,Layer7 check passed,,2,3,4,,,,192.168.122.42:3306,,tcp,,,,,,,,0,0,0,,,0,,0,0,0,0,0,0,0,0,1,1,,-,0,0,0,,,,,,,,,,,,,,
mysql,BACKEND,0,0,0,0,3000,0,0,0,0,0,,0,0,0,0,UP,1,1,0,,0,445,0,,1,6,0,,0,,1,0,,0,,,,,,,,,,,,,,0,0,0,0,0,0,-1,,,0,0,0,0,,,,,,,,,,,,,,tcp,roundrobin,,,,,,,0,0,0,,,,,0,0,0,0,0,,,,,1,0,-,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
```

Finally, if I replace the ```frontend sql``` block to:
```
frontend sql
        bind            :::3306 v4v6
        mode            tcp
        default_backend mysql
        ...
```
and restart haproxy systemd service, the same issue is still there.

**Comment by wtarreau** [comment]
> As I said, a network sniff shows that no communication occurs between haproxy [frontend] and mysql server [backend] (besides the regular checks).

I understood this part but I needed to know for sure whether the rule had matched in the frontend and the connection was lost in the backend or the rule was dropped in the frontend due to the rule not matching (e.g. due to some combinations of local proxies+DNAT rules or whatever that would make the dst_port see something different for example).

> and the stats:
> (...)
Could you please preserve the titles in the future ? It's really unreadable like this, I don't think anyone knows from memory what column to look at :-( But OK I trust that you've verified before copy-pasting this so I'm not going to waste my time redoing that work.

> Finally, if I replace the frontend sql block to:
> 
> frontend sql
>        bind            :::3306 v4v6
>        mode            tcp
>        default_backend mysql
>        ...
>
> and restart haproxy systemd service, the same issue is still there.

OK that definitely confirms the connection is dropped in the backend. Thanks. However it just makes no sense at all given how basic the config is. If you see the checks it means that the IP address is correct and from this point (assuming there aren't any special rules in the backend) there's nothing special with this config that could justify that a connection reaching the backend isn't forwarded to the server.

It will be needed to enable `option tcplog` in the frontend to get the minimum vital information because we're advancing in the dark here. Also I guess you're having timeouts and a few stuff in a defaults section. Could you please share its contents ?

**Comment by jean-christophe-manciot** [comment]
> there's nothing special with this config that could justify that a connection reaching the backend isn't forwarded to the server

There seems to be a misuse of the terms 'frontend' and 'backend' probably on my part which muddies the water.
The architecture is simple: a KVM host hosts 2 VMs:

1. an haproxy VM (which I call the frontend) 
2. a mysql server VM (which I call the backend).

Both VMs communicates correctly in IPv4 regarding the mysql checks triggered by haproxy.
The issue happens when a mysql client call is made from the **host** towards the frontend (haproxy). No subsequent network traffic is triggered (besides the checks) between both VMs (the frontend and the backend).
We would expect the frontend to try to contact the backend as a result of that mysql client call, but that does not happen at all, even at the TCP level.

**Comment by TimWolla** [comment]
Can you provide your HAProxy log excerpt as requested?

And for your next issue, don't ignore the issue template. It's there for a reason.

**Comment by wtarreau** [comment]
> There seems to be a misuse of the terms 'frontend' and 'backend' probably on my part which muddies the water. The architecture is simple: a KVM host hosts 2 VMs:
> 
>     1. an haproxy VM (which I call the frontend)
> 
>     2. a mysql server VM (which I call the backend).

Indeed, I was speaking about the only ones you mentioned in your config excerpt, i.e. the config sections.

> Both VMs communicates correctly in IPv4 regarding the mysql checks triggered by haproxy. The issue happens when a mysql client call is made from the **host** towards the frontend (haproxy). No subsequent network traffic is triggered (besides the checks) between both VMs (the frontend and the backend). We would expect the frontend to try to contact the backend as a result of that mysql client call, but that does not happen at all, even at the TCP level.

So to be clear about the sequence, the client from the host should establish a TCP connection to the VM containing haproxy on port 3306 which should match the IP and port being listened to by the listener configured on the "bind" line of the "sql" frontend. From there, haproxy accepts the connection and executes rules (if any) to know what backend section will process the connection. It's the "use_backend" or "default_backend" rule which does this. Then haproxy uses the parameters and servers found in this "backend" section to select a server to send the connection to.

So these are the possibilities:
  - client from the host cannot even route to the haproxy VM (network traffic from the host in the haproxy VM not confirmed to date)
  - two or more VMs on the same IP address and another one responds to the client on the host
  - single VM but iptables rules loaded on it rejecting incoming connections from the host
  - old process is still bound on the same IP:port and randomly (or always) receives the incoming connections instead of the process you think should process them
  - DNAT rule on the VM makes the destination port appear as different when checked => this one was eliminated by your test with "default_backend", but since it doesn't work better it doesn't prove it's not happening it only proves it is not a single cause.
  - some parameters in a "defaults" section affect the way the frontend handles incoming connection (maybe just a "timeout client 1" or something more subtle)
  - some unmentioned TCP rule in the frontend causes the connection to be rejected (we have to guess since we're only having config excepts)
  - the connection is passed to the backend and some unmentioned TCP rules there reject it
  - some parameters in a "defaults" section affect the way the backend deals with the connection (maybe "timeout server 1" or something more subtle like "dispatch", "transparent", which would route the connection somewhere else, or also "option abortonclose" maybe in some circumstances).
  - a bug in haproxy that would strangely affect exactly this trivial setup an no other similar one (but this does happen, essentially when they're special, hence my second request for the contents of your "defaults" sections).

Thus as you can see there are tons of possibilities and for now due to the lack of information we can only emit lots of hypothesis. This is extremely time-consuming and difficult. And in the end it delays the resolution of your problem.

**Comment by jean-christophe-manciot** [comment]
> Indeed, I was speaking about the only ones you mentioned in your config excerpt, i.e. the config sections.

Then how can you write "OK that definitely confirms the connection is dropped in the backend." when there is zero traffic between the frontend and the backend, even at the TCP level; the backend cannot drop something that it does not receive.

> * client from the host cannot even route to the haproxy VM (network traffic from the host in the haproxy VM not confirmed to date)
> * two or more VMs on the same IP address and another one responds to the client on the host
> * single VM but iptables rules loaded on it rejecting incoming connections from the host
> * old process is still bound on the same IP:port and randomly (or always) receives the incoming connections instead of the process you think should process them

I should have shown right away that it's not possible as the connection is correctly established between the host and the frontend:
![host - frontend](https://user-images.githubusercontent.com/13176858/200333720-8961be5a-7100-4b34-b336-c9fefb0e0b40.png)

> * DNAT rule on the VM makes the destination port appear as different when checked => this one was eliminated by your test with "default_backend", but since it doesn't work better it doesn't prove it's not happening it only proves it is not a single cause.

Are you talking about a NAT rule on the frontend iptables?

> * some parameters in a "defaults" section affect the way the frontend handles incoming connection (maybe just a "timeout client 1" or something more subtle)
> * some parameters in a "defaults" section affect the way the backend deals with the connection (maybe "timeout server 1" or something more subtle like "dispatch", "transparent", which would route the connection somewhere else, or also "option abortonclose" maybe in some circumstances).

Here are some settings from the global & default sections:
```
global
	chroot          /folder
	daemon
	group           haproxy
	log /dev/log	local0
	log /dev/log	local1 notice
	# ~ 5000 TLS connections / GB of RAM
	maxconn         30000
	stats socket    /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout   30s
	# Incompatible with <source> keyword
	###user            haproxy

defaults
        # Defining the load balancing algorithm to be used in a backend
        balance         roundrobin
        # Indicating in what order the servers' address should be resolved upon startup
        #       - last: address which appears in the state file
        #       - libc: internal resolver (gethostbyname() or getaddrinfo() depending on the operating system
        #       - none: the server should start without any valid IP address in a down state, waiting for the situation to get fixed later
	default-server  init-addr libc,last,none
	log	        global
	# Using all available backup servers instead of just the first one when all normal servers are down
	option          allbackups
	option	        dontlognull
	# Enabling session redistribution in case of connection failure by allowing the proxy to break cookie or ...
	# ... consistent hash based persistence and redistribute them to a working server
	option          redispatch
	# Full transparent mode
	# Connect to the server farm from the client's source address
	source          0.0.0.0 usesrc clientip
        timeout connect 5s
        timeout client  5s
        timeout http-request 5s
        timeout server  5s
```

> * some unmentioned TCP rule in the frontend causes the connection to be rejected (we have to guess since we're only having config excepts)

I removed all other settings from the frontend section, so you know it all.

> * the connection is passed to the backend and some unmentioned TCP rules there reject it

Same, I removed all other settings from the backend section, so you know it all.

**Comment by jean-christophe-manciot** [comment]
@TimWolla 
> Can you provide your HAProxy log excerpt as requested?

I have added ```option tcplog``` in the frontend section, but nothing is logged.

**Comment by jean-christophe-manciot** [comment]
I have just discovered the following in the journalctl log which appears for each mysql call from the host to the frontend:
```
[ALERT]    (1313626) : Cannot bind to tproxy source address before connect() for backend mysql. Aborting.
```
which is strange because on the frontend, there is:
```
# netstat -tunpevaW | grep haproxy
tcp6       0      0 :::3306                 :::*                    LISTEN      0          4990210    1431795/haproxy
```

It looks like haproxy tries to bind a second time each time the host contacts the frontend.

**Comment by jean-christophe-manciot** [comment]
Even better where 192.168.122.109 is the frontend and 192.168.122.42 the backend:
```
# netstat -tunpevaW | grep 3306
tcp6       0      0 :::3306                 :::*                    LISTEN      0          4990210    1431795/haproxy     
tcp        0      0 192.168.122.109:35484   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:35488   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:35498   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:35500   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:36304   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:36312   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:36328   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:36336   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:36342   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:42770   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:42780   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:42798   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:42800   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:50826   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:50842   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:50860   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:50864   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:59588   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:59602   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:59614   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:63690   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:63702   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:63704   192.168.122.42:3306     TIME_WAIT   0          0          -                   
tcp        0      0 192.168.122.109:63720   192.168.122.42:3306     TIME_WAIT   0          0          -                   
```

**Comment by capflam** [comment]
You are trying to connect to your mysql, listening in IPV4, from an IPV6 source address. If you remove `source ...` line, this will work as expected.

**Comment by TimWolla** [comment]
Christopher likely already gave the correct answer to your problem, but:

> There seems to be a misuse of the terms 'frontend' and 'backend' probably on my part which muddies the water.

Yes, there is a continued misuse of the terminology from your side. 'frontend' and 'backend' refer to the configuration blocks with the same name within your HAProxy config (and to the data structure that is internally created from these configuration blocks). I recommend that you have a look at HAProxy's starter guide and section 4 of the configuration manual to learn about the terminology: https://docs.haproxy.org/2.4/intro.html / https://docs.haproxy.org/2.4/configuration.html#4.

What you are referring to as "backend" is better referred to as "the MySQL server" or "the MySQL host" and what you are referring to as "frontend" (which seems to be overloaded to both mean the client and HAProxy itself) is better referred to as "the client" or if you want to refer to the HAProxy host use "the HAProxy host" or "the load balancer".

**Comment by jean-christophe-manciot** [comment]
@capflam 
It turns out you're absolutely right, although I do not understand why for several reasons:
- haproxy listens in IPv4 **and** IPv6 as indicated by ```bind            :::3306 v4v6```
- ```source 0.0.0.0``` uses the default value which makes the system select the most appropriate address to reach its destination without any preference for any address family
- ```usesrc clientip```: since there is no explanation in the [official configuration guide](file:///usr/share/doc/haproxy/html/configuration.html) about the keyword ```clientip```, one can only assume that it covers both address family.

**If the latter points to IPv4 only, I suggest to update the document accordingly**.

**Comment by wtarreau** [comment]
It may cover both address families but if your clients can be both v4 and v6 and the server is v4 only, it's clear that a forced source bind to v6 to connect to v4 cannot work! I think we would need to add a specific error flag in the logs for socket errors. For now you should have "SC" which the doc says that it will correspond to a failure to connect to the server, either because the server rejected the connection or sometimes due it being unreachable. But if we refine this to explicitly have "SE" for example for socket error on the server side during connect(), that could definitely help narrow the issue down. I just suspect that a number of errors will still happen during connect() and not bind().

In any case here we still didn't get any log to figure what was happening so it's not even a matter of lack of precision in the reporting. Maybe indeed we could add a reminder in the doc that trying to use transparent binding cannot work with dual-stack due to the fact that you can't have a source in one family and a destination in another one.

**Comment by capflam** [comment]
I guess we can close this issue. Thanks
