### ISSUE TITLE
Rate Limit Reply Headers

### ISSUE THREAD

**Issue by Fireant456** [haproxy/haproxy#1917]
### Your Feature Request

is there any possibility of sending back details regarding your connection and the rate limit you hit when accessing a resource? Discord does this on their API and we are wanting to have better insight with our API library into rate limits that our users are encountering.
https://discord.com/developers/docs/topics/rate-limits#header-format

### What are you trying to do?

Return detailed information about rate limit parameters in HTTP 429 response headers.

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by TimWolla** [comment]
This does not appear to be a feature request, but a request for help.

As indicated within the Issue Template:

Do **NOT** ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.
 
Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org

---------------

If this is indeed a feature request, then please fill in the issue template correctly and provide additional information/explain your request more clearly.

**Comment by Fireant456** [comment]
Did you click my link and even read my feature request? 

This is a perfectly valid request to implement HTTP 423 response headers including details on HAProxy rate limits.

**Comment by TimWolla** [comment]
> Did you click my link and even read my feature request?

Yes, I did.

> This is a perfectly valid request to implement HTTP 423 response headers including details on HAProxy rate limits.

No, it is not:

- You did not fill in the issue template in full.
- I don't see how the Discord developer documentation is relevant to HAProxy.
- HAProxy does not have a rate limit feature. It has features that can be configured to perform rate limiting. These features can also be used to add arbitrary headers if you want them to do this.

As such: see my previous reply.

**Comment by Fireant456** [comment]
Thank you, saying that this is already possible is a much better response rather than sending me back down a rabbit hole looking for someone to acknowledge my question. I've posted on the forums and in Slack/IRC many times and my questions go largely ignored.

At least after putting up a stink, I get someone confirming it is possible. That is what I wanted, have a nice day.
