### ISSUE TITLE
known condition suspected by cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1941]
### Tool Name and Version

cppcheck

### Code Report

```plain
src/arg.c:185:13: style: Condition 'len==1' is always false [knownConditionTrueFalse]
src/cfgparse.c:2798:22: style: Condition 'numa_cores' is always false [knownConditionTrueFalse]
src/cli.c:2222:7: style: Condition 'ns_nlen' is always false [knownConditionTrueFalse]
src/connection.c:1702:34: style: Condition 'done' is always false [knownConditionTrueFalse]
src/h1_htx.c:356:19: style: Condition '!ret' is always false [knownConditionTrueFalse]
src/h1_htx.c:902:19: style: Condition '!ret' is always false [knownConditionTrueFalse]
src/log.c:3238:13: style: Condition '*size>2' is always true [knownConditionTrueFalse]
src/mworker-prog.c:92:19: style: Condition 'ret==0' is always true [knownConditionTrueFalse]
src/server.c:5871:52: style: Condition '(volatile void*)srv->idle_node.node.leaf_p==NULL' is always true [knownConditionTrueFalse]
src/sock.c:93:24: style: Condition 'accept4_broken=1' is always true [knownConditionTrueFalse]
src/ssl_crtlist.c:819:8: style: Condition 'space' is always false [knownConditionTrueFalse]
src/ssl_crtlist.c:823:8: style: Condition 'space' is always false [knownConditionTrueFalse]
src/ssl_crtlist.c:827:8: style: Condition 'space' is always false [knownConditionTrueFalse]
src/ssl_crtlist.c:774:7: style: Condition 'space' is always false [knownConditionTrueFalse]
src/ssl_crtlist.c:798:7: style: Condition 'space' is always false [knownConditionTrueFalse]
src/ssl_sock.c:4199:15: style: Condition 'entry==lastentry' is always true [knownConditionTrueFalse]
src/ssl_sock.c:2816:14: style: Condition 'i==1' is always true [knownConditionTrueFalse]
src/tools.c:424:8: style: Condition 'i<size' is always true [knownConditionTrueFalse]
src/tools.c:5227:22: style: Condition 'output->data!=old_data' is always false [knownConditionTrueFalse]
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
I'm only focusing on core code (src/*):

> src/arg.c:185:13: style: Condition 'len==1' is always false [knownConditionTrueFalse]

- [x] True

> src/cfgparse.c:2798:22: style: Condition 'numa_cores' is always false [knownConditionTrueFalse]

- [ ] False positive, if USE_CPU_AFFINITY is set (compile time), numa_cores could be != 0

> src/cli.c:2222:7: style: Condition 'ns_nlen' is always false [knownConditionTrueFalse]

- [ ] False positive, if USE_NS is set (compile time), ns_len could be != 0

> src/connection.c:1702:34: style: Condition 'done' is always false [knownConditionTrueFalse]

- [x] True

> src/h1_htx.c:356:19: style: Condition '!ret' is always false [knownConditionTrueFalse]

- [ ] False positive, ret could be == 0 in this context

> src/h1_htx.c:902:19: style: Condition '!ret' is always false [knownConditionTrueFalse]

- [ ] False positive, same as above

> src/log.c:3238:13: style: Condition '*size>2' is always true [knownConditionTrueFalse]

- [x] True, potential BUG here, because `p` is incremented but `size` is not updated

> src/mworker-prog.c:92:19: style: Condition 'ret==0' is always true [knownConditionTrueFalse]

- [ ] False positive, seems like cppcheck is not aware of fork() behavior

> src/server.c:5871:52: style: Condition '(volatile void*)srv->idle_node.node.leaf_p==NULL' is always true [knownConditionTrueFalse]

- [ ] False positive, value is volatile so it's expected to be changed by other threads.

> src/sock.c:93:24: style: Condition 'accept4_broken=1' is always true [knownConditionTrueFalse]

- [ ] False positive, this is an inline assignment within a conditional if here, not a check

> src/ssl_crtlist.c:819:8: style: Condition 'space' is always false [knownConditionTrueFalse]
> src/ssl_crtlist.c:823:8: style: Condition 'space' is always false [knownConditionTrueFalse]
> src/ssl_crtlist.c:827:8: style: Condition 'space' is always false [knownConditionTrueFalse]

- [ ] False positive, space can be incremented (not 0) if `OPENSSL_NPN_NEGOTIATED` or `TLSEXT_TYPE_application_layer_protocol_negotiation` are set

> src/ssl_crtlist.c:774:7: style: Condition 'space' is always false [knownConditionTrueFalse]

- [x] True but not an issue, copy pasted code probably

> src/ssl_crtlist.c:798:7: style: Condition 'space' is always false [knownConditionTrueFalse]

- [ ] False positive, space can be > 0 if `OPENSSL_NPN_NEGOTIATED` is set

> src/ssl_sock.c:4199:15: style: Condition 'entry==lastentry' is always true [knownConditionTrueFalse]

- [ ] False positive, entry is set by list_for_each_entry()

> src/ssl_sock.c:2816:14: style: Condition 'i==1' is always true [knownConditionTrueFalse]

- [ ] False positive, for loop is used, i goes from 0 to 1

> src/tools.c:424:8: style: Condition 'i<size' is always true [knownConditionTrueFalse]

- [x] Edit: True, no bug but extra check, here `i<size` if always true

> src/tools.c:5227:22: style: Condition 'output->data!=old_data' is always false [knownConditionTrueFalse]

- [ ] False positive, output->data may be updated by `dl_dump_libs_cb()` callback.

**Comment by Darlelet** [comment]
>src/log.c:3238:13: style: Condition '*size>2' is always true [knownConditionTrueFalse]
True, potential BUG here, because p is incremented but size is not updated

This patch should fix this:
[0001-BUG-MINOR-log-fix-parse_log_message-rfc5424-size-che.patch.txt](https://github.com/haproxy/haproxy/files/10066508/0001-BUG-MINOR-log-fix-parse_log_message-rfc5424-size-che.patch.txt)

---------------------------------------

For other known conditions (not bugs):

>src/arg.c:185:13: style: Condition 'len==1' is always false [knownConditionTrueFalse]
True

See attached patch:
[0001-CLEANUP-arg-remove-extra-check-in-make_arg_list-arg-.patch.txt](https://github.com/haproxy/haproxy/files/10066632/0001-CLEANUP-arg-remove-extra-check-in-make_arg_list-arg-.patch.txt)


>src/tools.c:424:8: style: Condition 'i<size' is always true [knownConditionTrueFalse]
Edit: True, no bug but extra check, here i<size if always true

See attached patch: 
[0001-CLEANUP-tools-extra-check-in-utoa_pad.patch.txt](https://github.com/haproxy/haproxy/files/10066558/0001-CLEANUP-tools-extra-check-in-utoa_pad.patch.txt)


>src/connection.c:1702:34: style: Condition 'done' is always false [knownConditionTrueFalse]
True

Won't fix, because if flag printing is reordered in future commit, it could be the source of a new bug.



>src/ssl_crtlist.c:774:7: style: Condition 'space' is always false [knownConditionTrueFalse]
True but not an issue, copy pasted code probably

Won't fix, because if crtlist dumps are reordered, this could lead to a new bug.

**Comment by capflam** [comment]
Thanks @Darlelet, patches were merged !

**Comment by chipitsine** [comment]
should I close this or it will wait for backporting ?

**Comment by capflam** [comment]
No, we can close it. Backports will be handled as usual. Thanks !
