### ISSUE TITLE
Have a method to escape "]", ")" and "," in regsub

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#200]
## Output of `haproxy -vv` and `uname -a`

```
$ haproxy -vv
HA-Proxy version 1.8.20 2019/04/25
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label
  OPTIONS = USE_LIBCRYPT=1 USE_CRYPT_H=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_SYSTEMD=1 USE_PCRE=1 USE_PCRE_JIT=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2n  7 Dec 2017
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.38 2015-11-23
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace

$ uname -a
Linux <redacted> 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## What should haproxy do differently? Which functionality do you think we should add?

I would like to be able to use capture groups and character classes in the regular expressions used in the regsub converter.

Currently, the documentation states:

> It is important to note that due to the current limitations of the configuration parser, some characters such as closing parenthesis, closing square brackets or comma are not possible to use in the arguments. The first use of this converter is to replace certain characters or sequence of characters with other ones.

Howerver, that prevents the usage of character classes and capture groups. As far as I can tell, there isn't any way to escape these characters in the regex.

## What are you trying to do?

I specifically ran into this while trying to use regsub to transform the path i a `http-requests set-path` operation. In that particular case, I can continue to use reqrep in 1.8, and use `replace-uri` when I upgrade to 2.0. However, there are still cases where that won't work. For example if regsub is used in the expression with `http-request set-var` or if it is part of a chain with multiple converters.

**Comment by lukastribus** [comment]
Also see:
https://www.mail-archive.com/haproxy@formilux.org/msg29345.html

Request comes up periodically about this:
https://discourse.haproxy.org/t/how-to-use-in-a-regsub-converter-inside-a-log-format/4109
https://discourse.haproxy.org/t/mask-sensitive-data-in-logs/4250

This is really something we ought to implement/fix.


A [workaround in LUA has been posted](https://discourse.haproxy.org/t/mask-sensitive-data-in-logs/4250/4) in the thread above.

**Comment by wtarreau** [comment]
I agree. And I feel frustrated not to find a short-term solution involving
an escape mechanism that would *not* break any existing config. The least
troubling I could think of would be to pass \, in the argument and let the
converter parser unescape it, except that in order to pass this you'd
actually have to pass it this way : "\\\,", which is all but intuitive. I
also thought that we could decide that backslashes are not resolved inside
quotes for example, but this would also cause some breakage. We probably
need to sort this out while keeping an eye on regex back-references to be
sure not to break anything, since I think that's the other place where such
escapes are used. I'm really opened to any idea on the subject.

Willy

**Comment by rbjorklin** [comment]
We're also hitting this issue and it became very apparent with the removal of `reqrep` etc. in the 2.1 release. We are now blocked from upgrading.

**Comment by TimWolla** [comment]
> We're also hitting this issue and it became very apparent with the removal of `reqrep` etc. in the 2.1 release. We are now blocked from upgrading.

@rbjorklin You should be able to do everything reqrep did with `http-request replace-uri / replace-header / replace-value`.

**Comment by rbjorklin** [comment]
> > We're also hitting this issue and it became very apparent with the removal of `reqrep` etc. in the 2.1 release. We are now blocked from upgrading.
> 
> @rbjorklin You should be able to do everything reqrep did with `http-request replace-uri / replace-header / replace-value`.

Even the matching groups that are specifically called out in this issue? We're currently using them for some of our more exotic url rewrites.

**Comment by TimWolla** [comment]
> Even the matching groups that are specifically called out in this issue?

Of course. In fact there are even examples in the documentation: http://cbonte.github.io/haproxy-dconv/2.1/configuration.html#4.2-http-request%20replace-uri

**Comment by rbjorklin** [comment]
This does indeed seem to work, thanks for pointing me in the right direction!

**Comment by tmccombs** [comment]
I just ran into a specific case where `replace-uri / replace-header / replace-value` does not work. I want to use a regex replacement with capture group in a `http-request redirect`.

**Comment by git001** [comment]
@tmccombs please can you share some examples what you want to do and what should happen

**Comment by tmccombs** [comment]
Sure one specific example is I wanted to do something like this:

```
http-request redirect location %[url,regsub(/($|?),\1)] code 301 if { path_reg ^/prefix/.*/$ }
```
in order to redirect to remove a trailing slash. It's possible to do with using two separate rules (one if there is a query string and one if there isn't). but it is more complicated.

**Comment by wtarreau** [comment]
I'm all for finding a solution to this, but to date we didn't find one. We'll **need** to break **some** existing configurations whatever the solution we find. And that bothers me because I'm pretty sure that even that final solution will be far from being perfect, and that its limitations will piss off a number of users who in addition will have to walk through very tricky changes in their config.

At some point I imagined we could simply reuse the '\' but that will basically break all regex and groups. Then I though we could have a different escape character, but looking on my keyboard I failed to find one that nobody uses.

Ideally the best way to address this is to have a real parser for arguments (an in-depth one, not a left-to-right one) and that's what ought to break the least setups, but it will require massive code changes, and will significantly affect the error message processing :-/

I'm still open to ideas however, I'm sure not all solutions have been explored. But clearly, when weighing the risks of pissing everyone off, I strongly prefer the full parser rewrite because it's durable, than a dirty hack that will last 2 more years and piss off even more people after.

**Comment by TimWolla** [comment]
> We'll **need** to break **some** existing configurations whatever the solution we find.

Would a “comment” indicating the parser / config format version be a viable solution? I'm thinking about something similar to `"use strict";` in JavaScript. As an example: If the config file starts with `#V=2\n` then the “new” parser will be used, possibly allowing `#V=1\n` to explicitly select the old one and switch the default after a few versions.

**Comment by TimWolla** [comment]
> At some point I imagined we could simply reuse the '' but that will basically break all regex and groups. Then I though we could have a different escape character, but looking on my keyboard I failed to find one that nobody uses.

@wtarreau  Note that the markdown ate the backslash there. Use backticks to indicate "literal code": `\`.

**Comment by wtarreau** [comment]
Versioning a config only works if you do it from the start. A lot of deployments last more than 3 years and continue to evolve, so versioning a config is in fact putting the burden on the code side by having two versions to maintain forever. Regarding the backslash and markdown, thanks for the hint, it simply proves that escaping characters is not an isolated issue :-)

**Comment by wtarreau** [comment]
Actually I might have another idea which wouldn't break existing configs :-)

Since we've added support for single- and double- quotes, we've also added the ability to refine the evaluation within double quotes (environment variables are only evaluated there for example), and to
keep single-quoted strings as raw strings. We do also support enclosing single quotes inside double quotes. And that's the trick we should exploit. By modifying the argument parser, we could recursively use the quotes so that the argument parser itself could use quotes as delimiters for its arguments. This means we could have something like `location "%[url,regsub('/($|?)','\1')]"` and now there's no surprise anymore. Note the double quotes around the outer word to prevent the inner ones from being resolved first.

I don't think we have *that* many argument parsers, I think we might have one for actions and one for sample expressions, split into sample fetch and converters. That's definitely something which sounds reasonable and would come with the least surprize. Furthermore the parser could possibly detect parenthesis or braces inconsistencies and suggest to fix them using quotes in the error message.

What *needs* to be done is to make sure that we can recursively escape the backslash, like in shell, so that it's always possible to place a single quote within such a string.

I'll have a deeper look into this.

**Comment by wtarreau** [comment]
Good news guys, I managed to do this, while staying backwards compatible :-)

For example, this now works even without quoting because it's non-ambigous:
```
http-request set-header x-query "%[query,regsub([?;&]*,'')]"
```
This is also possible using double-quoting or quotes+backslashes:

```
tcp-request session set-var(txn.ipport) "str(),concat('addr=(',sess.ip),concat(',',sess.port,')')"
```

The principle is that it's always the lower-level function which parses as far as it can go so we can finally nest brackets and parenthesis. When facing characters like ')' or ',' where an argument delimiter is expected, these ones continue to be an argument delimiter, but if you want to make them part of the argument, they need to be enclosed in quotes. Note that the top-level parser already resolves quotes when it groups words, so in practice you need two levels of quotes as mentioned above (or one level where quotes are backslahed).

Please update to commit cd0d2ed6 to get all this.

I also (re-)discovered that regsub() doesn't support back-references. After all that made sense, since it was not possible to pass parenthesis to define the groups. That's something that would really deserve being done, I think it's not difficult, it's just that I haven't looked into it. This way we could finally freely transform random parts using regex a-la-sed.

**Comment by wtarreau** [comment]
Also I intend to add a section to the config documentation with a BNF of the config syntax, that would clearly help there! It'll just take quite some extra time.

**Comment by TimWolla** [comment]
@wtarreau I believe this one can be closed, no?

**Comment by wtarreau** [comment]
It could but then we'd lose the "add BNF to the config doc". Or we may open a new one with only that last part and close this one, it would be cleaner.

**Comment by TimWolla** [comment]
> Or we may open a new one with only that last part and close this one, it would be cleaner.

Okay, I've used GitHub's “reference in new issue” button to create a new issue. Closing this one now.

**Comment by Roxyrob** [comment]
How this solution resolve following cases:

```
http-request set-path "%[path,regsub(^/mypath(/|$),/)]"
```
or
```
http-request set-path "%[path,regsub(^/mypath$,/)]"
```

we get

```
"Variable expansion: Unrecognized character ')' in variable name."
```
for the first as "$" will be always variable expanded as "$)". For the second one as "$,"

**Comment by wlallemand** [comment]
It's unrelated, use the single-quotes instead of the double-quotes in your case. So the $ won't be expanded.

**Comment by Roxyrob** [comment]
I just tried single-quote and I get:

```
http-request set-path '%[path,regsub(^/mypath(/|$),/)]'

'http-request set-path' rule : failed to parse sample expression <path,regsub(^/mypath(/|$),/)> : invalid arg 2 in converter 'regsub' : missing arguments (got 1/2), type 'string' expected.
```
Instead
```
http-request set-path '%[path,regsub(^/mypath$,/)]'
```
Doesn't seems to correctly tell regsub to interper $ as end of line.

Tried also single quote internally "%[path,regsub('^mypath(/|$)',/)" with same error. Cannot escape $ or get error for regsub.

As now the only working rule was
```
http-request set-path '%[path,regsub(^/mypath/,/)]'
```
not managing url /mypath and without $ naturally all url starting with /mypath will match

**Comment by tmccombs** [comment]
I think you need the quotes inside the function call, like:

```
http-request set-path %[path,regsub('^/mypath(/|$)',/)]
```

**Comment by Roxyrob** [comment]
Hi @tmccombs 
As stated I tried many syntax variations without success. Also single-quote as you suggested:

```
http-request set-path %[path,regsub('^/mypath(/|$)',/)]
```

returns

```
'http-request set-path' rule : failed to parse sample expression <path,regsub(^/mypath(/|$),/)> : invalid arg 2 in converter 'regsub' : missing arguments (got 1/2), type 'string' expected.
```

**Comment by ashrash** [comment]
Hi I have a similar issue,

I need to escape a '?'. has anyone tried it ?

**Comment by wtarreau** [comment]
I can't figure why the single qute doesn't work to escape the string in your example above, however I got it to work with double quotes outside and single quote around the arguments (sadly the only examples involving regsub in the doc use it the other way around, wihch doesn't prevent the '$' from being evaluated). I need to better explain in the doc how parsing is done.

```
	http-request set-path '%[path,regsub("^/mypath(/|$)","/")]'
```

**Comment by TimWolla** [comment]
> I need to better explain in the doc how parsing is done.

see also: #712

**Comment by Roxyrob** [comment]
Hi @wtarreau,
on what haproxy version you got your example to work ? Eventually what is the min version supporting that ?

**Comment by wtarreau** [comment]
I did it on 2.2 to 2.4-dev. It changed with 2.2 to a top-down parser instead of left-right so that parenthesis, brackets and commas are finally supported in arguments.

**Comment by Roxyrob** [comment]
Ok, on 2.3.1 it is working with external single and internal double quotes

```
http-request set-path '%[path,regsub("^/mypath(/|$)","/")]'
```

Not working this (with external single quotes only)

```
http-request set-path '%[path,regsub(^/mypath(/|$),/)]'

```

Also, the first one seems correctly parsed but the regex correctly change "/mypath" to "/" but not seem to change "/mypath/" to "/" leaving "/mypath/". Am I doing something wrong ?

**Comment by Roxyrob** [comment]
I am sorry my mistake, regex with (/|$) seems to work, I'll do more testing to be sure.

Thank you a lot

**Comment by wtarreau** [comment]
FYI I'm currently writing the doc section explaining how the config parser works and who quotes and escapes must be used. It's almost done, this will significantly help because we all get into trouble once in a while there.

**Comment by wtarreau** [comment]
should be OK now with he fix above (we can still improve it, of course).

**Comment by Roxyrob** [comment]
Thank you @wtarreau

Regex are rarely a simple matther unfortunately... documentation are always welcome.

Also we meet 2 troubles, if you could help would be appreciated as we cannto find real solutions:

1. Upgrade to 2.3.1 from 1.8.2 with same haproxy configuration introduced "SSL handshake failure" for Win7 clients. We do not find niformation on documentation/release notes. It was disabled by default tls1.0, or same chiper suite as insecure ? Or compiling with old version nof openssl (like OpenSSL 1.0.2k-fips can do that also if compiling and haproxy -vv didn't retun errors)

2. Can haproxy log rewritten request (as sent to backend) to simply test regex without complex distributed multiple backends tcpdump + multiple active haproxy log analysis ?

**Comment by wtarreau** [comment]
For question 1, please open a new issue if you don't find this one addressed in an existing one.

For Q2, there are solutions. One of them is the `debug` converter which can emit the output to stdout or to a ring that you consult on the CLI. It passes the input to the output unmodified and duplicates it to the output. We could have called it "tee" :-)  In your case you could for example do this:
```
http-request set-path '%[path,debug(before,stdout),regsub(^/mypath(/|$),/),debug(after,stdout)]'
```
Then you run haproxy in foreground and will see lines prefixed with "before" and "after". When `stdout` is not specified, this will be sent to `ring0` which you can check on the CLI using `show events ring0`.

Instead of debug, you can also use `set-var` to set the input and output contents into a variable, and put them both where you want to use them and into a specific header.

One thing I'm doing all the time is to abuse the `redirect` action because it's trivial to test:
```
http-request redirect location '%[path,regsub(^/mypath(/|$),/)]'
```
Then I use `curl -v 127.1:8000/` and can check the `location` header in the response to check whether my rule worked. That's my preferred method for debugging but others are free not to like it :-)

And I would like to add an expression evaluator on the CLI. For example we could have:
```
> eval 'str("/path/to/file"),regsub(^/mypath(/|$),/)'
````
and see the output. But it would not be trivial to 100% respect the same parser as the config's, though once quoted it should be similar enough and convenient to test regex.

**Comment by Roxyrob** [comment]
Thank you @wtarreau,

The first solution works, I see "before" and "after" variables content in debug mode:
```
   [debug] before: type=str </mypath>
   [debug] after: type=str </>
```
I Tried second solution without success, setting

```
http-request set-path '%[path,regsub("^/mypath(/|$)","/")]'
```

curl -L -v http://test1.example.com/mypath returns

(curl)
```
GET /mypath HTTP/1.1
User-Agent: curl/7.29.0
Host: test1.example.com
Accept: */*

HTTP/1.1 301 Moved Permanently
content-length: 0
location: https://test1.example.com/mypath
```

So I see only the "before" format request , cannot see "after" forma request (as sent to backends). Using tcpdump on backend the regex works as no /mypath arrives on backend:

(tcpdump)
```
GET / HTTP/1.1
host: test1.example.com
pragma: no-cache
...
```

I don't know haproxy internals and I undertand probably there are real troubles to use normal log for "after" request info Anyhow it would be a great improvement, allowing request/response manipulation troubleshoting much easier and faster , avoid to remove haproxy nodes from clusters, change hosts mapping for real domains requests, stopping haproxy service, running standalone in debug mode, etc. Potencially modifying configurations and introducing issue when reactivated in clusters or imposing testing cycles on isolated test environments different from targets one.

Thank you anyway ! Haproxy is a great software.

**Comment by jamshid** [comment]
FWIW this is a hacky workaround to allow regsub() to url escape a comma. Normally a comma can't be used with regsub() because the haproxy.cfg parser reports `invalid arg 3 in converter 'regsub' : expected ')' before ',g)]'`.

```
backend www-backend
         # Replace range of characters to change comma. "+" should already be encoded but "-" should be sent as-is.
         http-request set-path %[path,regsub('[+]','%2B',g)]
         http-request set-path %[path,regsub('[-]','%2D',g)]
         http-request set-path %[path,regsub('[+--]','%2C',g)]
         http-request set-path %[path,regsub('%2D','-',g)]
```

**Comment by lapo-luchini** [comment]
> Ok, on 2.3.1 it is working with external single and internal double quotes

THANKS!!!!! I would have never ever gonna try that by myself…
