### ISSUE TITLE
TLS 1.0

### ISSUE THREAD

**Issue by jhartleycaw** [haproxy/haproxy#208]
Has TLS1.0 been removed from v2? 

I can upgrade from 1.9, but all my Outlook 2016 on W7 clients stop working, and this is usually a TLS1.0 problem. 

I can't find anything in the changelog, but thought I would ask,

Thanks

**Comment by lukastribus** [comment]
No, it hasn't, and this is not a bug.

Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
