### ISSUE TITLE
src/applet.c: resource leak suspected by coverity

### ISSUE THREAD

**Issue by shipitsin-ilia** [haproxy/haproxy#2086]
### Tool Name and Version

coverity

### Code Report

```plain
*** CID 1506910:  Resource leaks  (RESOURCE_LEAK)
/src/applet.c: 80 in appctx_new_on()
74     
75       fail_task:
76      sedesc_free(appctx->sedesc);
77       fail_endp:
78      pool_free(pool_head_appctx, appctx);
79       fail_appctx:
>>>     CID 1506910:  Resource leaks  (RESOURCE_LEAK)
>>>     Returning without freeing "sedesc" leaks the storage that it points to.
80      return NULL;
81     }
82     
83     /* Finalize the frontend appctx startup. It must not be called for a backend
84      * appctx. This function is responsible to create the appctx's session and the
85      * frontend stream connector. By transitivity, the stream is also created.
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
Nice catch, this is due to this new commit: https://github.com/haproxy/haproxy/commit/465a6c850629bd1fbbecb028af631ff81bd09e11

`fail_task` step should perform the free on `sedesc` instead of `appctx->sedesc`

Here is the redacted patch that restores original behavior:
[0001-BUG-MINOR-applet-free-sedesc-on-task-failure.patch.txt](https://github.com/haproxy/haproxy/files/11037793/0001-BUG-MINOR-applet-free-sedesc-on-task-failure.patch.txt)


While we're at it: is it expected that `sedesc` upvalue is not freed in the `fail_appctx` cleanup step?

**Comment by Darlelet** [comment]
Or should sedesc cleanup be conditional?
(do the cleanup if sedesc was allocated within the function, else skip the cleanup if sedesc was provided)

**Comment by capflam** [comment]
Indeed, the sedesc must only be released if it was allocated locally. The sedesc passed as parameter, if not null, must not be released on error.  Another way to fix the issue is to allocate the task first and release it if we fail to allocate the sedesc. This way there is no ambiguity about the sedesc origin.

**Comment by Darlelet** [comment]
>  Another way to fix the issue is to allocate the task first and release it if we fail to allocate the sedesc. This way there is no ambiguity about the sedesc origin.

+1 for this cleaner approach that fixes both issues at the same time (since prior to https://github.com/haproxy/haproxy/commit/465a6c850629bd1fbbecb028af631ff81bd09e11 provided sedesc could still be freed in the case the task failed to allocate)

Do you want me to do it?

**Comment by capflam** [comment]
I never refuse this kind of proposal :) Go ahead !

**Comment by Darlelet** [comment]
Here you go captain!
[0001-BUG-MINOR-applet-new-fix-sedesc-freeing-logic.patch.txt](https://github.com/haproxy/haproxy/files/11061453/0001-BUG-MINOR-applet-new-fix-sedesc-freeing-logic.patch.txt)

**Comment by capflam** [comment]
Thanks, pushed now !
