### ISSUE TITLE
src/jwt.c: failed to build when openssl deprecated features disabled

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2098]
### Tool Name and Version

gcc

### Code Report

```plain
build with "-DOPENSSL_API_COMPAT=0x10100000L -DOPENSSL_NO_DEPRECATED" fails


  CC      src/ssl_ocsp.o
src/jwt.c: In function ‘jwt_jwsverify_rsa_ecdsa’:
src/jwt.c:283:23: error: ‘RSA_PKCS1_PADDING’ undeclared (first use in this function)
  283 |         int padding = RSA_PKCS1_PADDING;
      |                       ^~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:988: src/jwt.o] Error 1
make: *** Waiting for unfinished jobs....

CI build: https://github.com/haproxy/haproxy/actions/runs/4559243824/jobs/8042986820#step:4:24
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by rlebreton** [comment]
Thanks for your report. I feared that I ended up using a deprecated mechanism when implementing RSAPSS in jwt but it appears that the problem is only a missing include. Here's a patch that fixes the compilation.
[0001-BUG-MINOR-ssl-Undefined-reference-when-building-with.txt](https://github.com/haproxy/haproxy/files/11136771/0001-BUG-MINOR-ssl-Undefined-reference-when-building-with.txt)
