### ISSUE TITLE
关于我在docker-compose使用haproxy:lts时遇到的sysctl "net.core.somaxconn" not allowed in host network namespace问题

### ISSUE THREAD

**Issue by MoliZhaoCn** [haproxy/haproxy#2108]
我的配置文件是这样的：
<img width="531" alt="image" src="https://user-images.githubusercontent.com/98500980/230585781-df7eb073-76b9-4ea2-a566-d0b812d09a09.png">
在我使用docker-compose启动时出现了以下问题：
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: sysctl "net.core.somaxconn" not allowed in host network namespace: unknown
根据错误提示，我推测是因为namespace的net.core.somaxconn出现了问题，但是我没有找到解决办法

**Comment by wtarreau** [comment]
This is not a way to report an issue. Please use and respect the template.

**Comment by MoliZhaoCn** [comment]
> This is not a way to report an issue. Please use and respect the template.
谢谢您的提醒，我想问一下，像这种问题我应该提交一个怎样的issues，谢谢您的回答，不胜感激

**Comment by wtarreau** [comment]
Please, English is the only language used here. There is no way you will get help if you don't speak English and don't respect the issue template by explaining your problem, your config etc. (For others, the message above says "Thank you for your reminder, I would like to ask, what kind of issues should I submit for this kind of question, thank you for your answer, I am very grateful"). I don't know what your problem is, I don't read Chinese and don't know what the screenshot above shows. By the way please don't send screenshots for files, but copy-paste them instead, it allows members to comment and/or search for some parts instead of having to retype them entirely.

**Comment by MoliZhaoCn** [comment]
> 



> Please, English is the only language used here. There is no way you will get help if you don't speak English and don't respect the issue template by explaining your problem, your config etc. (For others, the message above says "Thank you for your reminder, I would like to ask, what kind of issues should I submit for this kind of question, thank you for your answer, I am very grateful"). I don't know what your problem is, I don't read Chinese and don't know what the screenshot above shows. By the way please don't send screenshots for files, but copy-paste them instead, it allows members to comment and/or search for some parts instead of having to retype them entirely.

OK, thank you, I will take your opinion and change the way I ask questions, thank you, I am sorry to bring you trouble.
