### ISSUE TITLE
src/server.c: unused value suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2162]
### Tool Name and Version

coverity

### Code Report

```plain
5535                                }
5536                                free_trash_chunk(tmptrash);
    CID 1509239 (#6 of 6): Unused value (UNUSED_VALUE)assigned_pointer: Assigning value NULL to tmptrash here, but that stored value is overwritten before it can be used.
5537                                tmptrash = NULL;
5538                        }
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by Darlelet** [comment]
Well this one is very old! Nothing to worry about here.

Maybe coverity is reporting this as a new one because of the various code refacto around `srv_update_status()` function (ie: f71e0645c1ad777f111c173d47697e2a65980077): some code was moved around, coverity could be thinking that this is new code, but the printing logic wasn't touched.

However it could be relevant to come up with a cleanup that removes `tmptrash = NULL` assignments since `chunk_{printf,appendf}()` doesn't even check for the buffer argument being non NULL. Moreover, within `srv_update_status()` all dumping attempts are performed within code blocks that already ensure that tmptrash isn't NULL, so this is not very useful anyway.

**Comment by Darlelet** [comment]
FWIW, here is a patch that removes such "unused" assignments:
[0001-CLEANUP-server-remove-useless-tmptrash-assigments-in.patch.txt](https://github.com/haproxy/haproxy/files/11479870/0001-CLEANUP-server-remove-useless-tmptrash-assigments-in.patch.txt)

While doing this I also found a 2.8 specific memory leak which was introduced with f71e064 (a free was removed by error during the refacto).
Sorry for the inconvenience! Please find the corresponding fix below:
[0002-BUG-MINOR-server-memory-leak-in-_srv_update_status_o.patch.txt](https://github.com/haproxy/haproxy/files/11479871/0002-BUG-MINOR-server-memory-leak-in-_srv_update_status_o.patch.txt)

**Comment by capflam** [comment]
Both merged. Thanks !
