### ISSUE TITLE
cache try to allocate memory when checking config (-c)

### ISSUE THREAD

**Issue by aderumier** [haproxy/haproxy#217]
Hello,

I have a 2.0 server with cache configured to 4GB, server have 6GB memory.

I can't use haproxy -c to test config, when haproxy is already running, because in this case I need 8GB minimum. (4GB for running haproxy and 4GB for haproxy -c).

Maybe it could be great to not try to allocated memory when -c is used to check config.

**Comment by wtarreau** [comment]
I think it makes sense. -c is mostly used to check the config's validity, not whether or not it will run in a given environment. So if we can allocate the cache later in the startup process it would be great.

**Comment by wlallemand** [comment]
@aderumier This patch should solve your problem, however you can still have the problem during a reload since the cache is not shared between an old and a new worker.

[0001-BUG-MINOR-cache-alloc-shctx-after-check-config.patch.txt](https://github.com/haproxy/haproxy/files/3551178/0001-BUG-MINOR-cache-alloc-shctx-after-check-config.patch.txt)

**Comment by capflam** [comment]
A modified version of this patch has been pushed and backported to 2.0 and 1.9. But note it only avoids allocation during config check. So during reload the problem remains. You need twice the cache size available.

For the record, the commit id is d1d1e2294.
