### ISSUE TITLE
build failed on Fedora Rawhide / clang 16.0.5

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2193]
### Tool Name and Version

clang 16.0.4

### Code Report

```plain
src/debug.c: In function 'debug_iohandler_fd':
src/debug.c:1387:39: error: argument 2 null where non-null expected [-Werror=nonnull]
 1387 |                                       epoll_wait(fd, NULL, 0, 0) != -1 || errno != EBADF ? "epol":
      |                                       ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make: *** [Makefile:998: src/debug.o] Error 1
```

### Output of `haproxy -vv`

```plain
no
```

**Comment by wtarreau** [comment]
This one is in fact related to the libc and not the compiler. They've apparently tagged the syscall to mention that some fields may not be null. I despise doing this for syscalls because the system performs these checks which are documented and result in various errno values that we can check. But the trend of protecting developers from their own code leads to this.

Where this test is done we can't easily have a dummy local variable, and we certainly don't want to risk to poll for real! Would you be able to test either with `(void *)1` or preferably with `DISGUISE(NULL)` instead of NULL ? Both will do what we want anyway, with the latter also allowing the libc to remap the call to another syscall if needed, while checking for the pointer's validity.

**Comment by chipitsine** [comment]
both `(void *)1` and `DISGUISE(NULL)` convince clang.

**Comment by wtarreau** [comment]
On Fri, Jun 30, 2023 at 02:02:34PM -0700, Ilya Shipitsin wrote:
> both `(void *)1` and `DISGUISE(NULL)` convince clang.

Many thanks Ilya, I'll likely use the second one then since it's cleaner.

**Comment by wtarreau** [comment]
Should be OK now. Finally I changed the method to use epoll_ctl() instead. It will be more accurate and will be sure not to trigger a problem in the libc if it decides to remap the syscall internally.
