### ISSUE TITLE
HAProxy doesn't provision ingress ip address

### ISSUE THREAD

**Issue by simonebenati** [haproxy/haproxy#2215]
### Detailed Description of the Problem

In my rke2 cluster v1.25.9+rke2r1 . I am running it on openstack vms (baremetal).

I am running Metallb, calico as my cni and haproxy as my ingress controller.
What my goal is, is to expose a grafana dashboard to the outside via ingress.
When I try to provision the ingress no ip address gets assigned and therefore the dasbhoard is unreachable.

If I repeat the same process via nginx everything works. But I need HAProxy.

### Expected Behavior

I expect the ip addresses to be provisioned and therefore my dashboard to be reachable from the outside.

### Steps to Reproduce the Behavior

1. Install Metallb working in l2. Therefore install the l2advertisement cr and the ip address pool cr.
2. Install Haproxy via helm with the following helm value file enabling the handling of tcp traffic because i need it for another ingress later:
[values.yml.txt](https://github.com/haproxy/haproxy/files/12041105/values.yml.txt)
3. install prometheus operator via helm and enable ingress for grafana applying the ingressclassname of haproxy
4. check for the ingress ip address not being provisioned

### What is your configuration?

```haproxy
Openstack public cloud
Rancher2 v1.25.9+rke2r1
Metallb v0.13.10
HAProxy v0.15.0
Prometheus operator latest
```

### Output of `haproxy -vv`

```plain
Where do I have to run this command? inside the pod?
```

**Comment by lukastribus** [comment]
Sounds like you have an issue with the ingress controller, maybe this one https://github.com/jcmoraisjr/haproxy-ingress ?

Anyway, as indicated in the issue templates, this issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

* The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
* Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
 * Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)
