### ISSUE TITLE
The use of map base modulus method in haproxy

### ISSUE THREAD

**Issue by opencmit2** [haproxy/haproxy#2266]
### Detailed Description of the Problem

Configured haproxy's map based modulus extraction method, but the access results were the same for several different servers

### Expected Behavior

We need to see the true purpose of haproxy's map based modulus taking method

### Steps to Reproduce the Behavior

Configure haproxy's map base modulus method to proxy two backend servers

### What is your configuration?

```haproxy
listen  web_port
 bind 0.0.0.0:80
 mode http
 log global
 balance source
 server web1 0.0.0.0:5678 weight 1 check inter 3000 fall 2 rise 3
 server web2 0.0.0.0:6789 weight 1 check inter 3000 fall 2 rise 3
```

### Output of `haproxy -vv`

```plain
haproxy-1.8
Linux VM-4-11-centos 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by wtarreau** [comment]
I'm sorry but I don't understand what you're trying to do. You're speaking about maps, there are none in your config. Could you please post a config that causes a problem and describe the problem you are observing (and possibly describe why you think what you are observing is a problem) ?

As a side note, keep in mind that haproxy-1.8 is non longer supported, but your config is trivial enough and would work on all versions since 1.2 or so, so it will not matter I think.

**Comment by capflam** [comment]
The issue seems to be inactive, I'm closing.
