### ISSUE TITLE
unknown keyword 'ssl-default-bind-ciphersuites' in 'global' section

### ISSUE THREAD

**Issue by GitCod-Man** [haproxy/haproxy#2299]
### Detailed Description of the Problem

unknown keyword 'ssl-default-bind-ciphersuites' in 'global' section

### Expected Behavior

unknown keyword 'ssl-default-bind-ciphersuites' in 'global' section

### Steps to Reproduce the Behavior

unknown keyword 'ssl-default-bind-ciphersuites' in 'global' section

### What is your configuration?

```haproxy
unknown keyword 'ssl-default-bind-ciphersuites' in 'global' section
```

### Output of `haproxy -vv`

```plain
unknown keyword 'ssl-default-bind-ciphersuites' in 'global' section
```

**Comment by lukastribus** [comment]
You need to recompile with SSL enabled (`USE_OPENSSL=1`).

Use the forum or the mailing list if you have a question rather than a bug or feature request.

* The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [haproxy@formilux.org](mailto:haproxy@formilux.org)
* Subscribe to the list: [haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)
 * Unsubscribe from the list: [haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)
