### ISSUE TITLE
H2 rapid reset aka CVE-2023-44487

### ISSUE THREAD

**Issue by darix** [haproxy/haproxy#2312]
### Detailed Description of the Problem

An issue for tracking how haproxy is affected by CVE-2023-44487

- https://cloud.google.com/blog/products/identity-security/how-it-works-the-novel-http2-rapid-reset-ddos-attack
- https://blog.cloudflare.com/zero-day-rapid-reset-http2-record-breaking-ddos-attack/
- https://blog.cloudflare.com/technical-breakdown-http2-rapid-reset-ddos-attack/

### Expected Behavior

it should not be affected by  CVE-2023-44487 :)

### Steps to Reproduce the Behavior

see cloudflare technical blog

### Do you have any idea what may have caused this?

h2 protocol level bug?

### What is your configuration?

```haproxy
not applicable
```

### Output of `haproxy -vv`

```plain
not applicable
```

**Comment by janl** [comment]
https://www.mail-archive.com/haproxy@formilux.org/msg44134.html

**Comment by wtarreau** [comment]
Some updates and measurements there, along with some rules to avoid log pollution from random attackers that iwll inevitably appear in the next few days:

  https://www.mail-archive.com/haproxy@formilux.org/msg44136.html

So far I failed to harm the process more than with regular traffic (neither CPU nor concurrency).

I will not post my reproducer for now because there's no point in easing the job of hurting various sites for script kiddies. However if anyone has an effective repro that manages to harm haproxy more than with h2load or other regular tools, I'm obviously interested.

**Comment by wtarreau** [comment]
Closing since nothing new to add there.
