### ISSUE TITLE
Is there any impact to haproxy abount http2 vulneralibity?

### ISSUE THREAD

**Issue by fuka307** [haproxy/haproxy#232]
CVE 2019-9511 to 2019-9518 are any impact to haproxy's http2 settings.

**Comment by wtarreau** [comment]
On Thu, Aug 22, 2019 at 09:26:42PM -0700, fuka307 wrote:
> CVE 2019-9511 to 2019-9518 are any impact to haproxy's http2 settings.

No, as already mentioned on the mailing list ~10 days ago, these do not
have any impact. Most of them are related to memory allocation to build
responses, which doesn't happen in our case since we attempt to write
the response directly into the output buffer and only if there's enough
room. The memory allocation with empty headers does not happen either
here as we only fill an array with these ones, and increment the index
until a bound (100 by default) so I'd even say that empty headers are
cheaper to deal with than other ones. And the bugs having a CPU impact
do not harm us either because window updates are processed in batches so
data frames are scheduled only once the window has finished increasing,
and priorities are not implemented.

**Comment by fuka307** [comment]
> No, as already mentioned on the mailing list ~10 days ago, these do not
> have any impact. 

Sorry, I could not catch up this mentions.
Thank you for your replay.
