### ISSUE TITLE
DOC - Update manual to better explain track option for backend servers

### ISSUE THREAD

**Issue by nwehrman** [haproxy/haproxy#2328]
### Detailed Description of the Problem

Currently the manual reads that it's configured with `track [<proxy>/]<server>` but that's misleading as it's not actually a proxy.  The item that belongs there is the name of a backend server.

Proposed changes;
```
-track [<proxy>/]<server>
+track [<backend name>/]<server>
   This option enables ability to set the current state of the server by tracking
   another one. It is possible to track a server which itself tracks another
   server, provided that at the end of the chain, a server has health checks
-  enabled. If <proxy> is omitted the current one is used. If disable-on-404 is
+  enabled. If <backend name> is omitted the current one is used. If disable-on-404 is
   used, it has to be enabled on both proxies.
```

### Expected Behavior

Behaves as designed. Simple documentation clarification.

### Steps to Reproduce the Behavior

The track function won't actually use a proxy server so that term is misleading.

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by wtarreau** [comment]
Note, I had to edit your comment to quote the words under angle brackets because apparently the markdown editor here silently dropped them, likely taking them as html tags, so I didn't understand your request. It's fun to see quoting issues here after your other report about quoting :-)

However it's interesting that you said "it's not a proxy" because it definitely is one, at various levels (code, stats etc), but after looking up the doc for other such instances, I'm figuring that it was the only instance of `<proxy>/<server>`, all other ones mention `<backend>/<server>` instead, so I can understand how that would be more consistent, especially for a new reader who could wonder if we are trying to insist on a particular difference here by using a different word.

**Comment by wtarreau** [comment]
OK I updated it accordingly, I'm closing it now. Thank you!
