### ISSUE TITLE
Use explicit fetching of OpenSSL providers

### ISSUE THREAD

**Issue by DemiMarie** [haproxy/haproxy#2337]
### Your Feature Request

HAProxy should explicitly fetch OpenSSL providers to avoid locking in OpenSSL.

### What are you trying to do?

I am suggesting a workaround for OpenSSL 3.0’s performance problems.

### Output of `haproxy -vv`

```plain
Not applicable as this is based on reading documentation (both OpenSSL’s and HAProxy’s) rather than on actual usage.
```

**Comment by git001** [comment]
Please can you explain the FR a little bit more because I don't get the Idea you have in mind.

**Comment by wlallemand** [comment]
@DemiMarie I'm not getting your point, are you suggesting a fix for this issue https://github.com/openssl/openssl/issues/17627#issuecomment-1060123659 ?

**Comment by haproxyFred** [comment]
Perhaps this as something to see with https://github.com/openssl/openssl/blob/master/README-PROVIDERS.md

**Comment by wlallemand** [comment]
@haproxyFred we already have the [ssl-provider](http://docs.haproxy.org/2.8/configuration.html#ssl-provider)  option but I don't really see how this would fix the performance issues of OpenSSL 3.

**Comment by haproxyFred** [comment]
Me neither...

**Comment by haproxyFred** [comment]
Perhaps we should re-implement all the cryptographic algorithms in providers without locking :laughing: :laughing: :laughing:

**Comment by DemiMarie** [comment]
@haproxyFred @wlallemand @git001 https://github.com/openssl/openssl/issues/17064#issuecomment-973444945 and https://github.com/openssl/openssl/issues/17064#issuecomment-974146101 explain what is needed.  The tl;dr is that OpenSSL has a cache of algorithm implementations, but access to the cache requires a lock, which severely harms performance in multithreaded workloads.  Applications can regain performance by fetching the algorithm implementations themselves up front and then using the already-fetched implementations.  This avoids lock contention after startup.

**Comment by wtarreau** [comment]
I already had a look at this during the early days where openssl started to exhibit horrible performance. What I found was that a lot of internal stuff was calling functions that iterate over lists under a lock. I had not noticed anything that would allow to bypass that, because most of the time when we see massive contention, it's several function levels below us. But that should not prevent one from still trying, even if I don't have much hope anymore on the OpenSSL front :-(

**Comment by DemiMarie** [comment]
@wtarreau which internal stuff is this?

Unfortunately, shipping an in-tree copy of BoringSSL or LibreSSL is not going to work because of license compatibility problems.  Best solution is probably going to be either WolfSSL or the ASF fork of OpenSSL someone was proposing earlier.  What is the status of the latter?  Given how fast WolfSSL compiles, one could theoretically work around the lack of runtime feature detection by building the program from source every time HAProxy starts, though I don’t know if that is an option.

**Comment by wtarreau** [comment]
I don't remember what that was, I'm really bad with openssl layers. What I can say is that when we managed to trigger the watchdog on locks inside openssl, there were often 3-5 levels of callers that were also part of openssl themselves. I had read some of these functions and they were scanning lists under locks. I wondered if an option could have been to just locklessly cache a copy of the previous lookup for a fast response (since most of these are likely always the same) and it didn't appear to be easy to do given that these disgusting locks were everywhere.

I never spoke about shipping a copy of any lib, I'm not sure why it's mentioned here. SSL libs regularly see vulnerability reports and must absolutely not be forked and kept out of tree, that's the best way to miss important updates. Regarding wolfssl, I agree. The ASF fork has still not appeared, I suspect the authors are lacking manpower to work on it. Also, let's face it, now that the openssl code has already been sabottaged with all these locks, the perspectives of having to start a fork by working one year to clear all that mess is not quite appealing. There's also aws-lc which is quite promising. I've tested it on graviton3 and it's quite impressive.

Regarding the idea of building upon startup, that clearly cannot be an option. A server should already not even have a compiler installed, let alone its own software sources! And imagine how that would ruin experience of those running in highly scalable environments which pop VMs every few seconds! Instead these ones can rebuild wolfssl once to match their hardware setup, and make a package out of it.

**Comment by DemiMarie** [comment]
> I never spoke about shipping a copy of any lib, I'm not sure why it's mentioned here.

I mentioned this because right now all of the options are terrible.  Android, Chromium, and Cloudflare all do use their own copies of BoringSSL, which works because the downstreams work closely with upstreams and adapt to upstream changes.  I certainly don’t blame you for not taking this approach, though!

> The ASF fork has still not appeared, I suspect the authors are lacking manpower to work on it.

Is this something that HAProxy Technologies could help with?  “No” is a perfectly valid answer here, but I am curious, especially since (to me) it seems like it might help maintenance of HAProxy Enterprise.

**Comment by wlallemand** [comment]
Depends on what you want, HAProxy technologies provides packages with a maintained openssl 1.1.1+quictls patches. We don't really like maintaining this, but we do use the LTS openssl patches.

But if this is about maintaining a SSL fork, or developing a SSL stack, I fear we don't have the manpower nor the competence either.

I'll take a look again at the lock issues but honestly I don't have much hope about it. We looked at it multiple time and it was so deep in the openssl internals to be able to hack something useful.

**Comment by DemiMarie** [comment]
Is multi-process mode an option?  That should eliminate the lock contention at least, and one needs multiple processes for high availablity anyway.

**Comment by wlallemand** [comment]
We don't do that anymore, we changed our model from multiprocess to multithreads a while ago.

**Comment by wlallemand** [comment]
Closing this, as the problem is still in OpenSSL and not in HAProxy.
