### ISSUE TITLE
Documentation for `http-request wait-for-body` is unclear on a couple of points. 

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#2410]
The [documentation for `http-request wait-for-body`](https://docs.haproxy.org/dev/configuration.html#wait-for-body) is a little unclear.

The current text is:
```
This will delay the processing of the request or response waiting for the
payload for at most <time> milliseconds. if "at-least" argument is specified,
HAProxy stops waiting for the payload when the first <bytes> bytes are
received. 0 means no limit, it is the default value. Regardless the
"at-least" argument value, HAProxy stops to wait if the whole payload is
received or if the request buffer is full.  This action may be used as a
replacement to "[option http-buffer-request](https://docs.haproxy.org/dev/configuration.html#option%20http-buffer-request)".
```

But what happens if it times out? And does `stops waiting for the payload` mean that it returns an error to the client, or starts forwarding the data to the backend server?

From my experimentation, it appears that if the timeout is reached without getting the full payload it returns a 408 error response to the client. And if `at-least` bytes are received, then it will start streaming to the backend server.  Although I'm not entirely sure what happens if it receives more than `at-least` bytes, but it takes more than `time` milliseconds for the entire body to be transmitted. 

There are also a couple of grammatical errors in this paragraph:

- "if" in the second sentence should be capatalized
- 'Regardless the "at-least" argument value' should be 'Regardless _of_ the "at-least" argument'
- "HAProxy stops to wait if" should probably be  "HAProxy stops waiting if" 
- "may be used as a replacement to" should be "may be used as a replacement of"

**Comment by wtarreau** [comment]
Interesting, you're right, there are ambiguities. If I hadn't checked the code I would have responded incorrectly! It's often the case when a feature is documented while being implemented, some corner cases are still obvious for the developer and not necessarily explained in the doc.

Here this action is used to allow to take a decision based on arguments from the body. If the body doesn't come fast enough, the request is considered incomplete and indeed 408 is returned (that could be a typical slowloris attack). If the request is complete (either `at-least` bytes or a full request or a full buffer), then haproxy "stops waiting" which means that it continues processing the rules after this `wait-for-body` rule.

What is important to understand (and is not explicit either here) is that the request is entirely buffered during this time, nothing is transmitted anywhere since no routing decision has been taken yet. This is why the total size is limited to a buffer. So there's no notion of the time it takes for the body to be transmitted anywhere, what matters is the time it takes to receive `at-least` bytes, which should be lower than or equal to `time` for the request to be processed.

I agree that this paragraph should be reworded to better introduce the notion of the full body, or buffer size, or at-least. The rule is:
  - if the request body is complete, the analysis ends successfully.
  - if the buffer is full, the analysis ends successfully
  - if `at-least` bytes are received, analysis ends successfully
  - if `time` is reached since the beginning of the action, 408 is returned
  - otherwise we continue to wait (goto first line above).

I'll probably work on it as time permits, though if you feel easy with proposing a patch, it would be really welcome! And thanks for your grammatical corrections, I also agree with them ;-)

**Comment by tmccombs** [comment]
Thanks. If I get some time I can put together a patch to improve the documentation.
