### ISSUE TITLE
how do i load balance quic only without the http3 part?

### ISSUE THREAD

**Issue by sprappcom** [haproxy/haproxy#2430]
### Your Feature Request

i've checked online and saw 

  bind :443  ssl crt /etc/haproxy/certs/foo.com/cert.crt alpn h2
  bind quic4@:443 ssl crt /mycert.pem alpn h3
  
 but realised udp need to set mode as mode nat?
 

### What are you trying to do?

 any guide to load balance quic only? i need to use haproxy to terminate tls and do quic proxy
 
 how can this be done?

### Output of `haproxy -vv`

```plain
version 2.9
```

**Comment by lukastribus** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.
* The forum is at: https://discourse.haproxy.org/
* The mailing list (no need to subscribe) is: [[haproxy@formilux.org](mailto:haproxy@formilux.org)](mailto:haproxy@formilux.org)
* Subscribe to the list: [[haproxy+subscribe@formilux.org](mailto:haproxy+subscribe@formilux.org)](mailto:haproxy+subscribe@formilux.org)
* Unsubscribe from the list: [[haproxy+unsubscribe@formilux.org](mailto:haproxy+unsubscribe@formilux.org)](mailto:haproxy+unsubscribe@formilux.org)
