### ISSUE TITLE
Send SPOA message after response to client

### ISSUE THREAD

**Issue by mbrozzo** [haproxy/haproxy#2457]
### Your Feature Request

In the `spoe-message` section of the spoe engine configuration, for the event parameter I wold like an option such as "after-frontend-http-response" which is triggered after the frontend forwards the response to the client.

### What are you trying to do?

I have followed [your guide for traffic mirroring](haproxy.com/blog/haproxy-traffic-mirroring-for-real-world-testing#haproxy-traffic-mirroring-for-real-world-testing) and have read the documentation for SPOA engines.
I would like to implement traffic mirroring for a testing environment in a way that does not impact the production traffic. I have noticed that if the spoa-mirror is not running, HAProxy will wait until the timeout expires. Since the response from the mirror is not used, I would like for HAProxy to first forward the response to the client and then mirror the request to the testing environment (preferably without waiting for a response).

### Output of `haproxy -vv`

```plain
HAProxy version 2.4.24-d175670 2023/08/19 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.24.html
Running on: Linux 6.5.0-18-generic #18~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Feb  7 11:40:03 UTC 2 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_PROMEX=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL +EPOLL -EVPORTS +FUTEX +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PRIVATE_CACHE -PROCCTL +PROMEX -PTHREAD_PSHARED -QUIC +RT +SLZ -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=16).
Built with OpenSSL version : OpenSSL 3.0.11 19 Sep 2023
Running on OpenSSL version : OpenSSL 3.0.11 19 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[SPOE] spoe
	[CACHE] cache
	[FCGI] fcgi-app
	[COMP] compression
	[TRACE] trace
```

**Comment by capflam** [comment]
Unfortunately, it is not possible because there is no ruleset evaluation after haproxy has started to send the response to the client. And it is also not possible to mirror the request at this stage because it was already sent to the server and "cleared" from haproxy point of view. Once sent the request is no longer available. It is the reason why it is not possible to manipulate request headers from any response ruleset. 

To avoid to wait the timeout expiration when the SPOA is not running, you must enable the health-checks on your SPOE servers. The best it to use the `spop-check` option.

Note, that even it is still under discussion, we are seriously thinking to deprecate the SPOE. Unfortunately it is still based on an old design, totally outdated. It must be refactored since a while but it is a huge piece of work. And for every new version, it is harder to make it working properly. We have to be realistic. If there is no investment on the SPOE, the best is to remove it.

**Comment by shadyabhi** [comment]
>Note, that even it is still under discussion, we are seriously thinking to deprecate the SPOE. Unfortunately it is still based on an old design, totally outdated. It must be refactored since a while but it is a huge piece of work. And for every new version, it is harder to make it working properly. We have to be realistic. If there is no investment on the SPOE, the best is to remove it.

@capflam I don't want to go too off-topic, but I'll appreciate a short answer if possible.

I'm guessing, there isn't a wide adoption of SPOE, which is why HAproxy might plan on deprecating it. With that as a remote possibility, what will be the replacement? Is lua filter API considered a recommended way, via Rust for example. Writing plain lua for complex stuff isn't very productive.

**Comment by capflam** [comment]
@shadyabhi no problem. Well indeed, there is no time invest to refactor the SPOE because it is not widely used. 
The lua remains the recommended way to add small features. However it is not always possible to use lua for heavy processing. For now, there is no real solution to replace the SPOE. WASM  was mentioned but I don't know if it is a good candidate. At the end, we really need some help on this subject. To find a replacement but also to work on it. However, the SPOE will be removed without any solution to replace it.

**Comment by mbrozzo** [comment]
@capflam thank you very much for your answer, I understand the problem. Being new to HAProxy, I did not know it was possible to use Lua scripts. I will explore the possibility of implementing an asynchronous mirroring feature using a Lua script, but I think that you should consider adding request mirroring as a core functionality of HAProxy (should I create a separate feature request?) like Nginx has. Mirroring requests is extremely useful for testing an infrastructure under real load.
