### ISSUE TITLE
Long URIs Truncate Logged HTTP Version

### ISSUE THREAD

**Issue by maxmoehl** [haproxy/haproxy#2464]
### Detailed Description of the Problem

When logging requests with very long URIs, the HTTP version reported by `%HV` gets mangled. See also #2205.

### Expected Behavior

The URI length does not affect the reported HTTP version.

### Steps to Reproduce the Behavior

1. Define a custom log format with `%HV`
2. Send a request with a long URI (>1024)

### Do you have an idea how to solve the issue?

Increase `tune.http.logurilen`, but we'd like to avoid that to not exceed the syslog limit. However, the HTTP version is an important information we'd like to report reliably in any case.

### What is your configuration?

```haproxy
log 127.0.0.1:514 len 4096 format local syslog info
log-format "%ci:%cp [%tr] (%ID) %ft %b/%s %Th/%Ti/%TR/%Tw/%Tc/%Tr/%Tt %ST %B %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %[src,table_conn_rate(st_tcp_conn_rate)]/%[src,table_http_req_rate(st_http_req_rate)] %hr %hs \"%HM %HPO%HQ %HV\" %sslc %sslv %[ssl_fc_has_sni] %[ssl_c_used] %[ssl_c_sig_alg] %[ssl_fc_has_crt] %[ssl_c_err] %{+Q}[ssl_c_s_dn] %{+Q}[ssl_c_i_dn] %{+Q}[ssl_fc_sni] %{+Q}[var(txn.block_reason)]"
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.8.5-aaba8d0 2023/12/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.5.html
Running on: Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_PROMEX=1 USE_STATIC_PCRE2=1 USE_PCRE2=1 USE_PCRE2_JIT=yes
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE +STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=2).
Built with OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
Running on OpenSSL version : OpenSSL 3.0.2 15 Mar 2022
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.4.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Additional Information

* [local patch](https://github.com/cloudfoundry/haproxy-boshrelease/blob/master/haproxy-patches/disable-rfc-6455-compliance.patch)

**Comment by Darlelet** [comment]
Need to change this into a feature request since it is an historical behavior and not a bug.

**Comment by maxmoehl** [comment]
Should I re-create the issue or can you convert it?

**Comment by Darlelet** [comment]
Thanks @capflam 

@maxmoehl in fact what happens here is that `%HQ` may produce up to `tune.http.logurilen` bytes in the log payload.

Since both `tune.http.logurilen` and `log <length>` default to 1024, it means that any data found after `%HQ` in the logformat string may become truncated if the request URI appears to be long enough. Unfortunately we cannot guess at config time what your typical log payload would look like after the `%HQ` for a given logformat because most logformat tags involved here produce dynamic data that differ for each request.

Thus in your case I would suggest you to try to guess the maximum number of bytes that `%HQ` could take to ensure there remains enough space in the log buffer to hold data produced by logformat variables found after `%HQ` in your logformat string.
Or you may simply look for the minimal URI length that looks suitable to you for logs reporting (let say if you only care about the first 32 chars for the request uri in the logs, then this leaves a lot of space for remaining log data..)
Once you know the safe value, you may set `tune.http.logurilen` accordingly.

If that's not a convenient solution for you, you may also reorder your logformat expression so that most important/predictable data is generated first, leaving tricky tags that can possibly bloat the log payload such as `%HQ`  near the end of the logformat expression.
In your case this would mean putting `%HV` **before**  `%HQ`.

You could also simply drop `%HQ` if it's not an useful information in your case.

Hope this helps.

**Comment by maxmoehl** [comment]
Thanks for the prompt answer!

I should have clarified that we increase the length of the log to 4096, sorry (also added it to the issue up top):

```
log 127.0.0.1:514 len 4096 format local syslog info
```

Looking at one log produced using a very long path:

```
165.1.187.197:36655 [27/Feb/2024:17:25:21.368] (d31a1acd-87d4-48c7-9955-96ed54eee172-65DE1B01-58A5F7D) https-in~ http-routers-http2/node56 22/0/0/0/0/1/23 404 294 - - ---- 2612/2603/7/0/0 0/0 1/1 {curl/8.6.0|||||not-found.cf.eu10.hana.ondemand.com} {-} "GET /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa HTTP/0.9" TLS_AES_128_GCM_SHA256 TLSv1.3 1 0 - 0 0 "" "" "not-found.cf.eu10.hana.ondemand.com" ""
```

and comparing that to what my local cURL spit out:

```
$ curl -vvv 'https://not-found.cf.eu10.hana.ondemand.com/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/b?foo=bar'
* Host not-found.cf.eu10.hana.ondemand.com:443 was resolved.
* IPv6: (none)
* IPv4: 3.122.209.241, 3.124.208.223, 3.124.222.77
*   Trying 3.122.209.241:443...
* Connected to not-found.cf.eu10.hana.ondemand.com (3.122.209.241) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256 / x25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: C=DE; ST=Baden-W�rttemberg; L=Walldorf; O=SAP SE; CN=*.cf.eu10.hana.ondemand.com
*  start date: Jan  2 00:00:00 2024 GMT
*  expire date: Dec 31 23:59:59 2024 GMT
*  subjectAltName: host "not-found.cf.eu10.hana.ondemand.com" matched cert's "*.cf.eu10.hana.ondemand.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global G2 TLS RSA SHA256 2020 CA1
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://not-found.cf.eu10.hana.ondemand.com/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/b?foo=bar
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: not-found.cf.eu10.hana.ondemand.com]
* [HTTP/2] [1] [:path: /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/b?foo=bar]
* [HTTP/2] [1] [user-agent: curl/8.6.0]
* [HTTP/2] [1] [accept: */*]
> GET /aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/b?foo=bar HTTP/2
> Host: not-found.cf.eu10.hana.ondemand.com
> User-Agent: curl/8.6.0
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 404
< cache-control: no-cache, no-store
< content-type: text/plain; charset=utf-8
< x-cf-routererror: unknown_route
< x-content-type-options: nosniff
< content-length: 87
< date: Tue, 27 Feb 2024 17:25:21 GMT
< strict-transport-security: max-age=31536000; includeSubDomains; preload;
<
404 Not Found: Requested route ('not-found.cf.eu10.hana.ondemand.com') does not exist.
* Connection #0 to host not-found.cf.eu10.hana.ondemand.com left intact
```

It seems like everything is correct besides the truncated path / query and the wrong HTTP version. Does your suggestion to switch the order of arguments still apply in that case?

The main point that confuses me is that the length of the URI affects the HTTP version. I understand that these two are related since they are parsed from the same line of the request but the documentation never mentions that there may be side effects on the output of the HTTP version.

To be even more specific, the documentation for [tune.http.logurilen](http://docs.haproxy.org/2.8/configuration.html#3.2-tune.http.logurilen) states that:

> This prevents truncating long request URIs with valuable query strings in log lines.

Or phrased differently (to my understanding): It allows you to still log some of the query, even for very long paths. But as you can see above the query string is lost as well, so it doesn't even help if I want to preserve some of the query parameters?

So to my understanding it only saves you from exceeding the overall limit of the log line.

**Comment by Darlelet** [comment]
Oh yes indeed sorry I had a hard time to recall what the original issue was in #2205, you can ignore my first post, thanks for your patience!

You've summed it up right: both `%HQ` and `%HV` are correlated because they are both generated using original request line saved by haproxy upon request, whose maximum length (length of the capture) cannot exceed `tune.http.logurilen`.

As a request/start line typically looks like this:
```
GET /aaaaaaa/b?foo=bar HTTP/2
```
Here we can clearly see the issue: the HTTP version being specified after the URI (including the query), then it means that for `%HV` to properly decode the version from the start line, the saved request line must be complete (up to the HTTP version).

Here since `tune.http.logurilen` is only 1024 and you face URIs exceeding 1024 bytes, then it means that the request line copy in haproxy will be incomplete, resulting in truncated `%HQ` and wrong `%HV` because haproxy fails to find the version in the saved request line.


So this means you should indeed increase `tune.http.logurilen` to properly capture the whole request start line. But then to prevent `%HQ` from eating all the log payload space (here 4096 in your case), you should either put `%HQ` near the end (to ensure only `%HQ` gets truncated when lacking space), or save `%HQ` in a temp variable to manually truncate it, for instance (I didn't test so this might not work as-is, but I hope you get the idea):
```
    log-format "%[var(txn.hq),bytes(0,2048)] %HV"
    http-request set-var-fmt(txn.hq) "%HQ"
```
(here `%HQ` is first saved into txn.hq variable, and when log payload is generated using the above logformat, txn.hq is truncated to 2048 bytes to makes sure the log payload will not exceed the 4096 log length you set, and thus ensure `%HV` will be properly printed even if it's found after the uri in the logformat expression)

I must confess that the above workaround is not an elegant solution, and could end up wasting memory (because haproxy first captures the request line up to `tune.http.logurilen` and then we copy (again) the full uri into a temporary variable)...

Maybe we could consider saving the HTTP version (for logging) within a dedicated storage space upon request so that `%HV` doesn't rely on the request line copy anymore.

**Comment by maxmoehl** [comment]
That makes sense, I think we are on the same page now!

I've read the documentation again and noticed that there is a different interpretation of it. It could also mean that the property allows you to increase the limit to capture query parameters even for long paths which is in line with the behaviour.

For HTTP/1 any workaround is going to be tricky and even fixing this in HAProxy might be troublesome. But the relation between URI and HTTP version is also questionable for anything beyond HTTP/1 since there no longer is a classic request line but rather pseudo headers and ALPN. Still, the HTTP version is truncated on HTTP/2 with long paths / queries. Would this be something that could be changed?

Edit: It might be helpful to explain our use-case a bit: We run a multi-tenant platform and as such cannot control the length of the URI. Setting a reasonable limit to always capture the HTTP version is pretty much impossible, so I'm looking for a solution that is independent of that.

**Comment by Darlelet** [comment]
> Edit: It might be helpful to explain our use-case a bit: We run a multi-tenant platform and as such cannot control the length of the URI. Setting a reasonable limit to always capture the HTTP version is pretty much impossible, so I'm looking for a solution that is independent of that.

Note that the above limitation (`%HV` not working as expected with incomplete log request line capture as per `tune.http.logurilen`) doesn't apply to `req.ver` sample fetch, so maybe this could help:
```
mode http

log-format "req version: HTTP/%[var(txn.rqver)]" # use txn.rqver, see below
http-request set-var(txn.rqver) req.ver # save http version during request
```

(it is required to save `req.ver` during request handling in a variable with a scope available during the response, here `txn` because log generation generally happens after the response, thus we cannot directly use `req.ver` in the logformat expression because `req` scope is not available during the response)

There is also `capture.req.ver` which may directly be used in the logformat expression (`"%[capture.req.ver]"`), but it is currently limited to either "HTTP/1.0" or "HTTP/1.1" so it won't help in your case. On a side node, maybe we should consider adding support for newer HTTP versions in `capture.{req,res}.ver` to offer a reliable (and easy to use, at least easier than having to manually save `req.ver` as in the above example) `%HV` alternative for logs.

**Comment by maxmoehl** [comment]
That sounds great!

> There is also `capture.req.ver` which may directly be used in the logformat expression (`"%[capture.req.ver]"`), but it is currently limited to either "HTTP/1.0" or "HTTP/1.1" so it won't help in your case. On a side node, maybe we should consider adding support for newer HTTP versions in `capture.{req,res}.ver` to offer a reliable (and easy to use, at least easier than having to manually save `req.ver` as in the above example) `%HV` alternative for logs.

And +1 for that improvement!

**Comment by maxmoehl** [comment]
Since the original issue has been addressed via a workaround I'll go ahead and close this issue. I still think the improvement you've mentioned would be helpful!
