### ISSUE TITLE
Preserve stats across reloads

### ISSUE THREAD

**Issue by a-denoyelle** [haproxy/haproxy#2483]
### Your Feature Request

`Note`: this feature request is directly derived from the "guid" described here : https://github.com/haproxy/haproxy/issues/2482.

### 1. dumping stats

Stats should be dumped using a CLI command with a new format dedicated for reloading. This format should be close to the CSV dump, but will only display the stats which can be preserved. The first line will be a header which will list fields name. All remaining lines will refer to one haproxy object. Each of them will be prefixed with the "guid" and the element type.

For the first implementation, the CLI command should iterate over all known haproxy frontends, backends, listeners and servers, except if it does not have a "guid".

In order to observe sustained progress on this task, the very first implementation will not cover stats extra modules, but the design reflections will continually ensure that the design remains compatible with these extensions.

Until now the output types are not assigned to the metrics but to their values, which means that until a value is listed there is currently no way of knowing the type of a given metric, hence no way to select which columns will be dumped. Internally, all fields which could be considered as eligible to stats reloading are of type FN_COUNTER/FN_RATE and already stored together under fe_counters/be_counters structures. A new method of counter declaration should be implemented to allow to define their output type, structure origin
and offset. The objective is to render stats_fill_*_stats() functions more generic with another function which will dump the file headers with a list of all columns. Normally these functions should eliminate a significant portion of the hard-coded metrics in favor of those declared in the new format. This should constitute an incentive over time to declare new metrics using the new mechanism (less code to write, more info exposed).

### 2. loading stats on startup

New config elements must be added to dictate when stats will be preloaded on startup. For the first version, a simplified method close of the server-state-file will be implemented. A new global statement will contain the name of a file which contains the stats dump. For each frontend/backend section, another statement will be indicate if loading is active for all its element (proxy instance and listeners and/or servers) from the global file. Here is a
possible example of such a configuration :

```
global
	stats-file /tmp/haproxy.stats

defaults
	load-stats-file global

backend be1
	server s1

backend be2
	load-stats-file none
	server s2
```

Stats preloading should be done after parsing configuration. To ensure the most performance, new counter declaration will be used with a preloading of an array on the stats file header line parsing referencing the structure locations to fill. If a counter is unknown for the new process, it will be silently ignored. Then each lines are parsed using the "guid" to find the target object. If no instance is found, the line is silently ignored. If the target object type is different, a warning is reported and the line is skipped.

Each stat field should easily be decoded using the new counter declaration. One notable point is to be able to restore frequency counters. For them, the decoded value will be used as a prefill of the previous period.

**Comment by sigint2** [comment]
Just wanted to mention that this would be an excellent enhancement.

As a workaround for the current behavior, I've toyed with the idea of preserving stats by using a stick table, since stick tables are preserved across a reload. You could do something like have a stick table per proxy, with a gpc counter of ~100 elements. You could map "interesting" stats into an index in the array, and then could have some LUA task or similar that iterates through all of the current worker stats, and "clones" them into the relevant stick tables. 

Some stats only make sense in the context of the current process, or are ephemeral enough that they probably do not make sense to preserve ( like a healthcheck response error code or similar ) -- so the idea would be to only preserve a few relevant stats ( e.g., bytes in/out , backend uptime , last session on a server , etc.. ).  As you mentioned you'd have to take care to figure out which stats you'd want to add to, and which you just want to overwrite ( e.g., add to bytes in/out, override last session on a server ).

So this obviously has a number of shortcomings and is a bit of a hack. Mainly the idea was to preserve stats across reloads so that you can get all the information you need from haproxy all from the stats socket / runtime API. This is much preferred to prometheus for quick stats, since the stats socket is a "live" representation of the proxy state, and it is the same interface that is used for setting server state, etc.

**Comment by pierrecdn** [comment]
Not 100% sure how preserving values by dumping them into a file will help, for sure there won't be counter resets anymore, but does the fact that 2 processes at least can run concurrently during the reload phase could be handled this way, ie. won't we loose some data in the process?

**Comment by a-denoyelle** [comment]
@pierrecdn indeed, with this design, there will be stats loss for worker processes which are waiting for their connection closure. Our approach is a best-effort solution which should at least prevent counter resets.

A possible extension of this would be the ability to automatically dump stats before process exiting. Each worker process would have to use a dedicated file. It would be possible thus to keep the delta between the CLI stats dump and process worker final exiting. These values could be reinjected in an external database for stats collection. However I'm not sure it would be pertinent to reinject those values into the running haproxy process, as this would create an unexpected stats increase.

**Comment by wtarreau** [comment]
Another point to add to what Amaury said is that the essential difficulty with stats usually is with a single node during processes overlap. But in case where multiple nodes are already monitored, with some being able to appear or disappear, what are the residual issues caused by an extra process ? For example, are there per-node stats (strict 1:1) or is it possible to consider that any process is an independent node living its own life (since that's really the case in fact) ? Because maybe the sanest approach would be to make it easier to keep access to the stats socket of the leaving process till the end (what is currently granted via the master socket but might possibly need something easier once the difficulty is better understood).

**Comment by a-denoyelle** [comment]
After some new discussions with Willy, we have come with new ideas to extend the stat-file to preserve stats accross reloads. The main objective would be to allow to dump counters outside of frontends. Currently, this can be global "show info" counters or resolvers stats.

Thus, the stat-file format should allow special context header lines which inform about the types of dumped data. These context lines would start with a custom character ('#' typically) followed by the context type and a list of dumped column. 

For the first implementation, only proxies stats (frontend/backend/listeners/servers) preserve support will be done. We will implement info counters or resolvers stats support if this is deemed useful for enough users.

We also have discussed on the possibilty to have multiple stat-files input similarly to server-state files per backend. This could be useful to split stat-files per frontend/backend and also to have dedicated files for info counters and resolvers stats. For the first implementation, only a single stat-files input will be supported. 

Here is for reference an example of what such a stat-file could look like. Note that this is still under heavy development so nothing is fixed for now.

```
#fe guid,stot,bin,bout,dreq,dresp,ereq
foo,1,75,102540,0,0,0
bar,1,75,102540,0,0,0

#be guid,stot,bin,bout,dreq,dresp,econ,eresp,wretr,wredis,
baz,0,75,102540,0,0,0,0,0,0,

#resolvers send,snd_error,valid
0,0,0

#info pool_f,cum_conns,cum_req
0,10,20
```

Do not hesitate to share your observations on this.

**Comment by a-denoyelle** [comment]
To anyone of interest, I just merged patches for stats-file support in our dev branch. Please do not hesitate do test it and report us any observation. We still have time to change it before 3.0 release if needed.

As a quick sum-up, a stats-file can be generate with the following CLI command : 
```dump stats-file```
This can be saved in a dedicated file.

Then use global keyword `stats-file` to point to it, this allows haproxy process to preload initial counters.

**Comment by pierrecdn** [comment]
We gave a try, but as expected ran into the counter decrease issue (vs return-to-zero), following a reload.
In the end, it seems worse because the monitoring collection hallucinate big values (such as the old "32 bit counters cycle").

**Comment by wtarreau** [comment]
Thanks Pierre, this feedback is definitely valuable even if a bit sad. It means we may need to find a better solution, or maybe that the solution you had implemented is already optimal. I suspect that when monitoring a fleet of LBs, it can make sense to see them a the double of the real number of nodes, and consider that there are moments where there is no old process, hence half of the fleet is being used, and moments where they're all there (both old and new). Of course that doesn't address the per-process monitoring but it should report very accurate values across the whole farm.

On the opposite the solution here with the reloaded values is meant to help those with possibly less constaints (i.e. mostly drawing graphs from a single LB). We even envisioned a possibility to perform a final differential dump of the old process when it quits to refill the new one but that would be ugly and not necessarily super useful. Maybe eventually we should have a discussion about some possibilities around these limitations, that could better address your use cases. Maybe a completely different architecture could work better (e.g. external stats file mapped in shared mem and indexed by GUID etc). It would come with its own set of constraints of course, and every time we should keep in mind what we're trying to address and why, to make the best choices.
