### ISSUE TITLE
splice-response causing content-length-mismatch on v2.9

### ISSUE THREAD

**Issue by felipewd** [haproxy/haproxy#2505]
### Detailed Description of the Problem

Hello,

We were getting a few `content-length mismatches` errors from users downloading data using HTTP frontends with big streaming files (2MB). This is about 1 every 50,000 requests on our frontend with ~40-50Gbps traffic. (so every few 30-40 seconds). The last few 4-9KB were missing when the issue was presented.

We were able to log the offending requests with standard `httplog` and 2 things stood out:
- the termination state was always `----`, indicating no errors from the backend getting the data;
- The full reply was read from the backend, but was not received by the users.

This led us to disable `option splice-response`, with was enabled on our defaults sections, and the issue vanished.

### Expected Behavior

Being able to use `splice-response` without the occasional missing bytes.

### Steps to Reproduce the Behavior

Right...this is *hard*! We were never able to get this in a control setting, so this issue was production-environment only and even so with limited observability on our side.

### Do you have any idea what may have caused this?

Not at all

### Do you have an idea how to solve the issue?

We wish :-)

### What is your configuration?

```haproxy
Pretty boilerplate stuff here:

global
    nbthread 64
    hard-stop-after 7d
    maxconn 900000
    ulimit-n 3150919
    user haproxy
    group haproxy
    daemon
    unix-bind user haproxy mode 777


    node haproxy-frontend

    tune.idletimer 1000
    tune.bufsize 104857
    tune.pipesize 262144

    stats socket /var/run/haproxy_conexoes.sock mode 666 level admin expose-fd listeners
    stats timeout 10m

    log /var/tmp/logtape.unix local0

    h1-case-adjust content-length Content-Length
    h1-case-adjust content-type Content-Type
    h1-case-adjust content-range Content-Range
    h1-case-adjust cache-control Cache-Control
    h1-case-adjust server Server
    h1-case-adjust date Date


defaults
    mode    http
    
#    option splice-response    

    retries 1
    maxconn 900000
    timeout connect 1s
    timeout server 100s
    timeout client 100s
    timeout http-request 6s
    timeout http-keep-alive 40s
    timeout tunnel 300s
    timeout client-fin 4s
    timeout server-fin 4s
```

### Output of `haproxy -vv`

```plain
HAProxy version 2.9.6-9eafce5 2024/02/26 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.9.6.html
Running on: Linux 6.1.60 #1 SMP PREEMPT_DYNAMIC Wed Oct 25 19:17:36 UTC 2023 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_NS=1 USE_PCRE=1 USE_PCRE_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT +PCRE -PCRE2 -PCRE2_JIT +PCRE_JIT +POLL +PRCTL -PROCCTL -PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN -SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=128).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.6
Built with network namespace support.
Built with zlib version : 1.2.13
Running on zlib version : 1.2.13
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.45 2021-06-15
Running on PCRE version : 8.45 2021-06-15
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.2.0

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : none

Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace



uname -a

Linux ndt-spo-12 6.1.60 #1 SMP PREEMPT_DYNAMIC Wed Oct 25 19:17:36 UTC 2023 x86_64 Intel(R) Xeon(R) Gold 6338N CPU @ 2.20GHz GenuineIntel GNU/Linux
```

**Comment by capflam** [comment]
Thanks for the report. I tried to reproduce the issue without success. It seems the last data are dropped for an unknown reason. I'm digging in the code to figure out what may happen.

**Comment by felipewd** [comment]
hey @capflam thanks for the reply.

I can't blame you for not being able to reproduce this, even for us in production it takes a while for the issue to appear. The only way to fully get this was to isolate a streaming channel and trace every single request in a 300+GB log file. So...it's cumbersome.

**Comment by wtarreau** [comment]
This makes me think about a possible short read. I.e. splice() returning 0 when reading, and missing one or two pages, for example, due to lack of pipe memory, and that could be taken for an early client close. Another possibility was that everything was properly read but that the outgoing splice() splice failed by lack of socket room (e.g. TCP window) and for an unknown reason either did not prevent the stream from being closed because the end of stream was reached.

Christopher, we should discuss the opportunity to add new client/server termination flags indicating a truncated body. While this is valid (and the right way to advertise end without content-length), being able to report this condition would help, at least to know it didn't happen, because right now I don't think we'd report a server error when reading a shorter message than expected. But I could be wrong of course.

**Comment by capflam** [comment]
Well, if the payload is shorter than expected on the receipt side, an error is reported. Reading the description, I supposed the right size was reported in the logs (or at least a bigger size than sent to the client, to be sure the response was truncated). @felipewd, can you confirm my assumption on this point ? Can you also confirm that without `splice-response` option, the issue goes away ?

**Comment by wtarreau** [comment]
Ah OK, I thought it was still like in the past where a close marked the end of the response with no error reported. Cool, thanks!

**Comment by wtarreau** [comment]
@capflam Felipe indeed mentioned that when he disables `splice-reponse`, the issue vanishes.

**Comment by felipewd** [comment]
Hi @capflam and @wtarreau,

Yes, the issue does varnish without `splice-response`, and the log captured confirmed the correct value was read from the backend but 4-9KB less was received by the client. 

The scenario we were able to test this was: for each response, our backend server would flush the entire response (with `content-length` for accuracy) and issue a `shutdown (SHUT_WR)` on the haproxy backend socket to start a FIN proper shutdown.

We even captured the pcap response and saw that after the truncated response was delivered by haproxy to the client the same proper FIN/FIN+ACK was issue, so no RST or anything. That's when we compared the pcap response to the haproxy log files and noticed payload was missing a few KBs (9). Since `splice-response` was the only modifier we sued, removing it did indeed fixed everything. (side-note: our production machines dropped around 22% in network throughput performance removing splice for HTTP traffic)

Haproxy had around 30.000 sessions at the time (but the issued presented with less busy machines also), but the conf was prepared to handle this kind of traffic, even with bigger-than-usual pipe sizes for `splice`:

```
    maxconn 900000
    tune.bufsize 1048576
    tune.pipesize 262144
```

We have around 384GB of RAM on this test machine with ~52GB being used and the rest for page-cache and such. For sysctl-related confs, we have big pipes also enabled:

```
net.ipv4.tcp_window_scaling = 1
net.core.somaxconn = 16384
net.core.rmem_max = 12582912
net.core.wmem_max = 8388608
net.core.rmem_default = 262144
net.core.wmem_default = 131072
net.ipv4.tcp_rmem = 2048 262144 12582912
net.ipv4.tcp_wmem = 2048 131072 8388608
```

If you'd like to write a patch to increase some logging directives, we'll certainly collect some traffic with them. Also, if you have any ideas on how we can capture some hints on why this is happening, please let us know. splice is pretty useful to us for higher per-machine throughput.

**Comment by wtarreau** [comment]
Thanks Felipe, that's indeed useful. I find that your default rmem/wmem values are large but not extreme. They can sometimes take time to allocate for initial sockets. Also, in my experience values smaller than 4k are ignored so likely the 2048 min will be rounded up to 4096 anyway. Regardless I'm not seeing anything there that could cause any issue.

@capflam do you think we could learn more things with a test involving -dZ or -dF ? Maybe this only happens in zero-copy mode ?

It seems from the described scenario that we're facing some willingness to close a bit too fast apparently. I could imagine how we could en up in such a trap when using splicing since buffers are empty and might allow some conditions to be met. We'll definitely need to inspect the code to understand how this is possible.

The gains you're seeing with splicing are great. My best performance has generally been with 512k pipes and 64k buffers. Larger buffers tend to eat more memory and make the CPU caches less efficient. With pipes it's different since the data are not copied and the buffers are just recycled ASAP. But I trust that you've experimented quite a bit with that. Regardless that's also a good motivation for eventually supporting KTLS with splicing.

**Comment by capflam** [comment]
If without `splicing-response` option it works, it means the zero-copy mode with buffers is working well. So I guess there is an issue with the 2 step sending of the splicing (first, the snd_splice() when data are received and another one as a resume if some data were not fully sent) and the shutdown on server side. It was my first assumption. I must figure out how to reproduce this case. Because, reading the code, I'm unable to find the issue.

**Comment by wtarreau** [comment]
ok thanks!

**Comment by capflam** [comment]
By hacking the code, I'm able to reproduce a similar issue, and in theory, this should explain what you observed. When the server shut the connection down, if some data are blocked in the pipe for a while, it is possible to forward the shutdown to the frontend multiplexer that will close the connection too. This happens if data are blocked long enough to see the stream to be woken up. In this case, the shut is performed by `process_stream()`.

@felipewd, if it is possible, you can try the following patch. It should fix the issue.
[0001-BUG-MEDIUM-stconn-Don-t-forward-shutdown-to-SE-if-io.patch.txt](https://github.com/haproxy/haproxy/files/14840977/0001-BUG-MEDIUM-stconn-Don-t-forward-shutdown-to-SE-if-io.patch.txt)

I guess a good improvement could be to move some parts dealing with the pipes at a lower level to be visible from the mux connection. But, the passthrough multiplexer will be a problem in this case. In the mean time, the patch above should fix the issue and is backportable to 2.9

**Comment by felipewd** [comment]
hey @capflam I'll put in production for a few hours and let you know!

**Comment by felipewd** [comment]
hey @capflam this patch fixes the issue, confirmed! :-)

Thanks!

**Comment by capflam** [comment]
Many thanks @felipewd, I will push it !

**Comment by capflam** [comment]
Backported to 2.9.
