### ISSUE TITLE
Admin stats page should respect current URL in a browser

### ISSUE THREAD

**Issue by sammy007** [haproxy/haproxy#2511]
### Detailed Description of the Problem

Haproxy's stats page with admin capabilities could be also proxied and in order for those "Apply" buttons to work in this case they must respect current browser's URL. For instance if you have configured `/stats` path and actually accessing this page via http proxy with path rewrite by `/path/to/stats` after clicking "Apply" you end up on `/stats;st=DONE` which indeed does not work.

### Expected Behavior

Should respect URL in a browser for admin form action.

### Steps to Reproduce the Behavior

Proxy stats via nginx or haproxy with path rewrite. Like:
```
http-request replace-path /path/to/stats(/)?(.*) /stats\2
server s1 192.168.0.1:8080 check
```

### Do you have an idea how to solve the issue?

The solution is to not render path on server, easy fix could be just using relative paths. The hard fix is to set them using javascript.

### What is your configuration?

```haproxy
My configuration is that I am proxying that stats page via another haproxy with rewrite:


http-request replace-path /path/to/stats(/)?(.*) /stats\2
server s1 192.168.0.1:8080 check
```
```


### Output of `haproxy -vv`

```plain
2.9.6
```

**Comment by wtarreau** [comment]
I don't understand, you're purposely changing the URL in the middle of the path (which is a well-known broken pattern) and you expect that haproxy magically guesses how that was rewritten ? I mean, I could haproxy guess the page the browser accessed if it cannot rely on the path ? I even remember originally the admin page has caused some difficulties because the configured URI was not accessible when generating the output page and that required some changes, precisely to produce the POST URL because there was no other easy way to find it. But if you have proposals to address this, I'm all ears open.

**Comment by capflam** [comment]
@sammy007, any comment ? can you elaborate a bit or can we close the issue ?

**Comment by sammy007** [comment]
There is literally no reason to hardcode absolute path into that web page template, but so it goes. There is no well-known broken pattern either, just a power of url rewrite which is limited by 90s-like web mastering style.

**Comment by wtarreau** [comment]
Sorry, you're saying "there is no reason..." but what *solution* are you proposing instead ? IIRC the URL is present in the page for the POST link. And the "power of url rewrite" is precisely a 90s-style approach that fortunately died with the last people who were breaking the web that way. But regardless, if you have a reliable solution to propose for this I'm all ears open. I'm not a web developer and tried hard already to avoid this but reached a limit.
