### ISSUE TITLE
Checker dosen't close the conn and retained many time-wait connection

### ISSUE THREAD

**Issue by fatpa** [haproxy/haproxy#254]
HAProxy Version: v2.0.5

After enabling the mysql checker, i found the target host(mysql instance) continually increases the time-wait connection.
Review the source code 'haproxy/src/checks.c' and i can't find any close action after checking.

**Comment by lukastribus** [comment]
Don't ignore the issue template, it's there for a reason, and we need you to fill it out.

**Comment by wtarreau** [comment]
On Wed, Sep 04, 2019 at 05:06:36AM -0700, Fatpa wrote:
> HAProxy Version: v2.0.5
> 
> After enabling the mysql checker, i found the target host(mysql instance) continually increases the time-wait connection.
> Review the source code 'haproxy/src/checks.c' and i can't find any close action after checking.

time-wait is a proof that it is closed, otherwise it would be close-wait.
The time-wait happens because haproxy closes first. The change was brought
by commit 5488a62bfb ("BUG/MEDIUM: checks: make sure to close nicely when
we're the last to speak") which addresses the opposite situation, which
is that by aggressively closing, some servers report errors for each and
every check (reported against Postfix in issue #187). The commit above
thus addressed all 3 banner protocols at once (smtp, mysql, pgsql) to
make them close gracefully as in older releases.

Is the number of TIME_WAIT concerning for your use case ? If you have a
small number like just a few hundreds to few thousands, this will not
affect your ability to establish connections there. Otherwise it's
possible to revert part of the patch above and test again. If we get
the confirmation that mysql never complains about aggressive closes,
I'm totally fine with aggressively closing. But I had some memories
a long time ago about such errors requiring to increase the error count
limit for the test users. Please take a look in check.c for lines with
this comment "/* do not reset when closing, servers don't like this */"
and simply remove the 2-line test that follows.

**Comment by fatpa** [comment]
Thanks. It dosen't affect the ability now. I just wait for the next version and upgrade it.
