### ISSUE TITLE
3.0-dev* sometimes logs two spaces between captures and http_request

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#2556]
### Detailed Description of the Problem

So it seems to affect 3.0-dev* only and at least since -dev6 (haven't tested anything prior) up to dev9.
It logs a double space between captures and http_response in *some* cases.
It seems to affect NOSRV, 503 and some other cases.

So good:
`...} "GET ...`

Bad:
`...}  "GET ...`

### Expected Behavior

No double space

### Steps to Reproduce the Behavior

Triggering a NOSRV or 503

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
HAProxy version 3.0-dev6-9cf3d1f 2024/03/26 - https://haproxy.org/
Status: development branch - not safe for use in production.
Known bugs: https://github.com/haproxy/haproxy/issues?q=is:issue+is:open
Running on: Linux 5.10.0-28-amd64 #1 SMP Debian 5.10.209-2 (2024-01-31) x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_LIBCRYPT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB= USE_SLZ=1 USE_NS= USE_SYSTEMD=1 USE_PROMEX=1 USE_PCRE= USE_PCRE_JIT= USE_PCRE2=1 USE_PCRE2_JIT=
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER -NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_AWSLC -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX -PTHREAD_EMULATION -QUIC -QUIC_OPENSSL_COMPAT +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=4).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with the Prometheus exporter as a service
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.36 2020-12-04
PCRE2 library supports JIT : no (USE_PCRE2_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 10.2.1 20210110

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
  <default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
  <default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG

Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

### Last Outputs and Backtraces

```plain
Apr 30 11:27:00.000 n095157 haproxy[3958513]: 127.0.0.1:26706 [30/Apr/2024:11:27:00.023] somelisten1 somelisten1/s070098 0/0/0/1/1 503 1099 - - ---- 4/1/0/0/0 0/0 {www.example.com|varnish|||||||||||}  "GET /haproxy-check HTTP/1.1"
```

**Comment by Darlelet** [comment]
Thanks for the detailed report Christian

First bad commit is c6a7138420807db7cf0450208a3102584d424103

I'll have a look

**Comment by Darlelet** [comment]
Ok so previously `last_ispace` was only set to 0 when data was generated for `%hr` and `%hs` (to name a few). Since the faulty commit it may be set even if no data was generated (due to some unmet conditions), resulting in double space. I overlooked this special case, sorry!

I think the proper way to fix this would be to only set `last_ispace` to 0 if something was written for the current node, like this:
```diff
diff --git a/src/log.c b/src/log.c
index 4ff4e3ad4..e863616a8 100644
--- a/src/log.c
+++ b/src/log.c
@@ -4744,10 +4744,12 @@ int sess_build_logline(struct session *sess, struct stream *s, char *dst, size_t
 
 		}
  next_fmt:
-		if (tmp->type != LOG_FMT_SEPARATOR)
-			last_isspace = 0; // not a separator, hence not a space
-
-		if (value_beg == tmplog) {
+		if (tmplog > value_beg) {
+			/* data was generated for the current node value */
+			if (tmp->type != LOG_FMT_SEPARATOR)
+				last_isspace = 0; // not a separator, hence not a space
+		}
+		else {
 			/* handle the case where no data was generated for the value after
 			 * the key was already announced
 			 */
```

But I must test it first, because historically (before c6a7138420807db7cf0450208a3102584d424103) we had other cases where we could previously have double spaces (ie: `%[str()]`), and the proposed fix will prevent them as well.

**Comment by idl0r** [comment]
Ah, nice, you figured it out already. I was thinking about bisecting or a better test case otherwise.

**Comment by Darlelet** [comment]
I'm not 100% happy with the proposed fix because either way (avoiding or not double spaces), it isn't possible to tell if the current node was skipped because nothing was available for printing (at least when no encoding is used).

We have the `+M` (MANDATORY) option which is enabled by default for that purpose and is currently only evaluated in `lf_text()`: if no data is available, it will print `-`. (if you use `%[str()]` for instance it will output `-`)

However `%hr`, `%hrl`, `%hs` and `%hsl` are immune to that, so the fix is delicate because if a script that consumes log messages relies on a fixed number of items (separated by spaces) in the log string, then there's no way to know that we're currently looking at the proper field if `%hr` fails to output data for instance, the risk is that the script parser jumps to the next field and uses the wrong value for `%hr`.

Starting with 3.0, I would recommend enabling `+M` support for the all fields with no exceptions in addition to the proposed fix (which turns out to be purely cosmetic in fact, that is, avoiding unnecessary spaces), so that we still have a way to know that the field was expected but is empty (unless MANDATORY option is explicitly disabled for the log-format using `-M`).

```diff
diff --git a/src/log.c b/src/log.c
index 4ff4e3ad4..3fbca8e8d 100644
--- a/src/log.c
+++ b/src/log.c
@@ -4744,21 +4744,24 @@ int sess_build_logline(struct session *sess, struct stream *s, char *dst, size_t
 
 		}
  next_fmt:
-		if (tmp->type != LOG_FMT_SEPARATOR)
-			last_isspace = 0; // not a separator, hence not a space
-
 		if (value_beg == tmplog) {
 			/* handle the case where no data was generated for the value after
 			 * the key was already announced
 			 */
-			if (ctx.options & LOG_OPT_ENCODE_JSON) {
+			if (!(ctx.options & LOG_OPT_ENCODE)) {
+				/* no encoding, try to emit '-' if field is mandatory */
+				if (ctx.options & LOG_OPT_MANDATORY)
+					LOGCHAR('-');
+
+			}
+			else if (ctx.options & LOG_OPT_ENCODE_JSON) {
 				/* for JSON, we simply output 'null' */
 				iret = snprintf(tmplog, dst + maxsize - tmplog, "null");
 				if (iret < 0 || iret >= dst + maxsize - tmplog)
 					goto out;
 				tmplog += iret;
 			}
-			if (ctx.options & LOG_OPT_ENCODE_CBOR) {
+			else if (ctx.options & LOG_OPT_ENCODE_CBOR) {
 				/* for CBOR, we have the '22' primitive which is known as
 				 * NULL
 				 */
@@ -4771,6 +4774,12 @@ int sess_build_logline(struct session *sess, struct stream *s, char *dst, size_t
 		 * to end it
 		 */
 		LOG_VARTEXT_END();
+		if (tmp->type != LOG_FMT_SEPARATOR && tmplog != value_beg) {
+			/* current node isn't a space, and data was actually
+			 * generated, reset the space hint
+			 */
+			last_isspace = 0;
+		}
 	}
 
 	/* back to global ctx (some encoding types may need to output

```

In that case, `reg-tests/http-messaging/h1_host_normalization.vtc` would have to be patched because it uses `%hr` and expects that nothing gets printed when `%hr` fails. (it would be a breaking change)

@wtarreau @wlallemand do you have an opinion about this?

**Comment by Darlelet** [comment]
This patch series implements the logic from the comment above and addresses both the double space emission issue and OPT_MANDATORY option handling for all nodes. I'm waiting for feedback before merging it, given that the MEDIUM patch that enables the mandatory option handling for all nodes may be considered as a some kind of breaking change (required regtest to be patched, because `-` will now be printed for `%hr`, `%hrl`, `%hs` and `%hsl` when they don't emit data, and this may not be expected by some existing log parsers).
The old behavior can be forced by disabling the mandatory option using `-M` before `%hr`..`%hsl` fields.

[logformat_mandatory+spaces.patch.txt](https://github.com/haproxy/haproxy/files/15186453/logformat_mandatory%2Bspaces.patch.txt)

**Comment by idl0r** [comment]
Nice!
I can test it in about a week, around May 13th-.

**Comment by Darlelet** [comment]
Thanks @idl0r, I think it won't be necessary as we just had a quick talk with @wlallemand and @wtarreau.
We'll keep a special case for `%hr`, `%hrl`, `%hs` and `%hsl` to be conservative with previous behavior since it was intended (no `-` when captures are not enabled)

I'll try to merge fixes soon.

**Comment by Darlelet** [comment]
It should be fixed now!

**Comment by idl0r** [comment]
Thanks! :)
