### ISSUE TITLE
Possible mistakes from Svace

### ISSUE THREAD

**Issue by Bbulatov** [haproxy/haproxy#2586]
### Tool Name and Version

Svace

### Code Report

Hello!
During the static analys was found some mistakes in haproxy.
```plain
Bad copy past:
1) In file cfgparse.c:3044-3058, in 3056 instead of "curproxy->options &= ~PR_O2_CHK_SNDST;" must be "curproxy->options2 &= ~PR_O2_CHK_SNDST;"
2) In file tcpcheck.c:3433-3440, in 3437 instead of "memprintf(errmsg, "'%s' invalid log-format string (%s).\n", npat, *errmsg);" must be "memprintf(errmsg, "'%s' invalid log-format string (%s).\n", vpat, *errmsg);" (instead of npat must be vpat)
Dereference of null pointer:
1) In file cfgparse.c:1855 variable "outline" can be NULL pointer in some processing and after then will executed and dereferenced in tool.c:5856 
2) In file hlua.c:13055 return value of function hlua_gethlua(L) not checking, but it is usually checked for NULL and after then executing in hlua.c:13138  
3) In file mux_h2.c:6607 return value of function htx_get_head_blk(htx) not checking, but it is usually checked for NULL and after then executing in mux_h2.c:6608 
4) In file stick_table.c:5597 return value of function stktable_data_ptr(ctx->t,ctx->entry,dt) not checking, but it is usually checked for NULL and after then executing in stick_table.c:5613							
5) In file tools.c:4685 return value of function my_realloc2(out, out_len + (txt_end - txt_beg) + val_len + 1) not checking, but it is usually checked for NULL and after then executing in tools.c:4694
```

### Output of `haproxy -vv`

```plain
3.0.0
```

**Comment by wtarreau** [comment]
Hello!

thanks for this report, that's really nice. I can confirm the first two and have fixed them.
For the 1st null-deref, it doesn't happen because the condition to write into the output is that there are bytes left, and during the first call, outlinesize=0 so no write is permitted. Precisely, what always happens is that the first attempt to parse a line causes a PARSE_ERR_TOOLARGE, so the caller (readcfgfile) will allocate outline and set outlinesize accordingly then try again.

For the last one it's indeed possible though very unlikely and essentially harmless since only during boot, but I fixed it as well.
For the remaining ones (null-derefs 2,3,4). we'll have to check later.

Thanks!

**Comment by Darlelet** [comment]
Remaining one is potential null-deref: `3) In file mux_h2.c:6607`, what do you think about this one @capflam?

**Comment by capflam** [comment]
At this step, when `htx_get_head_blk()` is called, we know the HTX message is not empty, i.e. `htx->head != -1`. So, it is  safe, `blk` cannot be NULL here.
