### ISSUE TITLE
aws-lc HAProxy QUIC Interop image

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#2652]
### Your Feature Request

@a-denoyelle , can you please merge this

https://github.com/chipitsine/haproxy-qns/tree/aws-lc

into "aws-lc" branch of https://github.com/haproxytech/haproxy-qns ?

sorry for asking in "haproxy/haproxy" issues. haproxytech seems to be ignoring PRs: https://github.com/haproxytech/haproxy-qns/pull/2

### What are you trying to do?

aws-lc QUIC Interop image

### Output of `haproxy -vv`

```plain
nemam
```

**Comment by a-denoyelle** [comment]
This is merged here
https://github.com/haproxytech/haproxy-qns/tree/aws-lc

**Comment by a-denoyelle** [comment]
As a side-note, it could be useful to review the haproxy FLAGS used in Dockerfile since the 3.0 Makefile has been simplified. For the future, it could be also easier to merge all SSL variant into a single branch, either with different Dockerfile (eg, Dockerfile.quictls, Dockerfile.awslc, ...) or use a single unified Dockerfile with environment variable to select the SSL library. This is not a priority for me but I may have a look into these if there is no one interested.

**Comment by chipitsine** [comment]
thanks!

I'll review FLAGS later.
accidently, I left asan flags in aws-lc :)


at the end I think of matrix (asan, no asan) x (quictls, libressl, aws-lc, wolfssl)

**Comment by chipitsine** [comment]
@a-denoyelle , I merged QuicTLS and AWS-LC together

https://github.com/haproxytech/haproxy-qns/pull/2/files

(no LibreSSL yet, because conditional COPY in Dockerfile just makes me sad)
