### ISSUE TITLE
sticky udp socket for dns resolution when running in Kubernetes w/ Cilium

### ISSUE THREAD

**Issue by brunomiguel-teixeira** [haproxy/haproxy#2654]
### Detailed Description of the Problem

When running Haproxy in Kubernetes w/ Cilium as the CNI, Haproxy loses dns resolution when the CoreDNS pods are rotated (for whatever reason) and it never recovers.

### Expected Behavior

Haproxy should be able to failover, as needed, as the CoreDNS Pods change.

### Steps to Reproduce the Behavior

Deploy Haproxy with dns resolvers (using parse resolve-conf) in Kubernetes running with Cilium with KubeProxyReplacement.

### Do you have any idea what may have caused this?

After investigating, looking at the source code, what happens is the follow.

Haproxy uses a "persistent" UDP socket for DNS resolution. If this socket already exists, it is never refresh, or recreated.
https://github.com/haproxy/haproxy/blob/master/src/dns.c#L54
https://github.com/haproxy/haproxy/blob/master/src/dns.c#L97

```
static int dns_connect_nameserver(struct dns_nameserver *ns)
{
	struct dgram_conn *dgram = &ns->dgram->conn;
	int fd;

	/* Already connected */
	if (dgram->t.sock.fd != -1)
		return 0;

	/* Create an UDP socket and connect it on the nameserver's IP/Port */
	if ((fd = socket(dgram->addr.to.ss_family, SOCK_DGRAM, IPPROTO_UDP)) == -1) {
		send_log(NULL, LOG_WARNING,
			 "DNS : section '%s': can't create socket for nameserver '%s'.\n",
			 ns->counters->pid, ns->id);
		return -1;
	}
	if (connect(fd, (struct sockaddr*)&dgram->addr.to, get_addr_len(&dgram->addr.to)) == -1) {
		send_log(NULL, LOG_WARNING,
			 "DNS : section '%s': can't connect socket for nameserver '%s'.\n",
			 ns->counters->id, ns->id);
		close(fd);
		return -1;
	}

	/* Make the socket non blocking */
	fd_set_nonblock(fd);

	/* Add the fd in the fd list and update its parameters */
	dgram->t.sock.fd = fd;
	fd_insert(fd, dgram, dgram_fd_handler, tgid, tg->threads_enabled);
	fd_want_recv(fd);
	return 0;
}
```

When running Kubernetes w/ Cilium with KubeProxyReplacement, when Haproxy creates the socket and performs the initial `connect` operation, it performs so correctly by using the Kubernetes CoreDNS Service IP (the virtual one). However, for the OS Kernel, the foreign remote address seen by socket is a random Pod IP from CoreDNS. This occurs due the setup of Cilium which performs direct NAT at the kernel level using eBPF, making the socket see the actual Pod IP as the remote address. 
```
root     haproxy              26       udp4   192.168.8.16:58260        192.168.0.100:53          ESTABLISHED
```

Other CNIs (ex: Azure CNI) preserve Service IP in the connection tracking. In this scenario the actual socket reports the Kubernetes Service IP.

In the Haproxy code, this socket is never renewed. When running Kubernetes w/ Cilium, when the CoreDNS pods are renewed, this causes the dns resolution socket to start sending dns queries to "old" and inexistent CoreDNS Pods, effectively breaking DNS resolution forever until Haproxy is restarted.

### Do you have an idea how to solve the issue?

During testing, renewing the DNS resolution socket for every dns query solves the issue. I did not test any performance impacts etc of creating new sockets every time.

### What is your configuration?

```haproxy
Simple test configuration


defaults
 default-server init-addr last,libc,none
 log global
 mode http
 
 option httplog
 option redispatch
 option forwardfor

 timeout connect 10s
 timeout client 60s
 timeout server 60s
 timeout tunnel 1h

frontend ft_web 
  bind *:8080 name web
  default_backend bk

backend bk
 mode http
 balance leastconn

 server argo github.com:443 check weight 1 resolvers hapdns

resolvers hapdns
        parse-resolv-conf
        resolve_retries       300000
        timeout retry         1s
        hold other            5s
        hold refused          5s
        hold nx               5s
        hold timeout          5s
        hold valid            5s
```
```


### Output of `haproxy -vv`

```plain
Running Haproxy 2.6.X but still occurs in 3.X
```

### Additional Information

Running Cilium 1.15.X wit hKubeProxy replacement and eBPF maquerading.

**Comment by einval22** [comment]
Hi brunomiguel-teixeira !

Thanks a lot for reporting this and for the investigations ! 

In theory this could be a good optional feature (recreate DNS 'client' socket at each connection) in order to support such kind of "dynamic" environments, where DNS pods can disappear behind the DNS service IP and Cilium does the direct NAT of this service IP  in-kernel. 

But, at first, could you please, provide more details on the necessity of this Cilium part.  
Does it serve only as a kind of  in-kernel "DNS load balancer" to dispatch DNS requests among available DNS pods behind the DNS service IP ? Or Cilium performs direct NAT for all destination ports, I mean it "balances" in this way  all other services in the cluster, not only DNS ?  

My idea is about to rather workaround this problem via some advanced Cilium tunning, i.e. not use its direct NAT for  destination port 53, for example, than to patch haproxy.   Its seems logical from the haproxy side/design, which deals with large number of connections (hence, file descriptors), to preserve its UDP "client" socket FD between resolve retries. 

Many thanks in advance for the info !
Kind regards,

**Comment by Tristan971** [comment]
> But, at first, could you please, provide more details on the necessity of this Cilium part.

Cilium (and other CNIs) essentially establish and operate a VLAN across the Kubernetes hosts, dedicated to containers. This is so that containers are isolated network-wise from the host yet still able to transparently communicate with one another. (amongst plenty of other things ranging from IPAM to pod-level firewalling, etc etc)

That said, here we do run HAProxy on k8s with Cilium as CNI without issue, and I'd suggest @brunomiguel-teixeira to look into a nodelocaldns setup. ie: https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/

- It solves your issue, since the node-local dns cache is static, and is the one needing to keep up with coredns podIP resolution (& this works flawlessly in my experience)
- your DNS performance will *massively* improve since you won't incur latency for cached DNS lookups anymore (ie pod on host A calling coredns on host B) unless you are currently running CoreDNS as a daemonset (and I imagine you aren't)

**Comment by brunomiguel-teixeira** [comment]
Hey everyone. Thanks for the info.

Additionally, I have been diving some more into the issue and this is known limitation in Cilium. 
See: https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#limitations

```
When socket-LB feature is enabled, pods sending (connected) UDP traffic to services can continue to send traffic to a service backend even after it's deleted. Cilium agent handles such scenarios by forcefully terminating application sockets that are connected to deleted backends, so that the applications can be load-balanced to active backends. This functionality requires these kernel configs to be enabled: CONFIG_INET_DIAG, CONFIG_INET_UDP_DIAG and CONFIG_INET_DIAG_DESTROY.
```
Which is essentially what Haproxy does with the dns udp socket.

I'll definitely look in the NodeLocal DNS. Truth be told, we are aware of it but never really invested much into because it was another piece to deploy and maintain, and up until now we never really had any critical dns issues.

Unsure how you guys wish to proceed here regarding the "udp socket renewal feature"?

Cheers,

**Comment by Tristan971** [comment]
> because it was another piece to deploy and maintain

It is not entirely 0 work, but it’s been as close to 0 as it gets for us, if it’s any comfort

**Comment by einval22** [comment]
I suppose, we can close this one now.

Thanks @Tristan971 and @brunomiguel-teixeira  for more details about Cilium and NodeLocal DNS.
