### ISSUE TITLE
src/checks.c: possible null pointer dereference found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#267]
```
2906                        else {
2907                                /* we'll connect to the addr on the server */
    CID 1399807: Dereference after null check (FORWARD_NULL)98. var_deref_op: Dereferencing null pointer s.
2908                                *conn->dst = s->addr;
2909                        }
```

**Comment by capflam** [comment]
Only checks used to send email alerts have no server attached. For such checks, there are always an address and a port explicitly set. So the server is never NULL when used. It is not really obvious but it is not a bug.

@chipitsine, please be kind. Don't create so many issues about coverity reports. It takes time to evaluate if there is indeed a bug or not. At the end, we will finish by ignoring these issues just because it's too time-consuming. Most of time, it is a false positive and it pollutes the issue tracker. It is really better to spend time on really encountered bugs instead. Thanks.

**Comment by chipitsine** [comment]
There are limited numbers of issues. Once reviewed, there will be very few new issues
