### ISSUE TITLE
Double "transfer-encoding: chunked" header return 502 error (terminal code PH)...

### ISSUE THREAD

**Issue by mcarbonneaux** [haproxy/haproxy#2677]
### Detailed Description of the Problem

when backed send two `transfer-encoding: chunked` haproxy return to the client Error 502.

```
502 Bad Gateway
The server returned an invalid or incomplete response.
```

and they are in state terminal code PH.

### Expected Behavior

no error (tolerence to the double header), skip the second header...

### Steps to Reproduce the Behavior

request to reproduce the error:
```
GET /myapi HTTP/1.1
authorization: Bearer <mytoken>
cookie: SERVERID=app01-obi-pp
host: myfqdn.com
user-agent: myuseragent
```

response:
```
HTTP/1.1 200
vary: Origin
vary: Access-Control-Request-Method
vary: Access-Control-Request-Headers
date: Thu, 25 Jul 2024 08:26:53 GMT
keep-alive: timeout=60
transfer-encoding: chunked
x-content-type-options: nosniff
x-xss-protection: 1  mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
content-type: application/json
transfer-encoding: chunked
 
395
<mybody of 395 bytes>
0
```

### Do you have any idea what may have caused this?

the double header "transfer-encoding: chunked"

### Do you have an idea how to solve the issue?

skip the second header.

### What is your configuration?

```haproxy
haproxy 2.8.3
```

### Output of `haproxy -vv`

```plain
haproxy -vv
HAProxy version 2.8.3-86e043a 2023/09/07 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2028.
Known bugs: http://www.haproxy.org/bugs/bugs-2.8.3.html
Running on: Linux 6.1.74-talos #1 SMP PREEMPT_DYNAMIC Thu Feb  1 17:43:35 UTC 2024 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment
  OPTIONS = USE_PTHREAD_EMULATION=1 USE_LINUX_TPROXY=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_SLZ=1 USE_TFO=1 USE_PROMEX=1 USE_PCRE2=1 USE_PCRE2_JIT=1
  DEBUG   = -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS
 
Feature list : -51DEGREES +ACCEPT4 -BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL -ENGINE +EPOLL -EVPORTS +GETADDRINFO -KQUEUE -LIBATOMIC +LIBCRYPT +LINUX_CAP +LINUX_SPLICE +LINUX_TPROXY +LUA +MATH -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OPENSSL_WOLFSSL -OT -PCRE +PCRE2 +PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PROCCTL +PROMEX +PTHREAD_EMULATION -QUIC +RT +SHM_OPEN +SLZ +SSL -STATIC_PCRE -STATIC_PCRE2 -SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL -ZLIB
 
Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200
 
Built with multi-threading support (MAX_TGROUPS=16, MAX_THREADS=256, default=16).
Built with OpenSSL version : OpenSSL 3.1.4 24 Oct 2023
Running on OpenSSL version : OpenSSL 3.1.6 4 Jun 2024
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
OpenSSL providers loaded : default
Built with Lua version : Lua 5.4.6
Built with the Prometheus exporter as a service
Built with network namespace support.
Built with libslz for stateless compression.
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.42 2022-12-11
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 12.2.1 20220924
 
Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.
 
Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
         h2 : mode=HTTP  side=FE|BE  mux=H2    flags=HTX|HOL_RISK|NO_UPG
       fcgi : mode=HTTP  side=BE     mux=FCGI  flags=HTX|HOL_RISK|NO_UPG
<default> : mode=HTTP  side=FE|BE  mux=H1    flags=HTX
         h1 : mode=HTTP  side=FE|BE  mux=H1    flags=HTX|NO_UPG
<default> : mode=TCP   side=FE|BE  mux=PASS  flags=
       none : mode=TCP   side=FE|BE  mux=PASS  flags=NO_UPG
 
Available services : prometheus-exporter
Available filters :
	[BWLIM] bwlim-in
	[BWLIM] bwlim-out
	[CACHE] cache
	[COMP] compression
	[FCGI] fcgi-app
	[SPOE] spoe
	[TRACE] trace
```

**Comment by git001** [comment]
As there is no config in the issue maybe you can add [option accept-invalid-http-request](https://docs.haproxy.org/2.8/configuration.html#4.2-option%20accept-invalid-http-request) to fix the issue temporarily.

The long term solution should be to fix the backend so that it does not violate the RFC7230

**Comment by wtarreau** [comment]
This is expected as per the HTTP spec. The response featuring these two headers indicates that the body was chunked-encoded twice, which is a serious bug and normally only happens in attemps to perform smuggling attacks. The receiver will have a hard time decoding it reliably and will only be able to use heuristics.

https://www.rfc-editor.org/rfc/rfc9112#name-transfer-encoding : 
```
A sender MUST NOT apply the chunked transfer coding more than once to a
message body (i.e., chunking an already chunked message is not allowed).
```
I'm wondering if "option accept-invalid-http-response" allows to bypass it or not. Can you please give it a try?

**Comment by zeugri** [comment]
> I'm wondering if "option accept-invalid-http-response" allows to bypass it or not. Can you please give it a try?

Hello @wtarreau i'm @mcarbonneaux colleague. I just tested the 'option accept-invalid-http-response' at the backend level and it does not solves the behaviour. The PH/502 behaviour is still present.

**Comment by wtarreau** [comment]
OK thanks for testing. I'll have a look to see if there's a riskless way to relax this. I must confess that I'm feeling more and more incomfortable with relaxing certain checks that are only triggered by attacks and super rare applications that have been violating the specs for 25 years, because in parallel we're seeing reports of attacks affecting all such corner cases, and having all-or-none under a single flag is a bit annoying :-/

**Comment by git001** [comment]
> > I'm wondering if "option accept-invalid-http-response" allows to bypass it or not. Can you please give it a try?
> 
> Hello @wtarreau i'm @mcarbonneaux colleague. I just tested the 'option accept-invalid-http-response' at the backend level and it does not solves the behaviour. The PH/502 behaviour is still present.

Any chance to fix the server which sends the double T-E header?

**Comment by zeugri** [comment]
We totally agree. We submitted the issue just as a curiosity/notice mainly but the right way is to correct the application that sends the double header. From our point of view a fix is not necessarily needed. Le 13 août 2024 à 17:16, Willy Tarreau ***@***.***> a écrit :﻿
OK thanks for testing. I'll have a look to see if there's a riskless way to relax this. I must confess that I'm feeling more and more incomfortable with relaxing certain checks that are only triggered by attacks and super rare applications that have been violating the specs for 25 years, because in parallel we're seeing reports of attacks affecting all such corner cases, and having all-or-none under a single flag is a bit annoying :-/

**Comment by wtarreau** [comment]
OK thanks for the context! Just let us know if you cannot fix the application for whatever reason so that we see if we can find a reasonable workaround for this.

**Comment by wtarreau** [comment]
Guys, can we close this issue since it's in the application ? It can wait for Mathieu if he's still on vacation, I just don't want to let issues rot, it takes us time when rechecking backports. Thanks!

**Comment by zeugri** [comment]
Hello all,Yes it can be closed I think. Thanks a lot for the time spent Le 5 sept. 2024 à 17:42, Willy Tarreau ***@***.***> a écrit :﻿
Guys, can we close this issue since it's in the application ? It can wait for Mathieu if he's still on vacation, I just don't want to let issues rot, it takes us time when rechecking backports. Thanks!

**Comment by mcarbonneaux** [comment]
> OK thanks for testing. I'll have a look to see if there's a riskless way to relax this. I must confess that I'm feeling more and more incomfortable with relaxing certain checks that are only triggered by attacks and super rare applications that have been violating the specs for 25 years, because in parallel we're seeing reports of attacks affecting all such corner cases, and having all-or-none under a single flag is a bit annoying :-/

i'm ok with that to not relaxing the way of parsing request, but her is the response of trusted backend.
and when you have multi thousand web application behind your reverse proxy, and many that are not custom developped and very old... is not alway possible to fix the backend... and the reverse proxy is her to manage all the "bizarry" of the backend !

**Comment by wtarreau** [comment]
I know. I've worked in such environments as well, that's where haproxy has grown to support "accept-invalid-http-response" and error captures to show the applications that they needed to fix their code. I think that the way you present it (i.e. "trusted backend") is the right one, and is a valid argument for putting that under the "accept-invalid-http-response" hat since that's precisely the purpose of this option. It also means that it will relax other checks at the same time, but after all, either you trust the backend server or you don't, and if you trust it, it's probably fine to consider that haproxy's role here is to normalize what comes out of it as long as there's no ambiguity about what is transported.

I'm reopening and will check with Christopher what can reasonably be done.

**Comment by lukastribus** [comment]
I agree with the reasoning, I just also have to mention that we are gonna get vulnerability reports for this, even when it's not the default.

Perhaps we should also transition the keyword `accept-invalid-http-response` to `accept-unsafe-http-response` and it request counterpart, to drive home the point that this is not about being pedantic about the RFCs but simply about the fact that it is unsafe.

**Comment by wtarreau** [comment]
That's a good point. I regret the choice of the term "invalid" in the past, as indeed, the word "unsafe" is probably more suitable. A bit like we have insecure-fork and such stuff so that there's no doubt about the impacts. I think that basically everything we now drop by default as invalid is only because it has safety consequences, otherwise we tend to be rather permissive as long as there's no known impact. Maybe with 3.1 we could rename the "invalid" word to "unsafe" and emit a warning for the old one.

I'm just hesitating a little bit now because some people might think that we are the ones considering them unsafe (think about Rust's unsafe for example), while "invalid" also reminds about protocol violation (i.e. if you stay on a different version that lets this pass through, you might be more exposed). I don't know if there's a term that covers both "invalid" and "unsafe". Maybe "dangerous" (maybe not) ? Or we can add unsafe to the word invalid, or "accept-unsafe-violations-in-response"; after all I don't mind having ultra-long options for such things, they're rare and those using them have to know they're taking risks (and for users like Mathieu & Alex, sometimes it gives convincing arguments to pressure applications devs to fix the code when they say "you're forcing me to work in unsafe mode"). I'm open to suggestions here.

**Comment by git001** [comment]
How about `accept-rfc-violations-in-response` this offers the option to add some options like `h1,h2,h3` so that the user can decide which rfc violations should be passed. jm2c

**Comment by wtarreau** [comment]
It's missing the "unsafe" aspect that Lukas suggested. While many of us do know pretty well that RFC violations may result in vulnerabilities, end users are rarely aware about it, and their own customers even less. When you need to argue with a hosted customer against a bad practice that may result in danger for other hosted customers, everything counts, including the options names that you can present to explain what their applications imply.

**Comment by mcarbonneaux** [comment]
generaly we relax only when detect the problem and we have no option to fix rapidly or not possible fix, and generaly only for web site that have this problem.

**Comment by mcarbonneaux** [comment]
and for the double chunked header, the best solution is to remove the second one on the fly at haproxy level (normalise) in place of blocking (when is managed by accept-unsafe-http-response or not)...

**Comment by zeugri** [comment]
> and for the double chunked header, the best solution is to remove the second one on the fly at haproxy level (normalise) in place of blocking (when is managed by accept-unsafe-http-response or not)...

If haproxy is made to accept the unsafe/rfc-invalid response at first the normalisation needed can probably be done on the fly with already implemented backend rules (in our case with a http-response del-header for example).

**Comment by lukastribus** [comment]
We are talking about request smuggling attacks, I think normalizing/cleaning automatically is not an option, it makes the vulnerability worse.

Having the option to accept the invalid requests or responses and "manually" fixing the headers with existing rules as @zeugri mentioned is going to be the solution here.


> Or we can add unsafe to the word invalid, or "accept-unsafe-violations-in-response"; after all I don't mind having ultra-long options for such things

I agree with this, its way more important to be explicit and precise than it is to have short keywords.


> While many of us do know pretty well that RFC violations may result in vulnerabilities, end users are rarely aware about it, and their own customers even less. When you need to argue with a hosted customer against a bad practice that may result in danger for other hosted customers, everything counts, including the options names that you can present to explain what their applications imply.

Exactly.

**Comment by wtarreau** [comment]
In practice since T-E is a hop-by-hop and H1-specific header, it's removed in the mux itself and will never be seen by the HTTP rules, so it will not be needed to write a rule to get rid of it. We just need to tell the mux "ok be cool, that's a friendly server that we trust, try to fix its mess".

**Comment by capflam** [comment]
Well,  we can add a new option for this purpose. Technically speaking, it is not so hard. I'm not really happy about that but with a big warning in the documentation, it may be ok. However, @wtarreau, for now, T-E and C-L headers are not removed. The info is also stored as meta-data of the message, but the headers are not removed. Mainly because someone may want to retrieve them. But it is doable of course. In that case, we should add sample dedicated sample fetches to retrieve the info. Another solution would be to remove the duplicates `chunked` value when the awful option is set.

**Comment by capflam** [comment]
I'm working on this issue to relax the header parsing on server side (but not on client side) to accept empty T-E values and several `chunked` encoding. Both are in fact related. A buggy application may add a `Transfer-Encoding: chunked` header without checking if it is already there. And trying to fix this application, the cleanup may be also buggy and empty value may be left in place.

After talking about it with Willy, we decided to put it under the `accept-invalid-http-response` option and not add a new option. It is already painful enough to deal with one option. It will be really a mess to add a new one. The documentation is already clear on the security considerations when this option is set. However, it must be updated to list all exceptions. So we can rephrase it if necessary.

In addition, the `Transfer-Encoding` header will not be sanitized during the parsing. This way, it can be retrieved via a sample fetch, for any reason. However, it is sanitized during the formatting before to send the message. It is a hop-by-hop header, so we can choose to force the value to `chunked` and removing all other values (when the message must be chunked of course).

Finally, invalid T-E header will only be possible on server side via the `accept-invalid-http-response` because the buggy server may be considered as trusted and under control. It is not true on client side. And for now, we prefer to remain strict on this point on client side.

Any objection ?

**Comment by lukastribus** [comment]
> After talking about it with Willy, we decided to put it under the `accept-invalid-http-response` option and not add a new option. It is already painful enough to deal with one option. It will be really a mess to add a new one.

I'm confused. We didn't discuss adding yet another option for this specific case here.

What we discussed was to transition `accept-invalid-http-response` to something like `accept-unsafe-violations-in-response`, so that the fact that this is unsafe is obvious as it is explicit.

**Comment by capflam** [comment]
Ok, my bad. I'm ok by renaming the options (because I guess the request side should also be renamed). But I suspect it will be hard to remove legacy names :) But at least in new versions, this will be clear.

**Comment by lukastribus** [comment]
Yes, will have to do the obsolete keyword warning/error dance for a few releases, but I think it's worth it in the end.

Same for request of course.

**Comment by wtarreau** [comment]
Yeah the point is to add it to the existing option and engage into a renaming for the long term as suggested above. Very few deployments should use the option anyway, and getting a deprecation warning could be a nice reminder to reconsider whether or not the option is still needed. I agree that for now we don't need to do it on the client side. Maybe in the future we'll find cases where application clients need such a thing, but that's so dangerous that I would, too, prefer to avoid it.

**Comment by capflam** [comment]
I will rename them to `accept-unsafe-violations-in-http-request` and `accept-unsafe-violations-in-http-response`.  A bit longer but it is important to not loose the protocol in the option name.

**Comment by capflam** [comment]
In the mean time, I pushed the fix to support serveral "chunked" value in response.

**Comment by capflam** [comment]
The doc is now updated with the new option names.

**Comment by mcarbonneaux** [comment]
![image](https://github.com/user-attachments/assets/e00744a0-3cb6-4937-afff-853f2c507155)

you specified that you fixed in 2.8/2.9/3.0/3.x but i see only commit for 2.9/3.0/3.x !?

**Comment by lukastribus** [comment]
No, the 2.8 label is still there meaning that the fix has yet to be backported to 2.8.

**Comment by mcarbonneaux** [comment]
any idea when backported to 2.8 version ?

**Comment by capflam** [comment]
Thanks for the reminder, it is backported to 2.8 now.

**Comment by mcarbonneaux** [comment]
> Thanks for the reminder, it is backported to 2.8 now.

i you sure, because i don't find the "MEDIUM: h1: Accept invalid T-E values with accept-invalid-http-response option" commit in tag 2.8 !?

**Comment by mcarbonneaux** [comment]
ok i found in your source git: http://git.haproxy.org/?p=haproxy-2.8.git;a=commit;h=62f791f44b8e825b01a644853c84b405804b2d5d

**Comment by capflam** [comment]
Yep: http://git.haproxy.org/?p=haproxy-2.8.git;a=commit;h=62f791f44b8e825b01a644853c84b405804b2d5d

**Comment by mcarbonneaux** [comment]
is juste not synchronized with github.... is wy i've not found it ! :)

**Comment by mikkorantalainen** [comment]
If anybody else reads this years later, the important part to understand is that by spec repeated HTTP headers combine instead of overwriting the previous value. For example

```
transfer-encoding: chunked
transfer-encoding: chunked
```

is identical to

```
transfer-encoding: chunked, chunked
```

which would mean that the data is encoded as `chunked` and the result of that is then encoded as `chunked`. This is analogous to 

```
transfer-encoding: deflate, chunked
```

and it should be obvious that the order of encodings is important for correct decoding. As a result, a duplicate header must not be ignored and it always a bug in the software that emits erraneous headers.
