### ISSUE TITLE
Necessity of using both 'balance source' and 'stick on src' in HAProxy configuration.

### ISSUE THREAD

**Issue by hongyi-zhao** [haproxy/haproxy#2703]
Dear HAProxy community,

I'm currently configuring HAProxy for a SOCKS5 proxy setup, particularly to handle connections to websites like https://claude.ai. I have the following configuration:

```
listen socks5
    bind    0.0.0.0:16667
    
    balance source
    hash-type consistent
    stick-table type ip size 1m expire 60m
    stick on src
```

My questions are:

1. Is it necessary or beneficial to use both `balance source` and `stick on src` in this configuration?

2. What are the implications of using these directives together? Do they complement each other, or is one redundant?

3. Given that I'm using `hash-type consistent`, how does this interact with the `balance source` and `stick on src` directives?

4. For a SOCKS5 proxy setup, especially when dealing with websites that might require session persistence, what would be the recommended configuration?

5. Are there any potential drawbacks or performance implications of using this combination of directives?

I would greatly appreciate any insights or best practices you could share regarding this configuration.

See https://discourse.haproxy.org/t/necessity-of-using-both-balance-source-and-stick-on-src-in-haproxy-configuration/10175 for the related discussion.

Thank you for your time and expertise.

Best regards,
Zhao

**Comment by einval22** [comment]
Hi Zhao, 

Thanks for reporting this.

This question is related to configuration and to the  best practices. So, it is more suitable for the Discourse HAProxy community. Here we expect to see issues, which are related to some misbehavior, crashes and may be potentially qualified and investigated as bugs. 

Thanks again for posting this question at Discourse. I'm replying you there.

I'm closing this issue here.
