### ISSUE TITLE
DSCP change without loading configuration

### ISSUE THREAD

**Issue by slux78** [haproxy/haproxy#2774]
### Your Feature Request

Hello, I am currently using haproxy 2.4.26.
When it is necessary to change DSCP, I restart haproxy after changing the configuration file or reload the configuration by sending SIGUSR2 in master-worker mode. 
However, this causes a temporary disconnection of connected connections. 
I tried to change the server of the backend using the runtime API, but currently, tos cannot be changed. 

Am I missing something that already exists in haproxy for this feature?

If not, could you please add the function to change tos using the runtime API?

The current configuration being used is as follows: Currently, the frontend, not the backend's server, sets the tos for the http response.

```
global
   nbthread 8
   stats socket /var/run/haproxy.sock mode 660 expose-fd listeners level admin
   stats timeout 2m
   tune.h2.initial-window-size 6553600

defaults
    timeout connect 60s
    timeout client 7200s
    timeout server 2h
    timeout queue 5s
    option forwardfor
    option nolinger
    mode http

frontend fe
    bind 0.0.0.0:8080 proto h2
    bind [::]:8080 proto h2
    http-response set-tos 0x14

    acl is_hello path_sub /hello
    use_backend be if is_hello

backend be
    balance static-rr
    default-server maxconn 3000
    timeout connect 3s
    timeout server 11s
    server server1  162.60.70.81:7080   proto h2 check inter 1s observe layer4 error-limit 2 on-error mark-down
```

### What are you trying to do?

I would like to send a message through a Unix socket using the runtime API in order to change the DSCP value for currently connected connections, as well as any new connections that may be established in the future.

echo "set server be/server1 tos 0xe0" | socat stdio /var/run/haproxy.sock

### Output of `haproxy -vv`

```plain
# ./haproxy -vv
HAProxy version 2.4.26-5a096a7 2024/04/05 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2026.
Known bugs: http://www.haproxy.org/bugs/bugs-2.4.26.html
Running on: Linux 5.14.0-284.79.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 9 16:36:41 EDT 2024 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = cc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1
  DEBUG   = 

Feature list : -51DEGREES +ACCEPT4 +BACKTRACE -CLOSEFROM +CPU_AFFINITY +CRYPT_H -DEVICEATLAS +DL +EPOLL -EVPORTS +FUTEX +GETADDRINFO -KQUEUE +LIBCRYPT +LINUX_SPLICE +LINUX_TPROXY +LUA -MEMORY_PROFILING +NETFILTER +NS -OBSOLETE_LINKER +OPENSSL -OT +PCRE -PCRE2 -PCRE2_JIT -PCRE_JIT +POLL +PRCTL -PRIVATE_CACHE -PROCCTL -PROMEX -PTHREAD_PSHARED -QUIC +RT -SLZ -STATIC_PCRE -STATIC_PCRE2 +SYSTEMD +TFO +THREAD +THREAD_DUMP +TPROXY -WURFL +ZLIB

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=64).
Built with OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
Running on OpenSSL version : OpenSSL 1.1.1w  11 Sep 2023
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with gcc compiler version 11.3.1 20221121 (Red Hat 11.3.1-4)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2       flags=HTX|CLEAN_ABRT|HOL_RISK|NO_UPG
            fcgi : mode=HTTP       side=BE        mux=FCGI     flags=HTX|HOL_RISK|NO_UPG
       <default> : mode=HTTP       side=FE|BE     mux=H1       flags=HTX
              h1 : mode=HTTP       side=FE|BE     mux=H1       flags=HTX|NO_UPG
       <default> : mode=TCP        side=FE|BE     mux=PASS     flags=
            none : mode=TCP        side=FE|BE     mux=PASS     flags=NO_UPG

Available services : none

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [COMP] compression
        [TRACE] trace
```

**Comment by Darlelet** [comment]
I noticed that in your example you're using `set-tos` action, which acts on the client connection, not the server one.
To achieve the same on the server side connection, `set-bc-tos` action may be used (available since haproxy 3.0).

What about using a variable or a map to fetch the tos value and update this value from the runtime API/Lua when needed?

Something like this:
```haproxy
http-request set-bc-tos var(proc.my-tos)
#or
http-request set-bc-tos var(txn.my-key),map(mymap)
```

However this would only work for newly created connections, not existing ones.
Indeed, `set-bc-tos` has to be set before the connection to the server is created (ie: during request analysis), the tos
value will remain as-is for the whole connection (from connect to close).
This is a known limitation due to the fact that connection reuse logic relies on knowing "stable" connection parameters in order to check for compatible connections in reuse pool. Also, when a connection was reused from the pool of available conns, parameters cannot be changed (because the connection may be shared for multiple streams due to HTTP multiplexing)

As such, if we wanted to be able to dynamically change the tos value on existing (already created) connection, then we would need to prevent http reuse on such connections. Perhaps we should add a new action that may update the TOS at any time, but requires http-reuse to be set on "never" policy.

**Comment by Darlelet** [comment]
>I restart haproxy after changing the configuration file or reload the configuration by sending SIGUSR2 in master-worker mode.
>However, this causes a temporary disconnection of connected connections.

Well this is not expected, by reloading haproxy the old process shouldn't break existing connections and should stay alive the time needed for ongoing transactions to be finished. (with new connections being created on the new process of course)

Behavior can be controlled with [hard-stop-after](https://docs.haproxy.org/dev/configuration.html#3.1-hard-stop-after ) and [close-spread-time](https://docs.haproxy.org/dev/configuration.html#3.1-close-spread-time
)

**Comment by slux78** [comment]
Thank you for your kind response.
The test using SIGUSR2 was done about a year ago, and the connection that was connected at that time was disconnected, so the current designed program does not use the master-worker method. 
If there is no problem with this part, please ignore my rambling and misguided master-worker method mention.

Based on the test at that time, the my current program executes haproxy in a form like fork(“./haproxy -t ...”).

Currently haproxy is used to send and receive HTTP2 messages in my client site, and the number of concurrent connections is quite high. My client asked me to add a feature could change the TOS for the connection currently using without disconnecting.

**Comment by slux78** [comment]
Thank you for explaining the hard-stop-after and close-spread-time options.
I meant that I'd like todynamically change the TOS without disconnecting connections.

It would be great if it could work on either the frontend or the backend server. 

Initially, I inquired whether it was possible to improve this method since the option control is currently done through a runtime API for the backend server.

**Comment by Darlelet** [comment]
You're welcome

>It would be great if it could work on either the frontend or the backend server.
>Initially, I inquired whether it was possible to improve this method since the option control is currently done through a runtime API for the backend server.

The current method involves actions thay can be leveraged during transaction processing which allows for different values to be set on each individual connection based on conditional ACLs. The runtime API ("commands" over cli or network socket) allows to perform tasks alongside request processing. Those are different things

Now for the reason why set-tos actions (either frontend oriented one or backend oriented one) cannot be used to "upgrade" an existing connection dynamically: as explained in my first post, this is due to the fact that connection reuse logic relies on knowing "stable" connection parameters in order to check for compatible connections in reuse pool. Also, when a connection was reused from the pool of available conns, parameters cannot be changed anymore (because the connection may be shared for multiple streams due to HTTP multiplexing). Proxies with "mode http" enabled have http-reuse enabled by defult unless the policity is explicitly set to "never".

Technically speaking however, it could be possible to add option (or dedicated new actions) that could be used to dynamically change tos/mark values on a connection, provided that the current proxy doesn't do http-reuse. Perhaps it wasn't implemented yet because the need wasn't felt until now.

**Comment by slux78** [comment]
Thank you for you kind and detail explanation.

Please consider adding runtime api of dynamic tos change for the case http-reuse option is set to never.

I'll reopen or re-request this function after checking it's ok or not to use my program with setting http-reuse to 'never'.
