### ISSUE TITLE
Please document HAProxy's Security Policy for reporting vulnerabilities?

### ISSUE THREAD

**Issue by eslerm** [haproxy/haproxy#2775]
How should security researchers report vulnerabilities to HAProxy?

Does HAProxy prefer private security reports over reporting vulnerabilities in the public bug tracker?

Often projects will include a `SECURITY.md` file to define their "Security Policy", and includes information on how to privately contact the security maintainers. If that file exists, it will show up on https://github.com/haproxy/haproxy/security

I checked the [HAProxy website](https://www.haproxy.org/#secu) and could not find this information there either.

I highly recommend setting up [GitHub Private Security Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository). This is a great alternative to using email to handle reports, and can even be used to assign CVEs and to automatically alert downstream projects who vendor HAProxy.

**Comment by git001** [comment]
> How should security researchers report vulnerabilities to HAProxy?

For the Open Source version: [Mailing list](https://www.haproxy.org/#tact)  
For the Commercial one can you use [Contact our team](https://www.haproxy.com/contact-us) or if you already a customer could I imagine that you can open a ticket on [Customer Support Portal](https://my.haproxy.com/portal/cust/login)

> I highly recommend setting up [GitHub Private Security Reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository). This is a great alternative to using email to handle reports, and can even be used to assign CVEs and to automatically alert downstream projects who vendor HAProxy.

Well, as I'm not a fan of CVE and this Blog explains pretty well what's going on with CVE [CVE-2020-19909 is everything that is wrong with CVEs](https://daniel.haxx.se/blog/2023/08/26/cve-2020-19909-is-everything-that-is-wrong-with-cves/) and the follow up [Bogus CVE follow-ups](https://daniel.haxx.se/blog/2023/09/05/bogus-cve-follow-ups/) maybe a SECURITY.md could be helpful :man_shrugging:  .

if you think that's a good idea for HAProxy can you create a Patch and send it to the [Mailing list](https://www.haproxy.org/#tact) for review .

**Comment by capflam** [comment]
In addition, if you have found something sensitive and potentially dangerous, you can contact us on security@haproxy.org as mentioned at the end of the start guide (https://docs.haproxy.org/3.0/intro.html#5).

**Comment by eslerm** [comment]
Appreciate the info! I will contact security@haproxy.org

Could security@haproxy.org be documented in a more accessible and standard place? Such as the README.md or, ideally, a SECURITY.md?

> Well, as I'm not a fan of CVE and this Blog explains pretty well what's going on with CVE [CVE-2020-19909 is everything that is wrong with CVEs](https://daniel.haxx.se/blog/2023/08/26/cve-2020-19909-is-everything-that-is-wrong-with-cves/) and the follow up [Bogus CVE follow-ups](https://daniel.haxx.se/blog/2023/09/05/bogus-cve-follow-ups/) maybe a SECURITY.md could be helpful 🤷‍♂️ .

Daniel has done an amazing job at discussing issues within the CVE Program! Especially in regards to open source projects and unwarranted CVEs (CVEs assigned to non-security issues by external parties). You may be interested in his recent talk [CVEMITRECVSSNVDCNAOSS WTF with Daniel Stenberg](https://www.youtube.com/watch?v=Uol_0kd6saA).

That doesn't mean that CVEs have no value. And Daniel himself runs a CNA and assigns CVEs to every vulnerability in Curl.

The most important value of a CVE, imo, is the CVE ID which becomes the *common name* to refer to a specific vulnerability. Anyone who wants to discuss a specific vulnerability (across bug posts, mailing lists, announcements, etc) can refer to *a* CVE ID. This is especially important for downstream projects who need to be aware that vulnerabilities exist.

@bagder would never do this, but if Curl were to "silently patch" vulnerabilities by patching vulnerabilities without assigning CVE IDs, downstreams who vendor Curl as a dependency would not be aware that these vulnerabilities exist. And then users would be left running insecure code.

**Comment by wtarreau** [comment]
Actually the security list address is in the `contacts` section of the intro file, itself referenced by the readme. I understand that you faced a difficulty to find it. We need to make it a little bit more prominent but I want to avoid too broad exposure so that it doesn't end up first in spam engines. It's critically important for a security alias not to be spam-filtered to avoid the risk of blocking valid reports.

Regarding the usefulness of CVEs... I'm on the linux kernel security list and the majority of the reports are "I found this bug please assign me a CVE". I'm used to call them "Curriculum Vitae Enhancers". 2/3 to 3/4 of them have no relation with security. I recommend this lecture by the way, by two experts of the domain: https://opensourcesecuritypodcast.libsyn.com/episode-392-curl-and-the-calamity-of-cve

Actually I consider that everything we backport in stable releases should be taken and might have security impacts for some users. I really don't want us to become our own CNA, it's a lot of extra work. If we were really to go through that pain, I'd rather automatically file entries for each backported fix in this case.

**Comment by capflam** [comment]
I'm closing now. It can be discussed on the mailing list if necessary but there is no bug here
