### ISSUE TITLE
Possible dereference of null pointers

### ISSUE THREAD

**Issue by Bbulatov** [haproxy/haproxy#2804]
### Tool Name and Version

Svace-3.4

### Code Report

```plain
Hello!
During the static analysis was found possible mistakes in code:
1) In src/hlua.c return value of a function 'hlua_stream_ctx_get' is dereferenced at hlua.c:12291 without checking for NULL, but it is usually checked for this function in other situations
2) In src/listener.c After having been compared to a NULL value at listener.c:1622, pointer 'fe' is dereferenced at listener.c:1629. If the check is carried out in the first case for the existence of fe, then in the future there may be a situation when fe does not exist and ends up in listener.c:1629, accessing the object field of the fe->task structure, which can cause an error.
Please clarify whether it is necessary to add checks here or will this be redundant?
```

### Output of `haproxy -vv`

```plain
3.1.0
```

**Comment by Darlelet** [comment]
for the hlua.c:12291, I don't think `hlua_stream_ctx_get()` can return NULL here, because if hlua is NULL in `hlua_filter_delete()`, it means the `hlua_filter_new()` failed (filter `attach` method), and in this case in the filter API is not supposed call the `detach` method... but I might be wrong. Anyway, if that's the case a BUG_ON() may surely help to show it's intended to work that way.

For the listener case: this is ambiguous indeed, nice catch! For now, it seems that `fe` cannot be NULL, but in the past we made it so that the code could work with isolated listeners (without proxies), and this was not respected in 65ae1347c7d0495c70221dca3fdda20a04d53628.

See a57786e87d0746baec43ea888bf6cd30c490d2fb and GH #1859 for more info 

I think we could fix it by simply switching from `else` to `else if (fe)` to protect the block below.

**Comment by Darlelet** [comment]
Now fixed, thanks @Bbulatov
