### ISSUE TITLE
Unexpected replacement with http-request replace-uri

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#328]
## Output of `haproxy -vv` and `uname -a`

```
Linux *snip* 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

```
HA-Proxy version 2.1-dev1-7dda20-391 2019/10/01 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_LUA=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with Lua version : Lua 5.3.1
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS
            fcgi : mode=HTTP       side=BE        mux=FCGI

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
        [FCGI] fcgi-app

```

## What's the configuration?

```
global
	nbthread 1

frontend fe_http
	mode http
	bind *:8080
	
	http-request replace-uri //+ /
	http-request set-var(txn.uri) path
	http-response set-header Test %[var(txn.uri)]

	default_backend be_http

backend be_http
	mode http
	server example example.com:80
```

## Steps to reproduce the behavior

1. `http localhost:8080/foo///bar`

## Actual behavior

```
HTTP/1.1 404 Not Found
content-length: 345
content-type: text/html
date: Wed, 16 Oct 2019 12:18:11 GMT
server: ECS (dcb/7EA7)
test: /
```

## Expected behavior

```
HTTP/1.1 404 Not Found
content-length: 345
content-type: text/html
date: Wed, 16 Oct 2019 12:18:11 GMT
server: ECS (dcb/7EA7)
test: /foo/bar
```

## Do you have any idea what may have caused this?

replace-uri does not only replace the matched part, but everything.

## Do you have an idea how to solve the issue?

No.

**Comment by wtarreau** [comment]
Do you know if it's recent ? I'm asking because we recently had to address a long-standing H2 issue related to the URI handling recently and it could be a mistake in the replace-uri modification there.

However that makes me realize that a config like yours could be impacted by such a change. What happens is that in H2, technically the browser does send the full URI in the URI field and not just the path like H1 browsers usually do except when talking to servers. Historically since H2 used to be converted to H1 we were hacking this and placing only a Host header and a path instead, to emulate an H1 request. But this is wrong as we're forging a wrong request on the other side when forwarding this. Thus now we properly set the URI as received from the client.

Note that in H1 such URIs are already valid and may already be used by clients if they want, and with proxies they have no other choice anyway.

In your case your rule will result in the // from "https://" to be replaced by "https:/" in H2 requests, which means that we also need a "replace-path" just like we have "replace-uri". But in this case there's nothing to replace the path+query string at once. I suspect we'd need to create another object, "fullpath" maybe, which includes the path and the optional query string, that we can fetch, set and replace so that users don't have to write complex regex that have to work both with and without a scheme.

**Comment by TimWolla** [comment]
> Do you know if it's recent ?

I have no idea, but I'm seeing this on HAProxy 2.0.6-2~bpo10+1 as well. I am starting to use `replace-uri` just now and worked around the issue using `http-request set-path %[path,regsub(/+,/,g)]`.

I also don't believe that using the full URI is at fault here, the issue is that the replacement also "deletes" the bits that are not even matched! Currently the match is just being used to decide whether a replacement should happen at all and what capturing groups to use. After that the replacement affects the entire string instead of just the pieces that have been matched, contrary to regular expressions elsewhere.

**Comment by capflam** [comment]
`http-request replace-uri` replaces the uri using `<fmt>` if it matches the regular expression. It is a full replacement. Not a substitution. `'http-... repplace-header` and `http-... replace-value` work the same way. So your workaround using `http-request set-path` and the converter `regsub` is the right way to do what you want.

Here there is no bug. It works as expected.

**Comment by TimWolla** [comment]
Okay, then it's a “bug” in the documentation. The wording is not exactly clear and all the examples for `replace-*` contain a `(.*)` with a capturing group to re-insert the stuff removed.

But honestly `http-request replace-uri abc 123` resulting in `123` (even without a leading slash!) whenever the URI contains `abc` sounds like a footgun.

**Comment by wtarreau** [comment]
Doesn't it support back-references using backslashes ?

**Comment by capflam** [comment]
The documentation may be more explicit, but for me there no bug in the documentation. A `replace-*` rule replaces an element (uri/full header/header value) by `<replace-fmt>` if it matches the regular expression `<match-regex>`. Nowhere the documentation says these rules apply a substitution on the matched element. However, capturing groups and back-references are supported. So it is possible to do some kind of substitution. But it is a bit limited because it is impossible to do repetitive substitutions with such rules.

In your example, when you write `http-request replace-uri abc 123`, you say: if `abc` is found somewhere in the URI, then I want to replace the URI by `123`. It sounds like a footgun if you think of it as a substitution. If you think of it as a replacement, you'll probably never write this rule. 

`http-... replace-header` and `http-... replace-value` exist since more than 5 years and, AFAIK, nobody did not complain about any ambiguities. But writing documentation is hard exercise. So if you see how to make it better, you're welcome :)

**Comment by TimWolla** [comment]
> Nowhere the documentation says these rules apply a substitution on the matched element.

The documentation says "This matches the regular expression in the URI part of the request according to <match-regex>, and replaces **it** with the <replace-fmt> argument."

It's unclear what it refers to. It could be “the regular expression match” or “the URI part”. In most programming languages a replacement using a regular expression would only replace “the regular expression match” and indeed `regsub` works like that as well.

> `http-... replace-header` and `http-... replace-value` exist since more than 5 years and, AFAIK, nobody did not complain about any ambiguities.

Probably because mostly you can get by simply prepending a `(.*)` and moving on without reporting the “issues”.

> So if you see how to make it better, you're welcome :)

Getting rid of the “it” and adding some more exactly without a “catch all” group should probably improve things. I'll look whether I can prepare a suggestion patch.

**Comment by wtarreau** [comment]
OK thanks guys! And I agree that "it" is not quite clear there. This is the price to pay when most code authors and doc writers do not use english as their native language ;-)
