### ISSUE TITLE
src/ssl_sock.c: missing break found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#339]
```
*** CID 1406467:  Control flow issues  (MISSING_BREAK)
/src/ssl_sock.c: 10028 in cli_io_handler_set_cert()
10022                           if (ci_putchk(si_ic(si), trash) == -1) {
10023                                   si_rx_room_blk(si);
10024                                   goto yield;
10025                           }
10026                           appctx->st2 = STAT_ST_LIST;
10027     
>>>     CID 1406467:  Control flow issues  (MISSING_BREAK)
>>>     The case for value "STAT_ST_LIST" is not terminated by a 'break' statement.
10028                   case STAT_ST_LIST:
10029                           if (!new_ckchs) {
10030                                   /* there isn't anything to do there, come back
10031                                    with ctx.ssl.n[1] */
10032                                   if (it == 0)
10033                                           it++;
```

**Comment by wlallemand** [comment]
It's on purpose. Thanks.

**Comment by TimWolla** [comment]
> It's on purpose. Thanks.

I suggest to add either a comment indicating this or add a loop around the switch, because the `st2` is properly updated when reaching the end of the `case`.

As it's written currently this just screams for a well-intended (but incorrect) fix later.

**Comment by chipitsine** [comment]
I marked it as intentional in coverity.  I hope it could prevent people from such fixes

**Comment by wtarreau** [comment]
I just had a look, and I agree that the way the state machine is built is slightly confusing, because the switch() statement only covers 3 states: STAT_ST_HEAD, STAT_ST_LIST, STAT_ST_END, and leaves any other state yielding, possibly looping forever, but that's not mentioned and I don't think it's intentional. At least the code doesn't permit to say whether or not other states can happen. What I'd suggest is to adjust the end so that the STAT_ST_FIN+return 1 gets out of the switch/case and catches any other state:

```
   switch (state) {
     case ...:
     case ...:
   }
   /* END gets here. Other states should never happen */
   appctx->st2 = STAT_ST_FIN;
   return 1;
yield:
```
or even replace the comment with:
```
   BUG_ON(appctx->st2 != STAT_ST_END);
```
This way, at least for the reader, it's clear that it's intentional to catch all other unhandled states.

Also the return statements are confusing because one of them says "return 1; /*success*/" and the next one says "return 1; /*error*/" thus I suspect at least one of them is wrong, or that some extra subtlety is missing there :-) To simplify and clarify the exits of the handler (especially since it involves freeing the trash), I'd suggest to jump to a dedicated label for this:

```
  } /* end of switch/case */

  chunk_appendf(trash, "\nSuccess!");
  appctx->st2 = STAT_ST_FIN;
  ret = 1; /* success */

out:
  if (ci_putchk(si_ic(si), trash) == -1)
	si_rx_room_blk(si);
  free_trash_chunk(trash);
  return ret;

yield:
   appctx->ctx.ssl.it = it;
   si_rx_endp_more(si); /* let's come back later */
   ret = 0; /* yield */
   goto out;

error:
   chunk_appendf(trash, "\n%sFailed!", err);
   ret = 1; /* error (or 0 maybe?) */
   goto out;
```

Also I suspect there is a bug with the lock, because it is not released in cli_parse_set_cert() upon error (at the "end" label). These are mostly in the case of allocation errors but not only, as it looks like trying to replace an unknown cert can also exit in error and leave the lock set. The only place where it seems to be unset is in cli_release_set_cert() which will only be called on success.

Concerning the "missing break" reported, I know that gcc 8+ became quite annoying about this, and we even disable this warning in haproxy. By default it reads comments, and it's the first time in history that the compiler bases its warnings about code on the contents of comments, which is particularly absurd when you see the number of people who can't spell "through" correctly! I don't know if coverity does the same by the way. However there's also a gcc attribute for this (but as all attributes, it will error on older compilers). I think it usually is a good practise to add a "fall through" comment to make things explicit to the reader (especially to make sure that when people reorder blocks they don't break assumptions), but sometimes it's particularly obvious that the fall through is intended. I tend to force myself to place such comments nowadays anyway to shut up gcc but am not yet willing to change existing code for this.

**Comment by wlallemand** [comment]
> I just had a look, and I agree that the way the state machine is built is slightly confusing, because the switch() statement only covers 3 states: STAT_ST_HEAD, STAT_ST_LIST, STAT_ST_END, and leaves any other state yielding, possibly looping forever, but that's not mentioned and I don't think it's intentional. 
> At least the code doesn't permit to say whether or not other states can happen. What I'd suggest is to adjust the end so that the STAT_ST_FIN+return 1 gets out of the switch/case and catches any other state:

I fixed those issues in my current branch. Thanks.
 
> Also I suspect there is a bug with the lock, because it is not released in cli_parse_set_cert() upon error (at the "end" label). These are mostly in the case of allocation errors but not only, as it looks like trying to replace an unknown cert can also exit in error and leave the lock set. The only place where it seems to be unset is in cli_release_set_cert() which will only be called on success.

Hm that's right, I thought the release was called in every case but I just verified the code and it's only called when the client close the connection or when we leave the io_handler with 1.

**Comment by wlallemand** [comment]
> > Also I suspect there is a bug with the lock, because it is not released in cli_parse_set_cert() upon error (at the "end" label). These are mostly in the case of allocation errors but not only, as it looks like trying to replace an unknown cert can also exit in error and leave the lock set. The only place where it seems to be unset is in cli_release_set_cert() which will only be called on success.
> 
> Hm that's right, I thought the release was called in every case but I just verified the code and it's only called when the client close the connection or when we leave the io_handler with 1.

In fact there was a bug there which is fixed in 90b098c (" BUG/MINOR: cli: don't call the kw->io_release if kw->parse failed")

**Comment by wlallemand** [comment]
The IO handler was rewritten to be a little more comprehensible. Thanks for your comments.

**Comment by TimWolla** [comment]
I've updated the label from “works as designed” to “fixed”. Thanks.
