### ISSUE TITLE
EBTree with variables

### ISSUE THREAD

**Issue by bobvanderlinden** [haproxy/haproxy#348]
## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 1.7.5-2 2017/05/17
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -g -O2 -fdebug-prefix-map=/build/haproxy-2dHYaz/haproxy-1.7.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2
  OPTIONS = USE_GETADDRINFO=1 USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1 USE_NS=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with OpenSSL version : OpenSSL 1.1.0e  16 Feb 2017
Running on OpenSSL version : OpenSSL 1.1.0l  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.39 2016-06-14
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with Lua version : Lua 5.3.3
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with network namespace support

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [COMP] compression
        [TRACE] trace
        [SPOE] spoe
```

```
Linux vm0146 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u1~bpo9+1 (2019-09-30) x86_64 GNU/Linux
```

## What should haproxy do differently? Which functionality do you think we should add?

Currently the `map` function can be used to match a large number of strings. As is mentioned [here](https://www.haproxy.com/blog/introduction-to-haproxy-maps/), this function makes use of ebtrees to make sure the lookup time is limited. This has a great use-case for matching HTTP paths so that paths can be mapped to specific backends.

However, a lot of paths include variable segments. For instance `/user/:user_id/keys`. For these cases you'd need to use `map_reg`, so that the strings from the map file are interpreted as regular expressions and you can match the above example using `/user/[^/]+/keys`. The documentation mentions that `map_reg` does _not_ make use of ebtree and will evaluate the expressions one-by-one. This is very slow when handling thousands of paths.

Apparently, Vulcan proxy supports such cases. See documentation [here](http://vulcand.github.io/proxy.html#route). It allows using the syntax `/user/<user_id>/keys` and still uses a tree-like structure to match such paths. Note that Vulcan also does not support using regular expressions as a tree-like structure: the `<user_id>` syntax is specific to their implementation.

## What are you trying to do?

My use-case is using haproxy as a simplified API gateway. It needs to map HTTP paths to different backends.

Is this something that is a viable feature for HAProxy?

**Comment by wtarreau** [comment]
Just to be sure, isn't it the same as map_beg(), which matches the beginning of a word and also uses a tree ? Or then it's unclear what you're trying to do, in this case a real configuration example would be preferable.

**Comment by bobvanderlinden** [comment]
Ah, you are indeed right that this would work for `/users/:user_id` specifically. However, when you have the following APIs, this will break down:

```
/users
/users/:user_id
/users/:user_id/keys
/users/:user_id/repositories
```

If there are a large number of such APIs and they all individually may direct to a different host then I'm not sure any of the `map_*` functions will suffice.

**Comment by bedis** [comment]
@bobvanderlinden you're correct, the map_* won't apply.
Any idea how vulcan works on those? Does it simply strip the user id from the string before performing lookup?

@wtarreau this is a real valid use case I see in the field too

**Comment by bobvanderlinden** [comment]
> Any idea how vulcan works on those?

I'm not sure how they handle things. I've seen projects use a trie structure.

> Does it simply strip the user id from the string before performing lookup?

I don't think that would work. You don't know what part the user_id actually is when doing the lookup.

> this is a real valid use case I see in the field too

Awesome! :D I found it really interesting that there were so little solutions to make a simple API gateway for a number of microservices. Some come close, but will fall down due to performance reasons.

That said, I was able to make something like described above using a LUA action. See this example: https://gist.github.com/bobvanderlinden/43faa3c91895e6704974d813789d67d8

It's probably not as high performing as it could be, but it does some rudimentary tree-like lookup using variables. Note though that this implementation will only work when path variables are used directly between `/` and `/`. It is not possible to have the variable match on `something/that/contains/slashes`.

For my purposes, I wanted to have a unique identifier for each URL pattern so that we can log/measure which API was called without doing funky stuff like removing variables afterwards. This is also in the example, it is called `operation_id`.

**Comment by wtarreau** [comment]
But in what situations do you really need to extract that field without pre/post processing ? I mean in all your examples it's as simple as removing /users/ and getting the next word. You've presented proposals for solutions but still not the real problem you're trying to solve. This is why I'm having a hard time trying to figure a solution :-/

**Comment by bobvanderlinden** [comment]
@wtarreau I hope to give some more context:

We have a number of applications, each with their own set of APIs. We want to provide developers a single interface for these APIs using an API gateway. Such an API gateway can be implemented using HAProxy. However, I want the API gateway to serve an unified set of APIs.

## Example

Say we have 2 applications. One that serves logs and the other serves client information.
The logs service is hosted under `log-service.internal.company.com` and serves an API under `GET /api/logs/by_client/:client_id`.
The client information service is hosted under `client-service.internal.company.com` and serves an AIP under `GET /api/client/:client_id/information`.

We want a single host to be available for all APIs. This host is called `api.internal.company.com`. It serves the APIs in a more unified manner. See:

```
GET /clients/:client_id/information        https://client-service.internal.company.com/api/client/:client_id/information
GET /clients/:client_id/logs               https://log-service.internal.company.com/api/clients/:client_id
``` 

On the left the API of `api.internal.company.com` and on the right the URL to where HAProxy should direct the request to.

Notice that there is no single path prefix that can proxy to a single service. We need to specify the full API path so that we can direct that specific API to a specific service and rewrite the path to one that the service understands.

We can compare this to an API gateway that only allows path prefixes (using `map_beg`), like is shown in [Using HAProxy as an API Gateway](https://www.haproxy.com/blog/using-haproxy-as-an-api-gateway-part-1/). Using such an API interface is possible, but it will result in a mapping like the following:

```
GET /client/*        https://client-service.internal.company.com/api/*
GET /log/*               https://log-service.internal.company.com/api/*
```

Mapping a full path prefix (like `map_beg` does) will not give us the flexibility we need: it will not allow us to map each individual API to a separate service. This will prevent us from:

* Creating an unified API interface
* Keep our current set of APIs
* Individual API migrations between services

### Creating an unified API interface

We do not have the flexibility anymore on choosing the path for each individual API. That means that our full API set will look like:

```
GET /client/client/:client_id/information
GET /log/clients/:client_id
```

This will be very confusing for developers that are consuming these APIs, as `clients/:user_id/logs` seems like a nicer path for a logs API than `/log/clients/:user_id`.

### Keep our current set of APIs

We already have an API gateway with a set of APIs available for developers to use. We want to keep that set of APIs without making the developers migrate to a different set.

### Individual API migrations between services

In the future we want to be able to migrate individual APIs from one service to another. This often happens when a service grows too large and we want to split a feature-set off to a separate application. When we are using path prefixes we need to migrate a whole set of APIs and developers. When we can match individual APIs we can migrate APIs one-by-one.

## Possible solutions

Aka: what (other) people running into the above problem will look at.

We _could_ be using regular expressions to match each individual API (using `map_reg`) and do the necessary rewrites, but this is a very unoptimised method. The documentation states:

> this doesn’t perform ebtree lookups and instead checks each line

We need performance (and flexibility) since our API gateway needs to be serving 800 APIs spread over 44 applications. So using `map_reg` is insufficient.

Luckily LUA scripting is supported and it is indeed possible to implement individual API matching with that. The initial experiments in terms of flexibility are looking bright. However, I still need to see how performant this method is. I also think that this is quite a bit of effort for most people to implement such a system in LUA. I think most people running into this issue will skip HAProxy and go for a different solution.

We have been using HAProxy for different purposes already and it has served us well. The blog series about implementing an API gateway showed me that this is indeed a viable use-case for HAProxy and thus I wanted to explore how well it fits our purposes.

Let me know whether this issue is indeed something that falls within the context of HAProxy.

**Comment by bedis** [comment]
Hi here,

I had a talked this morning with @wtarreau and it seems there was a misunderstood on your issue.
And I admit I thought I first understood it, but now I missed some part (the rewrite) :)

So you basically want to do 3 actions in that order:
- pattern matching
- HTTP routing
- URL rewriting

I think I would do this in 2 steps for now in your case:
1. in the fronted, do the pattern matching and routing to the right backend
    This can be done today by executing a few regexes to "normalize" your url before doing a lookup into the map.
    Regex to rewrite /users/123456/(.*) into /user/:userid:/\1 and store it into a variable.
    You may need a very few regexes and we can use ACLs to check if they need to be executed: 'if { path_beg /users/ } { var(txn.myroute) -m found }' 
    Then, use this variable to do a lookup in the map to find out which backend to use:
           /user/:userid:/payroll     bk_payroll
    ':userid:' is just a tag you decide.
    You can even do this by chaining 2 maps, first to do the "anonymisation" of the URL and second to do the matching. First map would be a very few regexes based on the URLs you want to expose outside

2. in the backend, do the rewrite of the Host and URL path accordingly to what your service require
    Now, in the backend, you must do your application logic and rewrite the Host and URL path accordingly to your needs.

Can you share privately with me what your URL mapping looks like so I can see if the solution above is doable?

Baptiste

**Comment by wtarreau** [comment]
Thanks a lot for the details. From the beginning I understood that you were trying to extract the client_id from the URI, but Baptiste just explained to me what you explained above as well, which is that instead you want to match everything *but* the client ID.

A correct solution I'm seeing is to first rewrite the string to replace the dynamic part with a static one, and then to lookup that resulting string from the tree. In any case you will need to be able to define where the client_id location is in the request (e.g. between the 2nd and the 3rd slash on a few URIs, may between the 5th and 6th on a few other ones). So you could then have a few regex stripping the 1st, 2nd, 3rd field depending on the prefix, and replacing it with, say, ":client_id" so that you solely end up with URIs like "/clients/:client_id/path/to/client" or "/log/clients/:client_id/foo" that are trivially looked up even if you have 800 of them, and which then are easily manageable and understandable by anyone even not directly in relation with your LB config.

**Comment by wtarreau** [comment]
our responses have crossed :-)

**Comment by bobvanderlinden** [comment]
Thanks for the response. I indeed haven't thought about reordering the path parameters in such a way that `path_beg` could still be used.

However, reordering these parameters does need a rewrite for each instance where there is a unique prefix. I checked for our APIs how many rewrites would be needed and still came on a rough 200 unique paths. I'm not sure how fast rewrites are, but it doesn't seem like an ideal solution.

Our public API specification can be found online: https://ons-api.nl/APIS.html
The OpenAPI specification can be found here: https://ons-api.nl/assets/openapi.json
There are also private/undocumented APIs that are not shown in here, but the above link does give a bit of insight in the number different instances that need to be supported.

For now I'm going to keep working on the LUA solution until it will show unusable.

That said, I do still think this is a viable use-case as there are probably other people who are using haproxy as an API gateway in front of many microservices. I'm just not sure how many people run into this with haproxy or whether they are are looking at other solutions.

**Comment by wtarreau** [comment]
Thanks for the link. Indeed you have more than 200 unique paths but my point is that we can process them using prefixes. I looked at your public API (thanks for the link, that's pretty useful by the way). There are 683 formats in it. When you ignore letters in paths you end up with this:
  - 287 entries do not carry a variable argument
  - 118 match /something/{arg}
  - 179 match /something/something/{arg}
  - 81 match /something/something/something/{arg}
  - 18 match /somethingg/something/something/something/{arg}

So that's in fact only 4 rewrite rules, not 200. You'll have one rewrite rule for requests matching the prefixes with the argument in position 2 from a file holding 118 prefixes, one rewrite for requests matching the prefixes with argument in position 3 from a file holding 179 prefixes and so on. And from there you end up with your routing table written as "/path1/path2/{}/path3/path4  backend1" in a single map file. The benefit of proceeding like this, in addition to performance, is that it remains very manageable because you can even generate the prefix files from the main one if you want.

Now I'm not saying it's not interesting to see how we could make something like this more automatic and native, I'm just thinking that we have to be careful about the way to specify the part to ignore so that it matches everyone's use case. Maybe we should improve the map_beg() converter to be able to ignore path components refered to as a special character that would be passed as a converter argument for example. This would then result in this part to be replaced on the fly during the matching so that the tree remains usable, then in front you can continue to use it to directly route the unmodified request to the appropriate backend. It would just work iteratively as a longest match method.

**Comment by bobvanderlinden** [comment]
I'm trying to come up with a way to do that with those 4 rewrite rules, but I'm failing to see how this can work correctly. I'm not sure what I'm missing.

For instance the pattern:
```
/something/{arg}
```
Matches the following regex:
```
^(/[^/]+)/([^/]+)(.*)$
```
which needs to be replaced with:
```
\1/{}/\2
```
so that the variable is replaced with a static value (`{}`), like you showed in the map file.

This would indeed correctly change:

```
/clients/123/addresses
```
to
```
/clients/{}/addresses
```
But it would also change:
```
/admin/logo_image/download
```
To:
```
/admin/{}/download
```

The rewrite rule does not know whether `logo_image` is variable or whether `123` is variable. It only knows that when you take into account the full path pattern as far as I can see.

What am I missing?

**Comment by bobvanderlinden** [comment]
Ah, I'm starting to see what you mean.

* First lookup paths without variables.
* If none are matching, replace 5th path section with `{}` and do the lookup.
* if none are matching replace 4th path section with `{}` and do the lookup.
* etc.

That would indeed help a lot already. This looks very viable indeed. Will look into this more. Thanks!

Consider this issue solved for now :+1:

**Comment by wtarreau** [comment]
On Fri, Nov 08, 2019 at 02:06:39AM -0800, Bob van der Linden wrote:
> Ah, I'm starting to see what you mean.
> 
> * First lookup paths without variables.
> * If none are matching, replace 5th path section with `{}` and do the lookup.
> * if none are matching replace 4th path section with `{}` and do the lookup.
> * etc.
> 
> That would indeed help a lot already. This looks very viable indeed. Will look into this more. Thanks!

I was seeing it even simpler with having the 4 successive
"if match then replace", involving one map file per position, but that's
indeed the principle. However your method might be easier to use and to
deploy because you can do it with a single file and it will not cost much
more, you'll always do 4 or 5 rewrites instead of one, but it remains in
a same order of magnitude. Note, you may need to proceed on a variable
instead of the URI, that would require less operations and would not
require to save the URI to restore it. You can do it using set-var, var()
and regsub().

Willy

**Comment by bedis** [comment]
Despite this issue is closed, I still would like to see a "oneliner" for this type of use case, or something very turnkey to use for devs and ops :)

**Comment by wtarreau** [comment]
I do have an idea about this one. But it will require some adaptations to
the maps to pass more than one flag to the indexing method, and a modification
of the tree to support this delimitor. The idea would be to have an extra
argument to map_beg() to take a delimitor. This delimitor would be used
while indexing and matching to purposely adapt the presented contents and
trim the parts that are present at the location of this delimiting character.

For example, map_beg(/path/to/file,@) would index these strings :

   /blog/@/images  static_backend
   /blog/@/css     static_backend
   /blog/@/js      static_backend
   /blog/          dynamic_backend

Then when presented "/blog/12345/css", the matching function would see
that a delimitor is present, would call a longest match method stopping
on the delimitor, replace the user part with the delimitor and continue
the walk through the tree, until the end.

**Comment by bedis** [comment]
Hi Willy,

I think the people requiring this use case still value the information after the delimiter, I would rather go with something like:
  /blog/@userid/images

even if you totally ignore that string when loading it into the tree.

**Comment by wtarreau** [comment]
I'm not speaking about removing everything after the delimiter, but
about using it as a mark of the place where to skip till next char.
By having :

   /blog/@/images

it is possible to make it implicit that everything at '@' must be skipped
until the next '/' character, without requiring the users to enter regex
or complex configs. This would equally work with host names, for example:

     @.mydomain.com

It would then restart after the '.'. This would also allow multiple holes
like this :

    /blog/@/images/@.jpg
    /blog/@/images/@.gif

or:

    @.@.mydomain.@

**Comment by bobvanderlinden** [comment]
I think what @bedis means it's to not just match these values, but also capture them. I think it would be possible already when we are matching, but then it is quite convoluted to also capture them using regex.

Having the value available as a variable would be ideal. Not sure if that fits @bedis view as well?

**Comment by wtarreau** [comment]
Then we're just back to point 1 where there are as many different use cases
as users and since none of them is compatible, it'd rather be done in Lua
I'm afraid. Quite honestly, what is the *real* use case of extracting the
value during the routing ? I mean, you likely need to extract it at some
point but I'm pretty sure that it's far from being 1:1 with the routing
rules, and I suspect that the demand is convoluted by an attempt to save
2 lines of configuration. Because the initial demand was basically to map
a backend name in front of a series of prefixes. And now suddenly we want
to extract the field. You'll never pass this field as part of the backend
name!

I'm fine if there are multiple, slightly overlapping use cases, but please
all try to maintain a minimum of consistency or to clearly put down the
real use cases so that we can all architect together around them. Just
adding some "it would be nice if" on top of a design which responds to a
precise question doesn't help and only results in the first one not being
addressed, which is sad.

**Comment by bedis** [comment]
I did not mean capturing anything.
I just wanted to ensure that the "matching" URL part would be friendly for the dev.

I think capture can happen only when required, at a later step (IE in the backend) and we may create a new fetch for that if we see there is a new need and to avoid using regexes. (that said, the "word" converter may already be used for this use case)
