### ISSUE TITLE
HTTP/2 request L7 capture url always absolute-URL in 2.1.0

### ISSUE THREAD

**Issue by zhangyoufu** [haproxy/haproxy#389]
## What's the configuration?

some sanity check for HTTP request
```
http-request deny deny_status 400 if !HTTP_URL_SLASH !HTTP_URL_STAR
```

## Actual behavior

HTTP/2 requests are denied, HTTP/1.1 requests are allowed

## Expected behavior

both HTTP/1.1 and HTTP/2 requests should be allowed

## Do you have any idea what may have caused this?

There is some breaking change related to L7 capture `url` for HTTP/2 requests in 2.1.0

access log in 2.0.10
```
[30/Nov/2019:05:45:28.419] https~ minio/minio 0/0/1/1/2 403 580 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
[30/Nov/2019:05:45:32.461] https~ minio/minio 0/0/1/5/6 403 580 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/2.0"
```

access log in 2.1.0
```
[30/Nov/2019:05:42:28.677] https~ https/<NOSRV> 0/-1/-1/-1/0 400 211 - - PR-- 1/1/0/0/0 0/0 "GET https://minio.example.com/ HTTP/2.0"
[30/Nov/2019:05:42:49.435] https~ minio/minio 0/0/1/1/2 403 580 - - ---- 1/1/0/0/0 0/0 "GET / HTTP/1.1"
```

**Comment by wtarreau** [comment]
Yes, this was mentioned in the announce, actually versions before 2.1
hack the H2 request to make it look like an H1 request but this causes
trouble for end-to-end H2, as it loses the scheme and authority fields.
It just turns out that on H2, requests are *really* sent in absolute-uri
form. That's a behaviour change expected from HTTP/2 clients compared to
H1, cf RFC7540 #8.1.2.3:

  Clients that generate HTTP/2 requests directly SHOULD use the ":authority"
  pseudo-header field instead of the Host header field.

As such, your request sanitization rule should only be applied to H1 and
not to H2 as it effectively blocks valid H2 traffic.

**Comment by zhangyoufu** [comment]
@wtarreau Thanks for the information.

An `OPTIONS *` HTTP/2 request is currently logged as `OPTIONS https://example.com HTTP/2.0`. While an equivalent HTTP/1 request is logged as `OPTIONS * HTTP/1.1`. This might be confusing for log auditing.

**Comment by wtarreau** [comment]
On Sat, Nov 30, 2019 at 02:29:42AM -0800, Youfu Zhang wrote:
> An `OPTIONS *` HTTP/2 request is currently logged as `OPTIONS
> https://example.com HTTP/2.0`. While an equivalent HTTP/1 request is logged
> as `OPTIONS * HTTP/1.1`. This might be confusing for log auditing.

Sure but it is exactly the way it is sent by the client and specified in the
protocol. If you check the path it will indeed be "*" because the spec mandates
that "*" is used as the path for a request using the absolute-uri form with no
path component (the path starts at the / following the authority). Actually if
that helps you, you can adjust your log format to log the method, the path and
the version, this will emulate the old behaviour. But for new deployements I'd
recommend to stick to the new one instead, as I'm sure it will become more
standard over time as the protocols evolve (and it's convenient to have the
host part visible in the logs for example).

If we manage to implement log profiles for 2.2 then we could imagine creating
different log profiles to more easily report logs in a way that is compatible
with the old way, even when dealing with modern protocols and browsers.
