### ISSUE TITLE
http-response set-header does not work if http-request redirect applies

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#4]
## Output of `haproxy -vv` and `uname -a`

```
Linux *snip* 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
HA-Proxy version 2.0-dev0-2f167b-150 2019/01/18 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_ZLIB=1 USE_THREAD=1 USE_OPENSSL=1 USE_SYSTEMD=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace
```

## What should haproxy do differently? Which functionality do you think we should add?

haproxy should respect the configuration option to add custom HTTP response headers using `http-response set-header` when I use `http-request redirect`.

## What are you trying to do?

I am redirecting the bare domain `example.com` to different subdomain `test.example.com`, but need to be able to add the `Strict-Transport-Security` header to that redirect to be able to add my domain to the HSTS preload list.

See also: https://www.mail-archive.com/haproxy@formilux.org/msg29294.html

**Comment by TimWolla** [comment]
See also this mailing list discussion where the bug was reported first: https://www.mail-archive.com/haproxy@formilux.org/msg29294.html

**Comment by TimWolla** [comment]
A reg-test reproducing the issue is the following:

```
varnishtest "http-response set-header + http-request redirect"
feature ignore_unknown_macro

server s1 {
   rxreq
   txresp
} -start

haproxy h1 -conf {
  defaults
    mode http
    ${no-htx} option http-use-htx
    log global
    option httplog
    timeout connect         15ms
    timeout client          20ms
    timeout server          20ms

  frontend fe1
    bind "fd@${fe1}"
    http-response set-header foo bar
    http-request redirect location https://example.com if { path /redirect }

    default_backend be1

  backend be1
    server s1 ${s1_addr}:${s1_port}
} -start

client c1 -connect ${h1_fe1_sock} {
    txreq -url "/no-redirect"
    rxresp
    expect resp.status == 200
    expect resp.http.foo == bar

    txreq -url "/redirect"
    rxresp
    expect resp.status == 302
    expect resp.http.foo == bar
} -run
```

**Comment by wtarreau** [comment]
Please note that this works *exactly* as designed and documented and this behavior will not change as this would break a lot of configurations. From the doc : 

  Header transformations only apply to traffic which passes through HAProxy,
  and not to traffic generated by HAProxy, such as health-checks or error
  responses.

We need to turn this issue into a feature request instead and to remove all the misleading "affects:" labels. I've personally added it to my TODO list a while ago and the problem is more a matter of configuration than anything : how do we want to make the extra header fields configurable on the redirect line ? I have some ideas on the subject but they cannot be developed in this issue as we'd lose them.

As such this issue is invalid. I don't know if we can change its description to turn it into a new feature request, or if we need to close it as invalid and open a new one.

**Comment by TimWolla** [comment]
> As such this issue is invalid. I don't know if we can change its description to turn it into a new feature request, or if we need to close it as invalid and open a new one.

I updated the description of the issue to word it as a feature request, updated the labels and hidden my previous comments. Thus the issue history is preserved, but it is no longer misleading.

> how do we want to make the extra header fields configurable on the redirect line ? I have some ideas on the subject but they cannot be developed in this issue as we'd lose them.

I really wish that it does not require a new directive and / or duplication of configuration. Possibly a [`compatility_level` setting similar to Postfix](http://www.postfix.org/postconf.5.html#compatibility_level) would allow users to opt into the changed behaviour of passing HAProxy generated traffic through the normal response (header) processing?

**Comment by wtarreau** [comment]
> I updated the description of the issue

thank you!

> Possibly a compatility_level ...

No it's not related to this, it's a matter of how the whole stuff works. There simply is not any response at all to deal with while processing requests. A redirect is in fact an error which is pushed back to the client. It would be more than a major change to do this differently. It would require redirects to be performed only on the response path and to pretend there was a response while there was not. For example your http-response rules would not be able to block undesired server responses anymore without blocking your own pre-built responses. You'd get stickiness cookies emitted after your redirects, or entries counted into stick-tables as server errors while they're not. All of this would not make sense at all. And in addition this would only help for some isolated cases without dealing with them all, at the expense of breaking a lot of user useful stuff.

I've been thinking about a few possibilities instead. The first one was to move the redirect to an applet, just like we now do for stats. But then other users will complain that they can add headers to redirects and not to deny or to error responses. And we can obviously not move everything there, for the reason that these would not be usable when dealing with responses, that having such heavy processing when blocking requests under a DoS would instead amplify the DoS, and that it would still cause lots of confusion with headers processing rules having to apply both to servers and internally-generated traffic. By the way we already support "http-response redirect" and it couldn't be supported this way.

The other idea I was having on the subject, since it's most always a matter of adding headers, would be to implement the notion of headers list. These would work exactly like variables except that we would use them as a collection of headers to be added to a request or response at the end of the processing. This would allow to improve almost all request/response processing regardless of their direction and the fact that they are final rules or not.

It could look like this : 
      http-request add-header-list(res) Server Foo
      http-request add-header-list(res) HSTS bar

and later, a final rule could optionally make use of them : 
      http-request redirect location /overthere hdr-list res
or : 
      http-request deny code 429 hdr-list come-back-later if [ condition ]

We could even imagine supporting them for addition at the end of a number of rules :  
      http-request add-headers-from-list list-name

We could later imagine having some specific lists always added with certain error responses, such as "error", "error403" etc. For errors it would still be limited by the fact that some errors are produced outside of the rules path. But we also know that there's been a long demand for error page templates so that could be addressed there.

So we need to put more thinking into this in my opinion, and this is a design discussion that should move to the list. We can keep this entry open so that we don't forget this item.

**Comment by TimWolla** [comment]
This is resolved with `http-after-response set-header` in 2.2.

**Comment by lukastribus** [comment]
That's commit 6d0c3df ("MEDIUM: http: Add a ruleset evaluated on all responses just before forwarding"), and it's in v2.2-dev2.

@capflam @wtarreau How intrusive do you feel like this patch is? I'm wondering if we could backport this, maybe just to 2.1? This seems like an important feature, that people requested over the years.

*If* this is backported, we need to make sure the backported documentation explains when this feature has been introduced in that stable branch, otherwise people won't understand why it won't work for their older release (for example, the doc for the 2.1 branch should mention that this is supported since `2.1.4` - if we backport before that point release).

**Comment by capflam** [comment]
Well, this commit directly depends on few others but looking more deeply, it is based on the refactoring of the HTTP actions and part of refactoring of the errorfiles. So to backport this feature, around twenty patches or more must be backported too. Honestly, it is too much pain :) The 2.2.0 is coming soon. It could be a good reason to upgrade.

Anyway, for now, I'm busy on the checks refactoring. But if there is really a demand for this feature in 2.1, the best will be to work on a specific patchset. But it should be discussed with Willy first :)

**Comment by wtarreau** [comment]
I'm not against a backport into 2.1 however we must be careful not to break it. Knowing that it relies on 20+ patches doesn't reassure me. If we could have a "quick and dirty" alternative I'd be less worried. Also it's worth keeping in mind that the time invested on backports is not invested on development, so we must weigh this as well :-/

**Comment by lukastribus** [comment]
I was unaware of the dependencies, I fully agree to not backport then.

It would have been different if the patch was enough standalone, but not with that amount of changes required.
