### ISSUE TITLE
Haproxy  Add one more x-forwardfor-for when add “option forwardfor”

### ISSUE THREAD

**Issue by jagerzhang** [haproxy/haproxy#44]
version  1.7.8
Host： 192.168.1.101
Haproxy configuration

```
global
    daemon
    maxconn 100000
    stats timeout 2m
    pidfile /tmp/http.pid

defaults
    timeout http-request 10s
    timeout server 120s 
    timeout client 20s 
    timeout connect 4s 
    timeout tunnel 30m
    retries 3
    balance roundrobin
    option abortonclose
    option forwardfor    # Forward X-Forwarded-For
    option redispatch

frontend http
    bind :80
    mode http
    default_backend  test_svr

backend test_svr
    mode http
    server 192.168.1.102:8080 192.168.1.102:8080
```

The request Header info:
```
GET /api HTTP/1.0
X-Forwarded-For: 192.168.1.10, 192.168.1.11  ---> from request  
Proxy-Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36 /2.2.1.8
Accept-Encoding: gzip
X-Forwarded-For: 192.168.1.101  ---> Haproxy Added.
```

**Comment by git001** [comment]
Please can you try to use a more recent version, maybe 1.9.4, to be on the save site that this but is still in the current versions, thanks.

If you want to stick to 1.7 then please use the latest 1.7.

http://www.haproxy.org/bugs/bugs-1.7.8.html

**Comment by jagerzhang** [comment]
> Please can you try to use a more recent version, maybe 1.9.4, to be on the save site that this but is still in the current versions, thanks.
> 
> If you want to stick to 1.7 then please use the latest 1.7.
> 
> http://www.haproxy.org/bugs/bugs-1.7.8.html

Thanks for reply, There are two x-forwarded-for too where i try version 1.94
last time， i add the arg  `if-none` Solve the problem first.
I think all version has this bug，you could try request with x-forwarded-for.

**Comment by capflam** [comment]
It is expected and documented. See https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4.2-option%20forwardfor:

> This header contains a value representing the client's IP address. Since this header is always appended at the end of the existing header list, the server must be configured to always use the last occurrence of this header only.

Note also than multiple headers with the same name are semantically equivalent to a unique one with comma-separated values.

**Comment by jagerzhang** [comment]
thanks @capflam 
as your reply:
> Since this header is always appended at the end of the existing header list, the server must be configured to always use the last occurrence of this header only.

I think haproxy should add this owner ipaddress at the end off existing x-forwarded-for list, but not add a new same x-forwarded-for item.  

> Note also than multiple headers with the same name are semantically equivalent to a unique one with comma-separated values.

But many programs cannot  normal read the multiple headers with the same name， like packetbeat of elasticstack or `get_header('X-Forwarded-For')`  in twisted. 

 example：packebeat read messy code when header has two  X-Forwarded-For：
![image](https://user-images.githubusercontent.com/9711651/53137986-c6b09e00-35bf-11e9-9f06-afaacc8e7051.png)

**Comment by wtarreau** [comment]
Then you need to file bug reports for these buggy programs. What haproxy does is 100% compliant to the HTTP spec. HTTP says that a header field may appear multiple times if and only if it is defined as a comma-delimited list of values. Thus if your programs are having trouble reading this field, it means they will be unable to properly parse a list as well, and in all cases they are not HTTP compliant. Given that your capture above shows series of zero characters, I even suspect that your program might be vulnerable to attacks.

What you can do in the mean time to work around this bug is to make haproxy remove the existing x-forwarded-for headers using an "http-request del-header x-forwarded-for" rule.

**Comment by jagerzhang** [comment]
@wtarreau Thanks a lot.

**Comment by git001** [comment]
@jagerzhang is this issue now solved?

**Comment by jagerzhang** [comment]
> @jagerzhang is this issue now solved?

@git001 
Yes，I guess. Thanks all~
last time， i add the arg `if-none` to reject haproxy add x-forwarded-for header.
After all, I can't change the open source program like packetbeat.

**Comment by wtarreau** [comment]
Warning, if you use "if-none", haproxy will not add one if it is already present. Only use this if this header is added by YOUR infrastruture (i.e. another level of proxy before haproxy). Otherwise it will let clients set whatever they want! If you want haproxy to always set this header and remove the previous one, better delete it in the frontend using "http-request del-header x-forwarded-for".

**Comment by lukastribus** [comment]
Another alternative would be to use `http-request replace-value`, to adjust the existing header manually. Combined with a `if-none` enabled option `forward-for` directive, this would cover all cases.

But as always, do consider that everyone can set this header, so you need to know when to trust it.

Closing this as it works as expected, I suggest to switch to ML or discourse for further discussions about the workaround.

**Comment by mcarbonneaux** [comment]
x-forwarded-for are not rfc standard... and this header is a de-facto standard...
https://en.wikipedia.org/wiki/X-Forwarded-For 

as defined on mozilla site : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

only acceptable form is to add at the end... all reverse proxy/ LB/ADC use it in this way...

all softwre reading this header read it in this form... and are not abel to read multiple header http rfc form....

for examble tomcat ip valve are not abel to read this header in haproxy http rfc form...
https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html 
https://tomcat.apache.org/tomcat-8.5-doc/config/valve.html#Remote_IP_Valve
tomcat read the last header not the seconds one...

and when chain multiple proxy... haproxy overwrite the x-forward-for by adding a second one ... and tomcat read only the client ip of the haproxy second header not the first client ip of the chain...

if-none is not satisfesant because they not add haproxy ip if header is present...

an rfc has been added a standardised equivalent form of this defacto header... 
https://tools.ietf.org/html/rfc7239 
but quasi all software needing this information dont know this rfc... 

they need the two form of this header.... the HTTP RFC one if you realy want to support it (http rfc compliant but none are supporting it...)... and the defacto one (supported by every one)......

why not add option to select the form (multiple header or one line header form) ?!

**Comment by wtarreau** [comment]
Yes and all the examples you cited are perfectly in line with the HTTP standards and with what we do : RFC7230 : 

  "A sender MUST NOT generate multiple header fields with the same field
   name in a message unless either the entire field value for that
   header field is defined as a comma-separated list [i.e., #(values)]
   or the header field is a well-known exception (as noted below).

   A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.  The order
   in which header fields with the same field name are received is
   therefore significant to the interpretation of the combined field
   value; a proxy MUST NOT change the order of these field values when
   forwarding a message."

As you can see, haproxy emits this header this way because it is used as a comma-delimited list which is semantically equivalent. And all the examples you cite are perfectly compatible with this. Also, we've been doing this (like other components too by the way) for about 18 years now and I still have to be pointed to a mainstream software that has trouble parsing this because all mainstream software follow HTTP standards nowadays.

The reason for doing it the way it's done is because the alternative you propose is way slower : you first have to look for the last instance and only append to this instance, moving the tail. And possibly fold the other existing instances if any. For lots of people dealing with static servers or fast dynamic servers, wasting hundreds of nanoseconds looping on headers for ZERO added value (or to work around elementary server bugs) is not acceptable.

Now when the server is not HTTP compliant, as mentioned it's always possible to rewrite the header using one http-request rule, so there is really zero reason for annoying all users with slow operations when these users have properly working setups and others can write a rule. It's true however that most people having non-standard servers usually do not care about performance and can run 2 or 3 orders of magnitude below others, so this argument is not always understood, but believe me, some people do really care.

**Comment by mcarbonneaux** [comment]
OK but you have the option if-none that check the header... No? Why not add option arg to specify the way to add this header? (append at the end or add second one)... Is simpler than rule... 

All other proxy implementation do append (commercial or open source) and not add second header ... Why you no?

In my case haproxy are used in ingress container on k8s behind edge reverse proxy and in front of k8s tomcat container ... And I need to have the complete proxy chain in x-forward-for ... In that case the normal option does not work as expected ... And I've lost many time to understand why....

And in my case I've no probleme to lose some ms in checking one header.... And if had a option the only who add this options while check this header and loose some ms but it's a choice to loose it...

And if you add x-forward-for header and one exist... Is not safe... Beceause you the old one in place... Some time must be abel to overwrite when you are the first endpoint... To not trust the header send from untrusted host...in this way I think a overwrite option while be good...

In fact thay are two principal use case:
- when you are in front you must overwrite (not trust unknwo host) ...
- And when you are behind proxy chain you must append... Because the who who read this header while read it in this format...

Append second header (you are behind proxy chain but who who read this while not Abel to do) or send the header if-none (you trust unknown x-forward-for and forward it and not add the haproxy client ip) are not the général case in fact...

In fact is not performance problem or rfc compliance problem (it's not rfc standard, it's defacto standard) but general usage problem and defacto standard compliance .... 

This option as it's implemented are completely useless (but performant) ... In conclusion to implement correctly x-forward-for as all implement it in all case you must use http rewrite rule...

**Comment by wtarreau** [comment]
I'm sorry but it seems difficult to communicate with you in face of so many bold statements.
- "all other proxy implementation do append ..." => just the 3 first that come out of my head : Alteon (commercial), Stud (open source, now hitch), Stunnel (open source) do add a header field at the end of the headers.
- "adding xff when one exists is not safe" => it definitely is, because it is a list. And modifying the first one when two already exists is not safe however!
- the overwrite option already exists and was mentioned above multiple times
- while the XFF header itself is a de-facto standard, dealing with header lists _is_ RFC standard. The simple fact that this field appears in the header part of an HTTP request mandates that it follows the standards (dictated by 7230 and 7231).

I totally agree with your two use cases (front/behind), and that's how most people use it. The "if-none" option is for those having two possible paths in their infrastructure and is not recommended at all.

The fact that you claim the option is completely useless makes me think you didn't understand how to use it because the vast majority of configurations I've seen disagree with you here.

Thus to summarize, in case you're forced to use a bogus server that doesn't correctly parse HTTP headers : 
  - if you want to _replace_ xff : 
        http-request del-header x-forwarded-for
        option forwardfor
  - if you want to _append_ to an existing xff line : 
        http-request replace-value x-forwarded-for ^ "%[hdr(x-forwarded-for)], %[src]"

In all other cases, just use "option forwardfor" and you'll be good.

**Comment by jagerzhang** [comment]
> I'm sorry but it seems difficult to communicate with you in face of so many bold statements.
> 
> * "all other proxy implementation do append ..." => just the 3 first that come out of my head : Alteon (commercial), Stud (open source, now hitch), Stunnel (open source, now "Hitch") do add a header field at the end of the headers.
> * "adding xff when one exists is not safe" => it definitely is, because it is a list. And modifying the first one when two already exists is not safe however!
> * the overwrite option already exists and was mentioned above multiple times
> * while the XFF header itself is a de-facto standard, dealing with header lists _is_ RFC standard. The simple fact that this field appears in the header part of an HTTP request mandates that it follows the standards (dictated by 7230 and 7231).
> 
> I totally agree with your two use cases (front/behind), and that's how most people use it. The "if-none" option is for those having two possible paths in their infrastructure and is not recommended at all.
> 
> The fact that you claim the option is completely useless makes me think you didn't understand how to use it because the vast majority of configurations I've seen disagree with you here.
> 
> Thus to summarize, in case you're forced to use a bogus server that doesn't correctly parse HTTP headers :
> 
> * if you want to _replace_ xff :
>   http-request del-header x-forwarded-for
>   option forwardfor
> * if you want to _append_ to an existing xff line :
>   http-request replace-value x-forwarded-for ^ "%[hdr(x-forwarded-for)], %[src]"
> 
> In all other cases, just use "option forwardfor" and you'll be good.

Tks，It seems all right, I will try it later.

`http-request replace-value x-forwarded-for ^ "%[hdr(x-forwarded-for)], %[src]"`

**Comment by mcarbonneaux** [comment]
I already know how to do with rule...

But why developt "option forwardfor" that does not work as majority expect... 
Majority expect the MAY alternative of the rfc ... ok is not perfomant as you want...
But if you are oblige to use rule to do the work... that is not performant as you say...
i think it can be less performant as "option forwardfor" than rule....
Because is the form that the majority of web application expect (is partialy rfc compliante)...

Is more readable to write :
```
option forwardfor force
```
In place of
```
http-request del-header x-forwarded-for
option forwardfor
```

Or by default overwrite (more secure by default) ... Because you have already if-none to not overwrite in case of.... 

And is also more readable to read :
```
option forwardfor append
```
Than 
```
http-request replace-value x-forwarded-for ^ "%[hdr(x-forwarded-for)], %[src]"
```

Sorry but my alteon append... My F5 do also... My pulse vadc also... And my apache and nginx do the same... Appending at the end... And tomcat and jetty read in append form (because they not implement multiple header with the same name as one with coma...) ... And I've not verifyed but I think php work as same (are sapi dependant I think) ...

You think apache httpd/nginx/tomcat/jetty are not enough used?

You are a proxy, and you must implement as the rfc OK, but you must work fine with potential backend as they implemented the rfc and the defacto standard...

**Comment by lukastribus** [comment]
`req.fhdr` should be used instead of `hdr` and `replace-header` instead of `replace-value` to avoid unnecessarily parsing the header and support more than one incoming value in the header.

    http-request replace-header x-forwarded-for ^ "%[req.fhdr(x-forwarded-for)], %[src]"


(from https://discourse.haproxy.org/t/appending-to-the-xff-header-does-not-work-as-expected/6415/3)

**Comment by mcarbonneaux** [comment]
@wtarreau 
> As you can see, haproxy emits this header this way because it is used as a comma-delimited list which is semantically equivalent.

haproxy is partialy compliant with http standard because is conforming only on multiple header way of the http standard...
and mainstream software that only support coma way of doing are also partialy compliant of the http standard....

but haproxy are reverse proxy and must abel to address the two way of the standard... specialy because many backend program chose one of them not the two (because x-forward defacto standar is defacto... and not real standard...)... 

ok you chose the performance way of doing, but not the more compatible way of doing... and not completly compliant...

and is why a say that `forward` option must work in the two way of doing of the standard to be more compatible with majority of backend... event is the default way in haproxy is to append header for performance... and eventualy to explain in the documentation to the user that coma version are less performant but more compatible with legacy program...
