### ISSUE TITLE
External check incurs high CPU usage (> 100%)

### ISSUE THREAD

**Issue by rdev5** [haproxy/haproxy#45]
## Output of `haproxy -vv` and `uname -a`
```
HA-Proxy version 1.7.8 2017/07/07
Copyright 2000-2017 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux26
  CPU     = x86_64
  CC      = gcc
  CFLAGS  = -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv
  OPTIONS = USE_LINUX_SPLICE=1 USE_TPROXY=1 USE_LINUX_TPROXY=1 USE_LIBCRYPT=1 USE_GETADDRINFO=1 USE_ZLIB=1 USE_CPU_AFFINITY=1 USE_ACCEPT4=1 USE_NETFILTER=1 USE_GETSOCKNAME=1 USE_OPENSSL=1 USE_PCRE=1 USE_PCRE_JIT=1 USE_TFO=1 USE_PIE=1 USE_STACKPROTECTOR=1 USE_RELRO_NOW=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with OpenSSL version : OpenSSL 1.0.1i-fips 6 Aug 2014
Running on OpenSSL version : OpenSSL 1.0.2j-fips  26 Sep 2016 (VERSIONS DIFFER!)
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports prefer-server-ciphers : yes
Built with PCRE version : 8.33 2013-05-28
Running on PCRE version : 8.39 2016-06-14
PCRE library supports JIT : yes
Built without Lua support
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [COMP] compression
        [TRACE] trace
        [SPOE] spoe
```

## What's the configuration?

```
global
maxconn 2000000
daemon
nbproc 1
cpu-map 1 0
stats socket /var/run/haproxy.sock mode 777 level admin
external-check

defaults
maxconn 2000000
mode http
balance source
retries 3
timeout connect 10000
timeout client 45000
timeout server 60000
option dontlognull
option redispatch
option forwardfor 
option http-server-close

listen app-https
bind ... ssl ...
balance source
mode http
option httpclose
option forwardfor
# option tcp-check
option external-check
external-check path "/usr/bin:/bin"
external-check command /bin/true
server app1 ... backup check ssl ... fall 3 rise 5 inter 10000 weight 10
server app2 ... check ssl ... fall 3 rise 5 inter 10000 weight 10
```

## Steps to reproduce the behavior

1. We have 100+ servers spanning 70+ TCP/HTTP(S) groups specified with various ACLs, etc. running in production with a normal load average of 0.40.
2. The moment we switch one of our HTTP (SSL) services from either `httpchk` or `tcp-check` to an `external-check` and reload, we immediately begin to see CPU load skyrocket to 2.2-3.2 with real-time peaks observed at 4.1+ at times.
3. Reverting the check brings CPU load back down to normal averages

## Actual behavior

We have a monitor script that auto-refreshes every 5 seconds, reporting `uptime` amongst other things.

- At present, an external check which invokes **/bin/true** sits right at 2.0-2.4 load average.
- A shell script that collects arguments and HAPROXY_ environment variables and does `exit 0` was observed to be in the mid-3.0's load average range.

## Expected behavior

I would expect external checks to exhibit similar performance to other checks, something with a < 1.0 cumulative load average.

## Do you have any idea what may have caused this?
I'm still poring through haproxy's source code and commit history at this time, but feel it's related to some sort of blocking going on. A separate visual monitor very consistently shows CPU spike at 10s intervals as configured; CPU returns to near 0% utilization when the external check completes.

## Do you have an idea how to solve the issue?
Several [unverified] possibilities:
- Spreading health checks or increasing check frequency
- Review how commands are being invoked and whether some other blocking is in effect
- External checks appear to be forked to child PIDs; again, I'm still validating this. Whether it is or isn't, perhaps getting the forked PID out of the event multiplexing flow and allowing it to run on its own. The command should be wrapped with some agent responsible for writing the exit code to a memory address (in-memory caching?) which haproxy can poll for in a much lighter-weight manner and manage server states accordingly. Perhaps this is already implemented in the current event scheduling system. I only share it as a solution I can relate to based on a separate Javascript project (also single-threaded) where I needed basic "multi-threading" functionality.
- The actual external check itself is a shell script which executes several `curl` commands. I may be interested in profiling performance of a binary as an alternative to an interpreted shell script ([example](https://curl.haxx.se/libcurl/hiper/app.html))

**Comment by rdev5** [comment]
Don't suppose it might have anything to do with this `while` loop...?

https://github.com/haproxy/haproxy/blob/master/src/checks.c#L1973-L1974

**Comment by TimWolla** [comment]
@rdev5 Can you check what type of load it is? Is HAProxy running at 100% or is the bulk of the load generated in the kernel?

If it's HAProxy: Try getting a flame graph (http://www.brendangregg.com/FlameGraphs/cpuflamegraphs.html). You might need to install debug symbols for libssl / other shared libraries to make sense of it.

If it's the Kernel: Maybe fork + exec is slow on that machine?

**Comment by wtarreau** [comment]
Tim, I think you're right about the loop, given the high maxconn value in the config, it certainly takes time.
@rdev5 do you *really* need such a high value ? I doubt it given that you have a single process. 2 million concurrent connections with SSL would eat tens of gigs of RAM... Thus if possible, please try to set this to a more suitable value and see if it improves things.

There's unfortunately no clean solution to know the highest number of used FD, nor the list of used FDs. Some BSDs have a closefrom() syscall to replace this loop in a more efficient way, but that's all.

**Comment by TimWolla** [comment]
> Tim, I think you're right about the loop,

You want s/Tim/Matt/ here.

**Comment by wtarreau** [comment]
Ah yes, I claim ENOCOFFEE :-) I've read it as part of your response.

**Comment by git001** [comment]
@rdev5 there is a blog post about a similar setup for ~2M ssl connections, maybe it helps.

https://medium.freecodecamp.org/how-we-fine-tuned-haproxy-to-achieve-2-000-000-concurrent-ssl-connections-d017e61a4d27

**Comment by wtarreau** [comment]
@rdev5 I managed to implement a faster closefrom() call by abusing poll(). It skips over closed FDs and only closes the active ones. Poll() still takes a bit of time to return the list, but in my case I'm seeing that it roughly doubles the performance, scanning about 12 million FDs per second at only 5% CPU on my machine. I think it could reasonably easily be backported if you want to try it, you need these 3 patches from mainline : 
  - 2d7f81b8
  - 2555ccf4
  - 9188ac60
With this said you still need to be careful about your number of concurrent connections. Also it's worth keeping in mind that some external programs might as well close all FDs once started, and the large value will be inherited. This is something which could be improved here though.

**Comment by wtarreau** [comment]
I've changed the type to "help-wanted" and the status to "works as designed" because the huge number of FDs multiplied by the number of servers and the frequency of the forks provokes this. It doesn't mean we shouldn't try to further improve the situation, as indicated by the patch above trying to implement closefrom() on operating systems missing it, but the situation is indeed expected from the configuration.

**Comment by TimWolla** [comment]
> on operating systems missing it

Is that “missing it” correct? I believe you never actually use `closefrom`, even if available.

**Comment by wtarreau** [comment]
I have not yet done the native closefrom() because it will require another build option and was not needed for Matt. I really wanted to provide him with a quick thing he could try. I'll check with Olivier to get a working native closefrom() implementation that works on *BSD and may try again on Solaris once I repair my old Sun.

But the purpose of the patch clearly was to have an equivalent to closefrom() which is faster than the close() loop for those who don't have closefrom().

**Comment by mattborja** [comment]
@wtarreau Sorry for the delayed response. I'll won't be in the office until at least Monday to test (barring inclement weather), but will certainly give it a shot.

I also know that our `maxconn` is set a bit high, which incidentally was based off that article linked by @git001; our OS was tuned accordingly as this is sort of a "shared" load balancer that serves a variety of backends and I didn't want it becoming a bottleneck unnecessarily.

Will look through the patches and try to get to this Monday.

Thanks!

**Comment by wtarreau** [comment]
OK, thanks.

Keep in mind that it won't solve everything though. The patches will just cut the close time in half which might still be too much. But whatever the solution, the system still has to iterate over all of the process' fd table before the exec. I really think that this is a good example of why external checks can be a really bad thing, they cannot mix well with high fd count. Using an agent would be much better. We could even imagine removing this feature and having a separate, dedicated process forked by the master process which would deal with agent requests and turn them them to fork+exec to emulate the current external checks. At least I think we need to add some doc to explain such side effects so that nobody gets trapped into this again.

**Comment by robertomczak** [comment]
Hi,
I'm currently looking into long seamless reload time of HaProxy with 0 sessions active.
Our setup uses external-check as well. 
During investigation I've observer lots of EBADF (Bad file descriptor) in strace of HaProxy. (Attachment). [strace_17775.txt](https://github.com/haproxy/haproxy/files/2898249/strace_17775.txt)
For testing purposes our external-check command was replaced with /bin/true. 

Looks that issue with long reloads time can be related to issue covered here. 

Any idea when improved FDs handling might come to HaProxy ?

**Comment by wtarreau** [comment]
It's not an issue, it's the only way to close *all* open FDs. The patchset above aims at improving the situation by detecting those which are closed and skipping them. But anyway they have to be scanned by the kernel and nothing is free. We've already merged the patches above to improve the situation, but really, the next step ought to be to remove external check support if that causes so many issues.

**Comment by rdev5** [comment]
@wtarreau Hi William, I'm looking to get back into this hopefully this morning sometime. In the mean time, as you consider potentially removing external check support, I wonder if perhaps it would be possible to support a form of `remote-check`; something akin to polling an external URL with the same set of environment variables (i.e. `HAPROXY_SERVER_ADDR`, `HAPROXY_SERVER_PORT`, etc.) as request headers, query string parameters, etc.

**Comment by rdev5** [comment]
I suppose we could make it work with `agent-check` but it does make it much less maintainable. We really don't want "too many cooks in the kitchen" writing socket programs and scheduling cron jobs on our production load balancers and would prefer to stick with editing a single **haproxy.cfg** file that we can keep under source control.

**Comment by rdev5** [comment]
@wtarreau Sorry for the delay getting back to you on this; had to rebuild a new openSUSE image to do this.

I built, configured, and ran haproxy, profiling server `uptime` both before and after the patch and there is a definitely a **huge difference**!

Before the patch (at f131481):

```
$ while true; do uptime; sleep 1; done
...
up 0:28, 1 user, load average: 3.21, 2.92, 2.39
```

After the patch (at 2292edf6):

```
$ while true; do uptime; sleep 1; done
...
up 0:28, 1 user, load average: 0.07, 0.08, 0.03
```

Reverting the patch reproduces the issue. Also, I didn't test the individual patches, just the two snapshots mentioned above.

Thanks for looking into this for us and a quick turnaround.

How should we proceed from here?

**Comment by wtarreau** [comment]
Hi,
thanks for the feedback. If you have that much a difference, it means you're very close to the limit above which your checks are frequent enough to constantly have some close() calls running. I've just pushed to the master branch a few other patches which restore the initial limits before execing checks. This will make sure your external scripts or equivalent are not in turn wasting their time closing all fds.

We might consider backporting the closefrom() calls to recent branches, but I'm not a big fan of backporting that to older, very stable, branches, because any change always presents a risk of regression and if other people don't have this problem they won't value this improvement. Would you have any objection to upgrading to latest 1.9 if we backport it there ?

Regarding the possible removal of the feature in the long term, it's not planed yet but it definitely deserves some thinking. One clean way I'm thinking about would be to rely on the master process in master-worker mode. The workers could simply communicate with the master and the master would fork-exec the commands itself. This would also solve the chroot and permission issue, as you could still keep your workers secure. That's just an idea of course.

**Comment by rdev5** [comment]
@wtarreau Alright, so after talking with our vendor, they're willing to move up to 1.9 on their new image slated for release at the end of this month. If it could be backported there by around that time, that would be ideal.

**Comment by wtarreau** [comment]
Given this one was 7 months ago and didn't require any updates, I guess it's safe to close now.
