### ISSUE TITLE
src/ssl_sock.c: logically dead code found by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#451]
```
5833 read_error:
5834        fclose (fp);
    null: At condition capkey, the value of capkey must be NULL.
    dead_error_condition: The condition capkey cannot be true.
    CID 1306899 (#1 of 1): Logically dead code (DEADCODE)dead_error_line: Execution cannot reach this statement: EVP_PKEY_free(capkey);.
5835        if (capkey) EVP_PKEY_free(capkey);
5836        if (cacert) X509_free(cacert);
5837 load_error:
```

**Comment by wdauchy** [comment]
this one would mean to remove:

```
diff --git a/src/ssl_sock.c b/src/ssl_sock.c
index 124b2c60..af274663 100644
--- a/src/ssl_sock.c
+++ b/src/ssl_sock.c
@@ -5835,7 +5835,6 @@ ssl_sock_load_ca(struct bind_conf *bind_conf)
 
  read_error:
 	fclose (fp);
-	if (capkey) EVP_PKEY_free(capkey);
 	if (cacert) X509_free(cacert);
  load_error:
 	bind_conf->generate_certs = 0;
```

which would be correct as capkey will never need to be free because this is the last statement where an error could occur. But if we later modify this function and add other statement after which ends on read_error, we might simply forget to re-add this needed free on error. So I'm not sure this is worth doing this patch.

@capflam WDYT? as we were the one handling the main work around this function

**Comment by wtarreau** [comment]
Agreed, personally I'm not at all for removing temporarily dead code in
error processing or cleanup paths, it's the best way to introduce bugs
later when extending the code.

**Comment by chipitsine** [comment]
I will mark this as "intentional".
