### ISSUE TITLE
Feature request : cache purge

### ISSUE THREAD

**Issue by aderumier** [haproxy/haproxy#452]
Hello,

I would like to known if cache purge is on the roadmap ?

Be able to purge a specific url (or better with regex) from the cache.

Through socat  or maybe with HTTP method PURGE.

**Comment by wlallemand** [comment]
Hello,

When we integrated the cache in HAProxy, we wanted a really light cache in memory that could be used with small objects and a short expiration time. When we first designed it, we called it the "favicon cache". This cache could be used together with a full-featured cache like Varnish, but we never wanted to be a full-featured cache with complex rules and administration. That's why it was decided with @wtarreau to limit the features so people don't use it as a full-featured cache, and that limit began with the purge feature.

So, no, it's not on the roadmap and will probably never be. The only way to purge the cache is to reload or restart the process.

**Comment by uasan** [comment]
> So, no, it's not on the roadmap and will probably never be. The only way to purge the cache is to reload or restart the process.

Is a list of cache improvements https://github.com/haproxy/haproxy/issues/214, may appear on the roadmap?
Thanks.

**Comment by wtarreau** [comment]
I've not seen any submissions around this recently nor anyone stepping up to work on this.

**Comment by mr-manuel** [comment]
@wlallemand is this now possible or not? Found nothing in the latest documentation (http://cbonte.github.io/haproxy-dconv/2.5/management.html#9.3).

**Comment by wlallemand** [comment]
@mr-manuel please read my comment above. As mentioned, we never intended to implement this feature.

**Comment by bilogic** [comment]
> So, no, it's not on the roadmap and will probably never be. The only way to purge the cache is to reload or restart the process.

Both restart and reload did not clear the cache. Can share where it is stored on the disk? Thanks.

**Comment by wtarreau** [comment]
> Both restart and reload did not clear the cache. Can share where it is stored on the disk? Thanks.

You see, that's exactly why I don't want to implement a persistent cache: there's **no storage**, yet some users believe data remain stuck in the cache!

I'm sorry but you made a mistake somewhere in your analysis: maybe it's in the browser cache, maybe you failed to reload/restart haproxy, maybe you have another cache behind. But the cache in haproxy is exclusively in the process' private RAM so that a simple reload starts again with an empty cache. Haproxy's logs however will help you: if you don't see the request logged, it's in the client (browser?). If you see it in the logs, you'll figure from the response where it came from.

**Comment by bilogic** [comment]
Thanks, I agree now it is not HAProxy, but it wasn't clear at on set, perhaps such a specific behavior can be documented more prominently. I'm going to check out the logs.

**Comment by uasan** [comment]
> specific behavior

The point is that HAProxy does not use a persistent cache, yes, this is specific and unexpected, perhaps it should be implemented

**Comment by bilogic** [comment]
Pardon me for stirring this up, but I think like it or not, maintainers have the final say and I recently witnessed, even they, have to accept the final say of packages they depend on.

**Comment by irbian** [comment]
> Hello,
> 
> When we integrated the cache in HAProxy, we wanted a really light cache in memory that could be used with small objects and a short expiration time. When we first designed it, we called it the "favicon cache". This cache could be used together with a full-featured cache like Varnish, but we never wanted to be a full-featured cache with complex rules and administration. That's why it was decided with [@wtarreau](https://github.com/wtarreau) to limit the features so people don't use it as a full-featured cache, and that limit began with the purge feature.
> 
> So, no, it's not on the roadmap and will probably never be. The only way to purge the cache is to reload or restart the process.

Hi! is this still the current position?

**Comment by wtarreau** [comment]
> Hi! is this still the current position?

What recent change made you think that the conditions would have changed for this topic to be revisited ?

**Comment by irbian** [comment]
How would I know? I want to confirm that this haven't been reconsidered on the last year to take it into account for our purposes

**Comment by wtarreau** [comment]
The most effective purge remains to use a short time cache, that will purge by itself faster than it would take you to issue a command. Some users cache for a few seconds to a few minutes. Since the cache is not persistent across reloads, there's no point caching longer anyway, and if you need a true cache, better deploy a real one such as [Vinyl](https://vinyl-cache.org/tutorials/tls_haproxy.html).

**Comment by irbian** [comment]
noted, thank you for taking your time to answer
