### ISSUE TITLE
Ability to trigger Lua scripts on events

### ISSUE THREAD

**Issue by bedis** [haproxy/haproxy#474]
Currently HAProxy support running a Lua task at startup time, which is great.
That said, for some use cases, we may want to run tasks only on "events" happening in HAProxy.
What people currently do is a startup task with a "while-sleep" kind of loop. It does the job, but it is not "efficient" in most cases.

It would be great to be able to trigger that Lua task on events, for example:
- server going down
- server having request in queue
- backend having request in queue
- non exhaustive list, I think we can have many hooks in the code path

Of course, a minimum of context has to be provided to the Lua script by HAProxy such as server name / id, or backend, etc...

**Comment by roidelapluie** [comment]
Isn't the goal to have lua going away with SPOE at some point?

**Comment by TimWolla** [comment]
> Isn't the goal to have lua going away with SPOE at some point?

I hope not. SPOE comes with a much higher operational complexity compared to Lua. Lua also allows to easily extend the available sample converters without needing to write C.

**Comment by wtarreau** [comment]
@bedis We could indeed imagine triggering such actions on a few events. Server up or down could be examples of such events. However I'm more worried about how to define what to call when, or if we should have lists of subscriptions for each server for example. Subscription lists could work and be more flexible but that would require the Lua code to first register some callbacks.

Also it's important to keep in mind that the execution would happen in the global context (the same as the one where Lua gets initialized), and I'm not sure what would be the **_real_** benefits for the end user beyond saying "look friends how it's cool to be able to reimplement e-mail alerts entirely in Lua" for example.

Other examples you mentioned like "server having a request in queue" or "backend having a request in queue" are not events, they're states, so by definition there's nothing to call on this as it can remain forever. And the operations that queue/dequeue are on the critical path, and their cost, despite being very low, has been the first one noticed by people switching to threads. We managed to recover that after some tedious work but it's totally out of question to imagine even just triggering a Lua event just whenever we add one entry to or remove one from a queue!

Also it's very important to understand that Lua calls will be asynchronous, and that the conditions might change between the moment the event is triggered and the moment it's consumed. While for developers it's totally natural to think "OK my server switched state twice which is why I'm seeing two consecutive UP events", it will be all but natural to the average user, who will have to deal with events like "server up" when he only registers for "server down".

Last point, you don't want Lua to become a bottleneck, and it can very quickly happen given that Lua is single-threaded.

@roidelapluie Tim is right, these are two completely different things. Lua is used to quickly script anything you need in production. SPOE is used to write side products, like authentication, captcha, address validation or whatever, in whatever language you'd like, often one involving a compiler or an interpreter present on the system.

As a rule of thumb I'd say that SPOE requires a development team while Lua requires a skilled admin.

If you want a real world example, let's take HapTech's ALOHA load balancing appliance. There are some SPOE extensions in it for various complements to the load balancer (security extensions mainly), that come as separate processes that are configured totally independently of haproxy, and Lua is available so that the end user can script whatever he thinks about with no risk of degrading the product, with or without help from the vendor's support.

So these are two totally distinct things, and actually the overlap between the two remains quite thin.

**Comment by capflam** [comment]
I guess it is now possible since the 2.8 thanks to the event API. At least for server state changes. So I'm closing the issue. For new specific events, a new issue may be opened.

**Comment by Darlelet** [comment]
Starting with 3.2 pattern events (map/acl) are also available, see: https://github.com/haproxy/haproxy/commit/7ff9a1c341c4d9754fd8eddfae926639ff65c760
