### ISSUE TITLE
SRV record weight conflicting with agent-check

### ISSUE THREAD

**Issue by mhyllander** [haproxy/haproxy#48]
## Output of `haproxy -vv` and `uname -a`

```
/ # haproxy -vv
HA-Proxy version 1.8.17 2019/01/08
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-null-dereference -Wno-unused-label
  OPTIONS = USE_ZLIB=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2q  20 Nov 2018
Running on OpenSSL version : OpenSSL 1.0.2q  20 Nov 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : SSLv3 TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.5
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Encrypted password support via crypt(3): yes
Built with multi-threading support.
Built with PCRE version : 8.42 2018-03-20
Running on PCRE version : 8.42 2018-03-20
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with network namespace support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available filters :
        [SPOE] spoe
        [COMP] compression
        [TRACE] trace

/ # uname -a
Linux core-haproxy-ingress-controller-5hmk6 4.15.0-1036-azure #38~16.04.1-Ubuntu SMP Fri Dec 7 03:21:52 UTC 2018 x86_64 Linux
```

## What's the configuration?

```
backend platform-platform-re-worker-websocket
    mode http
    balance roundrobin
    timeout tunnel 60s
    server-template server-dns 100 _websocket._tcp.platform-re-worker.platform.svc.cluster.local resolvers kubernetes resolve-prefer ipv4 init-addr none check inter 2s weight 100 agent-check agent-port 9991

```

## Steps to reproduce the behavior

I am running haproxy deployed using haproxy-ingress in a kubernetes environment with CoreDNS as the DNS service. Dynamic scaling is done using SRV lookup, which allows the correct pod port to be discovered. The platform-re-worker has an agent-check which is returning a weight percentage, so that we can control the number of connections each server receives. Therefore I have also specified "weight 100" on the server-template line.

## Actual behavior

Using the stats port, I can get the current weights of the two platform-re-worker pods that are running:

```
$ curl -s 'localhost:1936?stats;csv' | grep -E 'weight|re-worker-websocket.*,UP,' | cut -d, -f1,2,18,19
# pxname,svname,status,weight
platform-platform-re-worker-websocket,server-dns1,UP,50
platform-platform-re-worker-websocket,server-dns2,UP,55
platform-platform-re-worker-websocket,BACKEND,UP,105
```

The problem is that the weights keep flipping back and forth between the expected values between 0 and 100, and the value 1:

```
$ curl -s 'localhost:1936?stats;csv' | grep -E 'weight|re-worker-websocket.*,UP,' | cut -d, -f1,2,18,19
# pxname,svname,status,weight
platform-platform-re-worker-websocket,server-dns1,UP,1
platform-platform-re-worker-websocket,server-dns2,UP,1
platform-platform-re-worker-websocket,BACKEND,UP,2
```

The weights change all the time, every second.

## Expected behavior

I would expect the weight to be based on the configured weight, and the percentage returned by the agent-check.

## Do you have any idea what may have caused this?

I believe this to be a conflict between setting the weights based on the weight from the SRV record lookup, and the weight set as the agent-check percentage of the configured "weight 100". If I disable SRV lookups the weights are set correctly, based only on the configured weight and agent-check.

```
backend platform-platform-re-worker-8001
    mode http
    balance roundrobin
    timeout tunnel 60s
    server-template server-dns 100 platform-re-worker.platform.svc.cluster.local:8001 resolvers kubernetes resolve-prefer ipv4 init-addr none check inter 2s weight 100 agent-check agent-port 9991
```

```
/ # curl -s 'localhost:1936?stats;csv' | grep -E 'weight|re-worker-8001.*,UP,' | cut -d, -f1,2,18,19
# pxname,svname,status,weight
platform-platform-re-worker-8001,server-dns1,UP,55
platform-platform-re-worker-8001,server-dns2,UP,50
platform-platform-re-worker-8001,BACKEND,UP,105
```

There is also some issue with how haproxy is setting the weights from the SRV records. This is what the SRV  records look like:

```
/ # dig _websocket._tcp.platform-re-worker.platform.svc.cluster.local SRV

; <<>> DiG 9.12.3 <<>> _websocket._tcp.platform-re-worker.platform.svc.cluster.local SRV
;; global options: +cmd
;; Got answer:
;; WARNING: .local is reserved for Multicast DNS
;; You are currently testing what happens when an mDNS query is leaked to DNS
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46191
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 2

;; QUESTION SECTION:
;_websocket._tcp.platform-re-worker.platform.svc.cluster.local. IN SRV

;; ANSWER SECTION:
_websocket._tcp.platform-re-worker.platform.svc.cluster.local. 5 IN SRV 0 50 8001 10-182-1-38.platform-re-worker.platform.svc.cluster.local.
_websocket._tcp.platform-re-worker.platform.svc.cluster.local. 5 IN SRV 0 50 8001 10-182-2-26.platform-re-worker.platform.svc.cluster.local.

;; ADDITIONAL SECTION:
10-182-1-38.platform-re-worker.platform.svc.cluster.local. 5 IN A 10.182.1.38
10-182-2-26.platform-re-worker.platform.svc.cluster.local. 5 IN A 10.182.2.26

;; Query time: 1 msec
;; SERVER: 10.128.0.10#53(10.128.0.10)
;; WHEN: Fri Feb 22 16:12:47 UTC 2019
;; MSG SIZE  rcvd: 501
```

As you see the SRV records specify weight "50". It's strange that haproxy was setting the weight to "1" as a result of the SRV lookups. Maybe there is a bug in that area as well. But, as mentioned above, disabling SRV records makes the weights work as they should.

## Do you have an idea how to solve the issue?

I think that if a user explicitly configures a weight and an agent-check, the weight returned by the SRV lookup should be ignored. Not using SRV lookups serves as a workaround, but I would still like to use them to discover ports, and use agent-checks at the same time.

**Comment by wtarreau** [comment]
That's an interesting example of how retrieving too many things from the DNS can result in changing more than desired. I don't necessarily agree with your proposed solution because many people use agents for other purposes than setting the weight, but I think we should probably have some way to specify filters about what we want to use from the SRV records. Just like we have a "resolve-prefer" directive to configure what address classes we want to use, maybe we should have a "resolve-ignore" with some info there ("weight", maybe anything else?). We could even imagine doing this for the agent as well by the way, except that usually agents are home-made and do not retrieve undesired settings.
@bedis any opinion on this ?

**Comment by mhyllander** [comment]
Hi! Yes, my idea was not thought through at all. Using a "resolve-ignore", or maybe "resolve-opts", to fine-tune the behavior of SRV lookups seems much better. As long as it's possible to configure differently per backend.
I was confused by that the weight was being set to 1, considering that the SRV records specified weight 50. How could that be?

**Comment by wtarreau** [comment]
You're right, there's indeed resolve-opts for this. We just need to extend it with something like "ignore-weight". I have no idea how the weight turns from 50 to 1 there though. That should not be hard to implement, I'm tagging it good-first-issue if someone wants to grab it and implement this option.

**Comment by hamshiva** [comment]
Hello,

I just ran into a similar issue but in a much more simple case as I am not using agent-check.

Running HA-Proxy version 1.8.20-1~bpo9+1 2019/05/04

I am using SRV record with server-template directive and it seems that the SRV record weights are not used by haproxy (no weight directive declared as param of server-template btw).

I'm not developper at all but as I can see in the source code over there https://github.com/haproxy/haproxy/blob/4bd58676275d557a654979948f587aaae8e15c0d/src/server.c between lines 2292-2312 the weight value from the SRV record is never used.
Thus the server use the default value 1 in my case and stay stable.

Regards,

**Comment by bedis** [comment]
Hi @hamshiva 

What you point is actually a "mapping" of DNS weight into HAProxy weight range.
DNS and HAProxy have different weights, respectively 0-65535 and 0-255.
The code you pointed aims at "mapping" DNS SRV weight into HAProxy's weight.

So basically, in the example above, to have a weight of 50, you must set your DNS SRV weight between 12800 and 13055.

**Comment by hamshiva** [comment]
Hi @bedis,

Thank you very much for your advice. It works like a charm. 
Would be nice to add something about this in the documentation.

Regards,

**Comment by hamshiva** [comment]
Hi @bedis,

Thank you very much for your advice. It works like a charm. 
Would be nice to add something about this in the documentation.

Regards,

**Comment by bedis** [comment]
Adding this on my TODO. I already updated the comment in the code :)

**Comment by bedis** [comment]
@mhyllander to come back to the original topic.

Can you tell me what prevents you from updating your DNS server with the weight you want?
Would it be possible to switch to A/AAAA instead of SRV? Since only SRV can change the weight.

**Comment by mhyllander** [comment]
@bedis The problem isn't so much the weight returned from the SRV lookup, as that haproxy is receiving weights from two different sources. I want to set the weight using the agent check, and to ignore the weight set by SRV lookup. To be honest I don't know if I can control the weights set in CoreDNS.

As you suggest, I have solved the situation by using A/AAAA lookups instead of SRV. This works as long as the port specified in Ingress is equal to the port set in the Pod.

**Comment by wtarreau** [comment]
As I mentioned it somewhere else, probably on the mailing list thread, it's indeed a matter of multiple sources. With new environments where the server farms are not determined by the config anymore and their state is not determined by the checks anymore, we end up with many sources for:
  - the list of servers
  - their addresses
  - their weight
  - their operational state
  - their maxconn

Currently the list can be provided by config, state-file and DNS SRV. Their addresses by config, state-file, CLI, and DNS A/AAAA. Their weights by config, state-file, CLI, stats page, agent-check, DNS SRV. Their operational state by config, state-file, CLI, stats, agent checks, health checks, Lua. Their maxconn by config, state-file, CLI, agent-check.

No wonder why every now and then someone faces a conflict. We can distinguish these between multiple sources, the automatic ones and the manual ones (e.g. the stats page is manual). The CLI is between the two because when used as an API it becomes automated. And the automatic (recurrent) sources can change the things on the fly and either interact badly with manual sources, or interact badly between them all.

I suspect we need to rethink the whole thing in terms of origins and not actions: what source does a server use for a given state or setting as a valid origin ? Ultimately this can be accomplished by filters on each source (such as the "ignore-weight" keyword proposal above) or might be achieved totally differently by explicitly mentionning a precedence of sources (as we do with init-addr). But recurrent sources will constantly override a given setting and cannot be placed above another source without causing issues mentioned here.

It's also worth mentioning that some automatic sources are not necessarily recurrent. For example, the agent-check may advertise a weight or maxconn, though it's not mandatory. As such it may convey some manual information (i.e. admin wants to stop this service and announces it via the agent). Probably that DNS is the one where admins have the least handle in fact due to the protocol: we do not decide to advertise or not advertise weights, they're always there.

Thus maybe in the end the ignore-weight filter remains a valid mid-term solution.

**Comment by bedis** [comment]
> It's also worth mentioning that some automatic sources are not necessarily recurrent. For example, the agent-check may advertise a weight or maxconn, though it's not mandatory. As such it may convey some manual information (i.e. admin wants to stop this service and announces it via the agent). Probably that DNS is the one where admins have the least handle in fact due to the protocol: we do not decide to advertise or not advertise weights, they're always there.

I disagree on this point.
Admins are able to automate anything and they use DNS as a source of trust, so they should be able to automate its configuration entirely.
From @mhyllander comment, I understand he is running in kubernetes and that is a limitation of kubernetes. This product can handle 10000 of container on top of 1000 of servers, but can't update a DNS weight... ==> feature request should be on their side.
Take Consul as an example, you can set the weight directly on the service definition on the running server and it will be propagated into HAProxy using the SRV record.


> Thus maybe in the end the ignore-weight filter remains a valid mid-term solution.

This is not a solution, this is a workaround. Unfortunately, I do agree that we don't really have the choice for now, but I am scared about the consequences...

**Comment by wtarreau** [comment]
What I mean is that the decision to adjust a weight doesn't necessarily have to come from the DNS. Combining an agent to advertise weight+maxconn based on the machine's load and DNS to advertise the farm's contents in terms of usable servers makes total sense to me. It would be complex, unreliable and pointless to have a backup agent have to interact with a DNS server just to say "please DNS server, lower my weight, I'm server 35 in the farm, I'm running backups, I'll tell you once it's done". Advertising weights using the DNS to indicate the server's sizing however totally makes sense to me.

DNS cannot be considered as instantaneous. As such it must advertise relatively stable information such as available servers. An agent can return an accurate weight and maxconn every second.

Keep in mind that DNS started to be used for this not because it's a technically good solution but because it was already available, easy to use and compatible with a lot of clients, resulting in very little changes to make everyone instantly benefit from it. There are obviously rough edges but it's completely understandable that in many environments the edges are rougher than in other ones.

**Comment by wtarreau** [comment]
So now that Daniel implemented the workaround suggested above, I'm turning this into a feature request, marking it done for -dev. Now we need to decide if it has to be backported to 2.0 or not. I don't think it's appropriate to backport such a feature into older, stabler releases by now (1.8 is 2-years old now), but I'll let @bedis judge since he's the maintainer here :-)

**Comment by bedis** [comment]
I don't think we need to backport it for now, we'll see if people ask for it.

**Comment by dschneller** [comment]
Just seeing this now. Ran into this with 1.8 today. Thanks a lot!
One more reason to upgrade to 2.1 finally 👍

**Comment by capflam** [comment]
Ok, I guess it will never be backported :) I'm closing now.
