### ISSUE TITLE
src/connection.c: coverity suspects unexpected control flow

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#490]
```
1167                ret = recv(conn->handle.fd, line, SOCKS4_HS_RSP_LEN, 0);
1168                if (ret < 0 && errno == EINTR) {
    CID 1401720 (#2 of 2): Unexpected control flow (UNEXPECTED_CONTROL_FLOW)continue_in_do_while_false: A continue statement within a do ... while (...) loop only continues execution of the loop body if the loop continuation condition is still true. Since the condition will never be true in a do ... while (false) loop, the continuestatement has the same effect as a break statement. Did you intend execution to continue at the top of the loop?
1169                        continue;
1170                }
```

**Comment by wtarreau** [comment]
Thanks for these ones. I used to get trapped by these ones a long time ago, but sadly they give a bad
example that persists over time because it gets copy-pasted or is used as a source of inspiration... The
best way to proceed there is the "while (1) { ... ; break; }". I noticed at least 6 of them in the same
file, I'll handle them. They're all pretty harmless as they only involve a signal receipt during these
protool headers but better fix them.

**Comment by wtarreau** [comment]
Finally done. Ilya, let me know if you prefer that I close the coverity-related issues myself when done, I'm assuming you use them as a marker to adjust on your side, but if you prefer that I close them when responding, I can do it as well.

**Comment by chipitsine** [comment]
I only mark false positives. Resolved issues are gone automatically from coverity on next run.
