### ISSUE TITLE
Proofread the documentation by native English speaker

### ISSUE THREAD

**Issue by kshpytsya** [haproxy/haproxy#501]
I would not want this to be taken as an insult but almost every time I read HAProxy docs or source code comments, I stumble upon some language constructs that reveal that the authors are not native English speakers. It is my humble belief that considering the maturity and much deserved popularity of HAProxy, it is entitled to have top class documentation as well.

**Comment by TimWolla** [comment]
Disclaimer: Not a native English speaker. Not a HAProxy Maintainer, but I help maintain this issue tracker and I submit patches on a regular basis.

> It is my humble belief that considering the maturity and much deserved popularity of HAProxy, it is entitled to have top class documentation as well.

Yes. In fact this is acknowledged in the CONTRIBUTING file: https://github.com/haproxy/haproxy/blob/332ded5f3a74997c0ec2c0df8f19d643bb92b024/CONTRIBUTING#L256-L319

In the past various contributors have submitted patches that fix typos or improve the phrasing unusual / incorrect language constructs. From my experience and [this sentence in the CONTRIBUTING file](https://github.com/haproxy/haproxy/blob/332ded5f3a74997c0ec2c0df8f19d643bb92b024/CONTRIBUTING#L267-L269) these are usually well-received and merged quickly. Personally whenever I adjust something within the code I also try to improve the surrounding code comments, but I don't actively go along and make those fixes, because for source code comments it clutters the commit history. Whenever I notice that the documentation is lacking, e.g. based off an issue created or one I encounter myself I submit a patch that I think improves the clarity.

If you have any specific suggestions where the language could be improved I'm sure everyone would appreciate it if you make the fixes and send a patch to the mailing list! That's the beauty of Open Source.

**Comment by kshpytsya** [comment]
It was my understanding that HAProxy is an Open Source backed by HAProxy Technologies company, which could afford hiring a technical writer for such a job.

**Comment by chipitsine** [comment]
Open source actually means that any interested party can hire such a technical writer

**Comment by wtarreau** [comment]
And even though there are tech writers at haptech, some native speakers, some not, keeping up to date with a fast-moving opensource project is a really tedious task. I think the way it currently works is not that bad, with contributors proposing bunches of fixes once in a while. Also lately I saw some patches adding some doc with spelling mistakes, I wanted to fix them but had to deal with something else. I'm all for keeping a high quality on the doc, as I absolutely hate reading or even hearing language mistakes (particularly in french which is my native language), and I know many other people feel the same. It's just that mistakes in the doc are bugs like bugs in the code, both are written by humans with finite skills and can only be improved by iterating.

Quite frankly patches are welcome, and if there are parts that make you really nervous, do not hesitate to send patches. I tend to take doc fixes in priority because for me it's more important than the code (and when doc and code disagree, the doc wins).

**Comment by lukastribus** [comment]
So can we close this ticket?

We have established that patches are very welcome. But this issue tracker is about the HAProxy open source project, not about what a commercial entity invests in or whom it may hire, imo.

**Comment by wtarreau** [comment]
I agree. Done :-)

**Comment by chipitsine** [comment]
I played a bit with automatic spellcheck

https://github.com/chipitsine/haproxy/runs/475742045

I agree to some of suggestions. I'll send patch tomorrow

**Comment by chipitsine** [comment]
@kshpytsya 

you might be interested
https://github.com/haproxy/haproxy/runs/512522200?check_suite_focus=true

it is automatic weekly spellcheck.
well, spelling is only one aspect of proofreading. you can participiate
