### ISSUE TITLE
gcc-9 emits warning (does not look smart)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#505]
```src/proto_uxst.c: In function ‘uxst_bind_listener’:
src/proto_uxst.c:256:3: error: ‘strncpy’ output may be truncated copying 107 bytes from a string of length 4095 [-Werror=stringop-truncation]
  256 |   strncpy(addr.sun_path, tempname, sizeof(addr.sun_path) - 1);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by wtarreau** [comment]
Sadly, I have no idea what to do here. GCC authors are becoming totally ridiculous, they should read strncpy()'s man page and discover that we're using it as intended to do exactly this. We can as well decide to reimplement the whole libc's functions so that gcc shuts up but what's the point of using C if we're not allowed anymore to use the standard functions that come with it ? It's getting really boring, and these people should use their compiler a little bit, they'd break it less.

**Comment by wlallemand** [comment]
That's weird, -Wstringop-truncation is supposed to check if we put the \0 after the strncpy, which is set in the code, so that should work even if the size argument was wrongly set. I tried to reproduce with -Wstringop-truncation and my gcc-9.2 but I don't have any warning. 

According to the documentation https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/Warning-Options.html#index-Wstringop-truncation what is done in the code shouldn't emit a warning.

With which version of gcc did you try, looks like a bug in your version in my opinion.

**Comment by cognet** [comment]
Maybe because gcc is stupid and expects the\0 to be put at sizeof(addr.sun_path) - 2, and not - 1, given we give sizeof(addr.sun_path) - 1 as length to strncpy ?

**Comment by wtarreau** [comment]
That wouldn't make sense. For me the warning corresponds to the fact that
we may unexpectedly truncate the input string that was 4kB long and that
may be truncated to 107 chars, and who knows what could happen by truncating
such a string... It's obvious that they decided to rewrite their compiler
in C++ because they can't read basic C. I think the only solution we'll
have is to remove yet another stupid warning.

It would be nice to have at least -Wno-stupid to remove all warning added
by trainees.

**Comment by chipitsine** [comment]
ok, let us wait for `-Wno-stupid` flag
