### ISSUE TITLE
PROXY protocol V2 local command indication for health checks

### ISSUE THREAD

**Issue by wez470** [haproxy/haproxy#511]
## Output of `haproxy -vv` and `uname -a`

```
root@yondu:/# haproxy -vv
HA-Proxy version 2.1.3 2020/02/12 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.3.html
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=8).
Built with OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
Running on OpenSSL version : OpenSSL 1.1.1d  10 Sep 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.32 2018-09-10
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE|BE     mux=H2
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [CACHE] cache
        [FCGI] fcgi-app
        [TRACE] trace
        [COMP] compression
```

```
Linux yondu 5.3.0-26-generic #28-Ubuntu SMP Wed Dec 18 05:37:46 UTC 2019 x86_64 GNU/Linux
```

Also tested using HAProxy 1.9 in Docker

## What's the configuration?

```
frontend http_front
   bind 0.0.0.0:7000
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   option tcp-check
   tcp-check send CLOSE\n
   server server1 127.0.0.1:8080 check send-proxy-v2
```

## Steps to reproduce the behavior

1. Setup a simple TCP server backend
2. Configure the backend for HAProxy with health checks and PROXY protocol v2
3. Run HAProxy and let it health check the backend

## Actual behavior

The following is an example set of bytes sent from HAProxy for proxy protocol during a health check:
`13 10 13 10 0 13 10 81 85 73 84 10 33 17 0 12 127 0 0 1 127 0 0 1 140 196 31 144`

## Expected behavior

Ideally the following bytes should be sent:
`13 10 13 10 0 13 10 81 85 73 84 10 32 0 0 0`
Byte 13 should represent that this is a local command (lower 4 bits are 0). This gives 32 as an integer representation (2 in upper 4 bits to indicate version 2). Byte 14, 15, and 16 should also be 0 according to https://www.haproxy.org/download/2.1/doc/proxy-protocol.txt.

## Do you have any idea what may have caused this?

Probably just the way it was implemented

## Do you have an idea how to solve the issue?

Unfamiliar with the code base, so not sure what it would take to update the proxy protocol v2 header for health checks to be more in line with the spec.

**Comment by wtarreau** [comment]
Interesting, it seems to have been broken since at least when V2 was implemented! I remember that sending LOCAL in v1 was a bit of a hack and it's possible we accidently lost it during the transition to v2. In case of health checks, the "remote" connection (i.e. the "other" side) is artificially set to the outgoing one so that proxy_v1 can send the local addresses. But for V2 we ought to only send LOCAL with no more info. So we should possibly check if the remote is an inbound or outbound connection to decide to send LOCAL in case of v2. Could you please try the attached patch, it seems to do the trick for me ?
[0001-WIP-BUG-MINOR-connection-make-sure-to-correctly-tag-.patch.txt](https://github.com/haproxy/haproxy/files/4225488/0001-WIP-BUG-MINOR-connection-make-sure-to-correctly-tag-.patch.txt)

**Comment by wez470** [comment]
Sorry, would you still like me to verify this? I wasn't setup to install and run from source when I opened this and was busy with other things. I can give it a go this weekend if you still need

**Comment by wtarreau** [comment]
No problem! If it's trivial for you to test, you're welcome. But I was already reasonably confident in that it would work based on my tests, so if it's a hassle, don't waste your time.
Thanks!

**Comment by wez470** [comment]
Sounds good. I probably will not bother then :slightly_smiling_face:

**Comment by ghost** [comment]
This actually breaks interop with dovecot which complains about zero TLV length afterwards. I'm pretty much sure dovecot is the culprit here, but can this be maybe made optional?

**Comment by TimWolla** [comment]
@alexat See this mailing list thread: https://www.mail-archive.com/haproxy@formilux.org/msg36890.html

**Comment by alexat** [comment]
For those experiencing the issue with dovecot, the patch to the latter is *VERY* simple. It makes dovecot ignore all additional data (addresses, TLVs) after encountering LOCAL.

`--- src/lib-master/master-service-haproxy.c     2020-03-05 15:35:53.000000000 +0100
+++ src/lib-master/master-service-haproxy.c     2020-04-23 13:54:03.983349810 +0200
@@ -387,6 +387,7 @@
                        /* keep local connection address for LOCAL */
                        /*i_debug("haproxy(v2): Local connection (rip=%s)",
                                net_ip2addr(real_remote_ip));*/
+                        i = size; /* we should skip all the remaining data which can be present in PROXY protocol */
                        break;
                case HAPROXY_CMD_PROXY:
                        if ((hdr->fam & 0x0f) != HAPROXY_SOCK_STREAM) {
`

I'm posting it there because people are more likely to search there than in mailing lists.

**Comment by alexat** [comment]
For those experiencing issue with dovecot, I'm attaching a very simple patch here that makes dovecot ignore all the supplementary data in LOCAL type PROXY header. Posting it here because people are more likely to search for related bug here.

[dovecot-haproxy-LOCAL-fix.zip](https://github.com/haproxy/haproxy/files/4522373/dovecot-haproxy-LOCAL-fix.zip)

**Comment by wtarreau** [comment]
Just for clarity the last commits above about NTLM are related to issue #581 instead (confused two IDs).

**Comment by capflam** [comment]
What is the status of this issue ? Is it fixed or not ? I asked because the commit was reverted. Because the 1.8 is up to date, if it is fixed, we can close the issue. I remove 1.7 and 1.6 labels. The issue is not critical enough to be backported to these versions.

**Comment by capflam** [comment]
So I guess I can close it now.
