### ISSUE TITLE
Health check duration Prometheus metric

### ISSUE THREAD

**Issue by clwluvw** [haproxy/haproxy#519]
## What should haproxy do differently? Which functionality do you think we should add?

Add backend health check duration in prometheus service to be exported.

## What are you trying to do?

Monitor the connectivity between backends and HAProxy

**Comment by capflam** [comment]
Sorry, but your patch is not valid. First, as mentioned on the ML,  this field must be expressed in seconds using a float representation. But, outside this point, the metric is never exported because the `promex_srv_metrics` matrix was not updated. It lists all exported server metrics.  Finally the README was not updated accordingly.

But don't bother with updating your patch, I already pushed the feature and it was backported as far as 2.0. So it should be good now.

**Comment by clwluvw** [comment]
Hi @capflam 
Don't you think it should have metrics like `max` or `avg`? Because Prometheus scrape interval is for example 10s and the health checks between this intervals aren't exported!

**Comment by haproxy-mirror** [comment]
At least max should be avoided because they require a reset. A nice metric
for timers can be a sum. This way the consumer can divide the sum variation
by the count variation and get a very accurate average.

**Comment by clwluvw** [comment]
For health checking avg isn't really enough I think. If we know the max health check duration we can have better look on what's going on health check failures!

**Comment by haproxy-mirror** [comment]
The problem with a max is that once you increase it it never goes down and
a high max hides all further values. That's why the max values we export in
the stats are basically not used anymore by anyone except as an indicator
of the highest amount of resource that was once needed (e.g. max concurrent
connections).

**Comment by clwluvw** [comment]
Oh you are right :+1: 
What about using percentiles (Prometheus Summary or Histogram)?

**Comment by haproxy-mirror** [comment]
Histograms are extremely expensive to store and to compute. I initially
wanted to have some, 15 years ago, that was before we started to see
large configs and high traffic. Maybe for checks that could remain more
or less manageable, but even there the required storage can be terrific
so it would need to remain optional and disabled by default so that only
those with small configs enable them.

However this is something to keep in mind as some fuel for a possible
stats redesign for 2.3 or later.

**Comment by clwluvw** [comment]
> Histograms are extremely expensive

Do you mean this about Summary, too?
