### ISSUE TITLE
RTSP request return 502 with NGINX backend

### ISSUE THREAD

**Issue by clwluvw** [haproxy/haproxy#540]
## Output of `haproxy -vv` and `uname -a`
```
HA-Proxy version 2.0.13-1ppa1~bionic 2020/02/15 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -O2 -fdebug-prefix-map=/build/haproxy-ooLwkU/haproxy-2.0.13=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=32).
Built with OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
Running on OpenSSL version : OpenSSL 1.1.1  11 Sep 2018
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.3
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE2 version : 10.31 2018-02-12
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
mode http
```

## Steps to reproduce the behavior

1. `nc -v localhost 80`
2. `OPTIONS / RTSP/1.0`

## Actual behavior

HAProxy return 502 because it says response is invalid:
```
  buffer starts at 0 (including 0 out), 16234 free,
  len 150, wraps at 16336, error at position 0
  H1 connection flags 0x00000000, H1 stream flags 0x0000404c
  H1 msg state MSG_RPBEFORE(8), H1 msg flags 0x00001404
  H1 chunk len 0 bytes, H1 body len 0 bytes :
  00000  <html>\r\n
  00008  <head><title>400 Bad Request</title></head>\r\n
  00053  <body>\r\n
  00061  <center><h1>400 Bad Request</h1></center>\r\n
  00104  <hr><center>nginx</center>\r\n
  00132  </body>\r\n
  00141  </html>\r\n
```

## Expected behavior

Returns `400 bad request`

**Comment by lukastribus** [comment]
RTSP is not HTTP.

**Comment by clwluvw** [comment]
@lukastribus I know RTSP isn't HTTP but others sent me this request and haproxy shouldn't response with 502! it's client error not server error!

**Comment by clwluvw** [comment]
@lukastribus I have test with other backends and haproxy response with 400 but with nginx I get 502! This is the problem!

**Comment by TimWolla** [comment]
nginx does not appear to send response headers in response to the given request, so I guess HAProxy considering that response invalid is correct. The question is whether HAProxy should have forwarded that request in the first place?

```
$ printf "OPTIONS / RTSP/1.0\r\n\r\n" |nc 172.17.0.2 80
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
```

**Comment by clwluvw** [comment]
@TimWolla Yes I think it’s better to response 400 by it self like Nginx.

**Comment by TimWolla** [comment]
I've proposed a patch on the mailing list: https://www.mail-archive.com/haproxy@formilux.org/msg36584.html

**Comment by wtarreau** [comment]
RTSP support has been explicitly added in 1.6 with commit 63d692c ("MEDIUM: http: allows 'R' and 'S' in the protocol alphabet") because the RTSP framing and messaging are exactly the same as HTTP/1.1 and a few users were asking for this.

What happens above is that the RTSP request is sent to the server which doesn't recognize it as HTTP and responds in HTTP/0.9 format, resulting in an unparsable HTTP message.

I thought we lost support for RTSP with HTX but apparently not, otherwise NGINX would have responded differently.

I don't know if there are still users of RTSP. I don't even know the versions in use nor if it is still advertised as RTSP or uses real HTTP versions now.

Maybe we should phase out support of this protocol for 2.3 ?

**Comment by daniel-corbett** [comment]
Hello, we've actually had users asking about this on Reddit about a month ago.  When attempting to duplicate I ran into issues with some of the methods not being sent.  I assumed they couldn't be translated with HTX -- I think it was "DESCRIBE" but I could be wrong.  I'd have to test again to verify.  Reddit thread here:  https://www.reddit.com/r/haproxy/comments/ep4p67/haproxy_and_rtsp/

**Comment by wtarreau** [comment]
There's no restriction on the methods in haproxy in general nor HTX specifically. For example I'm passing this request from the client to the server through haproxy (this is 2.2-dev4 so it's exclusively HTX):

```
client$ telnet 0 4445
Trying 0.0.0.0...
Connected to 0.
Escape character is '^]'.
SALUTDANIEL / RTSP/1.0

RTSP/1.0 200 OK

```

```
server$ nc -lp8008
SALUTDANIEL / HTTP/1.0
connection: keep-alive

RTSP/1.0 200 OK

^C
```

```
haproxy$ ./haproxy -db -f test.cfg
127.0.0.1:46138 [10/Mar/2020:15:55:07.358] px px/s1 250/0/0/4942/6926 200 38 - - ---- 1/1/0/0/0 0/0 "SALUTDANIEL / RTSP/1.0"
```

If some people still ask for it we have to maintain it, especially since it apparently continues to work fine as seen above!

**Comment by TimWolla** [comment]
> If some people still ask for it we have to maintain it, especially since it apparently continues to work fine as seen above!

Can I request that RTSP is being guarded behind a configuration option such as `option rtsp` (I don't care about the default) going forward? Or is it already possible to detect it using an ACL? I'd like to stop such non-HTTP requests instead of passing them to my backends.

**Comment by TimWolla** [comment]
> SALUTDANIEL / HTTP/1.0

I also notice that apparently the protocol *is* being changed before passing it to the backend. At least according to your comment.

**Comment by clwluvw** [comment]
I'm really agree with @TimWolla. When I set `mode http` in my backend configuration section I expect that all the requests to my backends were HTTP and others should be denied by HAProxy.

**Comment by wtarreau** [comment]
Wow I didn't even notice, good catch! Yes we definitely nede to make sure it's properly respected.
Regarding supporting an extra option, I'd say yes, why not. I think the RTSP use cases are rare enough that we can accept a bit of breakage, forcing the rare users to add an option. I *seem* to remember that RTSP/1.0 was exactly equivalent to HTTP/1.1 in terms of framing (keep-alive, pipelining, content-length, transfer-encoding, compression) because I have some memories of explicitly setting internally HTTP/1.1 framing when RSTP/1.0 was seen. But we definitely broke the version on output as noticed above.

**Comment by daniel-corbett** [comment]
> There's no restriction on the methods in haproxy in general nor HTX specifically. For example I'm passing this request from the client to the server through haproxy (this is 2.2-dev4 so it's exclusively HTX):


(All information below is with 2.1.3 -- latest 2-2-dev master also produces similar behavior)

Thanks for this info -- so it's pretty strange then.  Here's the behavior I am seeing.  First, I don't see these requests showing up in the request log when I am using `option httplog` (but I do see normal curl requests)

Next, when I initiate a VLC to an RTSP server this is the flow of a normal request:
OPTIONS -> (200 Response) -> DESCRIBE -> (401 Response) -> DESCRIBE -> (200 Response) -> SETUP (200 Response) -> PLAY (200 Response)

Here's the flow with HAProxy:
OPTIONS -> (200 Response) -> SETUP -> (401 Response) -> OPTIONS (200 Response)

As seen, when I introduce HAProxy, it seems that the first DESCRIBE is not being passed ( in fact I cannot even see this request in the debug logs with -d passed through the command line but I do see the client sending it using tcpdump/ngrep)



I'll try to keep debugging a bit further but for now I have attached a .zip with 4 files to this thread.
Inside you will find 2 pcap, the configuration, and haproxy debug log.

Please note that in the haproxy_rtsp.pcap my VLC client is connecting to HAProxy over localhost and HAProxys source IP is 192.168.1.13 connecting to the RTSP server on 192.168.1.71.  I hope this helps to provide a clear differentiation between VLC traffic & HAProxy traffic.

direct_rtsp.pcap = connection directly to rtsp server/camera
haproxy_rtsp.pcap = connection routed through haproxy to rtsp server/camera
haproxy_debug.log = output of -d at command line
haproxy.cfg = config used

[rtsp.zip](https://github.com/haproxy/haproxy/files/4315010/rtsp.zip)

**Comment by daniel-corbett** [comment]
Ahh, I didn't catch this before but it appears that when I use RTSP from VLC it's sending the full URL and not just the path portion within the request.  So it's sending  "DESCRIBE rtsp://127.0.0.1:554 RTSP/1.0"  -- strange that's not logging though even though it's passing on some of the requests.  Heres an example of a request that is being proxied on but not logged:
`printf "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0\r\n\r\n" |nc localhost 554`

**Comment by wtarreau** [comment]
Are you sure you're not having and issue with your config ? If you use
regular HTTP and http scheme here, is it logged ?

**Comment by wtarreau** [comment]
So with a quick test I can't reproduce your observation.

haproxy:
<pre>
$ ./haproxy -d -f htx8008.cfg
<133>Mar 11 05:02:48 haproxy[18896]: Proxy foo started.
00000000:foo.accept(0005)=001d from [127.0.0.1:37080] ALPN=<none>
00000000:foo.clireq[001d:ffffffff]: OPTIONS rtsp://127.0.0.1:554 RTSP/1.0
00000000:foo.srvcls[001d:001e]
00000000:foo.clicls[001d:001e]
00000000:foo.closed[001d:001e]
<134>Mar 11 05:03:45 haproxy[18896]: 127.0.0.1:37080 [11/Mar/2020:05:03:29.795] foo foo/s1 0/0/0/-1/15635 502 229 - - SH-- 1/1/0/0/0 0/0 "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0"
^C
</pre>

server:
<pre>
$ nc -lp8008
OPTIONS rtsp://127.0.0.1:554 RTSP/1.0
connection: keep-alive

^C
</pre>

client:
<pre>
$ printf "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0\r\n\r\n" |nc localhost 4445
HTTP/1.1 502 Bad Gateway
content-length: 107
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>502 Bad Gateway</h1>
The server returned an invalid or incomplete response.
</body></html>
</pre>

Config:
<pre>
$ cat htx8008.cfg
global
        log stdout local0
        stats socket /tmp/sock1 mode 666 level admin
        stats timeout 1h

listen foo
        bind :4445
        mode http
        log global
        option httplog
        timeout connect 1s
        timeout server 20s
        timeout client 20s
        server s1 127.0.0.1:8008
</pre>

**Comment by daniel-corbett** [comment]
ah ha, while drafting up a reply using your config right before hitting send I saw the log entry come in.  Seems the log entry didn't come in for about 20 seconds (timeout client) (although the response is immediate).  I realize now that it's logging once the request has finished.

<134>Mar 11 00:12:17 haproxy[2381]: 127.0.0.1:33908 [11/Mar/2020:00:11:57.299] foo foo/s1 577/0/3/20/20601 200 154 - - cD-- 1/1/0/0/0 0/0 "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0"

**Comment by daniel-corbett** [comment]
It seems strange though because the response is returned immediately.
$ time printf "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0\r\n\r\n" | nc -vv localhost 4445
Connection to localhost 4445 port [tcp/*] succeeded!
RTSP/1.0 200 OK
public: OPTIONS, DESCRIBE, PLAY, PAUSE, SETUP, TEARDOWN, SET_PARAMETER, GET_PARAMETER
date: Wed, Mar 11 2020 00:16:19 GMT

^C

real	0m0.749s
user	0m0.005s
sys	0m0.000s


<134>Mar 11 00:16:39 haproxy[2381]: 127.0.0.1:33964 [11/Mar/2020:00:16:19.462] foo foo/s1 0/0/0/7/20009 200 154 - - cD-- 1/1/0/0/0 0/0 "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0"

**Comment by daniel-corbett** [comment]
Now that I see it's logging after `timeout client` is reached that explains a little bit why my test config was not logging these particular requests because I stripped it down to the bare minimum to reproduce the issue (without any timeouts specified).  However, when using VLC I still do not see the DESCRIBE methods coming through when playing a stream.  I found another way to test what I'm seeing here's an example config:

```
global
        log stdout local0
        stats socket /tmp/sock1 mode 666 level admin
        stats timeout 1h

listen foo
        bind :554
        mode http
        log global
        option httplog
        timeout connect 1s
        timeout server 20s
        timeout client 20s
        server s1 wowzaec2demo.streamlock.net:554 

```

In VLC open the following URLs:
haproxy proxied: rtsp://haproxy-ip:554/vod/mp4:BigBuckBunny_115k.mov
Direct RTSP URL: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov

**Comment by wtarreau** [comment]
On Tue, Mar 10, 2020 at 09:17:01PM -0700, dcorbett-haproxy wrote:
> It seems strange though because the response is returned immediately.
> $ time printf "OPTIONS rtsp://127.0.0.1:554 RTSP/1.0\r\n\r\n" | nc -vv localhost 4445
> Connection to localhost 4445 port [tcp/*] succeeded!
> RTSP/1.0 200 OK
> public: OPTIONS, DESCRIBE, PLAY, PAUSE, SETUP, TEARDOWN, SET_PARAMETER, GET_PARAMETER
> date: Wed, Mar 11 2020 00:16:19 GMT
> 
> ^C

Note that there's no content-length here so likely the response is expected
to terminate the body by a close, and ilikely the server doesn't close there
so it will complete after the first timeout strikes. But given that the
request was passed between haproxy and the server with HTTP/1.0, very likely
the RTSP server expected haproxy to close as well. That's why we need to
address this versioning issue before drawing other conclusions.

Thanks,
Willy

**Comment by clwluvw** [comment]
Any updates here?

**Comment by clwluvw** [comment]
I have temporary added this acl to my cfg but I think it's better HAProxy reject none HTTP requests in `mode http`

**Comment by clwluvw** [comment]
As seen here http://mailman.nginx.org/pipermail/nginx-devel/2020-March/013051.html maybe it's good to support HTTP/0.9 response in HAProxy!

**Comment by bedis** [comment]
As a reminder, we introduced this "feature" because people wanted to do
"redirects" with RTSP (to re-route users to an other location).

**Comment by wtarreau** [comment]
Finally merged. RTSP is now restricted to `accept-invalid-http-request` in 2.6.
