### ISSUE TITLE
Increase backend connection reuse

### ISSUE THREAD

**Issue by coldeasy** [haproxy/haproxy#599]
## Output of `haproxy -vv` and `uname -a`

```
./haproxy -vv
HA-Proxy version 2.0.12-6bdfda-78 2020/04/03 - https://haproxy.org/
Build options :
  TARGET  = linux-glibc
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wno-implicit-fallthrough -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS =

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=12).
Built with network namespace support.
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE     mux=H2
              h2 : mode=HTTP       side=FE        mux=H2
       <default> : mode=HTX        side=FE|BE     mux=H1
       <default> : mode=TCP|HTTP   side=FE|BE     mux=PASS

Available services :
        prometheus-exporter

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
```
```uname -a
Linux bikkuriworkarch 5.6.5-arch3-1 #1 SMP PREEMPT Sun, 19 Apr 2020 13:14:25 +0000 x86_64 GNU/Linux
```
## What's the configuration?

```
global
   stats socket /tmp/haproxy.stats.sock mode 666 level admin
   log stdout  format raw  local0  info
   nbthread          8

defaults
    log global
    option httplog
    mode                    http
    option                  dontlognull
    option                  redispatch
    retries                 0
    timeout connect         5s
    timeout client          10m
    timeout server          15m
    maxconn                 3000
    option                  http-server-close
    option                  http-keep-alive
    http-reuse              always
    default-server pool-purge-delay 60m

listen stats
    bind 0.0.0.0:3213
    stats enable
    stats uri /

frontend metrics
    mode http
    bind 0.0.0.0:6001
    option http-use-htx
    maxconn 1
    http-request use-service prometheus-exporter

frontend healthz
    mode http
    bind 0.0.0.0:6002
    monitor-uri /

frontend  default
    option                  http-keep-alive
    bind 0.0.0.0:6000
    maxconn 20000
    default_backend default_be

backend default_be
    mode http
    server server1 127.0.0.1:8081 check inter 2s
    server server2 127.0.0.1:8082 check inter 2s
    server server3 127.0.0.1:8083 check inter 2s
    server server4 127.0.0.1:8084 check inter 2s
    server server5 127.0.0.1:8085 check inter 2s
    server server6 127.0.0.1:8086 check inter 2s
    server server7 127.0.0.1:8087 check inter 2s
    server server8 127.0.0.1:8088 check inter 2s
    server server9 127.0.0.1:8089 check inter 2s
    server server10 127.0.0.1:8090 check inter 2s
```

## Steps to reproduce the behavior

To be terse, I gave 10 servers in the config but we have 120. A server responds with a median latency of 3ms and a p99 of 5ms.

1. Run a load generator (e.g. gatling) that is not configured to use persistent connections, with increasing request rate to 20K r/s over 7 minutes.
2. Query HAProxy stats and observe the reuse percentage. 

## Actual behavior

Anywhere between 30-40 percent of backend connections get reused.

## Expected behavior

Closer to 99% of backend connections get reused.

## Do you have any idea what may have caused this?

I believe it's related the condition
```
(srv->cur_sess + srv->curr_idle_conns <= srv->counters.cur_sess_max)
```
in  `srv_add_to_idle_list`. This limits the number of idle connections to observed max sessions. In this case, the observed max was 3 so my theory if the server is chosen by one of the other 5 threads handling a request, an idle connection will not get used (since `srv->idle_orphan_conns` is per-thread). 

## Do you have an idea how to solve the issue?
My naive fix was to modify the condition to 
```
(srv->cur_sess + srv->curr_idle_conns <= (srv->counters.cur_sess_max * global.nbthread))
```
which, when tested, gave >99% connection reuse. I'm sure there's a more elegant solution though (making the counters thread local?) or maybe this is intentional behaviour

**Comment by wtarreau** [comment]
The limit is on purpose because up to 2.1 it's not possible for a thread to steal another thread's connection. With your change you'll end up in multiplying the number of idle connections per server by the number of threads, which can quickly result in FD outage or source port outage on high loads, which was the problem that appeared immediately in early 2.0 development with the idle connections.

In 2.2-dev these connections can be reused between threads, so we don't need to take care of other threads' idle conns count, and you'll see this 99% reuse.

Note that in 2.0 you can already set "option prefer-last-server" which will significantly improve the reuse by keeping a front connection to the same backend server if possible. This will leave less idle connections behind and make sure one is still available for the current server.

Last point, be careful, your version is vulnerable to CVE-2020-11100, you really need to update it to 2.0.14!

**Comment by wtarreau** [comment]
I'm tagging as "works as designed" but not closing yet in case you'd want to share more info.

**Comment by coldeasy** [comment]
Thanks for the detailed response and the heads up on the CVE.
Unfortunately we cannot use `option prefer-last-server` as we have other patches in place which control load balancing (I hope to explain this in the mailing list in future).
I look forward to using the 2.2 series but we're probably a way off before being able to adopt that.
Do you have any numbers around the load and number of servers at which you started to see source port/FD exhaustion? Could the existing condition `ha_used_fds < global.tune.pool_low_count` protect against FD exhaustion? The max load we allow per-haproxy instance is approximately 14K request per second. 

We're happy to maintain the patch until we can adopt the 2.2 series if we can make sure we don't encounter the issues you're describing - do you have any suggestion on how to make the change safer? I was thinking maybe simply adding the thread count instead of multiplying - might not get the same level of reuse in the general case but for low concurrency servers we should see a significant increase in reuse.

**Comment by chipitsine** [comment]
there are few things to keep you from port/FD exhaustion. I'm thinking of writing detailed guide similar to https://www.nginx.com/blog/tag/ephemeral-port-exhaustion/


one of those things is IP_BIND_ADDRESS_NO_PORT

```
[ilia@MININT-GOKPRIV haproxy]$ grep -r IP_BIND_ADDRESS_NO_PORT .
./CHANGELOG:    - MINOR: enable IP_BIND_ADDRESS_NO_PORT on backend connections
./src/proto_tcp.c:#ifdef IP_BIND_ADDRESS_NO_PORT
./src/proto_tcp.c:			setsockopt(fd, SOL_IP, IP_BIND_ADDRESS_NO_PORT, (const void *) &bind_address_no_port, sizeof(int));
./doc/configuration.txt:  Since Linux 4.2/libc 2.23 IP_BIND_ADDRESS_NO_PORT is set for connections
[ilia@MININT-GOKPRIV haproxy]$ 

```



it is automatically enabled on 4.2 kernels. as for RHEL 3.10 kernels there's a trick, feature is backported, however include files do not have proper constant (you still can define it manually during build)


another thing is closing tcp connections using RST, it enables ephemeral port immediately (unfortunately, I've forgotten RFC number)


almost always backend also closes connection using RST (unless it is nginx).

**Comment by lukastribus** [comment]
`IP_BIND_ADDRESS_NO_PORT` is only useful when you are actually forcing a specific source IP address. In that case it allows the kernel to consider the full 5-tuple, which is a specific problem when forcing a source IP address.

It doesn't help otherwise.

**Comment by chipitsine** [comment]
as far as I looked to source, IP_BIND_ADDRESS_NO_PORT seems to work automatically (except my notice about RHEL 3.10 kernels)

but I need to look again :)

**Comment by lukastribus** [comment]
You don't have to configure it, if that's what you mean. That doesn't mean it's a magic bullet. It addresses a very specific source port exhaustion problem, when bind() is used (which in the haproxy context means when the `source` keyword is used on the server line).

You can read more about it in the kernel commit https://github.com/torvalds/linux/commit/90c337da1524863838658078ec34241f45d8394d

**Comment by chipitsine** [comment]
hmm, I missed thing about specifying `source`

**Comment by wtarreau** [comment]
So let's make a little bit of math. You're dealing with 14k req/s randomly spread over 120 servers. This means that each request has one chance over 120 of reusing its previous connection and 119 chances over 120 to pick another server and release that connection. And for these 119 other servers, it's only possible to pick 1/8 of their idle connections (those on the same thread), resulting in 7/8 of the accumulated 119/120 idle connections not being used. So over one second with enough incoming connections, you'd leave 7/8*119/120 = 87%, or for 14000 = 12148 unused idle connections.

By default, global.tune.pool-high-fd-ratio is set to 25% of the total FD count and haproxy will refrain from accumulating unused idle connections like this once 25% of the FDs are in use. So if your haproxy process starts, say, with 4096 fds, you'd start purging idle connections once 1024 FDs are in use.

All depends on the maximum number of concurrent connections on the front. I'm seeing 20k on your frontend, so if you want to be able to sustain that number, on the front with very limited killing of idle connections, you'd need to support having enough FDs to keep these 87% idle conns, which means 20k/(1-87%) = 153k outgoing connections. This added to the 20k incoming ones results in 173k concurrent FDs.

At such large numbers of FDs you should increase the global.tune.pool-high-fd-ratio to avoid uselessly wasting FDs, let's say you set it to 90%, and you'd need to set your "ulimit -n" value to 200k in your service config (alternatively you can just set maxconn to ~100k in the global section and it should be fine).

But there's a catch. With so many outgoing connections, you'll indeed miss some source ports if the kernel doesn't properly allocate them. But given they are spread over 120 servers, we're talking about only around 1500 connections per server so that should be OK.

**Comment by coldeasy** [comment]
> So let's make a little bit of math. You're dealing with 14k req/s randomly spread over 120 servers. This means that each request has one chance over 120 of reusing its previous connection and 119 chances over 120 to pick another server and release that connection. And for these 119 other servers, it's only possible to pick 1/8 of their idle connections (those on the same thread), resulting in 7/8 of the accumulated 119/120 idle connections not being used. So over one second with enough incoming connections, you'd leave 7/8*119/120 = 87%, or for 14000 = 12148 unused idle connections.

I'm a bit confused by this, but I realise I'm not anywhere near as familiar with the code base so I if I'm taking up too much of your time feel free to let me know. I'm basing the following on having the config option `http-reuse    always` and `balance roundrobin`.

My reading of the code suggests that when client -> frontend connections are persistent, then each client session caches up to 5 connections to backend servers. After this, connections are offered to the servers "orphaned idle connection pool". For simplicity lets take the extreme example of no session idle conns (`max-session-srv-conns = 0`). On every frontend request, if the target server is not cached by the session, the handling thread can pick from 1/8 orphaned idle connections to the server. But assuming each thread handles each request with equal probability, then in a second we'd expect to see an idle connection used for every server for every thread.
The problem comes about with overload and a spike in concurrent sessions that will increase the number of connections in the orphaned idle connection pool and will become unused once the such a spike passes.
If `max-session-srv-conns = 5` (default), then I think your description comes into effect and we end up with quite a low probability of reusing one of those connections previously cached to the session. I'm not quite sure what becomes of those connections if they remain unused for a long period of time.

**Comment by wtarreau** [comment]
For me the connections attached to the session are idle as well and will expire like others, it's just that they're still preferentially tracked by a given session in order to help for the cases where a single H2 front connection emits plenty of streams that want to reach multiple backend servers in parallel and we want to maintain as much as possible some reuse between them.

Regarding this:
> But assuming each thread handles each request with equal probability, then in a second we'd expect to see an idle connection used for every server for every thread.

please keep in mind this can only be true when the total number of connections is significantly higher than the number of servers times the number of threads so that all idle lists start to fill up. And in this case don't forget to verify that you do have enough total FDs not to stop keeping connections. It could be useful to have a "show info" output when it starts to misbehave.

**Comment by coldeasy** [comment]
Thanks for all the input on this - it was very helpful. I'll close this out.
