### ISSUE TITLE
Use the fastest http parser

### ISSUE THREAD

**Issue by jobs-git** [haproxy/haproxy#60]
Use the fastest http parser with [picohttpparser](https://github.com/h2o/picohttpparser)

**Comment by lukastribus** [comment]
Maybe you should spend a few minutes to explain why you think that this would be beneficial, why the current implementation does not suffice, as well as a use case that requires this.

Otherwise, if all you have to spare for this feature requests are 5 seconds, why should we take the time to take a look at this?

**Comment by jobs-git** [comment]
its just suggestion, if you dont care then that's just fine
