### ISSUE TITLE
Clarify that a subdir match (`-m dir`) matches anywhere down the hierarchy

### ISSUE THREAD

**Issue by TimWolla** [haproxy/haproxy#61]
It was reported in https://www.mail-archive.com/haproxy@formilux.org/msg33009.html (Re: Small question regarding the sub-dir match (i.e. `-m dir`) with regard to "rooted" patterns) that the documentation regarding the sub-dir match is a bit unclear in that it could be misunderstood to only match directories at the prefix:

> On Mon, Mar 11, 2019 at 12:58 PM Tim Düsterhus <*snip*> wrote:
> > The documentation only talks about a slash-delimited value, not about
> > being at the beginning.
>
> Technically yes, it works as documented, except the documentation is
> misleading by using the work `subdir match` right in the beginning...
>
> Moreover the name of the operator is `dir` which (my guess is that)
> most would just mistakenly associate with a file-system, where they
> would expect to match a prefix.
>
> I would strongly suggest adding an explicit warning in the
> documentation about this pitfall.

Consider amending the documentation.

**Comment by wtarreau** [comment]
Finally done, 3 years later... At least it was not lost.

**Comment by sottolski** [comment]
not sure, is a comment on such an oldie useful? I believe there might be a tiny mistake in the text.

"the string "/images/png/logo/32x32.png", would match "/images", "/images/png", "images/png", "/png/logo", "logo/32x32.png" or "32x32.png" but not "png" nor "32x32".

wouldn't "png" still be a match due to /images/png/logo/ in the path? I understand that the example wants to show that it would not match the png from 32x32.png

Maybe a clearer example would be something like

"the string "/images/png/logo/32x32.jpeg", would match "/images", "/images/png", "images/png", "/png/logo", "logo/32x32.png" or "32x32.jpeg" but not "jpeg" nor "32x32".

(although the file suffix wouldn't normally live in a /png/ directory :-))
