### ISSUE TITLE
src/filters.c: null pointer dereference suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#631]
```
225                else {
   deref_ptr_in_call: Dereferencing pointer err. [show details]
226                        flt_dump_kws(err);
227                        indent_msg(err, 4);
228                        memprintf(err, "'%s' : unknown keyword '%s'.%s%s",
229                                  args[0], args[cur_arg],
   CID 1399858 (#1 of 1): Dereference before null check (REVERSE_INULL)check_after_deref: Null-checking err suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
230                                  err && *err ? " Registered keywords :" : "", err && *err ? *err : "");
231                        goto error;
232                }
```

**Comment by TimWolla** [comment]
I'd say that this is intentional / won't fix, because it mirrors the usual code that concatenates error messages, such as this one within `ssl_sock.c`:

https://github.com/haproxy/haproxy/blob/5eb5e253e6ee22605c54e6720cf6c7ab5265baa2/src/ssl_sock.c#L2805-L2806

**However** `flt_dump_kws` should possible be changed from `*out ? *out : ""` to `out && *out ? *out : ""` which should also get rid rid of the coverity warning.

**Comment by chipitsine** [comment]
I will mark as intentional, thank you!

**Comment by TimWolla** [comment]
I'll reopen this because of my “however”.

**Comment by chipitsine** [comment]
I think if we allow "protective programming", ok, let keep things that way. Done in purpose, right.

I'm slightly afraid that every static scanner will find such issues again and again :(
