### ISSUE TITLE
Show request URL in 'show sess'

### ISSUE THREAD

**Issue by zbebeto** [haproxy/haproxy#663]
When someone is under web heavy load and facing bad performance, there is an information that makes all the difference : what urls are being served in a point in time . 
All that is needed is to add to the output of this command the "path" that is being served:
echo 'show sess' | socat unix-connect:/tmp/haproxy stdio
The "show sess" shows a lot of incredible information BUT does not show the path that is being served.... it would help a lot to find the bad performance origins... how ? you will clearly see whats is taking long ... and what paths... not only the backend.
The output of the 'show sess' is something like:
0x5635839442e0: proto=tcpv4 src=172.31.4.64:41558 fe=java-corp be=bk_default srv=haproxy16 ts=08 age=3s calls=5 rq[f=48848280h,i=0,an=8000h,rx=,wx=,ax=] rp[f=80400000h,i=0,an=a00000h,rx=2m57s,wx=,ax=] s0=[7,8h,fd=32,ex=] s1=[7,118h,fd=33,ex=] exp=4s
what is nedded? To add a field to this output... the field with the "path" of the url that is being served.

**Comment by zbebeto** [comment]
ok

**Comment by zbebeto** [comment]
thanks a lot

**Comment by wtarreau** [comment]
I've been missing it quite a bit as well, and have been wondering whether we should do something for it. The problem is that it will double the memory consumption and cause quite a noticeable slowdown by forcing to keep a copy of the request buffer for the very rare case where the request appears in a "show sess" output, which represents 1-to-1 million to 1-to-1 billion of the requests on a typical prod. Maybe one thing that could be done would be to report the copy taken for the logs if it exists. This way it would not add further slowdown to anyone. Another point is that this output should not appear by default because it is mostly used for debugging and issue reporting, and that would disclose a lot of private information.

**Comment by zbebeto** [comment]
Talking about privacy I'm not worried because I'm a sysadmin with access to logs and everything...
Talking about memory ... An excellent option would be an option to enable It and disable it with ease.... And then it could be used in production temporarily when needed...

This feature would save lots of emergency situations in production....

**Comment by zbebeto** [comment]
I have been waiting for It for years ... And then I decided to try opening an issue to you....

**Comment by zbebeto** [comment]
Squid is a software that makes this info available.... I was using an squid instance to provide this information in emergencies only because I was out of options... 
If you do... I Will cut off the squid instance for example ....lots of Benefits...

**Comment by zbebeto** [comment]
My web stack has varnish .. .. haproxy and squid...
Haproxy is the https/http entrypoint and balancer ... Varnish is the cache... And the unique function of squid is to provide this information : what urls are being served and how long they are burning....this is not a log information ... Is a hot information ... A real time information ... Perfect ...the web site this stack serves , takes 120.000.000 http hits a day in a hot day ...

**Comment by capflam** [comment]
This was implemented. The `show-uri` option can be used for `show sess` command to display the captured URI.

**Comment by ghubsfdsv** [comment]
AT LAST !!!!!!!!!!!!!! THANKS A LOT !
