### ISSUE TITLE
src/server.c: buffer overflow suspected by coverity

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#708]
```
3348
3349                                st = container_of(node, struct state_line, name_name);
    CID 1402202 (#1 of 1): Copy into fixed size buffer (STRING_OVERFLOW)40. fixed_size_dest: You might overrun the 512-character fixed-size string mybuf by copying st->line without checking the length.
3350                                memcpy(mybuf, st->line, strlen(st->line));
3351                                mybuf[strlen(st->line)] = 0;
3352
3353                                srv_state_parse_line(mybuf, global_file_version, params, srv_params);
3354                                if (params[0] == NULL)
3355                                        goto next;
```

**Comment by capflam** [comment]
It is a false positive. The `state_file` tree is filled in the same function, at line [3239](https://github.com/haproxy/haproxy/blob/9ab8f8d1b6a6a6cf3277f88d2b808057de1cd0e2/src/server.c#L3239). the line of a `state_line` is a copy of the buffer used to read lines of the global state file, using `fgets()` and  with a maximum size of `SRV_STATE_LINE_MAXLEN - 1` (511). So at line 3350, `st->line` cannot overrun `mybuf` because its maximum length is 511.

**Comment by chipitsine** [comment]
I've marked as false positive, thank you
