### ISSUE TITLE
src/hlua.c: null pointer dereference suspected by coverity (new defect)

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#719]
```
*** CID 1401718:  Null pointer dereferences  (NULL_RETURNS)
/src/hlua.c: 3883 in hlua_applet_http_new()
3877                    return 0;
3878            lua_settable(L, -3);
3879     
3880            htx = htxbuf(&s->req.buf);
3881            blk = htx_get_first_blk(htx);
3882            BUG_ON(!blk || htx_get_blk_type(blk) != HTX_BLK_REQ_SL);
>>>     CID 1401718:  Null pointer dereferences  (NULL_RETURNS)
>>>     Dereferencing a pointer that might be "NULL" "blk" when calling "htx_get_blk_ptr".
3883            sl = htx_get_blk_ptr(htx, blk);
3884     
3885            /* Stores the request method. */
3886            lua_pushstring(L, "method");
3887            lua_pushlstring(L, HTX_SL_REQ_MPTR(sl), HTX_SL_REQ_MLEN(sl));
3888            lua_settable(L, -3);
```

**Comment by capflam** [comment]
It is a false positive. `hlua_applet_http_new()` is called when an HTTP lua service is started, during the request analysis. At this step, the first block is always defined because the request headers have been received and it is always a request start-line because nothing has been forwarded yet. It is a implicit contract during all the request analysis. Here the `BUG_ON()` macros is here to explicitly state `blk` is expected  to be defined and it must be a request start-line.

**Comment by chipitsine** [comment]
I've marked as false positive, thank you!

**Comment by TimWolla** [comment]
I wonder why coverity did not detect that `BUG_ON()` is equivalent to an assert.

**Comment by chipitsine** [comment]
I think, I should add `DEBUG_STRICT=1` to coverity build

**Comment by chipitsine** [comment]
generally speaking, if people build haproxy without `DEBUG_STRICT=1`, they may encounter null dereference, right ?

**Comment by TimWolla** [comment]
> generally speaking, if people build haproxy without `DEBUG_STRICT=1`, they may encounter null dereference, right ?

Yes, but no. The BUG_ON implies that there's a programming mistake somewhere if the condition is true. So by definition any null pointer coming in is a programming mistake elsewhere. So the BUG_ON basically just moves the segfault from the NULL  dereference to an intentional segfault a line before.
