### ISSUE TITLE
:scheme header incorrectly set to https while proxying to a http/2 cleartext (h2c) backend

### ISSUE THREAD

**Issue by shamsimam** [haproxy/haproxy#77]
## Output of `haproxy -vv` and `uname -a`

```$ haproxy -vv
HA-Proxy version 1.9.6 2019/03/29 - https://haproxy.org/
Build options :
  TARGET  = generic
  CPU     = generic
  CC      = clang
  CFLAGS  = 
  OPTIONS = USE_ZLIB=1 USE_POLL=1 USE_KQUEUE=1 USE_THREAD=1 USE_OPENSSL=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2r  26 Feb 2019
Running on OpenSSL version : OpenSSL 1.0.2r  26 Feb 2019
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with transparent proxy support using:
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.43 2019-02-23
Running on PCRE version : 8.43 2019-02-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
     kqueue : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use kqueue.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTTP       side=FE
              h2 : mode=HTX        side=FE|BE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace
```

```
$ uname -a
Darwin XXX 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
```

## What's the configuration?

```
global
   maxconn 4096
   daemon

defaults
   log   global
   option http-use-htx
   timeout connect 10s
   timeout client 30s
   timeout server 30s
   maxconn 3000

frontend waiter
    mode http
    bind *:9090 proto h2
    default_backend local_node

backend local_node
    mode http
    server localhost localhost:8080 proto h2
```

## Steps to reproduce the behavior

1. Run a backend at port 8080 (I ran an nginx server) that can print details about the request.
2. Launch HA-Proxy with the configuration above. 
3. Run `curl --http2-prior-knowledge http://localhost:9090`
4. Notice the `:scheme` header received by the backend running at port 8080.

## Actual behavior

The `:scheme` header is set to `https` and potentially the payload is encrypted too.

![image](https://user-images.githubusercontent.com/6611249/55736200-757e3180-59e8-11e9-971d-5321a2d55c05.png)

## Expected behavior

The `:scheme` header should be `http` and the payload should be sent as `h2c`

![image](https://user-images.githubusercontent.com/6611249/55736218-829b2080-59e8-11e9-9b49-4672bf841f20.png)

## Do you have any idea what may have caused this?

Nope.

## Do you have an idea how to solve the issue?

If the backend is not supporting SSL, we should send h2c traffic to the backend. In particular, the scheme should be `http`.

Related forum post: https://discourse.haproxy.org/t/incorrect-scheme-set-while-proxying-to-a-http-2-cleartext-h2c-backend/3618

**Comment by wtarreau** [comment]
The :scheme is a design mistake of HTTP/2 inherited from SPDY. It should never had made its way into the protocol for client-to-server requests since it's only useful to proxies to know how to forward the request. It is set to https in order to make sure that *if* a server ever wants to check what's there, at least it will look like what browsers put there, so it's a principle of least surprise.

It is unrelated to the type of outgoing connection, it should at best be related to what was placed there first. But it's very common to chain multiple SSL offloaders and reverse proxies and this field makes absolutely no sense there. Many users simply decrypt SSL in front of their H2 server for performance reasons with an SSL offloader that has no clue about H2, and they receive "https" there as well.

I'm a bit reluctant to make it configurable, I think it will only add confusion to end users with no proven benefit. What issue is this causing to your application exactly ? Because if you connect to the same service using H2 from a regular browser, you will have "https" there as well, and I suspect that your application works from a browser.

**Comment by shamsimam** [comment]
Hi @wtarreau 

My application is configured as an h2c server written in Jetty (as a result it does not work directly from a browser).
Jetty treats the request as secure when it sees the `:scheme` header set to `https`, this causes the requests to fail as they incorrectly report to being secure requests.
Since HA-Proxy is configured to send h2c traffic to the backend, I think it makes sense to send `http` as the scheme in the request.
We have traditionally relied on the `X-Forwarded-Proto` header to determine the scheme of the client request. 

Regards,
Shams.

**Comment by shamsimam** [comment]
Clarifying question: when using `bind *:9090 proto h2` (without SSL), is it correct to expect the `:scheme` to be `http` (i.e. we are using `h2c` and not `h2` to talk to the backend)?

**Comment by wtarreau** [comment]
On Fri, Apr 12, 2019 at 02:12:18PM -0700, Shams wrote:
> Clarifying question: when using `bind *:9090 proto h2` (without SSL), is it
> correct to expect the `:scheme` to be `http` (i.e. we are using `h2c` and not
> `h2` to talk to the backend)?

Really, you don't know what was used on the stage before. And very likely
it was https because browsers only use h2 for https, so if you arrive on
haproxy using h2 without SSL, it usually means another component has
stripped SSL one stage before reaching it. Again, the scheme is only
useful to outgoing proxies.

Ideally haproxy should forward the scheme it received. It should possibly
work in HTX mode as it's a pseudo header, but I'm not sure at all that it
is not forced all the time for the cases it's not present in H1.

Willy

**Comment by shamsimam** [comment]
> Really, you don't know what was used on the stage before. 

I arrived at HA-Proxy with `http`, request was using `http` scheme in `curl`. The HA-Proxy config is also set up to listen for `h2c` requests (`proto h2` without SSL). My question is whether it is correct to expect that HA-Proxy will only accept `h2c` requests and the `:scheme` that should be sent to the backend with `localhost:8080 proto h2` is `http` and not `https`?

> Ideally haproxy should forward the scheme it received.

If that is the case, can we ensure that `http` is the scheme that is sent to the backend as that is not what I am currently experiencing.

**Comment by wtarreau** [comment]
As I already said, the point is not whether or not your question is correct, but what is usually correct for something misdesigned. Given that the scheme doesn't exist outside of the H2 protocol itself, and that the transport is modified by offloaders without H2 being aware of it, the way we received the request or we send forward it is irrelevant to the contents of this pseudo-header. In the best case we could imagine transfering it when we know it, which would still void any H1->H2 possibilities. In practice, aside forward proxies nobody uses :scheme. I think you are just confused because you're looking at it and were surprised.

**Comment by gouki777** [comment]
so,haproxy unsupported (http-h2c) protocol? I had the same problem.  
My service is GRPC/(h2c),but protocol is http.  
if you have fixed.please tell me.
<pre>
frontend waiter
    mode http
    bind *:9090 proto h2
    default_backend local_node

backend local_node
    mode http
    server localhost localhost:8080 proto h2
</pre>

**Comment by wtarreau** [comment]
@gouki777  what problem exactly are you facing ? I used exactly this setup when I worked on the gRPC tests and it worked fine. You're obviously missing the defaults section which sets the HTX mode otherwise this config cannot even start. Please be a bit more explicit on our problem.

**Comment by gouki777** [comment]
@wtarreau
i used option http-use-htx.    
I used config (bind *:8443 ssl crt /usr/local/etc/haproxy/haproxy.pem alpn h2) [https://] web is good.
frontend proto h2 ->backend proto h2 not working.  
my config:
<pre>
global
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS
  ssl-default-bind-options ssl-min-ver TLSv1.1

defaults
  log global
  maxconn 40960
  mode http
  option dontlognull
  timeout connect 5000ms

listen stats
    bind :19090
    mode http
    stats uri /haproxy_stats

frontend grpc
    mode http
    option http-use-htx
    bind *:80 proto h2
    default_backend http2-server
backend http2-server
    mode http
    option http-use-htx
    server k8s1 10.80.78.1:80 check proto h2
</pre>
my web is HTTP2 is good. code 200，but look this error 404.
<pre>
# curl -vosa "http://www.iftest.com/" --http2-prior-knowledge
* Expire in 0 ms for 6 (transfer 0x55e4eec165c0)
* Expire in 1 ms for 1 (transfer 0x55e4eec165c0)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Expire in 1 ms for 1 (transfer 0x55e4eec165c0)
* Expire in 2 ms for 1 (transfer 0x55e4eec165c0)
* Expire in 1 ms for 1 (transfer 0x55e4eec165c0)
* Expire in 1 ms for 1 (transfer 0x55e4eec165c0)
* Expire in 1 ms for 1 (transfer 0x55e4eec165c0)
*   Trying 10.21.8.224...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55e4eec165c0)
* Connected to www.iftest.com (10.21.8.224) port 80 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55e4eec165c0)
> GET / HTTP/2
> Host: www.iftest.com
> User-Agent: curl/7.64.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< x-content-type-options: nosniff
< content-length: 19
< date: Mon, 22 Apr 2019 10:04:31 GMT
< 
{ [19 bytes data]
100    19  100    19    0     0    260      0 --:--:-- --:--:-- --:--:--   260
* Connection #0 to host www.iftest.com left intact
</pre>

**Comment by lukastribus** [comment]
@gouki777 this has nothing to do with the issue reported here. Let's stick to the discourse thread:

https://discourse.haproxy.org/t/haproxy-not-work-h2c-proto-h2-in-http-protocol/3750

**Comment by wtarreau** [comment]
Closing this one since the reported finally found the issue in his server configuration.

**Comment by shamsimam** [comment]
@wtarreau Can you clarify what is the incorrect server configuration?

Based on these images (from the issue description):

![image](https://user-images.githubusercontent.com/6611249/55736200-757e3180-59e8-11e9-971d-5321a2d55c05.png)

![image](https://user-images.githubusercontent.com/6611249/55736218-829b2080-59e8-11e9-9b49-4672bf841f20.png)

it appears to be incorrect scheme being sent by haproxy on the request.

**Comment by wtarreau** [comment]
I don't know the detail, it was mentioned by the reporter here on discourse link above : https://discourse.haproxy.org/t/haproxy-not-work-h2c-proto-h2-in-http-protocol/3750 : 
"sorry.The problem is in the backend.I error"

In your case, yes as you've found you're seeing two different schemes and as I explained that's expected and unfixable at the protocol level without having a specific option to indicate which one you *want* to see on the server side. The scheme is unusable since it is bogus by design as soon as it passes through any intermediary as it is not updated by pure TLS offloaders and is not presented over HTTP/1.1, unless it's for a proxy connection.

Maybe if we enumerate all possible combinations it will be easier to figure what could be improved to provide a good natural choice by default, but I doubt it, especially if applications rely on it :-/

**Comment by wtarreau** [comment]
Ah you were the reported, I thought it was the one from discourse in fact. I'm sorry I closed your issue then while he was the one who hijacked it. I'm reopening it.

**Comment by shamsimam** [comment]
Thank you for reopening the issue.

> In your case, yes as you've found you're seeing two different schemes and as I explained that's expected and unfixable at the protocol level without having a specific option to indicate which one you want to see on the server side. 

Isn't the setting of `proto h2` (without SSL in the server option) clearly indicate that we want to send non-SSL requests (i.e. scheme=http) to the server?

**Comment by wtarreau** [comment]
No, as I explained already the server-side connection is totally unrelated to the scheme, which is presented by the client. *IF* applications use the scheme, it's like yours, to build links. Given that no browser supports H2 in clear, they already expect to see https links and send a matching scheme, even if there is a naïve TLS offloader in the middle or an H2-aware intermediary like haproxy decrypting TLS and passing the request in H2 clear to the server. We could imagine trying to pass the scheme between the two sides, except that there is not necessarily one on the other side if the request comes from H1. Imagine just for an instant a config looking like this :

     frontend foo
          bind :443 ssl crt ... alpn h2,http/1.1
          bind :80
          use-backend bar
     backend bar
          server local 10.1.2.3:80 proto h2
          server remote 10.11.22.33:443 ssl alpn h2

On the frontend you can get an SSL request from H1 or H2. Only the H2 one will have a scheme. On port 80 you can get a clear request from H1 and H2. Only the H2 one will have a scheme. Given that browsers don't support H2C, requests coming there will come from bots, search engines, Curl or TLS offloaders. And on the server side, you have one local server and a remote one accessed over TLS. It's clearly visible that the scheme information is totally unrelated to the server-side settings and 100% to the way the client initiated its connection (and I'd say the *initial* client since we can already receive a previously deciphered connection).

Maybe we should find a way to represent this inside HTX and have the ability to manipulate it using http rules. For example some intermediaries which can process H1/H2 will also pass some headers like x-ssl:true or whatever, which some might want to rely on to decide on the scheme to pass.

**Comment by shamsimam** [comment]
>  IF applications use the scheme, it's like yours, to build links.

If the application is aware of proxies, the defacto standard is to rely on the [`X-Forwarded-Proto` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto).

The contention with this issue is that the `:scheme` header is being generated by haproxy. Since haproxy knows the connection (ssl or not) it is using to connect to the backend, it should generate the appropriate `:scheme` header for the connection.

**Comment by wtarreau** [comment]
On Sun, Jun 02, 2019 at 04:30:11AM -0700, Shams wrote:
> >  IF applications use the scheme, it's like yours, to build links.
> 
> If the application is aware of proxies, the defacto standard is to rely on the [`X-Forwarded-Proto
> ` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto).
> 
> The contention with this issue is that the `:scheme` header is being
> generated by haproxy. Since haproxy knows the connection (ssl or not) it is
> using to connect to the backend, it should generate the appropriate `:scheme`
> header for the connection.

Haproxy is not the client here, it's an intermediary. It's not inventing
this connection thus it should not present a scheme that is purposely
unrelated to what is being done. If the application wanted to know what
scheme is being used over its own connection, it wouldn't have to rely on
a proxied header nor proxied scheme. If it wants a scheme it's precisely
because it knows there is zero relation between the connection it receives
and what the client askd for. If in your case you only want the application
to process clear traffic over a clear port even if the client is remote,
why not simply hard-code http in the application or simply rely on the
connection's properties ?

Willy

**Comment by shamsimam** [comment]
> If in your case you only want the application to process clear traffic over a clear port even if the client is remote, why not simply hard-code http in the application or simply rely on the connection's properties ?

The client is the same in both cases, curl. The command is `curl --http2-prior-knowledge http://localhost:9090`.

The scheme is correctly read as `http` when haproxy is not intermediating the request. The only difference between the two wireshark images I presented above is having haproxy in the middle or not. Consequently, any difference in the `:scheme` headers of the request should be attributed to changes introduced by haproxy.

**Comment by wtarreau** [comment]
On Sun, Jun 02, 2019 at 07:04:18AM -0700, Shams wrote:
> > If in your case you only want the application to process clear traffic over a clear port even if the client is remote, why not simply hard-code http in the application or simply rely on the connection's properties ?
> 
> The client is the same in both cases, curl. The command is `curl
> --http2-prior-knowledge http://localhost:9090`.
> 
> The scheme is correctly read as `http` when haproxy is not intermediating the
> request. The only difference between the two wireshark images I presented
> above is having haproxy in the middle or not. Consequently, any difference in
> the `:scheme` headers of the request should be attributed to changes
> introduced by haproxy. 

At this point I think you're insisting on deliberately not wanting to read
what I explained multiple times and in different ways. This is sad because
instead of helping to try to find a constructive way to improve the situation
this just makes me want to give up. Yes I perfectly know that it is haproxy
which sets the header this way, and no it has nothing to do with the outgoing
connection. Here the best solution would possibly be to *try* to copy the
one we received from the client regardless of the protocol used on the
other side. But given that the only complaint we've got for now is from
someone going in loops over the same argument instead of participating to
a technical solution, I think the priority to address this will remain
quite low.

Willy

**Comment by shamsimam** [comment]
> At this point I think you're insisting on deliberately not wanting to read what I explained multiple times and in different ways.
> But given that the only complaint we've got for now is from someone going in loops over the same argument instead of participating to a technical solution...

It is certainly not my intent, I'm sorry if it appears so. I really do wish to have a constructive way to improve the situation. I would proffer a reason for your interpretation of my state as possibly being that I do not have enough background to truly understand all the complexities provided as explanations. Not participating to arrive at a technical solution intentionally is something I would not like to be accused of as I know that is not the case. Perhaps having a table of all the incoming frontend and outgoing backend protocols and the resolved `:scheme` header might help move the discussion forward and set expectations of expected values.

>  I think the priority to address this will remain quite low.

I understand that there are many other features or issues the team is working on and this issue being prioritized low. I do hope not being interpreted as unwilling to arrive at an agreeable solution be one of the reasons for such prioritization of this issue.

**Comment by TimWolla** [comment]
@capflam Is commit 3b44c54129a4f8334834dda6344c512e76e883fa related to this issue?

**Comment by capflam** [comment]
@TimWolla, yes, definitely. I don't know if that's exactly what @shamsimam  expected. But it is related.

**Comment by TimWolla** [comment]
@capflam I've switched the status back to “reviewed” from “invalid” then. Maybe “fixed” is an appropriate label in the end if Shams confirms that it fixes the issue.

**Comment by wtarreau** [comment]
On Fri, Jun 14, 2019 at 05:26:20AM -0700, Tim Düsterhus wrote:
> @capflam I've switched the status back to "reviewed" from "invalid" then.
> Maybe "fixed" is an appropriate label in the end if Shams confirms that it
> fixes the issue.

That was indeed for his problem, and "fixed" should be the right status
as the purpose was to transmit the front scheme to the back whenever
possible instead of always emitting "https".

Willy

**Comment by shamsimam** [comment]
Thank you very much for the fix.

**Comment by wtarreau** [comment]
I don't think we'll backport this one to 1.9 because it requires significant modifications to the HTX layer while 2.0 is going to be released in a matter of days. Thus I'd rather keep 1.9 in the current state with this limitation and encourage everyone to switch to 2.0 which is long-term supported instead.

**Comment by shamsimam** [comment]
Okay, thanks for the heads up.

**Comment by shubhamranjan** [comment]
We are facing a similar issue with one of our grpc application server running asp dotnet core 3.1 behind Haproxy 2.0.16.

Frontend is configured with ssl bind  and backend is unencrypted . When the request is going to the backend, `:scheme` is still set to `https` instead of `http` because of which the server seems to rejecting the grpc calls.

Is there a way to override the `:scheme` header ? We tried overriding using the ideal header injection way but that doesn't seem to take priority.

**Comment by nazar554** [comment]
> 
> 
> We are facing a similar issue with one of our grpc application server running asp dotnet core 3.1 behind Haproxy 2.0.16.
> 
> Frontend is configured with ssl bind and backend is unencrypted . When the request is going to the backend, `:scheme` is still set to `https` instead of `http` because of which the server seems to rejecting the grpc calls.
> 
> Is there a way to override the `:scheme` header ? We tried overriding using the ideal header injection way but that doesn't seem to take priority.

@shubhamranjan Did you find a solution?

**Comment by shubhamranjan** [comment]
> 
> 
> > We are facing a similar issue with one of our grpc application server running asp dotnet core 3.1 behind Haproxy 2.0.16.
> > Frontend is configured with ssl bind and backend is unencrypted . When the request is going to the backend, `:scheme` is still set to `https` instead of `http` because of which the server seems to rejecting the grpc calls.
> > Is there a way to override the `:scheme` header ? We tried overriding using the ideal header injection way but that doesn't seem to take priority.
> 
> @shubhamranjan Did you find a solution?

No, the following workaround is possible though:

1. Use self signed certs in backend services and disable cert verification for backend services on haproxy.
2. Alternatively, move frontend to unencrypted (no ssl bind).

**Comment by wtarreau** [comment]
The https scheme is set by default to https over H2 when unknown on the front side because the vast majority of deployments use it this way, regardless of the apparent front connection's status as SSL offloading is something frequent, and we don't want to risk "downgrading" requests by accident. If you absolutely need to force the scheme to http, you can do it by rewriting the URI:
```
   http-request set-uri http://%[req.hdr(Host)]%[pathq]
```

Or even `http-request set-uri http://%[baseq]` with the latest 2.4-dev8.

**Comment by nazar554** [comment]
@wtarreau That didn't help, still getting

```
  Trace id "0HM6JCNB24BRB:00000001": HTTP/2 stream error "PROTOCOL_ERROR". A Reset is being sent to the stream.
      Microsoft.AspNetCore.Connections.ConnectionAbortedException: The request :scheme header 'https' does not match the transport scheme 'http'.
trce: Microsoft.AspNetCore.Server.Kestrel[37]
```
![зображення](https://user-images.githubusercontent.com/12029825/108239823-f36a0280-7152-11eb-9301-531d11ecf749.png)

**Comment by nazar554** [comment]
@wtarreau Actually, nevermind it works if I change the healthcheck to
```
option httpchk GET http://<hostname>/health HTTP/2.0
```

**Comment by gscorrea** [comment]
I am having the same issue, but with the "http-check send" for health check.
I can not set uri with http://<hostname>, because hostname will change for each server being checked.
I need to send a HTTP2 GET request where the HEADER :scheme: is set to http (not https) and HEADER :authority: is the IP address of each server on the server line
I know that setting the HEADER :authority: question is off topic for this thread, but the HEADER :scheme: issue is not and since I need both, I will ask here hoping to get an answer.
Help would be very appreciated. 
````
frontend nrfs
    bind 10.10.10.1:80
    mode http
    acl nrf-52 dst 10.10.20.1
    acl nrf-56 dst 10.10.20.2
    acl nrf-61 dst 10.10.20.3
    use_backend rdm52-nrf if nrf-52 { path -i -m beg /nnrf-nfm/v1/nf-instances }
    use_backend rdm56-nrf if nrf-56 { path -i -m beg /nnrf-nfm/v1/nf-instances }
    use_backend rdm61-nrf if nrf-61 { path -i -m beg /nnrf-nfm/v1/nf-instances }

backend rdm52-nrf
    source 10.10.10.2
    option httpchk
    http-check send meth GET uri /nnrf-disc/v1/nf-instances ver HTTP/2 hdr :scheme http
    http-check expect rstatus (2|3|4)[0-9][0-9]
    server nrf52 10.10.20.1:80 check inter 2m downinter 2m proto h2
    server nrf61 10.10.20.3:80 check backup inter 2m downinter 2m proto h2
    server nrf56 10.10.20.2:80 check backup inter 2m downinter 2m proto h2

backend rdm61-nrf
    source 10.10.10.2
    option httpchk
    http-check send meth GET uri /nnrf-disc/v1/nf-instances ver HTTP/2 hdr :scheme http
    http-check expect rstatus (2|3|4)[0-9][0-9]
    server nrf61 10.10.20.3:80 check inter 2m downinter 2m proto h2
    server nrf56 10.10.20.2:80 check backup inter 2m downinter 2m proto h2
    server nrf52 10.10.20.1:80 check backup inter 2m downinter 2m proto h2

backend rdm56-nrf
    source 10.10.10.2
    option httpchk
    http-check send meth GET uri /nnrf-disc/v1/nf-instances ver HTTP/2 hdr :scheme http
    http-check expect rstatus (2|3|4)[0-9][0-9]
    server nrf56 10.10.20.2:80 check inter 2m downinter 2m proto h2
    server nrf61 10.10.20.3:80 check backup inter 2m downinter 2m proto h2
    server nrf52 10.10.20.1:80 check backup inter 2m downinter 2m proto h2
````

**Comment by nazar554** [comment]
@gscorrea Maybe try `http-check send meth GET uri-lf "http://%si/nnrf-disc/v1/nf-instances" ver HTTP/2.0`
`%si` is `server_IP`. You can also add `%sp` for `server_port`

**Comment by capflam** [comment]
Unfortunately, for now `%si` and `%sp` are not available from health-checks. I'm working on it to make them available. I'll also add corresponding sample fetches (`bc_dst` and `bc_dst_port`).

**Comment by gscorrea** [comment]
Is there any other way that I can accomplish that? I am running HAPROXY 2.2.2.
Which release will this be available?
Thanks for prompt reply and support.

**Comment by capflam** [comment]
Well, the sample fetches are quite isolated thus, it may easily be backported. Exposing `%sî` and %`sp` is probably small enough to be backported too to the 2.2. But it should be evaluate first. 

BTW, if you are running on the 2.2.2., you should consider to upgrade to the last 2.2 because hundreds bugs were fixed. Especially a major one related to the H2 health-checks.

**Comment by wtarreau** [comment]
By the way, I'd like to chime in to remind users that having different host names among servers in a same load balancing farm stems from a very very very very bad architecture (and fortunately almost nobody does that mistake anymore). Host names are integral part of a resource's location, and load balancing requests between different resources makes no sense. I know how it's often done, host names are rewritten along the chain to try to partially work around the mess (and some even abused the http-send-name-header for this). But that's a terribly bad practice which is very hard to get out of once you start applying it. It causes all sort of trouble like broken cookies, messed up redirects, bad links in pages, regularly results in information leaks during errors or outages, broken fail-over, or non-working logouts and should be avoided above all.

I know that the people who manage load balancers rarely have the choice and have to swallow whatever they're thrown in the face (which is how haproxy ended up as a swiss army knife). But at least it is important to tell application architects that their architecture is wrong and that their application WILL face big trouble due to the huge number of hacks required to make it behave as a single application while it's in fact a collection of individual ones. It's OK when it's a legacy application trying to end its life peacefully, but it's not OK when it's a new application.

**Comment by gscorrea** [comment]
Do you have a tracking number for this health check enhancement on the 2,2?

**Comment by capflam** [comment]
It was pushed in upstream (fd81848c and 003df1cff) and backported to 2.3, For now, I only plan to backport the first one to 2.2.

**Comment by capflam** [comment]
FYI, the 2.3.10 is out with the commits above.

**Comment by capflam** [comment]
backported to 2.2. It will be shipped in the next 2.2 release, planned this week.

**Comment by phihos** [comment]
To the people ending up here via Google search like me:

If you have the issue with a ASP.NET Core Kestrel webserver and would not like to apply the [suggested workaround](https://github.com/haproxy/haproxy/issues/77#issuecomment-779716122) then you can set [KestrelServerOptions.AllowAlternateSchemes](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.server.kestrel.core.kestrelserveroptions.allowalternateschemes) to `true` to disable `:scheme` validation.

**Comment by wtarreau** [comment]
Thank you for sharing your findings @philos!
