### ISSUE TITLE
nice finding of cppcheck

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#777]
`src/http_fetch.c:117:10: warning: Either the condition '!p' is redundant or there is overflow in pointer subtraction. [nullPointerArithmeticRedundantCheck]`

**Comment by wtarreau** [comment]
So the code in question is:
```
116   p   = memchr(ctx.value.ptr, ' ', ctx.value.len);
117   len = p - ctx.value.ptr;
118   if (!p || len <= 0)
119         return 0;
```
So on this one, cppheck is wrong:
  - either p is null and len is not used
  - or p is not null and len is positive and valid

Thus you can tag it as a false positive.

**Comment by TimWolla** [comment]
> Thus you can tag it as a false positive.

No, cppcheck is correct here. The `!p` **is** redundant, because if `p` is `0` then `len` will be `<= 0` for sure. Zero minus a non-negative number is less than or equal to zero (unless you wrap around).

So basically the `if` could simply be: `if (len <= 0)`.

**Comment by wtarreau** [comment]
No, it's wrong, as it depends on how far ptr is relative to p. Let's say you're on 32 bits with 3G/1G split (hence 3GB addressable in userland), you can have p=NULL and ctx.value.ptr=0x2300000. Then len is 0x1d00000 and is positive.

And even on x86_64, cppcheck doesn't know where I'm looking. I'm allowed to scan the vsyscall area for example, which is readable and mapped at 0xffffffffff600000. Thus len is 0x900000 when p is null. That's the problem when tools decide they know better than you what you do with your data.

**Comment by TimWolla** [comment]
> No, it's wrong, as it depends on how far ptr is relative to p. Let's say you're on 32 bits with 3G/1G split (hence 3GB addressable in userland), you can have p=NULL and ctx.value.ptr=0x2300000. Then len is 0x1d00000 and is positive.

Okay, yes, you are right of course. The `!p` part is required. I guess that cppcheck assumed undefined behavior for signed integer wraparound which is explicitly defined for HAProxy.

But I'd say that the `len <= 0` still is misleading to the human reader, because it could simply be `!len` or `p == ctx.value.ptr`. Something like the following:

```
	p   = memchr(ctx.value.ptr, ' ', ctx.value.len);
	len = p - ctx.value.ptr;
	if (!p || !len) /* if no space was found or if the space is the first character */
		return 0;
```
or
```
	p   = memchr(ctx.value.ptr, ' ', ctx.value.len);
	if (!p || p == ctx.value.ptr) /* if no space was found or if the space is the first character */
		return 0;
	len = p - ctx.value.ptr;
```

Am I incorrect here?

**Comment by wtarreau** [comment]
Yep that's right. Your first version is the cleanest one and the most accurate one. I'm OK with taking it as a cleanup if you want.

I haven't checked history but I wouldn't be surprized if initially we only had the "len <= 0" part and that due to a coverity check or so, we added "!p" :-)

**Comment by chipitsine** [comment]
I think that cppcheck does not like the idea that substraction can be applied when `p == NULL`, is it allowed to perform arithmetic on NULL pointers ?

**Comment by TimWolla** [comment]
@chipitsine Can you check whether cppcheck still complains about `if (!p || !len)`?

**Comment by wtarreau** [comment]
@chipitsine There's no operation on null pointers here, there is a difference between two pointers. If one is null, it's just a particular case among many others and this particular case is handled on the next line. This means that whatever the representation of null, even if we end up with crap in len, we still test for !p to cover for this case so there's no reason to have an issue here.

I agree with Tim, let's run it on the test he suggests (which is more correct anyway). If it shuts up we can merge the cleanup patch (and if it doesn't we can to it as well, but quite frankly we have sufficiently more complex issues to spend our energy on so that not to waste too much on cppcheck's susceptibility.

**Comment by chipitsine** [comment]
I  tested patch from @TimWolla 

```
	p   = memchr(ctx.value.ptr, ' ', ctx.value.len);
	if (!p || p == ctx.value.ptr) /* if no space was found or if the space is the first character */
		return 0;
	len = p - ctx.value.ptr;
```

cppcheck thinks issue is resolved.

**Comment by TimWolla** [comment]
@chipitsine Did you also check that one:

```
	p   = memchr(ctx.value.ptr, ' ', ctx.value.len);
	len = p - ctx.value.ptr;
	if (!p || !len) /* if no space was found or if the space is the first character */
		return 0;
```

The one in this comment is the one preferred by Willy.

**Comment by chipitsine** [comment]
no, cppcheck is not happy about this one.

**Comment by TimWolla** [comment]
Too bad :frowning_face:

@wtarreau Can you please commit either of the versions (or just close this issue)?

**Comment by wtarreau** [comment]
Hi Tim,
apparently there's only one which addresses the issue (the first one), but OK, let's merge this one. I'll do this tomorrow.
Thanks guys!

**Comment by wtarreau** [comment]
Ilya, feel free to close this one once you've confirmed that cppcheck is happy! Thanks guys!
