### ISSUE TITLE
maybe bug: ssl verify required not sending host name correctly?

### ISSUE THREAD

**Issue by f1-outsourcing** [haproxy/haproxy#795]
I have these config lines in haproxy 2.2

```
  server mail01 mail01.local:443 ssl verify required
  server mail02 mail02.local:443 ssl verify required
```

What I noticed is that the first server check failed in haproxy while these tests were generating the correct certificates.

```
echo | openssl s_client -showcerts -servername mail01.local -connect 192.168.10.41:443 2>/dev/null | openssl x509 -inform pem -noout -text
echo | openssl s_client -showcerts -servername mail02.local -connect 192.168.10.42:443 2>/dev/null | openssl x509 -inform pem -noout -text
```

When I did this test 
`openssl s_client -connect mail01.local:443`
I got another fail, which was correct because the default certificate, was a self signed certificate by exchange. When I changed this default certificate so the default was the same as host mail01.local. 
I started to get a green L6OK message in haproxy. 

This leads me to believe that maybe haproxy is not supporting sni in the health checks.

**Comment by jmagnin** [comment]
haproxy does support sni for health checks, see [check-sni](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#check-sni)

Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
