### ISSUE TITLE
HAProxy with TPROXY

### ISSUE THREAD

**Issue by shailendra-singh93** [haproxy/haproxy#803]
I am looking for the solution on HAProxy with Transparent proxy on centos-7

so far, i have created 4 servers ( 2 HTTP server --> HAProxy server --> ClientMachine) (edited) 

I have configured haproxy.conf file as :

global
   log /dev/log local0
   log /dev/log local1 notice
   chroot /var/lib/haproxy
   stats timeout 30s
   #user haproxy
   #group haproxy
   user root
   group wheel
   daemon
defaults
   log global
   mode tcp
   option tcplog
   option dontlognull
   timeout connect 5000
   timeout client 50000
   timeout server 50000
frontend App_in
   bind 192.168.133.160:80 transparent
   mode tcp
   default_backend App_out
backend App_out
   mode tcp
   log global
   source 0.0.0.0 usesrc clientip
   balance roundrobin
   server http-1 192.168.133.133:80
   server http-2 192.168.133.142:80

when i am trying to curl from ClientMachine i get response as empty reply

[root@test-vm ~]# curl 192.168.133.160 -i -v
* About to connect() to 192.168.133.160 port 80 (#0)
*   Trying 192.168.133.160...
* Connected to 192.168.133.160 (192.168.133.160) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.133.160
> Accept: */*
>
* Empty reply from server
* Connection #0 to host 192.168.133.160 left intact
curl: (52) Empty reply from server

Can anyone help please???

**Comment by jmagnin** [comment]
This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.
 
Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
