### ISSUE TITLE
Not able to enable H2

### ISSUE THREAD

**Issue by waytoharish** [haproxy/haproxy#805]
HA proxy

We are trying to enable HTTP2 for Frontend as well backend but backend still on http1
Front End alpn h2,http/1.1
Backend 'alpn h2,http/1.1`
Default -option http-use-htx

**Comment by lukastribus** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
