### ISSUE TITLE
Mix 2 method of balancing

### ISSUE THREAD

**Issue by asurovenko** [haproxy/haproxy#808]
Hello all!
Haproxy can balance traffic using http param:
`balance url_param userid`
if that param is new or absent than haproxy will use round robin.
Can I configure haproxy to use leastconn insead round robin with url_param balancing?
If there's known user_id -> send request to known server
If there's new user_id -> send request to server with least connection?

Thanks!

**Comment by asurovenko** [comment]
`added the status: invalid label`
It's not true, please remove that label.

**Comment by lukastribus** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
