### ISSUE TITLE
Consistent server-template assignment between peers.

### ISSUE THREAD

**Issue by tmccombs** [haproxy/haproxy#814]
## What should haproxy do differently? Which functionality do you think we should add?

Have a way to make the stickiness to server ip addresses consistent between peers in a cluster of haproxy instances, even if the order of DNS results is not consistent, when server-template is used (or for that matter multiple server lines with the same hostname).

Some ways this might be done:

- Sort DNS results before assigning to servers. Probably the easiest to implement, but will probably have error modes if haproxy processes get different results for some reason, or are started when the backends are in different states.
- Change stick-tables to map to ip-address (or possibly hostname, though that would only work for SRV discovery) instead of "server id". I'm not sure how backwards compatible that change would be
- Have some way to synchronize the association of ip addresses with servers between peers.

## What are you trying to do?

I have multiple instances of haproxy running, for high-availability, and would like sessions to be sticky to backend servers based on part of the request (such as a cookie or path component). I also want to use `server-template` to dynamically allocate servers based on DNS results. I would prefer just to use an A record with multiple resources, but a SRV record would also be acceptable.

I've considered trying to change the DNS servers to respond in a consistent order, however, doing so would require me to compile and maintain a package for my DNS server software myself to enable support for that, and after looking through the source code for how ip addresses are associated with servers, I think that would only mitigate the problem in an ideal situation, not solve it entirely. For example, if one of the haproxy instances started later than the others, and the set of backend servers had changed since, then the new haproxy process might still end up with different assignments than the older processes.

**Comment by tmccombs** [comment]
Another option: keep the current behavior for server assignment, but when propagating  stick tables use the ip address (or possibly hostname) rather than server id, and then assign the appropriate server on the peer.

**Comment by vkryzh** [comment]
Need this feature badly. Service-discovery brakes stick-table each time pods in k8s are scaled up or down :( Using confd for service discovery instead and to reload haproxy, but it has own bugs as well :(

**Comment by chipitsine** [comment]
hello, @failytaler 

what do you mean by "it has own bugs as well" ? can you provide some details ?
maybe open another issue ?

**Comment by vkryzh** [comment]
@chipitsine Sure, trying to triage some bug right now. Will update on any success. In short, we are using stick tables, 1 haproxy server with a local peer. Confd reloads HAProxy, but HAProxy resets stick table at some moment (cannot link it with reload actually) and not closing the existing connections (it has no reason to - all servers are UP). This leads to customers that should be one server to be split between nodes. We tried to reload haproxy 10 times per second and stick table was successfully transferred, But at some moment all data just disappears like magic without any traceable events. Maybe you will recommend how we can log/monitor stick-table health (we are trying to watch API, but it barely helps)

Internal server-templates cannot be used for sure because of the bug stated by @tmccombs - servers are messed up during service discovery. So confd is the only way we see right now (we can give proper names for servers based on ip/name). But several days ago half of our customers appeared in different servers and we are investigating this issue right now.

**Comment by tmccombs** [comment]
We've actually seen the issue with restarts/reloads causing stick-tables to get reset as well. In fact, we were initially using the dynamic config approach, but ran into the stick-tables reset bug. We then tried moving the service to a separate haproxy cluster that has config that changes less frequently , so doesn't need to reload very often and using server-template. Then we encountered this bug/absence of feature. Fortunately for us, the backend servers for this particular service don't change very often, so we were able to switch back to dynamic config in a seperate cluster. 

Unfortunately, we have not been able to create a minimal reproducible case of the stick-table reset on reload problem.

**Comment by wtarreau** [comment]
What version do you use ? I'm asking because that was part of the features that went into 2.0, and that was enabled by default. Now by default what is exchanged is not the server ID but its name, precisely so that the server's ordering doesn't count anymore. And it was designed in a way to make it easy to extend it and add "server_addr" if some needed that to work around random DNS ordering. But please note that if your servers get random addresses from multiple DNS responses, you don't even have a way to make sure the same address exists on the other node! So there's always a minimum needed to maintain consistent stickiness between nodes.

**Comment by tmccombs** [comment]
We are currently using 1.8 in production, but have been in the process of testing upgrading to 2.0 in pre-production environments, and hope to upgrade to 2.0 soon.

> And it was designed in a way to make it easy to extend it and add "server_addr" if some needed that to work around random DNS ordering. 

This is precisely the problem I have. The DNS ordering is random, and which results not only in different server ids, but different server names for the same servers in different peers. And just to be clear, you are saying there isn't currently a way to use server_addr instead of server_id/server_name, but the code is written in a way it could be easily added?

By the way, other than the 2.0 announcement, I can't really find any documentat of being able to use server_name as a data type in stick tables (for example configuation.txt doesn't list it is an available data type for stick tables.

**Comment by wtarreau** [comment]
OK but then how can you be sure that you have the same servers are the same on each side ? I mean, if you're having many IPs advertised by the DNS for a same name, the responses also depend on the addresses the DNS server will return, so you could fairly well have different farms.

Concerning the ability to implement server_addr, I remember that the idea consisted in using temporary IDs mapped via a dictionary between peers, so that the way to identify a server could be based on different criteria without having to evolve the underlying protocol. What matters is that each side knows what to match the string against. So instead of exchanging the server's name we could decide to exchange the textual representation of the server's address and that must work the same. I just don't remember what we had in mind regarding the way to configure the matching criterion (it was about 1.5 years ago).

Regarding server_name, indeed I don't see it mentioned in the doc, but from what I remember, it's automatically enabled along with server_id. @haproxyFred do you confirm ?

**Comment by tmccombs** [comment]
> OK but then how can you be sure that you have the same servers are the same on each side ? I mean, if you're having many IPs advertised by the DNS for a same name, the responses also depend on the addresses the DNS server will return, so you could fairly well have different farms.

I'm sorry, I'm having a hard time parsing this. But maybe if I give a more concrete example of what is happening that will help.


Perhaps I should give a more concrete demonstration of the problem:

Suppose I have DNS configured with something like this:

```named
service.example.com.  IN A 10.0.0.1
                         A 10.0.0.2
                         A 10.0.0.3

```
where this record set is dynamically configured using the ip addresses from the instances in a dynamically scaled group of servers.

And I have two haproxy peers with a backend containing configuration like:

```haproxy
stick-table type string len 36 size 10k peers mypeers
stick on req.hdr(my-header)
server-template service 3 service.example.com:8080 check resolvers myresolvers init-addr none
```

and my DNS server responds with records in a random order (or rotates the order). So haproxy instance A gets them in the order 10.0.0.1, 10.0.0.2, 10.0.0.3 but instance B gets them in the order 10.0.0.2, 10.0.0.3, 10.0.0.1.

So then A ends up with servers like:

```
server1 -> 10.0.0.1
server2 -> 10.0.0.2
server3 -> 10.0.0.3
```

but B has servers like:

```
server1 -> 10.0.0.2
server2 -> 10.0.0.3
server3 -> 10.0.0.1
```

So, while the stick tables are propagated between the peers, sessions are only sticky if all the client's request happen to end up on the same haproxy server.

> OK but then how can you be sure that you have the same servers are the same on each side ? I mean, if you're having many IPs advertised by the DNS for a same name, the responses also depend on the addresses the DNS server will return, so you could fairly well have different farms.

If I understand correctly, you're saying that using the ip address wouldn't work in the case that the server-template is using SRV records (as opposed to A records as in my example above), where the target hostnames for the service themselves point to A record sets containing multiple records/ip address?

Given that I think it would make sense to use the target hostname (`server->hostname`?) if it is using an SRV record or the ip address (`server->addr`?) if it is using an A record.

This is all assuming that the "server_name"  you refer to is the name for the server line in haproxy (like "server1", "server2", "server3" in the above example), which is consistent with what I have seen in the source code (for example https://github.com/haproxy/haproxy/blob/398da62c38014c76006571e0caa52a3799f41815/src/stream.c#L1415). If I'm missing something and "server_name" actually means something like the hostname received in response to a SRV DNS query, then perhaps I can get this working by using SRV records and upgrading to 2.0?

**Comment by tmccombs** [comment]
Another possible approach to this could be to make the server name dynamic based on the DNS response (target hostname for a SRV request, ip address for an A request). I don't know what all the implications of that would be, and it might need to be opt-in, since it might break existing configurations and scripts. But that would actually be nice in other ways, since the server name would then be more meaningful/useful than a static prefix plus an index. And then the existing peering and stick-tables logic wouldn't need to be changed.

**Comment by vkryzh** [comment]
We are using latest HAProxy. Our main issue why we are trying to develop a bicycle the next and it breaks the whole beauty of stick tables for us:
During initial DNS discovery, we have SRV record with 100 servers server list looks like:

- srv1 IP1 UP
- srv2 IP2 UP
- srv3 IP3 UP
...

We downscale our server or k8s health-check fails and one of servers is undiscoverable.
HAProxy reevaluates list of servers. The new list looks like:

- srv1 IP2 UP
- srv2 IP1 UP
- srv3 IP3 MAINT/DOWN
...

As you can see, servers in SRV record shuffled. Order is changed.
So clients, connected to srv1 will stay there, but new clients that want to be connected to the server1 will appear on server2, because in stick table srv1 is now pointing to IP2.
Using external confd service we use name linked to SRV record name, not just srv#. So, during rediscovery servers in the list are not shuffled.

Examples of Server-template:
```
server-template srv NUM _http._tcp.SERVICE_NAME.NS.svc.cluster.local resolvers localdns check inter 5s downinter 10s fastinter 2s fall 5 on-marked-down shutdown-sessions 
```

Example for Confd:
```
  {{range lookupSRV "http" "tcp" "SERVICE_NAME.NS.svc.cluster.local}}
  server {{.Target}} {{.Target}}:{{.Port}} check inter 5s downinter 10s fastinter 2s fall 5 on-marked-down shutdown-sessions
  {{end}}
```
But in this case we have another issue and cannot use it in Production - it breaks stick-tables in some cases during reload. We can now reproduce this only during significant server count change (we downscale backends from 400 to 5 for example). Stick tables just being cleared all at once immediately. However, if we scale-down 100 servers at time, everything is good, but this behaviour cannot be explain and trusted.

**Comment by wtarreau** [comment]
@tmccombs I understand well your description and that matches what we said would justify having the option to stick on the address instead of the name.  What I meant regarding the number of addresses vs number of servers is that if you have less templates than advertised servers, you can already end up with different farms on the two nodes. Based on your explanation it doesn't seem to be the case though.

Regarding the ability to rename the servers, no, as you guessed, that's not feasible, they're used as a primary key at plenty of places in the conf (use-server, track, queue, ...), to be managed over the CLI, to report in logs and stats.

However I'm wondering, what criterion are you sticking on, and is your traffic HTTP ? I'm asking because the safe way to stick on HTTP is by using a cookie, and we happen to have this `dynamic` keyword on the `cookie` directive, that makes use of the server's IP and port. It was designed precisely for your use case, where only the IP and port matter.

**Comment by tmccombs** [comment]
> What I meant regarding the number of addresses vs number of servers is that if you have less templates than advertised servers, you can already end up with different farms on the two nodes. Based on your explanation it doesn't seem to be the case though.

Oh, yeah, I can see how that would be a problem. In our case, we always want to keep the number of servers >= the number of addresses (we set it to the maximum capacity of the auto-scaling group). Having to specify the number of servers for a template is actually a little inconvenient for us, but I'm sure there is a good reason for that.  I'm also not sure what the use case would be to have the number of servers less than the number of addresses but also want to peer stick tables.

> However I'm wondering, what criterion are you sticking on, and is your traffic HTTP ? I'm asking because the safe way to stick on HTTP is by using a cookie, and we happen to have this dynamic keyword on the cookie directive, that makes use of the server's IP and port. It was designed precisely for your use case, where only the IP and port matter.

It is HTTP. Unfortunately however, I don't think the `cookie` directive will work for us. For the particular use case I am concerned about, we are sticking on a document id from the request path.  For performance reasons, we want requests for the same document to go to the same backend server, even if they come from different clients. Think multiple people collaborating on a document in real time. This also means that for a single client, we may want to send multiple requests to different backend servers.

**Comment by tmccombs** [comment]
> What I meant regarding the number of addresses vs number of servers is that if you have less templates than advertised servers, you can already end up with different farms on the two nodes.

I thought about this some more, and I realized that you would run into a similar problem if the configuration for different haproxy instances had mismatched server names for a backend for whatever reason. I wonder if having less templates than advertised servers should be handled in a similar way to how that is currently handled. Of course, it would probably be good to state in the documentation that the number of tables should be >= the number of advertised servers for good behavior when using peering.

**Comment by tmccombs** [comment]
I'd like to take a stab at implementing this.

@wtarreau I don't suppose you have a link to previous discussion/documentation on how server_addr would work?

**Comment by wtarreau** [comment]
Hi @tmccombs 

Sorry for the lag. I don't seem to have a link to such a discussion, but the general principle is the following: right now stickiness is performed by exchanging server IDs, these IDs being unique within a backend. Given that most people don't set them, many end up with dynamic IDs simply corresponding to the position of the server in the farm. For some users it was a problem because they wanted to stick to a server from its name, regardless of the position in the farm (e.g. when confs are generated, they're not necessarily in the same order). Thus we thought that it could be great to make it possible to synchronise peers on the server name rather than on its ID.

In order to achieves this, we've though about extending the peers protocol to support dictionaries so that we don't have to pass long names with each and every counter, this would be impractical in terms of bandwidth. Thus there is a small dictionary on each side with automatically assigned IDs and a sliding window. Names that are not found in the local dict just cause the oldest name to be evicted and take its ID. The new name is announced and the other side does the same, resulting in both sides always knowing the same correspondance between IDs and names. The serverid value is then rewritten to use the selected server's temporary ID when the message is being sent, and the other one figures the server from its dictionary and turns it back into the regular server's ID.

We thought that the next step would naturally be to use address:port as the primary indexing key instead of using the server's name, so the code was written with that in mind to try to ease this addition. Typically what you'd have to do is to add an option in the peers section (or maybe rather per peer node) to mention that the key is the server's address, and start to encode, lookup, index and exchange compacted sockaddr_storage structures instead of  names. On the other side, you'll need to look up the server based on the address. For large farms this will eat quite some CPU, but it's probably not an issue. You should have a look at the RDP cookie stuff, as it already does exactly this (figure the first available server using that IP:port, maybe IP alone, but the principle is the same).

Of course it will not be bijective anymore, as addresses are not unique identifiers. So we must make it clear that the *first* matching server will always be selected. I can't find the option that indicates that we're indexing on names instead of IDs, so maybe it's still missing. I thought we had it.  Maybe call that "sid-mapping" followed by "id", "name" or "addr". The discussion on this is still open and your suggestions based on what you discover will be welcome. Just let us know if you figure that some deeper preliminary changes are required. Better not censor yourself so that we do something that can evolve, rather than finding the shyest solution and regret it one year later.
