### ISSUE TITLE
Cannot banlance https to backend

### ISSUE THREAD

**Issue by Mon-ius** [haproxy/haproxy#827]
```
❯ haproxy version
HA-Proxy version 2.2.2-1ppa1~bionic 2020/08/01 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.

```
I have an HTTP **service A** run at https://domain:8080 with and a modified protocol **service B** run at localhost:8081. I would like to use haproxy to balance them at https://domain:443. They should be identified by their protocol.

```
frontend port443-in
    bind *:443 tfo ssl crt path-to-pem
    tcp-request inspect-delay 5s
    tcp-request content accept if HTTP
    use_backend port8080 if HTTP
    default_backend port8081
```

```
backend port8080 <- **service A**
    server server1 127.0.0.1:8080 check

backend port8081  <- **service B**
    server server1 127.0.0.1:8081
```

However, the service A return ` Client sent an HTTP request to an HTTPS server.`, which means it receives HTTP instead of https.

**Comment by jmagnin** [comment]
This is a configuration issue. 

Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.
 
Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
