### ISSUE TITLE
Missing support for IPv6 when using the "accept-proxy" / "server *" feature

### ISSUE THREAD

**Issue by eriklax** [haproxy/haproxy#832]
## Detailed description of the problem

Support for IPv6 when using the "accept-proxy" feature using "server *" and "source * usesrc clientip".

## Expected behavior

I would expect it to work since it could, and I would expect the feature to work the same on IPv4 and IPv6.

## Steps to reproduce the behavior

This should connect to localhost over IPv6.

```
printf "PROXY TCP6 ::1 ::1 0 80\r\nGET / HTTP/1.0\r\n\r\n" | nc 127.0.0.1 1234
```
## Do you have any idea what may have caused this?

There is a few places in the src/proto_tcp.c file where the socket() and connect() doesn't work properly with IPv6. Probably because it uses the wrong sockaddr to decide which address-family and address to use. Looking at a strace, the socket() family is AF_INET, the bind() works, but the connect() doesn't.

## What is your configuration?

```
listen test
        bind *:1234 accept-proxy
        mode tcp
        server internet *
        source * usesrc clientip
```

**Comment by wtarreau** [comment]
Even though it might not be obvious, your config explicitly sets the server to IPv4 : "*" is an alias for "0.0.0.0". There's no trivial way to set a server to both IPv4 and IPv6, because the server must have one address, hence belongs to a single address family, then all operations are made using that address family. I think that in your specific case it would be useful to have two servers, one IPv4 and one IPv6 using address ::: and pick either depending on the incoming connection's address family. For example (completely untested but you get the idea):
```
       use-server v4 if { src 0.0.0.0/0 }
       use-server v6
       server v4 0.0.0.0 source 0.0.0.0 usesrc clientip
       server v6 ::: source ::: usesrc clientip 
```

**Comment by wtarreau** [comment]
Even though it might not be obvious, your config explicitly sets the server to IPv4 : "*" is an alias for "0.0.0.0". There's no trivial way to set a server to both IPv4 and IPv6, because the server must have one address, hence belongs to a single address family, then all operations are made using that address family. I think that in your specific case it would be useful to have two servers, one IPv4 and one IPv6 using address ::: and pick either depending on the incoming connection's address family. For example (completely untested but you get the idea):
```
       use-server v4 if { src 0.0.0.0/0 }
       use-server v6
       server v4 0.0.0.0 source 0.0.0.0 usesrc clientip
       server v6 ::: source ::: usesrc clientip 
```

**Comment by eriklax** [comment]
I can confirm this is working. But had to add if after the use-server on v6

```
use-server v6 if { src ::/0 }
```
