### ISSUE TITLE
HAProxy v2.2 issue with %[url] variable including protocol

### ISSUE THREAD

**Issue by RaspberryPj** [haproxy/haproxy#846]
Just upgraded to v2.2 of haproxy, previously using v1.8.

Using a redirect rule adding `www` before the host portion but wanting to retain the remainder of the url using the following command for a number of domains:

`http-request set-var(req.scheme) str(https)`
`http-request redirect code 301 location %[var(req.scheme)]://www.domainname.com%[url] 		if { hdr(host) -i domainname.com }`

For v1.8, a user browsing to `https://domainname.com/path/or?query=whatever` is successfully redirected to `https://www.domainname.com/path/or?query=whatever`

However on v2.2 the same implementation of `%[url]` results in the user getting: `https://www.domainname.comhttps//domainname.com/path/or?query=whatever`

It seems that on v1.8 the `%[url]` is returning the path as expected but in v2.2 an incorrect `https//host` portion is returned and also doesn't include the `:` protocol delimiter either.

**Comment by jmagnin** [comment]
This change was introduced with this [commit](http://git.haproxy.org/?p=haproxy.git;a=commit;h=30ee1efe676e8264af16bab833c621d60a72a4d7)

note that this is an issue tracker for bug reports and feature requests. 
Please use the  forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
