### ISSUE TITLE
When using "balance uri whole" algorithm in HAProxy 2.2.x, HTTP/2 and HTTP/1.1 requests select different servers respectively. 

### ISSUE THREAD

**Issue by serimin** [haproxy/haproxy#870]
## Detailed description of the problem
HTTP/2 and HTTP/1.1 request in HAproxy 2.2.x select different servers respectively when using "balance uri whole" algorithm.
So, we can't use backend cache farm effectively, because of low cache hit ratio and can't upgrade from 2.0.x.

## Expected behavior
I think that balance algorithm should work the same for both http/1.1 and http/2.

## Steps to reproduce the behavior

1. use "balance uri whole" in Backend
2. curl test(http/1.1, http/2 for same url)
3. verify chosen server from logging

## What is your configuration?

```
backend bk_test
    balance uri whole
    hash-type consistent

    # Rewrite Host Header
    http-request set-header Host %[path,map_beg(/etc/haproxy/acl/test.path,test.com)]
    http-request deny if { hdr(Host) test.com }
    http-request replace-path /[\w.]*/(.*) /\1

    server test1 10.1.1.1:80 check
    server test2 10.1.1.2:80 check
    server test310.1.1.3:80 check
    server test4 10.1.1.4:80 check
    server test5 10.1.1.5:80 check
    server test6 10.1.1.6:80 check
    server test7 10.1.1.7:80 check
    server test810.1.1.8:80 check
    server test9 10.1.1.9:80 check
    server test10 10.1.1.10:80 check
```

## Output of `haproxy -vv` and `uname -a`

```
# haproxy -vv
HA-Proxy version 2.2.3 2020/09/17 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.3.html
Running on: Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64
Build options :
  TARGET  = linux-glibc
  CPU     = native
  CC      = gcc
  CFLAGS  = -O2 -march=native -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits -DTLS_TICKETS_NO=4 -DMAX_SESS_STKCTR=10
  OPTIONS = USE_PCRE=1 USE_PCRE_JIT=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1 USE_SYSTEMD=1

Feature list : +EPOLL -KQUEUE +NETFILTER +PCRE +PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED +BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL +SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=20).
Built with OpenSSL version : OpenSSL 1.1.1g-v1  22 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g-v1  22 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.4.0
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE version : 8.44 2020-02-12
Running on PCRE version : 8.44 2020-02-12
PCRE library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 4.8.5 20150623 (Red Hat 4.8.5-28)

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services : none

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app

# uname -a
Linux aeg-s041.testa 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## If HAProxy crashed: Last outputs and backtraces

```
(paste your output here)
```

**Comment by wtarreau** [comment]
That's a known limitation caused by the fact that URIs are *really* different in H1 and H2: H1 mostly uses origin URIs (but not exclusively) while H2 only uses absolute URIs. I recently discussed (I don't remember where) about the ability to add more arguments to balance uri to support normalizing URIs or focusing on path+query string instead. In any case it will mean a rebalance when migrating from an old to a new config, but that should be for good. I think that as a first step we could have the normalized version which would strip the scheme from absolute URIs, and start from the authority, up to and including the query string. In H1 we'd prepend the host name in front of the URI when it starts with a '/'. I think something like this shouldn't be too hard to implement, could be backported, and could suit most users. What do you think ?

**Comment by wtarreau** [comment]
Tagging as "works as designed" but I definitely want to see this topic progress!

**Comment by serimin** [comment]
Ok, I agree this.
I really need this.

**Comment by wtarreau** [comment]
I'm starting to think that we could possibly consider that by default we always prepend the host name in front of the relative URI so that nobody has to think about this, and add a special "path-only" argument to strip the host part and always start at the first slash. I'm leaning towards breaking compatibility in -stable by backporting it so that the mess only happens once (during the upgrade). Maybe we could find a better solution for backports though.

**Comment by wtarreau** [comment]
Or maybe what we could do is this:
  - have "path-only" to always strip the host (backportable, will make h1 and h2 work similarly when set)
  - not change the default uri in stable branches so that without option h1 and h2 will still differ
  - change the new default in 2.3 and above to always include the host if not present, which can be disabled by "path-only", so that h1 and h2 always provide similar URIs

**Comment by wtarreau** [comment]
OK, what about this ? It works for me.
[0001-MINOR-backend-add-a-new-path-only-option-to-balance-.patch.txt](https://github.com/haproxy/haproxy/files/5266204/0001-MINOR-backend-add-a-new-path-only-option-to-balance-.patch.txt)

**Comment by vedranf** [comment]
I also encountered this behavior recently and is preventing us from smooth upgrade. I agree with the last comment of having path-only option to mimic old behavior while default can differ. It's important to be able to achieve old behavior (without hacks) as with caching it's often not possible to do the instant switch/upgrade as that entails terabytes or more of content being re-pulled and re-cached from the origin servers, something that might take months and might not even be possible unless done very gradually, thus forcing people to stick with old version for unnecessary long time.

Patch just now appeared. Will test and report back. Thanks!

**Comment by serimin** [comment]
I've just tested this patch.
It works well.

Thank you!!

**Comment by wtarreau** [comment]
Perfect, thanks both for your insights and feedback. I'm going to merge it into 2.3, and backport it then since it's a riskless backport as-is!

**Comment by wtarreau** [comment]
OK now merged and backported as far as 2.1 since that's where the issue was introduced.

**Comment by serimin** [comment]
Ah!! sorry.
When using "balance uri", not "balance uri whole", same issue seems to exist.

**Comment by wtarreau** [comment]
Did you add the new option "path-only" after "balance uri" ? That was the purpose of the patch and it works in my tests (even in the regtest I added)

**Comment by serimin** [comment]
I mean "balance uri path-only" option works well, but I don't consider "balance uri" option.

**Comment by wtarreau** [comment]
so you need it with "balance uri whole" ? If so, just add "balance uri path-only whole".

**Comment by serimin** [comment]
Ah, Okay! All works well.

Sorry to confuse you!!

Thank you very much.

**Comment by wtarreau** [comment]
No problem, I wasn't very clear initially. Thanks!

**Comment by wtarreau** [comment]
So I guess we can close this one now.
