### ISSUE TITLE
System holds TCP FIN for 3 seconds during VM01 failover

### ISSUE THREAD

**Issue by pawan1001** [haproxy/haproxy#882]
Hi Team,

We are facing the following issue during failover:-

When rebooting VM01 (node 1),and VIPs are shifted to VM02 (node 2).
It is taking 3-4 seconds to bring VIP up on VM02.

We have some query :-
VM is sending FIN msg even after VIP is up.
Client sent CER to server but not received CEA for 3-4 second.
Why FIN is send by the Haproxy after 3 sec.

We have capture the tcp dump, but not able to found root cause.

**Comment by lukastribus** [comment]
Haproxy does not send any TCP packets, your kernel does, haproxy is just an application using the socket API.

That said:

Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
