### ISSUE TITLE
http-response return does not work when a backend is not defined or when the backend is down

### ISSUE THREAD

**Issue by jaroslawr** [haproxy/haproxy#893]
With this haproxy.cfg:

```
defaults
        mode http
        timeout client 10000
        timeout connect 100
        timeout server 600

frontend lolcathost
        bind localhost:8080
        http-response return status 200
```

I get a 503 response from a GET to localhost:8080. I also still get a 503 when I add a `default_backend` but the backend is not actually up:

```
defaults
        mode http
        timeout client 10000
        timeout connect 100
        timeout server 600

frontend lolcathost
        default_backend jetty
        bind localhost:8080
        http-response return status 200

backend jetty
        server localhost_8082 localhost:8082
```

Only with a backend both defined and running I get the 200 response.

I use haproxy 2.2.3:

```
HA-Proxy version 2.2.3-6a551a-16 2020/09/23 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.3.html
Running on: Linux 5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64
```

**Comment by TimWolla** [comment]
@jaroslawr While this issue appears to contain all the necessary information: Can you please make sure to not ignore the issue template that is filled in by default when creating a new bug report? It exists for a reason.

Regarding your issue: You probably need <strike>either `http-after-response return` or </strike> `http-request return` (or see Christopher's response).

**Comment by capflam** [comment]
`http-response` ruleset is applied on the server response. Here, because the server connection failed, there is no server response. Thus this ruleset is not evaluated. The only ruleset evaluated on HAProxy internal responses is `http-after-response`. But this ruleset is more limited than others.

So, now, depending on what you want to do, you can use the `return` action within an `http-request` rule with some conditions. Or you can define a custom `errorfile` or an `http-error` to customize your 503 errors with a syntax similar to the `return` action.

**Comment by jaroslawr** [comment]
@capflam I indeed misunderstood the feature, thanks!
