### ISSUE TITLE
http-request timeout not works always

### ISSUE THREAD

**Issue by clwluvw** [haproxy/haproxy#897]
## Detailed description of the problem

I have created a session with `nc` to my haproxy and after 19 sec it gets 408.
Sometimes it returns 408 in 2 sec but not always and I can't see any `BADREQ` in haproxy log!
```bash
time nc ${IP} 80 -v
Connection to ${IP} 80 port [tcp/http] succeeded!
HTTP/1.1 408 Request Time-out
content-length: 110
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
^C
nc ${IP} 80 -v  0.00s user 0.00s system 0% cpu 19.015 total
```

```bash
time nc ${IP} 80 -v
Connection to ${IP} 80 port [tcp/http] succeeded!
HTTP/1.1 408 Request Time-out
content-length: 110
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>
^C
nc ${IP} 80 -v  0.00s user 0.00s system 0% cpu 2.999 total
```

## Expected behavior

Based on my configuration below and `timeout http-request` option it should get me 408 after 2 sec!

## Steps to reproduce the behavior

1. `time nc IP 80 -v`
2. Wait until 408 response shown
3. Ctrl + C to see how much time wasted

## What is your configuration?

```
defaults
    mode                    http
    log                     global
    log-format "%ci:%cp [%tr] %ft %b/%s %TR/%Tw/%Tc/%Tr/%Ta %ST %B %U %CC %CS %tsc %ac/%fc/%bc/%sc/%rc %sq/%bq %hr %hs %{+Q}r"
    option                  http-server-close
    option                  forwardfor
    option                  redispatch
    option                  log-health-checks
    option                  log-separate-errors
    retries                 4
    timeout http-request    2s
    timeout queue           1m
    timeout connect         5ms
    timeout client          5s
    timeout server          20s
    timeout check           500ms
    maxconn                 80000
```

## Output of `haproxy -vv` and `uname -a`

Using haproxy 2.2.4 with docker (https://hub.docker.com/layers/haproxy/library/haproxy/2.2.4/images/sha256-841112eb6c3239f028d006f214b37df0b7e16791d4c26de74cf6eb172c24ee1e?context=explore)

**Comment by capflam** [comment]
Could you provide your frontend configuration too. And please share your logs too. Because, with your timeout settings, I always have the 408 response after 2s.

**Comment by clwluvw** [comment]
@capflam 
```
frontend my-frontend
    bind *:80
    bind *:443 ssl crt /usr/local/etc/haproxy/one.pem crt /usr/local/etc/haproxy/two.pem
    capture request header Host len 100
    acl myacl path_beg /1/ || path_beg /2/
    http-request set-header Host something if myacl
    http-request replace-path ^/[1-2]/(.*) /something/\1 if myacl
    default_backend my-backend

frontend stats
    bind *:9102
    http-request use-service prometheus-exporter if { path /metrics }
    stats enable
    stats uri /stats
    stats refresh 10s
```

Thats the second bug I think that I don't have any logs for my `nc` requests. I think they should be `BADREQ` but I don't see any `BADREQ` in my logs!

**Comment by wtarreau** [comment]
The need for Ctrl-C is shocking. Netcat should close immediately when receiving the 408 response. This could make one think about a deeper issue but I have no idea which one. Are you sure you're not facing network losses, which could explain a delay in the connection setup and in closing ?

One thing that could explain the long time and lack of logs could be that the socket would be configured with "defer-accept", in which case it remains in the kernel for quite some time before being handed off to haproxy. But this requires the "defer-accept" keyword on the "bind" line, which is not there. And I'm not aware of a way to force this system-wide.

**Comment by capflam** [comment]
About Netcat, I'm not sure it is a problem. My netcat does the same. With telnet, the connection is closed as expected. I guess it depends on the Nectat version. Mine (nmap version 7.80) does not reply with a FIN packet when it receives a FIN from HAproxy.

BTW, a delay of 19s is weird because it does not match any configured timeout. At this stage, you must be sure to have no other program listening on the port 80. Maybe a quick network capture will help you to figure out what happens.

**Comment by clwluvw** [comment]
I don't think it's because of my host because my front active sessions gets too high after upgrading to 2.2.4 and also in my test when I send an invalid char I will receive 400 Bad Request after 5-6 sec for example!
```bash
time nc ${IP} 80 -v
Connection to ${IP} 80 port [tcp/http] succeeded!
s
HTTP/1.1 400 Bad request
content-length: 90
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>400 Bad request</h1>
Your browser sent an invalid request.
</body></html>
^C
nc ${IP} 80 -v  0.00s user 0.01s system 0% cpu 6.430 total
```
I'm still can't see my BADREQ logs from my IP!

I'm using OpenBSD netcat (Debian patchlevel 1.206-1ubuntu1) on ubuntu 18.04
@wtarreau @capflam

**Comment by wtarreau** [comment]
How often does it fail for you ? It never does for me with your config, it's always exactly 2s timeout and I always get the logs (I used `log stdout local0` here since I don't know your global config) :
```
haproxy -db -f bug-897.cfg
<133>Oct 14 14:14:10 haproxy[10341]: Proxy my-frontend started.
<133>Oct 14 14:14:10 haproxy[10341]: Proxy stats started.
<133>Oct 14 14:14:10 haproxy[10341]: Proxy my-backend started.
<131>Oct 14 14:14:16 haproxy[10341]: 127.0.0.1:45396 [14/Oct/2020:14:14:14.713] my-frontend my-frontend/<NOSRV> -1/-1/-1/-1/2002 408 237 0 - - cR-- 1/1/0/0/0 0/0 {} "<BADREQ>"
<131>Oct 14 14:14:21 haproxy[10341]: 127.0.0.1:45398 [14/Oct/2020:14:14:19.442] my-frontend my-frontend/<NOSRV> -1/-1/-1/-1/2002 408 237 0 - - cR-- 1/1/0/0/0 0/0 {} "<BADREQ>"
```

And the client:

```
$ time nc -v 127.1 8080
localhost [127.0.0.1] 8080 (?) open
HTTP/1.1 408 Request Time-out
content-length: 110
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>

real    0m2.004s
user    0m0.001s
sys     0m0.000s
$ time nc -v 127.1 8080
localhost [127.0.0.1] 8080 (?) open
HTTP/1.1 408 Request Time-out
content-length: 110
cache-control: no-cache
content-type: text/html
connection: close

<html><body><h1>408 Request Time-out</h1>
Your browser didn't send a complete request in time.
</body></html>

real    0m2.004s
user    0m0.001s
sys     0m0.000s
```

As Christopher mentioned, are you really really certain you're not sharing your port with another service ? This would explain the lack of logs and the strange timeouts. Could you please start haproxy under strace to see it really respond ? If it does it should also tell us more about what's happening thre.

**Comment by clwluvw** [comment]
@wtarreau I'm sending my logs to rsyslog and currently I have 1K req/sec on my haproxy so it's working very well I think :)
Also I can't run it with strace because I use it on docker and using official docker image.
If my frontend session rate won't increase it would be acceptable that it's my problem but they has been growth about 2x and it seems this is not just me!
My logging configs:
```
    log         127.0.0.1 local0
    log-send-hostname
```

**Comment by clwluvw** [comment]
My active frontend seasons raised to 10K but I can't see any near of this number for BADREQ! My req/sec doesn't increase as this much but my node socketstat used increases as well! :disappointed:

**Comment by wtarreau** [comment]
Wait a minute. Are you sure you don't have a proxy provided by docker itself ? This would also explain everything here. No log, longer timeout than needed etc. Please when your netcat connection is established, run "ss -antp | grep 127.0.0.1:80" as root, I'd like to see the name of the processes. I'm pretty sure we'll see docker there!
And if you don't see it, please enter the docker container and run it there. Chances are that you won't see the connection for a while due to this!

**Comment by wtarreau** [comment]
Well replace 127.0.0.1 with your ${IP} but you get what I mean.

**Comment by clwluvw** [comment]
@wtarreau I'm seeing something very strange! When I run the `nc` command, it will said that `Connection to ${IP} 80 port [tcp/http] succeeded!` but I don't see any connection in `ss` output and after 17 sec it will show my connection as a `ESTAB` and after 2 sec it will terminate as it expected!
It seems haproxy timeout is working correctly but I don't know how netcat is saying connection is succeeded but there is no connection appear in my server!
The process that handle these connections are haproxy also with one pid. I think it's because I set the network mode to `host`.

**Comment by wtarreau** [comment]
When you say the process handling this connection is haproxy, do you see it inside the container or also outside ? Because your observation further fuels the suspicion of an intermediate process handling these connections.

In any way, that's another proof that such awful mechanisms to run a process only add complexity and trouble by hiding trivial behaviors. I'm impressed by your patience, I would have long ago got rid of the shitty docker in this setup!

**Comment by clwluvw** [comment]
@wtarreau I see outside the container because there were no `ss` in container :grimacing: 
So you still thinks this is because of docker?

**Comment by wtarreau** [comment]
I'm not saying I think is because of docker, all I'm saying is that your environment is one of the most horrible I've seen in terms of debugability, and that the only difference between your environment and all other properly working ones seems to be this blind usage of docker. There's nothing observable there at all, you're facing issues that nobody else ever sees and you have no way to diagnose anything except just guessing, with a wet finger in the wind. It's not normal not to be able to follow a connection from end to end. If you don't have "ss" in the container, well, just install it or use "netstat -atnp" instead (if it's installed at all). And maybe you should start by placing haproxy outside of docker with your config to see if it works better. No need to add more fog  and complexity when things already don't work.

**Comment by TimWolla** [comment]
> @wtarreau I see outside the container because there were no `ss` in container grimacing

You can use `nsenter -t <pid> -n ss …` to execute `ss` within the network namespace of the container. But if you are running the container with `--net=host` as you say that one will be equivalent to the host network namespace.

@wtarreau The docker proxy only comes into effect if one uses Docker's feature to NAT host ports to container ports. Personally I also run Docker for everything except HAProxy. But the containers communicate via IPv6 for everything. Then Docker does not touch networking at all, there's only a few virtual bridges.

**Comment by capflam** [comment]
I'm closing this issue. Feel free to reopen it if necessary. Thanks
