### ISSUE TITLE
 Latency awareness?

### ISSUE THREAD

**Issue by neobie** [haproxy/haproxy#899]
Haproxy is great for Mysql load balancing.
I wish to know if latency awareness is available ?
Something like if Latency (PING) to server1 > 1s, disable this server temporary.

Thanks.

**Comment by wtarreau** [comment]
This would be a terribly bad idea. Think about this, if all your servers are suddenly slow because of any reason, in cluding the link on your LB being lower, then you'll disable all your servers and end up breaking the service.
If you still want to do this, it's perfectly possible, it simply consists in setting a low "timeout check" value, such as "timeout check 1s", and the server will indeed be disabled each time it takes more than one second to respond to a check. But really I'd advise against doing this.

**Comment by capflam** [comment]
I guess the Willy's response it good enough. Using a low timeout for health-checks should do the trick.
We can close the feature request.
