### ISSUE TITLE
"http-request set-src" affects connection, not transaction or request

### ISSUE THREAD

**Issue by lukastribus** [haproxy/haproxy#90]
Michael Brown (@supermathie) reported this, further researched it and provided a workaround on discourse:
https://discourse.haproxy.org/t/cloudflare-haproxy-is-using-the-wrong-ip-for-http-requests-after-the-first/3769

## Output of `haproxy -vv` and `uname -a`

```
lukas@dev:~/haproxy$ ./haproxy -vv
HA-Proxy version 2.0-dev2-a48237-261 2019/05/02 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_GETADDRINFO=1

Feature list : +EPOLL -KQUEUE -MY_EPOLL -MY_SPLICE +NETFILTER -PCRE -PCRE_JIT -PCRE2 -PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -REGPARM -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H -VSYSCALL +GETADDRINFO -OPENSSL -LUA +FUTEX +ACCEPT4 -MY_ACCEPT4 -ZLIB -SLZ +CPU_AFFINITY -TFO -NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=2).
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built without compression support (neither USE_ZLIB nor USE_SLZ are set).
Compression algorithms supported : identity("identity")
Built without PCRE or PCRE2 support (using libc's regex instead)
Encrypted password support via crypt(3): yes

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available services : none

Available filters :
        [SPOE] spoe
        [COMP] compression
        [CACHE] cache
        [TRACE] trace

lukas@dev:~/haproxy$ uname -a
Linux dev 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
lukas@dev:~/haproxy$
```

Not a regression though, from the initial commit 2fbcafc9ce 4 years ago until latest HEAD the behavior is the same.

## What's the configuration?

```
global
 maxconn 100
 log 10.0.0.4 syslog debug

defaults
 mode http
 option httplog
 log global
 timeout connect 10s
 timeout client 120s
 timeout server 120s
 option http-keep-alive

frontend myfrontend
 bind :80
 http-request set-src hdr(x-forwarded-for) #if { src 10.0.0.4 }
 default_backend be_ip

backend be_ip
 server www 10.0.0.33:80

```

## Steps to reproduce the behavior

In a keep-alived client connection, issue multiple subsequent requests with different x-forwarded-for values (certain CDNs or if another frontend haproxy layer has http-reuse enabled)

1. Opening a telnet window to haproxy and paste something like this:

```
GET / HTTP/1.1
Host: localhost
X-Forwarded-For: 192.168.0.1

GET / HTTP/1.1
Host: localhost
X-Forwarded-For: 192.168.0.2

GET / HTTP/1.1
Host: localhost
X-Forwarded-For: 192.168.0.3

GET / HTTP/1.1
Host: localhost

```

## Actual behavior 1

When set-src is unconditionally called (no src based ACL), the first three request will show up fine in haproxy logs. The forth request will keep the src from the last set-src call (`192.168.0.3`)

## Actual behavior 2

When set-src is conditioned by an ACL (only trust X-Forwarded-For from known trusted proxies or CDNs), then the behavior is worse, because after the first set-src call (`192.168.0.1`), the ACL stops matching, because we replaced the actual low level connection IP.

## Expected behavior

Expected behavior would be to only set the source IP for this specific request/transaction, `http-request` implies exactly that, without impacting subsequent transactions on the same connection.

## Do you have any idea what may have caused this?

set-src works on the connection layer.

## Do you have an idea how to solve the issue?

Either we are able to fix the underlying technical issue (I assume this is complex), or we document this behavior clearly along with some workarounds (already provided on discourse by Michael).

**Comment by TimWolla** [comment]
@lukastribus I guess this should at least be a “severity: medium”, because: “For a bug, it generally indicates something odd which requires changing the configuration in an undesired way to work around the issue.”. The work around is clearly an undesired change. It could even qualify as “severity: major”, because passing incorrect IP addresses could introduce “severe reliability issues” if one uses this to restrict access to trusted IP addresses.

**Comment by lukastribus** [comment]
Agreed for severity: medium.

But it's not something that crashes and blocks the application at 02 am in the morning after running fine for days. That would be major.

**Comment by wtarreau** [comment]
I see why this is happening. In the past we didn't have such a feature and the only way to have a request element dictate the source was by using the "source ... usesrc hdr_ip()". There are specific provisions for this in the connection setup code. But here we're facing a new class of problems that was not envisioned previously. I think we need to change the way it works to flag the connection and mention that its source (or possibly destination) was set from L7 and should be rechecked once assigned differently. It's in fact a bit more complicated than this but it should give the idea :-)

**Comment by capflam** [comment]
1.9 is EOL

**Comment by lukastribus** [comment]
Just documenting the workaround from @Supermathie with a two changes:

* replaced X-F-F with `cf-connecting-ip` (X-F-F can contain multiple IPs)
* denying direct access to this domain

```
# allow cloudflare src ranges (https://www.cloudflare.com/ips-v4 + https://www.cloudflare.com/ips-v6)
acl is_cloudflare src -f /etc/cloudflare/ips-v4
acl is_cloudflare src -f /etc/cloudflare/ips-v6

# WORKAROUND: https://github.com/haproxy/haproxy/issues/90
acl is_cloudflare var(sess.cloudflare) -m found
http-request set-var(sess.cloudflare) always_true if { http_first_req } is_cloudflare

# deny cloudflare bypass for this domain
http-request deny if { hdr(host) -i example.org } ! is_cloudflare

# set true source if cloudflare
http-request set-src hdr(cf-connecting-ip) if is_cloudflare

```

And for automatic and atomic updates of the file, I call wget from cron, save to temporary file and rename:

    wget "https://www.cloudflare.com/ips-v4" -qO /etc/cloudflare/ips-v4.tmp && mv /etc/cloudflare/ips-v4.tmp /etc/cloudflare/ips-v4; wget "https://www.cloudflare.com/ips-v6" -qO /etc/cloudflare/ips-v6.tmp && mv /etc/cloudflare/ips-v6.tmp /etc/cloudflare/ips-v6

**Comment by SpComb** [comment]
The workaround using `var(sess.cloudflare)` as the conditional presumably fixes the "Actual behavior 2" case for a conditional configuration with requests that do have the header set, but does it fix the "Actual behavior 1" behavior for mixed requests on a keepalive connection with and without the request header?

I assume that the fourth request without any `X-Forwarded-For` set will continue to incorrectly keep the src from the previous request, even with this workaround?

**Comment by Supermathie** [comment]
> I assume that the fourth request without any `X-Forwarded-For` set will continue to incorrectly keep the src from the previous request, even with this workaround?

Correct; if you are getting traffic from a trusted source with a mix of X-F-F set and unset, you'll need to save the original IP somewhere and restore it if X-F-F is not present.

**Comment by aleskiontherun** [comment]
2.4 is also affected. Any plans to fix this? We were quite confused when we started to see people browsing our websites from uptime monitoring IP addresses, until we discovered this issue 😬

**Comment by wtarreau** [comment]
I did not notice there had been updates on this one, it went lost despite me always sorting by last update :-/

Given that the connection selection algorithm in 2.4 is quite strict and uses all the elements that were used to configure the connection, it should not happen. But I suspect that we forgot about this specific directive and only saw the `source ... use_src` one. Sometimes I regret that we've implemented `set-src` because it does non-natural things that always pass below the radars.

I'll discuss this with Amaury tomorrow, he's the one who knows exactly how connections are indexed, and hopefully we can figure how to handle this. I don't have any easy solution in mind for pre-2.4 though :-/

**Comment by aleskiontherun** [comment]
>Sometimes I regret that we've implemented set-src because it does non-natural things that always pass below the radars.




I felt the same way during my investigation, like why are we doing this at all!? But you know it's there and there's a bunch of articles explaining how to "properly" set the source IP address, so you kind of go for it anyway. I don't think we really ever needed it in the first place.

**Comment by wtarreau** [comment]
Now I have a better understanding of the problem. First, I mis-analysed it yesterday, I thought the issue was on connection reuse that could incorrectly reuse a connection initiated from a different source but it's totally unrelated. What we're seeing here is that the frontend connection's source address is overwritten from L7 info once for all.

Let's do a bit of history here to retrace the genesis of this feature:

- In 1.6-dev3 we got `set-src` with this commit: 2fbcafc9c ("MEDIUM: http: Add new 'set-src' option to http-request"). Its purpose was to be able to retrieve a connection's apparent source address from a header so that logs could produce the proper info (similar to mod_rpaf/mod_realip etc). Given that log would produce the address from the connection it made sense to overwrite it there.
- in 1.7-dev4, this was extended to support source port (since that one couldn't be set by `set-src`)
- in 1.7-dev4, a different needed to be able to direct a request to a specific address was met and conveniently addressed by using a combo of transparent mode + `set-dst` which would change the apparent destination address

Note that during all this, only keep-alive was supported, there was a single request per connection at a given instant so all of this appeared reasonable. The only immediately visible limitation was the "actual behavior 1" above which is not really a problem in environments making use of this if the first proxy is trusted to always place the address.
 
"Actual behavior 2" is more of a problem that is also a desirable behavior in some situations, because the purpose of changing the apparent source precisely is to replace the uninteresting one with the one that is deemed the right one (think about the proxy protocol for example).

All of these choices flew into pieces with the arrival of H2 in 1.8, because multiple requests can simultaneously set their own source address into the same connection, which makes no sense at all. But this doesn't void users' needs.

So what could we do about this ? My guess is that if we're in this situation, it's because users really want to have a per-request source address in some situations (which was the original intent of @anezirovic's patch in the first place). 
The same could be said of the destination address (i.e. H2 to many H1 outgoing connections to different addresses). So the right solution would be to have some per-stream storage for the source and destination addresses, that could be manipulated using the `set-src` and `set-dst` rules.

But there are some caveats. While it seems obvious enough that `set-src`/`set-dst` actions in the `tcp-request connection` and `tcp-request session` rule sets ought to update the *connection*'s addresses, the actions called in the `tcp-request content` rule-set only ought to update the one in the *stream*, just like for HTTP. This also means that for logging etc, we'd need to first try to retrieve the info from the stream if present (to take care of a potential replacement), otherwise fall back to the connection's.

All of this is not overly complex but touches various entries that are at all levels from the topmost to the lowest ones, and I'm pretty sure we'll quickly face some difficulties (e.g. with transparent mode etc) when the source is attempted to be retrieved from the connection while we'd first need to check upper.

Fortunately, the `set-src` and `set-dst` actions in tcp rulesets were added very recently and are not even part of any released version. So I think the very first thing to do would be to temporarilly roll them back to avoid spreading the damage further (are you OK @capflam?). The second thing to do is to properly document the current limitations of set-src and set-dst and explain exactly how they work (i.e. they *replace* the connection's source address, and must definitely not be used in a context of untrusted front proxy that could sometimes miss one, nor in H2).

Then the next step would be to *try* to implement a set of per-stream src/dst and carefully use these ones if set, then fall back on the connection's.

We could imagine going further and have a connection, a session, and a stream level with different sample fetches to explicitly retrieve one or the other. E.g. the PROXY protocol would set at the session level and not affect the connection level. This at least deserves to be studied, as it's not necessarily more difficult than what's explained above and might avoid future trouble or confusion.

**Comment by capflam** [comment]
I pushed patches to fix this issue. Now, sessions and stream-interfaces carry their own source and destination addresses. Thus source and destination addresses of the client connection, at the connection level, are not altered anymore, except by "tcp-request connection" rules. At the session level, "tcp-request session" rules may alter these addresses. Addresses retrieved via the PROXY protocol or the NetScaler client IP insertion protocol are also set at the session level. Finally "tcp-request content" and "http-request" rules may alter client source and destination addresses at the stream level, updating the frontend stream-interface. The highest available level is used to get them, with a fallback mechanism on underlying layers.

It is a feature of the 2.5. Thus previous versions are still affected by this issue. Backports are not planned.

**Comment by capflam** [comment]
Because backports are not planned for now, I'm closing this issue now keeping version labels, for the record.

**Comment by bensig** [comment]
Thought it would be helpful to leave this here... I used the comments here to get it origin IPs working from Cloudflare on haproxy 2.4 on Ubuntu 22:

```
#       Cloudflare origin IP
        acl from_cf src -f /etc/haproxy/cf-ips/CF_ips.lst
        acl cf_ip_hdr  req.hdr(CF-Connecting-IP) -m found
        http-request set-header X-Forwarded-For %[req.hdr(CF-Connecting-IP)] if from_cf cf_ip_hdr
        http-request set-src hdr(x-forwarded-for) if from_cf
        http-request set-var(sess.cloudflare) always_true if { http_first_req } from_cf
```

Thanks

**Comment by Supermathie** [comment]
> `http-request set-var(sess.cloudflare) always_true if { http_first_req } from_cf`

Yes, this is more or less what [our solution was](https://discourse.haproxy.org/t/cloudflare-haproxy-is-using-the-wrong-ip-for-http-requests-after-the-first/3769/4).

**Comment by lwimmer** [comment]
For completeness sake (as 2.4 is still supported and it took me a while to figure this out):

The posted workaround(s) do not work for 2.4 with HTTP/2, they only work with HTTP/1.1.

The reason is, that `http_first_req` does not seem to work with HTTP/2, therefore the `sess` variable is never set.

I can also confirm that the workaround is no longer needed with 2.6 (I have not tested 2.5).
