### ISSUE TITLE
Haproxy peers section not respecting init-addr none

### ISSUE THREAD

**Issue by tplueer** [haproxy/haproxy#919]
## Detailed description of the problem

It seems like the haproxy peers section is not respecting the option init-addr when starting up. If one of the servers inside the peers section is not reachable / resolvable during startup it just fails with invalid address.

When the server which is not resolvable is commented out it starts working.

## Expected behavior

Since the documentation says the server keyword allows the same options as used inside a backend section
i would expect it accepts the init-addr none parameter.

## Steps to reproduce the behavior

1. Create peers section like inside the config below
2. Make one peer not accessible via dns
3. Start HaProxy
4. It should fail with the error "Invalid address"
5. Make all peers accessible via dns
6. Start HaProxy
7. It should work

## Do you have any idea what may have caused this?
HaProxy checks the dns resolution of the peer during startup.

## Do you have an idea how to solve the issue?
I would suggest using the local peer section first during startup if no peer is available.
After the peers are reachable sync the already written keys from local to the new peer.

## What is your configuration?

```
peers proxy_peers
  bind 0.0.0.0:10001
  default-server init-addr none
  server node_1
  server node_2 node_2.haproxy.service.consul:10001 init-addr last,libc,none resolvers mydns
  server node_3 node_3.haproxy.service.consul:10001 init-addr last,libc,none resolvers mydns
```

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.2.2 2020/07/31 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2025.
Known bugs: http://www.haproxy.org/bugs/bugs-2.2.2.html
Running on: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64
Build options :
  TARGET  = linux-musl
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -Wall -Wextra -Wdeclaration-after-statement -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-stringop-overflow -Wno-cast-function-type -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference
  OPTIONS = USE_PCRE2=1 USE_PCRE2_JIT=1 USE_GETADDRINFO=1 USE_OPENSSL=1 USE_LUA=1 USE_ZLIB=1

Feature list : +EPOLL -KQUEUE +NETFILTER -PCRE -PCRE_JIT +PCRE2 +PCRE2_JIT +POLL -PRIVATE_CACHE +THREAD -PTHREAD_PSHARED -BACKTRACE -STATIC_PCRE -STATIC_PCRE2 +TPROXY +LINUX_TPROXY +LINUX_SPLICE +LIBCRYPT +CRYPT_H +GETADDRINFO +OPENSSL +LUA +FUTEX +ACCEPT4 +ZLIB -SLZ +CPU_AFFINITY +TFO +NS +DL +RT -DEVICEATLAS -51DEGREES -WURFL -SYSTEMD -OBSOLETE_LINKER +PRCTL +THREAD_DUMP -EVPORTS

Default settings :
  bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with multi-threading support (MAX_THREADS=64, default=4).
Built with OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
Running on OpenSSL version : OpenSSL 1.1.1g  21 Apr 2020
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2 TLSv1.3
Built with Lua version : Lua 5.3.5
Built with network namespace support.
Built with zlib version : 1.2.11
Running on zlib version : 1.2.11
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with PCRE2 version : 10.35 2020-05-09
PCRE2 library supports JIT : yes
Encrypted password support via crypt(3): yes
Built with gcc compiler version 9.3.0
Built with the Prometheus exporter as a service

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
            fcgi : mode=HTTP       side=BE        mux=FCGI
       <default> : mode=HTTP       side=FE|BE     mux=H1
              h2 : mode=HTTP       side=FE|BE     mux=H2
       <default> : mode=TCP        side=FE|BE     mux=PASS

Available services :
	prometheus-exporter

Available filters :
	[SPOE] spoe
	[COMP] compression
	[TRACE] trace
	[CACHE] cache
	[FCGI] fcgi-app
```

```
Linux node_2 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 Linux
```

**Comment by wtarreau** [comment]
For me, neither the checks nor the resolvers are supported there, thus by definition a number of keywords cannot be supported. I'm surprised by the wording if it says it supports the same keywords :-(  Those which are supported are the ones related to the transport layer (i.e. how to configure SSL, mutual-auth, SNI etc to communicate with other nodes). I guess a doc update is needed.

Just out of curiosity, what are you trying to do with init-addr none ? Did you just try to temporarily disable a peer maybe ?

**Comment by tplueer** [comment]
> I guess a doc update is needed.

Yes I think so. The [2.2 docs](https://cbonte.github.io/haproxy-dconv/2.2/configuration.html#3.5) say:
```
As previously mentioned, "peer" keyword may be replaced by "server" keyword
with a support for all "server" parameters found in 5.2 paragraph.
```
The 5.2 paragraph contains the init-addr parameter.

> Just out of curiosity, what are you trying to do with init-addr none ? Did you just try to temporarily disable a peer maybe ?

I have a dynamic haproxy environment which consists of a minimum of three nodes which all share the same config and should also share the same rate limits counters etc.

During startup each of the instances gets started one after another and registers itself inside consul. After the registration is complete it can take up some seconds until the SRV records are updated with the new instance ip, this is where the problem is happening since the configuration is generated in advance and the node is already present inside the peers configuration 
but there is a chance it's not yet started.

**Comment by fabiohecht** [comment]
I have the same issue. I'm trying to create 3 HAProxy pod replicas in a K8s StatefulSet. They all share the same config, so `peer` comes in handy (since `server` does not allow referencing the own instance). When the first replica starts, the other 2 names cannot be resolved yet, so `init-addr none` would solve the issue. Is there a workaround (other than generating a different config file for each instance)?

**Comment by capflam** [comment]
As specified in the documentation, the server lines in a peer section only support ip addresses, not hostnames. Thus the `init-addr` option is irrelevant in that case because there is no resolution. For the same reason, it is not possible to configure a resolver.
Note the error message reports a parsing error because `node_2.haproxy.service.consul` is not an ip address.

So it is not a bug and it works as expected. I don't really know if it is possible to add startup or dns resolution for peers. But you may create a Feature request.

**Comment by fabiohecht** [comment]
Thanks for you message, but I beg to disagree.

I can successfully use hostnames in the peers section, as long as they resolve.

Here is the relevant `peer` section:
```
    peers proxies
        peer proxy-0 proxy-0.proxy.namespace.svc.k8s.my-domain.net:8081
        peer proxy-1 proxy-1.proxy.namespace.svc.k8s.my-domain.net:8081
        peer proxy-2 proxy-2.proxy.namespace.svc.k8s.my-domain.net:8081
```

The trick to make it work in my setup is to create all pods with the peers section commented out, so the pods can start and let the K8s service create the DNS names. Then I uncomment the peers section and restart all pods. All seems to work fine then. At least I see the metrics:

```
# HELP haproxy_process_active_peers Current number of active peers.
# TYPE haproxy_process_active_peers gauge
haproxy_process_active_peers 2
# HELP haproxy_process_connected_peers Current number of connected peers.
# TYPE haproxy_process_connected_peers gauge
haproxy_process_connected_peers 2
````

Probably the documentation should be updated to reflect reality. And if `init-addr` would work it would be really great.

**Comment by wtarreau** [comment]
Actually the "server" declarations in "peers" sections are not real servers but still peers. They're not checked, nor are part of an LB group for example. This is why here are some limitations. The choice of "server" here was to help document the supported keywords, given that most of them are in fact related to the setup of the transport layer. Some users use TLS with mutual auth here and that's where reusing the servers capabilities is really useful.

That doesn't mean that peers will never improve to support more server features, but there will always be some differences due to their nature.

I would suggest that we improve the doc and possibly adjust a few pieces of code to make things more consistent. For example if you can configure an FQDN in "peer" but not in "server" or such things, that's something which could be improved. Similarly we possibly need to explicitly reject "check", "inter", "init-addr", "peers" or "resolvers" on such "server" entries. I personally don't like seeing feature-oriented keywords being silently ignored when irrelevant because they make people think they might help if they don't break.

**Comment by tplueer** [comment]
I've create a feature request #930 to support init-addr parameter inside the peer section.
Should this issue be closed then or do you need it to stay open for the documentation update ?

**Comment by lukastribus** [comment]
Please leave it open as the documentation needs to be addressed.

**Comment by f-leclere** [comment]
I have the same issue. I'm trying to create 2 HAProxy pod replicas in a openshift StatefulSet. 
goal: avoid traffic, caching and sticky tables issues on pod redeployment
Constraint: Deployments configurations are develop for multiple environments and managed through Kustomize + Kapp tooling using prefix feature (below prefix is "int-"), so ips or hostnames can't be define statically.

is it an another way to setup haproxy 2.5.5 to do that ?

Below peers definition extract of my current configuration tryal
```
peers od-haproxy-peers
    bind *:10024
    default-server init-addr none
    server localglobalpeer
    server od-haproxy-0 int-haproxy-0.$(KUST_HAPROXY_HEADLESS_SERVICE_NAME).${POD_NAMESPACE}.svc.cluster.local:10024 resolvers default-resolver resolve-prefer ipv4 check maxconn 500 check inter 5s fastinter 1s downinter 2s rise 2 fall 3 maxqueue 20 on-marked-down shutdown-sessions init-addr none
    server od-haproxy-1 int-haproxy-1.$(KUST_HAPROXY_HEADLESS_SERVICE_NAME).${POD_NAMESPACE}.svc.cluster.local:10024 resolvers default-resolver resolve-prefer ipv4 check maxconn 500 check inter 5s fastinter 1s downinter 2s rise 2 fall 3 maxqueue 20 on-marked-down shutdown-sessions init-addr none
```

**Comment by capflam** [comment]
@EmericBr, I don't know if it was addressed or not

**Comment by EmericBr** [comment]
Indeed, as willy said the declated servers are not true servers and can't use periodic resolving. I think currently resolving is done one time for all at startup and it is clearly not obvious to handle a periodic resolving a IP change since the peers protocol maintain establised connections.

**Comment by f-leclere** [comment]
@EmericBr , thanks for your answer
I understand well current implementation, but what could be the way outside IAAS machines to implement an haproxy cluster at pods level to avoid traffic lost, sticky tables lost or haproxy data cache lost occuring during pods redeployment or on cluster pods discarding ? 
How to use haproxy features at cloud consumer level not at cloud provider level ?
How make haproxy more cloud nativ on futur releases?

**Comment by EmericBr** [comment]
I agree but the peers protocol was older than those usage, it uses maintained connection and nothing was designed to break them and re-create because a resolver detects that an IP is changing. This could be done in futur and must be added to the brainstorm process on peers protocol v3 so we will keep the feature request open but it is clearly not obvious to be done in the current code.

**Comment by wtarreau** [comment]
I understand your concern. But the point is that even DNS itself is not a solution to everything in cloud environments, as we're seeing on a daily basis with tons of consistency issues being reported all the time. Some users even went away from this completely because their host names are not preserved across reloads, making the DNS unusable.

Other people need to add/remove nodes and will complain that there are never enough peers entries, forcing them to pre-provision them in excess, as we used to do for servers with server-template. I mean, let's not reproduce the old recipes that are known not to work, because they address the symptoms instead of the cause of the problem.

The root cause of the problem is not that one well-known LB's address is changing over time, it's that the architecture is flexible and that among the architecture changes, some concern just an LB's address. But other changes will appear.

I think that the right approach would rather be to include the peers in the reflexion around the discovery stuff, in order to make sure we can provision/remove them on the fly via an API. **This** will be scalable and reliable. And this is the direction taken by every cloud player after tried the DNS as well and having noticed how ugly a a hack it was (it was never designed for this).

Another approach for such a fast-changing architecture is use an aggregator and make your haproxy nodes only talk to that one. This way the number of LBs can evolve in any direction, only the aggregator is the reference and distributes the tables to its subscribers.

**Comment by wtarreau** [comment]
The doc was updated and the config parser will now emit a warning on the most commonly misused parameters (init_addr, resolvers, check, ...). I think we can now close.

**Comment by ArielLahiany** [comment]
I'm experiencing the same problem.
Once I deploy the StatefulSet the first pod is stuck because its unable to resolve the DNS of the other peers.
Is there a way to solve this?

**Comment by mrkoggles** [comment]
@ArielLahiany did you ever find a solution?

**Comment by ArielLahiany** [comment]
@mrkoggles 
Unfortunately, as far as I can tell there is no good solution for that problem at the moment.
At least not out-of-the-box one.
