### ISSUE TITLE
build fails on reg-tests/seamless-reload/abns_socket.vtc

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#924]
failed build: https://github.com/haproxy/haproxy/runs/1290002082?check_suite_focus=true

**Comment by wlallemand** [comment]
I can reproduce both failure without the openssl no deprecated feature.

The abns_socket one is marked "broken" so it shouldn't be launched, however I found out that it is not that broken and there might be a real bug, but we should definitely avoid launching "broken" reg tests.

**Comment by chipitsine** [comment]
hmm, indeed we run all tests. I'll send a patch

**Comment by chipitsine** [comment]
I did not try to bisect yet. I'll try soon

**Comment by wlallemand** [comment]
I already bisected the abns_socket one, the problem was caused by 87acd4e                                                                                                                                                
("BROKEN/MEDIUM: listeners: rework the unbind logic to make it idempotent").

Regarding the second one I can't make it work even with the commit that introduced it.

**Comment by chipitsine** [comment]
second one may require some additional features like PCRE. we can enable features one by one

**Comment by wlallemand** [comment]
It does not need PCRE, the regex are the PCRE one of vtest, they are not within the HAProxy configuration.

**Comment by wlallemand** [comment]
@chipitsine Is it possible to have the detail of these vtest errors because I'm not even sure of reproducing the same issue? Thanks

**Comment by chipitsine** [comment]
I think we should split into 2 issues. I'll provide repro steps for second one later.

**Comment by wlallemand** [comment]
This reg-test was reactivated in commit 501c995.
