### ISSUE TITLE
How do you rate limit by domain name / host?

### ISSUE THREAD

**Issue by hiqsociety** [haproxy/haproxy#932]
I only saw "Rate Limit by URL" but how do i rate limit by domain name /  host?

**Comment by jmagnin** [comment]
This issue tracker is for tracking bugs and feature requests directly relating to the development of the software itself.
 
Use the forum or the mailing list if you have a question rather than a bug or feature request.
 
The forum is at: https://discourse.haproxy.org/
 
- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
