### ISSUE TITLE
reg-tests/ssl/ssl_crt-list_filters.vtc failed with centos 6, libressl, openssl-1.0.2

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#944]
https://github.com/haproxy/haproxy/runs/1364461587
https://travis-ci.com/github/haproxy/haproxy/jobs/430961815

the most interesting is openssl-1.0.2, it should support EC, right ?

https://travis-ci.com/github/haproxy/haproxy/jobs/430961811

**Comment by wtarreau** [comment]
Actually it's not the builds but the tests, which is more annoying :-/

**Comment by wlallemand** [comment]
That doesn't work with < 1.1.1 because there are multiple certificate types for the same SNI, the clientHello callback is required for this. But I don't know why it's not working with libreSSL, I thought this supported it, maybe there are still some mistakes in the #ifdef. I will test this locally.

So the test should be removed at least for OpenSSL < 1.1.1, I don't think we have a way to specify a required OpenSSL version for the tests.

**Comment by wlallemand** [comment]
I made some tests with libreSSL 3.0.2 and 3.2.2 and there is no problem with the 3.2.2 version.
LibreSSL 3.0.2 is probably too old to support the clientHello callback.

**Comment by chipitsine** [comment]
probably, we can drop older LibreSSL, 3.2.2 is buggy, but we will switch to 3.2.3 when it is released.
however, we want to keep testing against openssl-1.0.2 at least

**Comment by chipitsine** [comment]
as for centos 6, we can discuss whether to keep it or not. 
it is EOL already

**Comment by wlallemand** [comment]
I'll mark the test as broken for now.

**Comment by wlallemand** [comment]
Please let the ticket open until we find a proper solution. (changing the CI or finding a way to execute this test only at the right places).

**Comment by wtarreau** [comment]
@wlallemand should this still remain open ? It doesn't seem it got any progress in 1.5 years, and SSL has significantly changed since. Feel free to close if that's OK.

**Comment by wlallemand** [comment]
The problem was to be able to enable the test only with openSSL >= 1.1.1, that's the case since 8d264387c3b44268a1cf64b9e6aef8177257f24d. Closing.
