### ISSUE TITLE
How do I configure to disconnect the haproxy back end to the server when the front end connection disconnects

### ISSUE THREAD

**Issue by danielpine** [haproxy/haproxy#946]
When keepalived and HaProxy are used together,
VIP float away when keepalived is turned off on only one machine,
 but the links HAProxy and Server have already established on this machine will not be released.

**Comment by lukastribus** [comment]
Please do not ask questions in the issue tracker. This issue tracker is for tracking bugs and
feature requests directly relating to the development of the software itself.

Use the forum or the mailing list if you have a question rather than a bug or feature request.

The forum is at: https://discourse.haproxy.org/

- The mailing list (no need to subscribe) is: haproxy@formilux.org
- Subscribe to the list: haproxy+subscribe@formilux.org
- Unsubscribe from the list: haproxy+unsubscribe@formilux.org
