### ISSUE TITLE
Dump/reload some stat counters

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#954]
## What should haproxy do differently? Which functionality do you think we should add?

Some users have expressed a few times they would like to preserve stats over reloads. While for plenty of cases it makes no sense technically speaking, there are situations where the requirement makes sense and where reasonable solutions could be acceptable. The essential issue is related to billing.

Having the ability to dump per-server bytes exchanged, requests counts, connetions counts with the state files for example so that these values are preloaded on restart when the server is identified, could be a nice improvement. It would not solve everything and the remaining activity in the old process would not be accounted for, but based on the various discussions this sounds acceptable.

What's interesting with this approach of just keeping volume information is that it solves the main issue with trying to preserve the whole stats across reloads, which is that averages, rates, max etc cannot easily be preserved, and that changing server IDs is a problem. Here we'd just preload counters a bit like an operational state. It is important to define a limited set of information to be passed, and to make them optional, because their values can become confusing, e.g. when comparing the total bytes sent by a server to the one of the backend which will be much lower.

This requires further thinking before being implemented, as doing it wrong would be even harder to solve. Maybe reporting past counters as a separate column would be more convenient to use (i.e. reporting tools would just sum them up and that would solve the problem of relevance of new numbers vs the backend's or vs the process' uptime).

## What are you trying to do?

Ease reporting of per-application usage.

## Output of `haproxy -vv` and `uname -a`

```
haproxy 2.3.0
```

CCing @pierrecdn, @wdauchy, @wlallemand, @bedis, @nmerdan

**Comment by nmerdan** [comment]
For my own use case, losing visibility to what the older process' are doing is much more impacting than not having the volume information counters transferred to the new process. Most modern graphing/alerting systems can deal with this pretty well with stuff like non-negative derivatives. This is a bigger problem if you are reloading frequently (but so is losing visibility into the old processes), which is not my use case.

Solution where the master process would collect all the data of all the worker processes, as discussed in #740, and expose all of them using one command (show stat proc all?) would be good to have visibility into the old process (if we make it still update its stats), but that won't work well with transferring the data, since then we'll have some stuff doubled (like bytes transferred for example). And if we don't transfer, we'll again have a negative derivative once the old process goes away. 

Just my 2c, I don't yet have a solution that covers both requirements.

EDIT:
If we do a derivative before the sum per-process, we should be able to avoid the last mentioned issue.

**Comment by idl0r** [comment]
I also just had a case, where I could need reliable data:
https://www.mail-archive.com/haproxy@formilux.org/msg39815.html

**Comment by NicolasCARPi** [comment]
HAProxy 3.0 can do that now! :tada: 

From: https://www.haproxy.com/blog/announcing-haproxy-3-0

> Persisting stats after a reload: Reloading HAProxy will no longer reset the HAProxy Stats page, as long as you call the new Runtime API command dump stats-file first to save the current state to a file and then load that file with the stats-file configuration directive. Ensure that you've set a GUID on each frontend, backend, listen and server object by using the new guid keywords.

(so I guess this issue can be closed)

**Comment by a-denoyelle** [comment]
Indeed, thanks for the remainder. And if you or anyone has tested this feature yet, do not hesitate to give us feedback. If this feature is considered useful, we have plan to extend it to preserve more counter values.
