### ISSUE TITLE
Define the range of status codes that count as error for http_err_cnt / http_err_rate

### ISSUE THREAD

**Issue by wtarreau** [haproxy/haproxy#961]
## What should haproxy do differently? Which functionality do you think we should add?

Initially http_err_cnt and http_err_rate were added to stick tables to ease detection of bots and scanners. As such it was important to be able to match only the 4xx codes.

Nowadays, a number of users report that they want to use this exactly the other way around, to count per-URL error rates on the backend. As such, the 4xx isn't much usable anymore.

It seems that it could make sense to extend a table's configuration to mention in it the lower and upper bounds of status codes that are considered as an error in that table, so that the track-sc rules apply only on matching ranges.

It will require changes around stream_inc_http_err_cnt() which will need to be called unconditionally and check the range for each tracked stick table (need to see if this is expensive and if it can be bypassed when not used). It will also cause a problem with the few places where a test is made on a condition not using the status code before deciding to increment the error count. The main ones are deny, tarpit, and parsing/connection errors. All of them can probably be forced to 403 when calling this and documented as such, as it's what they really correspond to.

## What are you trying to do?

Typically keep track of faulty URLs on a server, which are known to fail due to the server and not to the client.
An alternative could be to have a second set of counters "http_fail_cnt" and "http_fail_rate" but it's not certain it would be easier to implement nor to use. At least it would still require the ability to tune the status code range (though it would probably address the special cases above).

Point to note (not tested for now), a workaround for this might be to use something like `http-response return status 400 if { status 502 }` to count only server errors, but it's a bit ugly.

## Output of `haproxy -vv` and `uname -a`

```
HA-Proxy version 2.4-dev0-a2a46e-74 2020/11/17 - https://haproxy.org/
```

**Comment by CaptainDredge** [comment]
Any progress on this one? I made an attempt to do this through a stick table where the `track-sc*` is `path_beg` and I'm incrementing `gpc0` whenever status is `>=500` but the problem is that currrently `status` fetch does not return a `5xx` response code in cases where there was connection errors or server timeouts etc. i.e. in cases where Haproxy itself throws 5xx. Do you have any solution for this?

**Comment by wtarreau** [comment]
No, no particular progress. I don't know how you tried to increment gpc0 in cse you didn't get a response however, as `http-response` rules will never be executed; Maybe you tried via `http-after-response` ?

**Comment by Darlelet** [comment]
Well unfortunately as discussed in #1980, `http-after-response` won't help as is because `sc-inc-gpc0` (and other stick table related actions) are not made available through `http-after-response` (only a limited list of actions are exposed at the moment).

Exposing them seems fairly simple (via `http_after_res_keywords_register` registration). Should we consider this a proper workaround?

**Comment by wtarreau** [comment]
I don't know, we may need to discuss this with Christopher to make sure there are no chicken-and-egg effects, and that stick-counters are still available in after-response. My question was more related to know how this was tested in fact :-)

**Comment by wtarreau** [comment]
I think it's done now in 3.0. @capflam do you agree we can close it ?

**Comment by capflam** [comment]
Indeed. The commits: 9d827e10497a57623e903e0be41fe9b02efb5da5 and 4cc25f26f94859bf4dbc2d036d9d23e5a5a7a2de
