### ISSUE TITLE
Starter Guide Table of Contents is partially out of order

### ISSUE THREAD

**Issue by jerrac** [haproxy/haproxy#996]
## Detailed description of the problem

While reading the starter guide I found that the table of contents listed some sections out of order. This was slightly confusing.

### Highlighted Screenshot
![highlighted Screenshot_2020-12-06 HAProxy version 2 2 5 - Starter Guide](https://user-images.githubusercontent.com/910764/101283791-a4d2dc00-3791-11eb-86d2-9550d99229d8.png)

## Expected behavior

The TOC should be in order.

## Steps to reproduce the behavior

1. View the 2.2 or 2.4 starter guides.

## Do you have any idea what may have caused this?
I'd guess whatever tool is used to generate the url is not using the correct sorting algorithm on the TOC.

## Do you have an idea how to solve the issue?
Nope. 

## Additional information (if helpful)
It's a tiny issue, and I didn't find any other reports, so figured I might as well make sure it's noted. I'd guess this issue should stay at the bottom of the priority stack... :)

**Comment by lukastribus** [comment]
The Starter Guide is probably the only document that has beyond 9 subsections ...

The code is in @cbonte 's https://github.com/cbonte/haproxy-dconv

**Comment by wtarreau** [comment]
Maybe the simplest fix would be that we cut it into two sections in order to have less than 9 total per section :-)

**Comment by capflam** [comment]
Fixed by the commit e68e7e84 and backported as far as 2.4. I'm closing now.

**Comment by cbonte** [comment]
Hi all, this is now fixed in haproxy-dconv.
https://github.com/cbonte/haproxy-dconv/commit/9bf0fd2328733012fb182ac9395b19be0eab7cb6

I think it happened because there was at least one missing chapter in the summary provided by configuration.txt. The sort criteria didn't respect natural order when a missing chapter is added to the summary.

Now, the chapters are sorted only when the summary is fully rebuilt.
